To run this notebook, you will need a `.env` file at the root of the project. It should contain the following keys:
```
LLM_SERVICE=OpenAI
OPENAI_API_KEY=...
OPENAI_ENDPOINT=...
OPENAI_DEPLOYMENT_NAME=...
OPENAI_API_VERSION=...
```

The first step is to load the libraries we'll be using. I am importing `pandas` for basic data manipulation, and a package called [discovery_utils](https://github.com/nestauk/discovery_utils) that Karlis made. It contains various functions that we have used and reused across Discovery projects, including functions for extracting structured information using LLMs. You can read more about how the `llm` module works [here](https://github.com/nestauk/discovery_utils/wiki/Checking-data-with-LLM).

In [1]:
import pandas as pd
from discovery_utils.utils.llm import batch_check

from discovery_heat_pump_futures import PROJECT_DIR

Karlis has created two datasets for this project: one containing research abstracts from [OpenAlex](https://openalex.org/), and one from [Google Patents](https://patents.google.com/).

In [2]:
openalex_df = pd.read_csv(
    "https://discovery-hub-open-data.s3.eu-west-2.amazonaws.com/future_heat_pumps/heat_pumps_openalex.csv"
)
patents_df = pd.read_json(
    "https://discovery-hub-open-data.s3.eu-west-2.amazonaws.com/future_heat_pumps/heat_pumps_patents.json",
    lines=True,
)

/tmp/ipykernel_7240/865600020.py:1: DtypeWarning: Columns (52) have mixed types. Specify dtype option on import or set low_memory=False.
  openalex_df = pd.read_csv(

The patents dataset looks like this:

In [3]:
patents_df.head()

,publication_number,application_number,family_id,url,filing_date,grant_date,publication_date,priority_date,title,title_translated,abstract,abstract_translated,top_terms,country_code,inventor_harmonized,assignee_harmonized,cpc
0,WO-2024184245-A1,EP-2024055431-W,85462233,https://patents.google.com/patent/WO2024184245A1,20240301,0,20240912,20230303,Heat source unit of an air heat pump,False,"Heat source unit (1) of an air heat pump, havi...",False,"[fan, louvers, heat source, source unit, cente...",WO,"[{'name': 'HEINTZ NICOLAS', 'country_code': 'B...","[{'name': 'DAIKIN EUROPE NV', 'country_code': ...","[{'code': 'F24F13/082', 'inventive': False, 'f..."
1,US-11994321-B2,US-202017420370-A,71406811,https://patents.google.com/patent/US11994321B2,20200103,20240528,20240528,20190103,High performance compressors and vapor compres...,False,The present disclosure relates to a new breed ...,False,"[compressor, pressure, motor, refrigerant, pum...",US,"[{'name': 'LEE KANG P', 'country_code': 'US'},...","[{'name': 'ASPEN COMPRESSOR LLC', 'country_cod...","[{'code': 'F25B31/026', 'inventive': True, 'fi..."
2,WO-2022023086-A1,EP-2021070024-W,71846293,https://patents.google.com/patent/WO2022023086A1,20210716,0,20220203,20200729,A heating system,False,A heating system (1) has a turbine (20) for bu...,False,"[flue gas, heat exchanger, air, wshp, water, h...",WO,"[{'name': 'FLYNN LIAM', 'country_code': 'IE'},...","[{'name': 'ENERGY SERVICES LTD', 'country_code...","[{'code': 'Y02B30/18', 'inventive': False, 'fi..."
3,CN-211854451-U,CN-202020379578-U,73135275,https://patents.google.com/patent/CN211854451U,20200323,20201103,20201103,20200323,Cold and hot water supply system for poultry s...,False,The utility model provides a poultry is slaugh...,False,"[hot water, cold, water pipe, supply system, p...",CN,"[{'name': 'WU TAN'EN', 'country_code': ''}]",[{'name': 'TAIZHOU HONGYE ENVIRONMENTAL TECH C...,[]
4,WO-2024162444-A1,JP-2024003342-W,91030893,https://patents.google.com/patent/WO2024162444A1,20240201,0,20240808,20230202,Heat pump device,False,A heat pump device according to one embodiment...,False,"[discharge, temperature, compressor, pressure,...",WO,"[{'name': 'SAGAWA KENTARO', 'country_code': 'J...","[{'name': 'FUJITSU GENERAL LTD', 'country_code...","[{'code': 'F25B1/00', 'inventive': True, 'firs..."

Below, we specify a helper function that can also be used on the OpenAlex data to concatenate the titles and abstracts of individual patents/abstracts. This new `"title_abstract"` field will be the input to `LLMProcessor`.

In [4]:
def format_title_abstract(
    df: pd.DataFrame, title: str = "title", abstract: str = "abstract"
) -> pd.DataFrame:
    """Format the title and abstract for LLM input.

    Args:
        df (pd.DataFrame): DataFrame containing the title and abstract columns.
        title (str): Name of the title column.
        abstract (str): Name of the abstract column.

    Returns:
        pd.DataFrame: DataFrame with a new column 'title_abstract'
            containing formatted text.
    """
    df["title_abstract"] = (
        "TITLE: "
        + df[title].str.lower().fillna("")
        + " ABSTRACT: "
        + df[abstract].str.lower().fillna("")
    )
    return df


patents_df = format_title_abstract(patents_df, title="title", abstract="abstract")
patents_df.head()

,publication_number,application_number,family_id,url,filing_date,grant_date,publication_date,priority_date,title,title_translated,abstract,abstract_translated,top_terms,country_code,inventor_harmonized,assignee_harmonized,cpc,title_abstract
0,WO-2024184245-A1,EP-2024055431-W,85462233,https://patents.google.com/patent/WO2024184245A1,20240301,0,20240912,20230303,Heat source unit of an air heat pump,False,"Heat source unit (1) of an air heat pump, havi...",False,"[fan, louvers, heat source, source unit, cente...",WO,"[{'name': 'HEINTZ NICOLAS', 'country_code': 'B...","[{'name': 'DAIKIN EUROPE NV', 'country_code': ...","[{'code': 'F24F13/082', 'inventive': False, 'f...",TITLE: heat source unit of an air heat pump AB...
1,US-11994321-B2,US-202017420370-A,71406811,https://patents.google.com/patent/US11994321B2,20200103,20240528,20240528,20190103,High performance compressors and vapor compres...,False,The present disclosure relates to a new breed ...,False,"[compressor, pressure, motor, refrigerant, pum...",US,"[{'name': 'LEE KANG P', 'country_code': 'US'},...","[{'name': 'ASPEN COMPRESSOR LLC', 'country_cod...","[{'code': 'F25B31/026', 'inventive': True, 'fi...",TITLE: high performance compressors and vapor ...
2,WO-2022023086-A1,EP-2021070024-W,71846293,https://patents.google.com/patent/WO2022023086A1,20210716,0,20220203,20200729,A heating system,False,A heating system (1) has a turbine (20) for bu...,False,"[flue gas, heat exchanger, air, wshp, water, h...",WO,"[{'name': 'FLYNN LIAM', 'country_code': 'IE'},...","[{'name': 'ENERGY SERVICES LTD', 'country_code...","[{'code': 'Y02B30/18', 'inventive': False, 'fi...",TITLE: a heating system ABSTRACT: a heating sy...
3,CN-211854451-U,CN-202020379578-U,73135275,https://patents.google.com/patent/CN211854451U,20200323,20201103,20201103,20200323,Cold and hot water supply system for poultry s...,False,The utility model provides a poultry is slaugh...,False,"[hot water, cold, water pipe, supply system, p...",CN,"[{'name': 'WU TAN'EN', 'country_code': ''}]",[{'name': 'TAIZHOU HONGYE ENVIRONMENTAL TECH C...,[],TITLE: cold and hot water supply system for po...
4,WO-2024162444-A1,JP-2024003342-W,91030893,https://patents.google.com/patent/WO2024162444A1,20240201,0,20240808,20230202,Heat pump device,False,A heat pump device according to one embodiment...,False,"[discharge, temperature, compressor, pressure,...",WO,"[{'name': 'SAGAWA KENTARO', 'country_code': 'J...","[{'name': 'FUJITSU GENERAL LTD', 'country_code...","[{'code': 'F25B1/00', 'inventive': True, 'firs...",TITLE: heat pump device ABSTRACT: a heat pump ...

In [5]:
# to show what the formatted column looks like
patents_df["title_abstract"].values[0]

'TITLE: heat source unit of an air heat pump ABSTRACT: heat source unit (1) of an air heat pump, having a casing (10), a fan (22) accommodated in the casing (10) and being rotatable about a center axis (30), a bell mouth (32) having an opening (32), and a grille (40, 42) covering the opening (32). the grille (40, 42) comprises a plurality of longitudinal first louvers (46), wherein each of the first louvers (46) has an entry portion (66) facing the fan (22) and at least the entry portion (66) is inclined relative to the center axis (30) of the fan (22), wherein the angle of inclination (α) changes in the longitudinal direction of the respective first louver (46).'

In [6]:


# Download OpenAlex dataset
openalex_df = pd.read_csv(
    "https://discovery-hub-open-data.s3.eu-west-2.amazonaws.com/future_heat_pumps/heat_pumps_openalex.csv"
)

# Download Patents dataset
patents_df = pd.read_json(
    "https://discovery-hub-open-data.s3.eu-west-2.amazonaws.com/future_heat_pumps/heat_pumps_patents.json",
    lines=True,
)

# Optional: Save locally for offline reuse
openalex_df.to_csv("heat_pumps_openalex.csv", index=False)
patents_df.to_json("heat_pumps_patents.json", orient="records", lines=True)

print("Datasets downloaded and saved locally.")

/tmp/ipykernel_7240/3393018013.py:2: DtypeWarning: Columns (52) have mixed types. Specify dtype option on import or set low_memory=False.
  openalex_df = pd.read_csv(

Datasets downloaded and saved locally.

In [7]:
import openai
from openai import OpenAI
client = OpenAI()

In [8]:
# 0 ── Imports & basic config
import math
from pathlib import Path
from datetime import datetime
import pandas as pd
from tqdm.auto import tqdm
import json
from time import sleep
from dotenv import load_dotenv
import os
from openai import OpenAI
import re

/home/pascualdiego/projects/DiscoveryHP/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [10]:
#For Circularity Score#
!pip install nltk


import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')  # Optional but improves lemmatizer accuracy

/bin/bash: line 1: pip: command not found

[nltk_data] Downloading package wordnet to
[nltk_data]     /home/pascualdiego/nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/pascualdiego/nltk_data...

True

In [13]:
# -------------------------------
# Load environment and OpenAI client
# -------------------------------
load_dotenv()  # Adjust path if needed
client = OpenAI()

In [12]:
# --------------------------------------------------------------------------- #
# Heat Pump Thesis Classifier  | fully integrated with environment + KWS #
# --------------------------------------------------------------------------- #
#  What this notebook does end‑to‑end:                                        #
#   1.  Loads patents (JSONL) and research papers (CSV)                       #
#   2.  Calls OpenAI gpt‑4o‑mini model to                            #
#         • classify each item into one of 22 sub‑categories                  #
#         • extract short abstract + core innovation                          #
#         • assign cost, efficiency, circularity scores (0‑3)                 #

import os, json, math, pandas as pd
from tqdm.auto import tqdm
from dotenv import load_dotenv
from discovery_heat_pump_futures import PROJECT_DIR
from openai import OpenAI
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime

# Load environment + OpenAI
load_dotenv(dotenv_path=PROJECT_DIR / ".env")
client = OpenAI()

MODEL_NAME = "gpt-4o-mini"
T_CLASSIFY = 0.1
OUTPUT_PATH = PROJECT_DIR / "outputs/fullset_classified_patents_CEscore.jsonl"
MAX_WORKERS = 10
filter_keywords = True  # ← toggle keyword filtering

# ---- 1. CATEGORIES ---------------------------------------------------------
CATEGORIES = {
    "1.1": "Compressors", "1.2": "Refrigerants", "1.3": "Heat-exchangers", "1.4": "Motor & Drives", "1.5": "Lubrication & oil management",
    "2.1": "Elastocaloric", "2.2": "Electrocaloric", "2.3": "Magnetocaloric", "2.4": "Ionocaloric", "2.5": "Barocaloric",
    "2.6": "Thermoelectric", "2.7": "Electro- & Chemisorption", "2.8": "Thermoacoustic", "2.9": "Sorption / Absorption", "2.10": "Hybrid & cascade",
    "3.1": "Topology & configuration", "3.2": "Controls & optimisation", "3.3": "Operational integration",
    "4.1": "Flexible cycles", "4.2": "Defrost & icing mitigation", "4.3": "Thermal storage",
    "5.1": "Design-for-disassembly", "5.2": "Modular assemblies", "5.3": "Recycled materials", "5.4": "Additive manufacturing", "5.5": "Predictive maintenance"
}

# ---- 2. KEYWORD UNIVERSE ---------------------------------------------------
KWS = {
    "1.1": ["scroll", "rotary", "vane", "twin-screw", "reciprocating", "isothermal compressor", "oil-free", "variable-speed", "economiser"],
    "1.2": ["R32", "R454B", "R290", "propane", "CO₂", "carbon dioxide", "low-GWP", "natural refrigerant", "azeotrope", "zeotropic", "ionic liquid"],
    "1.3": ["micro-channel", "plate heat exchanger", "fin-tube", "enthalpy exchanger", "phase-change heat exchanger", "anti-fouling", "frost-free", "3-D printed"],
    "1.4": ["IPM motor", "SiC inverter", "PMSM", "sensor-less", "flux-weakening"],
    "1.5": ["oil-separator", "mist injection", "CRII", "low-viscosity oil"],
    "2.1": ["elastocaloric", "shape-memory", "Ni-Ti"], "2.2": ["electrocaloric", "ferroelectric"], "2.3": ["magnetocaloric", "gadolinium"],
    "2.4": ["ionocaloric", "ion-solvation"], "2.5": ["barocaloric"], "2.6": ["thermoelectric", "Peltier", "Seebeck"],
    "2.7": ["electrochemical compressor", "chemisorption"], "2.8": ["thermoacoustic"],
    "2.9": ["adsorption heat pump", "absorption heat pump", "lithium bromide"], "2.10": ["cascade heat pump", "hybrid heat pump"],
    "3.1": ["cascade", "booster", "trans-critical", "bi-valent", "ground-source"], "3.2": ["model predictive control", "MPC", "PID", "fault detection", "digital twin"],
    "3.3": ["smart-grid", "thermal district network", "hybrid boiler"], "4.1": ["ejector cycle", "regenerative cycle", "parallel-compressor"],
    "4.2": ["defrost", "icing sensor", "hot-gas bypass", "nano-coating"], "4.3": ["PCM storage", "phase change material", "heat battery", "stratified tank"],
    "5.1": ["tool-less", "snap-fit", "reversible adhesive", "design-for-disassembly", "DfD"], "5.2": ["modular cartridge", "remanufactur", "refurbish", "life-extension"],
    "5.3": ["recycled", "bio-polymer", "PCR plastic", "reclaimed copper", "low-GWP foam"], "5.4": ["additive manufacturing", "3-D print", "near-net shape", "binder-jet"],
    "5.5": ["predictive maintenance", "condition monitoring", "service-as-a-product"]
}
KW2CAT = {kw.lower(): cat for cat, kwlist in KWS.items() for kw in kwlist}

# ---- 3. ISO HEURISTIC ------------------------------------------------------
ISO_LEVERS = {
    "maintain": [
        "predictive maintenance", "preventive maintenance", "condition monitoring",
        "remote diagnostics", "fault detection", "service-as-a-product", "self-healing system"
    ],
    "reuse": [
        "remanufacture", "remanufacturing", "refurbish", "refurbished", "repair", "repairability",
        "cartridge", "replaceable module", "core exchange", "component reuse", "second life"
    ],
    "recycle": [
        "recycled", "recycling", "reclaim", "reclaimed", "material recovery",
        "mono-material", "material loop", "mechanical recycling", "chemical recycling", "closed-loop"
    ],
    "reduce": [
        "near-net shape", "additive manufacturing", "3d printing", "lightweight design",
        "material efficiency", "yield improvement", "low-waste", "minimal material use", "net-shape forming"
    ],
    "regenerate": [
        "bio-based", "biobased", "bio-polymer", "biopolymer", "biocomposite",
        "renewable feedstock", "natural material", "biodegradable", "biomaterial", "plant-derived"
    ]
}

import re
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def normalize(text):
    # Lowercase, strip punctuation, lemmatize
    words = re.findall(r'\b\w+\b', text.lower())
    return [lemmatizer.lemmatize(w) for w in words]

def iso_score(text):
    hits = []
    tokens = normalize(text)
    token_text = " ".join(tokens)  # faster for substring matching

    for kws in ISO_LEVERS.values():
        matched = sum(1 for kw in kws if any(kw in token_text for kw in normalize(kw)))
        hits.append(0 if matched == 0 else 1 if matched == 1 else 2 if matched == 2 else 3)
    return math.ceil(sum(hits) / 5)


# ---- 4. PROMPT GENERATOR ---------------------------------------------------
def make_prompt(title, abstract):
    return f"""
You are a sustainable heating technology analyst.

TITLE: {title}
ABSTRACT: {abstract}

Answer:
1. What is the core technical innovation? (max 25 words)
2. Is it relevant to heat pumps? ('yes' or 'no')
3. If yes, assign exactly ONE category code: {', '.join(CATEGORIES.keys())}
4. Score 0-3 for:
   a) cost_reduction_potential
   b) efficiency_gain_potential
   c) circularity_score (use ISO 59004 lever heuristic)
 Respond ONLY as JSON:
{{"is_relevant": "...", "summary": "...", "category": "...",
  "cost_score": ..., "efficiency_score": ..., "circularity_score": ...}}
""".strip()

# ---- 5. RUN PARALLEL CLASSIFICATION ----------------------------------------
print("▶︎ Loading and preparing data ...")
patents_df = pd.read_json("heat_pumps_patents.json", lines=True)
print("Total patents loaded:", len(patents_df))

if filter_keywords:
    patents_df["text"] = (patents_df["title"] + " " + patents_df["abstract"]).str.lower()
    patents_df = patents_df[patents_df["text"].apply(lambda t: any(k in t for k in KW2CAT))].copy()
    print("After keyword filtering:", len(patents_df))

# Load already processed IDs
processed_ids = set()
if OUTPUT_PATH.exists():
    with open(OUTPUT_PATH, "r") as f:
        processed_ids = {json.loads(line)["publication_number"] for line in f}
    print("Resuming from checkpoint. Already done:", len(processed_ids))

# Classifier function
def classify(row):
    if row["publication_number"] in processed_ids:
        return None
    try:
        prompt = make_prompt(row["title"], row["abstract"])
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=T_CLASSIFY,
            response_format={"type": "json_object"}
        )
        result = json.loads(response.choices[0].message.content)

        # Add both LLM and ISO circularity scores
        combined_text = f"{row['title']} {row['abstract']}"
        result["circularity_score_llm"] = result.pop("circularity_score")
        result["circularity_score_iso"] = iso_score(combined_text)

        result.update({
            "publication_number": row.get("publication_number", ""),
            "title": row["title"],
            "abstract": row["abstract"],
            "url": row.get("url", "")
        })
        return result
    except Exception as e:
        print(f"⚠️ Error on {row.get('publication_number', '')}: {e}")
        return None



# Run it
print("▶︎ Starting classification ...")
t0 = datetime.now()
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor, open(OUTPUT_PATH, "a") as f_out:
    futures = [executor.submit(classify, row) for _, row in patents_df.iterrows()]
    for future in tqdm(as_completed(futures), total=len(futures)):
        result = future.result()
        if result:
            f_out.write(json.dumps(result) + "\n")
print(f"🎉 Done in {datetime.now() - t0}")
print(f"✅ Output saved to: {OUTPUT_PATH}")

▶︎ Loading and preparing data ...
Total patents loaded: 45957
After keyword filtering: 9304
▶︎ Starting classification ...

  0%|          | 0/9304 [00:00<?, ?it/s]

2025-05-20 16:35:55,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:55,616 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:55,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:55,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:55,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:55,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:56,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:56,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:56,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:35:56,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 2/9304 [00:20<21:38:56,  8.38s/it]

⚠️ Error on US-10753655-B2: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'
2025-05-20 16:36:16,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 4/9304 [00:23<10:16:18,  3.98s/it]

⚠️ Error on CN-109340867-B: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'
2025-05-20 16:36:18,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 5/9304 [00:24<6:53:34,  2.67s/it]

2025-05-20 16:36:19,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 6/9304 [00:24<4:56:15,  1.91s/it]

⚠️ Error on KR-20210123516-A: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'

  0%|          | 8/9304 [00:24<2:37:56,  1.02s/it]

⚠️ Error on CN-215260626-U: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'
⚠️ Error on CN-210085240-U: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'

  0%|          | 10/9304 [00:25<1:55:31,  1.34it/s]

⚠️ Error on CN-108635894-B: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'
⚠️ Error on US-11255325-B2: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'
⚠️ Error on US-11994321-B2: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'

  0%|          | 12/9304 [00:26<1:11:51,  2.16it/s]

⚠️ Error on US-2023302875-A1: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'
2025-05-20 16:36:20,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:21,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 15/9304 [00:26<46:52,  3.30it/s]

2025-05-20 16:36:21,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:21,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 17/9304 [00:27<49:32,  3.12it/s]

2025-05-20 16:36:22,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 18/9304 [00:27<44:55,  3.44it/s]

2025-05-20 16:36:22,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 19/9304 [00:27<40:49,  3.79it/s]

2025-05-20 16:36:22,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:22,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 21/9304 [00:27<32:01,  4.83it/s]

2025-05-20 16:36:22,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 22/9304 [00:27<29:52,  5.18it/s]

2025-05-20 16:36:22,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:22,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 24/9304 [00:28<23:04,  6.70it/s]

2025-05-20 16:36:22,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:23,495 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 26/9304 [00:28<37:02,  4.18it/s]

2025-05-20 16:36:23,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 27/9304 [00:29<36:49,  4.20it/s]

2025-05-20 16:36:23,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:24,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 29/9304 [00:29<29:25,  5.25it/s]

2025-05-20 16:36:24,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:24,292 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:24,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 31/9304 [00:29<30:59,  4.99it/s]

2025-05-20 16:36:24,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 33/9304 [00:30<25:17,  6.11it/s]

2025-05-20 16:36:25,202 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 34/9304 [00:30<37:24,  4.13it/s]

2025-05-20 16:36:25,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:25,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 36/9304 [00:30<33:15,  4.64it/s]

2025-05-20 16:36:25,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:25,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 37/9304 [00:31<35:29,  4.35it/s]

2025-05-20 16:36:25,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:25,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:25,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:26,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 42/9304 [00:31<20:08,  7.67it/s]

2025-05-20 16:36:26,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 43/9304 [00:31<26:54,  5.74it/s]

2025-05-20 16:36:27,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 44/9304 [00:32<32:44,  4.71it/s]

2025-05-20 16:36:27,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:27,146 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  0%|          | 46/9304 [00:32<26:14,  5.88it/s]

2025-05-20 16:36:27,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:27,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 47/9304 [00:32<25:42,  6.00it/s]

2025-05-20 16:36:27,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 49/9304 [00:32<21:44,  7.10it/s]

2025-05-20 16:36:27,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 50/9304 [00:33<22:46,  6.77it/s]

2025-05-20 16:36:27,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 51/9304 [00:33<24:27,  6.31it/s]

2025-05-20 16:36:27,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:27,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 53/9304 [00:33<18:06,  8.51it/s]

2025-05-20 16:36:28,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:28,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 55/9304 [00:33<28:42,  5.37it/s]

2025-05-20 16:36:29,254 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 56/9304 [00:34<42:46,  3.60it/s]

2025-05-20 16:36:29,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 57/9304 [00:34<38:26,  4.01it/s]

2025-05-20 16:36:29,421 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:29,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:29,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:29,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 61/9304 [00:35<23:51,  6.46it/s]

2025-05-20 16:36:29,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:29,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:29,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 64/9304 [00:35<18:36,  8.28it/s]

2025-05-20 16:36:29,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:30,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 66/9304 [00:36<34:00,  4.53it/s]

2025-05-20 16:36:31,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:31,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 68/9304 [00:36<26:50,  5.74it/s]

2025-05-20 16:36:31,146 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:31,152 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 70/9304 [00:36<21:57,  7.01it/s]

2025-05-20 16:36:31,269 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:31,441 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 72/9304 [00:36<21:58,  7.00it/s]

2025-05-20 16:36:31,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:31,654 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 74/9304 [00:37<23:03,  6.67it/s]

2025-05-20 16:36:31,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:32,345 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:32,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 76/9304 [00:37<31:25,  4.89it/s]

2025-05-20 16:36:32,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:32,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:32,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 80/9304 [00:38<23:01,  6.68it/s]

2025-05-20 16:36:32,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:32,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:33,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 83/9304 [00:38<21:39,  7.09it/s]

2025-05-20 16:36:33,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 84/9304 [00:38<22:06,  6.95it/s]

2025-05-20 16:36:33,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 85/9304 [00:39<29:48,  5.15it/s]

2025-05-20 16:36:33,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 86/9304 [00:39<30:53,  4.97it/s]

2025-05-20 16:36:34,112 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 87/9304 [00:39<27:48,  5.53it/s]

2025-05-20 16:36:34,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:34,238 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 88/9304 [00:39<25:41,  5.98it/s]

2025-05-20 16:36:34,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 90/9304 [00:40<37:50,  4.06it/s]

2025-05-20 16:36:35,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 91/9304 [00:40<39:00,  3.94it/s]

2025-05-20 16:36:35,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:35,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:35,562 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 93/9304 [00:40<33:19,  4.61it/s]

2025-05-20 16:36:35,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 95/9304 [00:41<25:40,  5.98it/s]

2025-05-20 16:36:35,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:35,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 97/9304 [00:41<20:47,  7.38it/s]

2025-05-20 16:36:35,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:36,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 99/9304 [00:41<24:59,  6.14it/s]

2025-05-20 16:36:36,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 100/9304 [00:41<29:09,  5.26it/s]

2025-05-20 16:36:36,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 101/9304 [00:42<28:14,  5.43it/s]

2025-05-20 16:36:36,940 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 102/9304 [00:42<28:05,  5.46it/s]

2025-05-20 16:36:37,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 103/9304 [00:42<37:59,  4.04it/s]

2025-05-20 16:36:37,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 104/9304 [00:42<33:03,  4.64it/s]

2025-05-20 16:36:37,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:37,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 106/9304 [00:43<28:25,  5.39it/s]

2025-05-20 16:36:37,818 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:38,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 108/9304 [00:43<28:04,  5.46it/s]

2025-05-20 16:36:38,185 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:38,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:38,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 111/9304 [00:44<30:09,  5.08it/s]

2025-05-20 16:36:38,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 112/9304 [00:44<29:56,  5.12it/s]

2025-05-20 16:36:39,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:39,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:39,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 115/9304 [00:44<24:55,  6.15it/s]

2025-05-20 16:36:39,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|          | 116/9304 [00:45<29:43,  5.15it/s]

2025-05-20 16:36:39,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 117/9304 [00:45<28:54,  5.30it/s]

2025-05-20 16:36:40,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 118/9304 [00:45<42:45,  3.58it/s]

2025-05-20 16:36:40,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:40,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:40,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 121/9304 [00:46<29:24,  5.20it/s]

2025-05-20 16:36:40,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:40,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:40,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 124/9304 [00:46<22:12,  6.89it/s]

2025-05-20 16:36:41,262 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 125/9304 [00:46<28:44,  5.32it/s]

2025-05-20 16:36:41,696 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 126/9304 [00:47<31:31,  4.85it/s]

2025-05-20 16:36:41,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 127/9304 [00:47<32:09,  4.76it/s]

2025-05-20 16:36:42,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 128/9304 [00:47<30:06,  5.08it/s]

2025-05-20 16:36:42,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:42,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 130/9304 [00:47<25:02,  6.11it/s]

2025-05-20 16:36:42,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:42,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:42,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 133/9304 [00:47<19:14,  7.95it/s]

2025-05-20 16:36:42,866 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:42,940 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 134/9304 [00:48<26:25,  5.78it/s]

2025-05-20 16:36:43,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 136/9304 [00:48<27:33,  5.55it/s]

2025-05-20 16:36:43,332 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:43,573 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  1%|▏         | 138/9304 [00:48<27:17,  5.60it/s]

2025-05-20 16:36:43,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:43,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:44,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:44,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 141/9304 [00:49<25:35,  5.97it/s]

2025-05-20 16:36:44,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:44,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 143/9304 [00:49<21:07,  7.23it/s]

2025-05-20 16:36:44,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 145/9304 [00:50<27:01,  5.65it/s]

2025-05-20 16:36:44,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:45,050 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 147/9304 [00:50<26:31,  5.75it/s]

2025-05-20 16:36:45,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:45,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:45,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 150/9304 [00:50<23:22,  6.53it/s]

2025-05-20 16:36:45,502 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:45,700 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:45,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 152/9304 [00:51<22:51,  6.67it/s]

2025-05-20 16:36:45,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 154/9304 [00:51<24:18,  6.27it/s]

2025-05-20 16:36:46,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 155/9304 [00:52<35:27,  4.30it/s]

2025-05-20 16:36:46,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 156/9304 [00:52<32:55,  4.63it/s]

2025-05-20 16:36:46,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:47,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 158/9304 [00:52<26:06,  5.84it/s]

2025-05-20 16:36:47,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:47,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 160/9304 [00:52<26:29,  5.75it/s]

2025-05-20 16:36:47,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 161/9304 [00:52<25:59,  5.86it/s]

2025-05-20 16:36:47,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:47,613 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:48,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:48,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 164/9304 [00:53<31:48,  4.79it/s]

2025-05-20 16:36:48,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 166/9304 [00:53<25:22,  6.00it/s]

2025-05-20 16:36:48,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 167/9304 [00:54<28:56,  5.26it/s]

2025-05-20 16:36:48,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 168/9304 [00:54<27:20,  5.57it/s]

2025-05-20 16:36:49,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 169/9304 [00:54<29:41,  5.13it/s]

2025-05-20 16:36:49,286 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 170/9304 [00:54<32:16,  4.72it/s]

2025-05-20 16:36:49,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 171/9304 [00:55<41:57,  3.63it/s]

2025-05-20 16:36:49,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:50,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 173/9304 [00:55<30:23,  5.01it/s]

2025-05-20 16:36:50,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 174/9304 [00:55<32:32,  4.68it/s]

2025-05-20 16:36:50,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 175/9304 [00:55<29:57,  5.08it/s]

2025-05-20 16:36:50,807 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 176/9304 [00:56<41:40,  3.65it/s]

2025-05-20 16:36:51,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:51,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:51,209 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 179/9304 [00:56<25:29,  5.97it/s]

2025-05-20 16:36:51,220 - openai._base_client - INFO - Retrying request to /chat/completions in 0.461386 seconds
2025-05-20 16:36:51,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:51,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 181/9304 [00:57<29:09,  5.22it/s]

2025-05-20 16:36:51,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:51,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 183/9304 [00:57<27:55,  5.44it/s]

2025-05-20 16:36:52,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:52,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:52,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 185/9304 [00:57<29:57,  5.07it/s]

2025-05-20 16:36:52,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 187/9304 [00:57<23:32,  6.45it/s]

2025-05-20 16:36:52,867 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 188/9304 [00:58<30:28,  4.99it/s]

2025-05-20 16:36:53,198 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 189/9304 [00:58<31:37,  4.80it/s]

2025-05-20 16:36:53,250 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:53,431 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 191/9304 [00:58<29:41,  5.12it/s]

2025-05-20 16:36:53,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 192/9304 [00:59<32:48,  4.63it/s]

2025-05-20 16:36:53,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:53,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:54,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:54,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 195/9304 [00:59<23:00,  6.60it/s]

2025-05-20 16:36:54,490 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 197/9304 [00:59<26:56,  5.63it/s]

2025-05-20 16:36:54,694 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 198/9304 [01:00<25:42,  5.90it/s]

2025-05-20 16:36:55,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 199/9304 [01:00<32:08,  4.72it/s]

2025-05-20 16:36:55,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 200/9304 [01:00<33:53,  4.48it/s]

2025-05-20 16:36:55,579 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 201/9304 [01:00<33:48,  4.49it/s]

2025-05-20 16:36:55,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:55,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:55,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:55,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:56,274 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:56,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 206/9304 [01:01<27:52,  5.44it/s]

2025-05-20 16:36:56,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 208/9304 [01:02<32:57,  4.60it/s]

2025-05-20 16:36:57,020 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:57,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:57,095 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:57,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 212/9304 [01:02<22:55,  6.61it/s]

2025-05-20 16:36:57,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:57,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:57,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 215/9304 [01:03<24:51,  6.10it/s]

2025-05-20 16:36:58,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 216/9304 [01:03<31:39,  4.78it/s]

2025-05-20 16:36:58,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:58,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 218/9304 [01:03<29:36,  5.11it/s]

2025-05-20 16:36:58,676 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:59,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 220/9304 [01:04<30:39,  4.94it/s]

2025-05-20 16:36:59,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 221/9304 [01:04<29:40,  5.10it/s]

2025-05-20 16:36:59,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 222/9304 [01:04<33:08,  4.57it/s]

2025-05-20 16:36:59,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:36:59,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 224/9304 [01:05<26:53,  5.63it/s]

2025-05-20 16:36:59,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 225/9304 [01:05<26:50,  5.64it/s]

2025-05-20 16:37:00,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 226/9304 [01:05<31:07,  4.86it/s]

2025-05-20 16:37:00,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:00,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 228/9304 [01:06<31:16,  4.84it/s]

2025-05-20 16:37:00,798 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 229/9304 [01:06<32:59,  4.59it/s]

2025-05-20 16:37:01,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 230/9304 [01:06<29:37,  5.10it/s]

2025-05-20 16:37:01,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:01,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  2%|▏         | 232/9304 [01:06<22:55,  6.60it/s]

2025-05-20 16:37:01,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 233/9304 [01:06<28:04,  5.39it/s]

2025-05-20 16:37:01,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:01,764 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 235/9304 [01:07<26:24,  5.72it/s]

2025-05-20 16:37:02,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 236/9304 [01:07<35:48,  4.22it/s]

2025-05-20 16:37:02,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:02,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 238/9304 [01:07<27:47,  5.44it/s]

2025-05-20 16:37:02,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:02,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 239/9304 [01:07<25:16,  5.98it/s]

2025-05-20 16:37:03,177 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:03,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:03,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 241/9304 [01:08<31:59,  4.72it/s]

2025-05-20 16:37:03,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 244/9304 [01:08<25:58,  5.81it/s]

2025-05-20 16:37:03,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 245/9304 [01:09<26:15,  5.75it/s]

2025-05-20 16:37:03,766 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:04,094 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 247/9304 [01:09<26:07,  5.78it/s]

2025-05-20 16:37:04,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:04,684 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 249/9304 [01:10<32:57,  4.58it/s]

2025-05-20 16:37:04,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:04,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 250/9304 [01:10<30:38,  4.93it/s]

2025-05-20 16:37:05,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 252/9304 [01:10<29:59,  5.03it/s]

2025-05-20 16:37:05,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 253/9304 [01:10<31:07,  4.85it/s]

2025-05-20 16:37:05,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:05,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:05,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 256/9304 [01:11<25:40,  5.87it/s]

2025-05-20 16:37:05,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 257/9304 [01:11<25:59,  5.80it/s]

2025-05-20 16:37:06,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 258/9304 [01:11<27:47,  5.42it/s]

2025-05-20 16:37:06,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 259/9304 [01:12<35:20,  4.27it/s]

2025-05-20 16:37:06,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:06,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 261/9304 [01:12<26:49,  5.62it/s]

2025-05-20 16:37:06,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:06,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 263/9304 [01:12<21:40,  6.95it/s]

2025-05-20 16:37:07,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:07,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 265/9304 [01:12<27:17,  5.52it/s]

2025-05-20 16:37:07,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:07,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 267/9304 [01:12<20:58,  7.18it/s]

2025-05-20 16:37:08,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:08,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 269/9304 [01:13<25:39,  5.87it/s]

2025-05-20 16:37:08,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 270/9304 [01:13<28:15,  5.33it/s]

2025-05-20 16:37:08,429 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:08,431 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:08,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 273/9304 [01:13<20:25,  7.37it/s]

2025-05-20 16:37:08,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 274/9304 [01:14<25:37,  5.87it/s]

2025-05-20 16:37:09,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 275/9304 [01:14<32:12,  4.67it/s]

2025-05-20 16:37:09,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 276/9304 [01:14<31:16,  4.81it/s]

2025-05-20 16:37:09,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 277/9304 [01:14<29:29,  5.10it/s]

2025-05-20 16:37:09,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 278/9304 [01:15<32:59,  4.56it/s]

2025-05-20 16:37:10,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 279/9304 [01:15<30:42,  4.90it/s]

2025-05-20 16:37:10,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:10,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 281/9304 [01:15<22:24,  6.71it/s]

2025-05-20 16:37:10,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:10,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 283/9304 [01:15<16:43,  8.99it/s]

2025-05-20 16:37:10,670 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:11,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 285/9304 [01:16<33:50,  4.44it/s]

2025-05-20 16:37:11,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 286/9304 [01:16<36:08,  4.16it/s]

2025-05-20 16:37:11,536 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:11,684 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 288/9304 [01:17<27:20,  5.50it/s]

2025-05-20 16:37:11,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:11,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 290/9304 [01:17<28:51,  5.20it/s]

2025-05-20 16:37:12,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:12,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 292/9304 [01:17<23:24,  6.42it/s]

2025-05-20 16:37:12,292 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:13,051 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:13,051 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 294/9304 [01:18<34:29,  4.35it/s]

2025-05-20 16:37:13,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 296/9304 [01:18<31:12,  4.81it/s]

2025-05-20 16:37:13,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:13,386 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:13,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 299/9304 [01:18<22:30,  6.67it/s]

2025-05-20 16:37:13,568 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:13,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 301/9304 [01:19<21:46,  6.89it/s]

2025-05-20 16:37:14,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:14,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 302/9304 [01:19<32:34,  4.61it/s]

2025-05-20 16:37:14,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 304/9304 [01:20<36:08,  4.15it/s]

2025-05-20 16:37:15,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:15,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 306/9304 [01:20<27:47,  5.40it/s]

2025-05-20 16:37:15,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 307/9304 [01:20<32:33,  4.60it/s]

2025-05-20 16:37:15,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:15,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 309/9304 [01:21<31:20,  4.78it/s]

2025-05-20 16:37:15,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:16,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 310/9304 [01:21<30:23,  4.93it/s]

2025-05-20 16:37:16,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 312/9304 [01:21<29:23,  5.10it/s]

2025-05-20 16:37:16,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 313/9304 [01:21<29:54,  5.01it/s]

2025-05-20 16:37:16,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 314/9304 [01:22<31:50,  4.71it/s]

2025-05-20 16:37:16,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 315/9304 [01:22<34:48,  4.30it/s]

2025-05-20 16:37:17,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:17,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 316/9304 [01:22<30:39,  4.89it/s]

2025-05-20 16:37:17,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:17,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 318/9304 [01:22<27:10,  5.51it/s]

2025-05-20 16:37:17,667 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 320/9304 [01:23<24:25,  6.13it/s]

2025-05-20 16:37:18,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 321/9304 [01:23<24:54,  6.01it/s]

2025-05-20 16:37:18,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:18,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 323/9304 [01:23<24:41,  6.06it/s]

2025-05-20 16:37:18,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  3%|▎         | 324/9304 [01:23<29:12,  5.12it/s]

2025-05-20 16:37:18,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:18,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 326/9304 [01:24<25:09,  5.95it/s]

2025-05-20 16:37:19,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 327/9304 [01:24<25:21,  5.90it/s]

2025-05-20 16:37:19,359 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:19,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 328/9304 [01:24<31:21,  4.77it/s]

2025-05-20 16:37:19,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 330/9304 [01:25<27:13,  5.49it/s]

2025-05-20 16:37:19,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 331/9304 [01:25<25:27,  5.88it/s]

2025-05-20 16:37:20,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 332/9304 [01:25<29:40,  5.04it/s]

2025-05-20 16:37:20,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:20,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:20,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 334/9304 [01:25<22:53,  6.53it/s]

2025-05-20 16:37:20,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 336/9304 [01:25<20:56,  7.14it/s]

2025-05-20 16:37:20,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 337/9304 [01:26<24:07,  6.20it/s]

2025-05-20 16:37:20,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:20,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 339/9304 [01:26<24:51,  6.01it/s]

2025-05-20 16:37:21,251 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 340/9304 [01:26<25:11,  5.93it/s]

2025-05-20 16:37:21,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 341/9304 [01:26<30:56,  4.83it/s]

2025-05-20 16:37:22,094 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 342/9304 [01:27<40:00,  3.73it/s]

2025-05-20 16:37:22,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:22,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 343/9304 [01:27<38:28,  3.88it/s]

2025-05-20 16:37:22,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:22,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:22,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 346/9304 [01:27<26:32,  5.63it/s]

2025-05-20 16:37:22,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▎         | 348/9304 [01:28<25:42,  5.81it/s]

2025-05-20 16:37:23,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 349/9304 [01:28<29:34,  5.05it/s]

2025-05-20 16:37:23,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 350/9304 [01:29<39:15,  3.80it/s]

2025-05-20 16:37:23,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 351/9304 [01:29<34:46,  4.29it/s]

2025-05-20 16:37:23,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:24,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 353/9304 [01:29<27:56,  5.34it/s]

2025-05-20 16:37:24,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:24,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:24,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 355/9304 [01:29<27:19,  5.46it/s]

2025-05-20 16:37:24,603 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 357/9304 [01:29<20:38,  7.23it/s]

2025-05-20 16:37:24,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 358/9304 [01:30<27:44,  5.37it/s]

2025-05-20 16:37:24,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:25,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:25,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 360/9304 [01:30<22:23,  6.66it/s]

2025-05-20 16:37:25,657 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:25,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 362/9304 [01:31<28:53,  5.16it/s]

2025-05-20 16:37:26,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 364/9304 [01:31<27:16,  5.46it/s]

2025-05-20 16:37:26,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:26,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 366/9304 [01:31<23:04,  6.46it/s]

2025-05-20 16:37:26,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:26,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 368/9304 [01:31<25:15,  5.90it/s]

2025-05-20 16:37:26,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:26,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 370/9304 [01:32<22:53,  6.51it/s]

2025-05-20 16:37:27,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 371/9304 [01:32<31:09,  4.78it/s]

2025-05-20 16:37:27,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:27,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 373/9304 [01:32<23:10,  6.42it/s]

2025-05-20 16:37:27,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:27,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 374/9304 [01:32<22:02,  6.75it/s]

2025-05-20 16:37:27,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 376/9304 [01:33<20:41,  7.19it/s]

2025-05-20 16:37:28,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 377/9304 [01:33<27:30,  5.41it/s]

2025-05-20 16:37:28,172 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:28,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:28,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 380/9304 [01:33<19:48,  7.51it/s]

2025-05-20 16:37:28,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 381/9304 [01:34<24:43,  6.01it/s]

2025-05-20 16:37:28,709 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:29,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 383/9304 [01:34<26:50,  5.54it/s]

2025-05-20 16:37:29,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:29,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 385/9304 [01:34<27:28,  5.41it/s]

2025-05-20 16:37:29,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 386/9304 [01:35<30:29,  4.88it/s]

2025-05-20 16:37:29,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:29,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 388/9304 [01:35<24:56,  5.96it/s]

2025-05-20 16:37:30,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 389/9304 [01:35<24:31,  6.06it/s]

2025-05-20 16:37:30,185 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:30,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 390/9304 [01:35<23:57,  6.20it/s]

2025-05-20 16:37:30,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:30,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 393/9304 [01:35<15:09,  9.80it/s]

2025-05-20 16:37:30,425 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:31,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:31,513 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 395/9304 [01:36<36:12,  4.10it/s]

2025-05-20 16:37:31,648 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 397/9304 [01:37<32:54,  4.51it/s]

2025-05-20 16:37:31,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:31,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:31,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 399/9304 [01:37<25:20,  5.86it/s]

2025-05-20 16:37:32,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 401/9304 [01:37<20:52,  7.11it/s]

2025-05-20 16:37:32,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:32,270 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 403/9304 [01:37<18:54,  7.85it/s]

2025-05-20 16:37:32,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:33,020 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 405/9304 [01:38<29:21,  5.05it/s]

2025-05-20 16:37:33,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:33,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 406/9304 [01:38<32:00,  4.63it/s]

2025-05-20 16:37:33,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:33,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:33,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:33,614 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 410/9304 [01:38<21:04,  7.03it/s]

2025-05-20 16:37:33,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 412/9304 [01:39<19:18,  7.68it/s]

2025-05-20 16:37:34,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 413/9304 [01:39<24:18,  6.09it/s]

2025-05-20 16:37:34,166 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 414/9304 [01:39<22:33,  6.57it/s]

2025-05-20 16:37:34,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 415/9304 [01:40<35:29,  4.17it/s]

2025-05-20 16:37:34,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:34,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  4%|▍         | 417/9304 [01:40<25:10,  5.89it/s]

2025-05-20 16:37:35,215 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:35,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 419/9304 [01:40<25:13,  5.87it/s]

2025-05-20 16:37:35,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 420/9304 [01:40<26:57,  5.49it/s]

2025-05-20 16:37:35,503 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:35,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 422/9304 [01:40<20:33,  7.20it/s]

2025-05-20 16:37:35,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 423/9304 [01:41<20:43,  7.14it/s]

2025-05-20 16:37:36,401 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:36,404 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:36,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 424/9304 [01:41<37:37,  3.93it/s]

2025-05-20 16:37:36,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:36,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 427/9304 [01:41<23:41,  6.24it/s]

2025-05-20 16:37:36,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 429/9304 [01:42<25:25,  5.82it/s]

2025-05-20 16:37:37,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 430/9304 [01:42<25:59,  5.69it/s]

2025-05-20 16:37:37,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:37,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:37,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:37,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 434/9304 [01:43<23:39,  6.25it/s]

2025-05-20 16:37:37,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 435/9304 [01:43<22:20,  6.62it/s]

2025-05-20 16:37:37,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 436/9304 [01:43<22:45,  6.49it/s]

2025-05-20 16:37:38,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:38,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 438/9304 [01:43<21:49,  6.77it/s]

2025-05-20 16:37:38,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 439/9304 [01:43<21:46,  6.79it/s]

2025-05-20 16:37:38,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:38,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 441/9304 [01:44<22:09,  6.67it/s]

2025-05-20 16:37:38,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:39,179 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 442/9304 [01:44<30:16,  4.88it/s]

2025-05-20 16:37:39,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 444/9304 [01:44<23:33,  6.27it/s]

2025-05-20 16:37:39,429 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:39,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 445/9304 [01:44<22:48,  6.48it/s]

2025-05-20 16:37:39,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:39,847 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 447/9304 [01:45<24:15,  6.08it/s]

2025-05-20 16:37:40,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 449/9304 [01:45<30:31,  4.84it/s]

2025-05-20 16:37:40,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 450/9304 [01:45<29:57,  4.92it/s]

2025-05-20 16:37:40,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:40,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 452/9304 [01:46<21:49,  6.76it/s]

2025-05-20 16:37:40,813 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 453/9304 [01:46<24:45,  5.96it/s]

2025-05-20 16:37:40,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:41,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 455/9304 [01:46<18:39,  7.91it/s]

2025-05-20 16:37:41,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:41,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 457/9304 [01:46<24:42,  5.97it/s]

2025-05-20 16:37:41,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 458/9304 [01:47<34:17,  4.30it/s]

2025-05-20 16:37:42,345 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 459/9304 [01:47<36:21,  4.05it/s]

2025-05-20 16:37:42,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:42,423 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:42,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:42,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 463/9304 [01:48<23:32,  6.26it/s]

2025-05-20 16:37:42,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▍         | 464/9304 [01:48<23:59,  6.14it/s]

2025-05-20 16:37:42,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:42,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:43,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 467/9304 [01:48<25:58,  5.67it/s]

2025-05-20 16:37:43,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:43,859 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 468/9304 [01:49<30:59,  4.75it/s]

2025-05-20 16:37:44,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 470/9304 [01:49<26:53,  5.48it/s]

2025-05-20 16:37:44,235 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:44,237 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 471/9304 [01:49<25:34,  5.76it/s]

2025-05-20 16:37:44,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 473/9304 [01:49<22:29,  6.54it/s]

2025-05-20 16:37:44,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:44,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:44,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:45,080 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 476/9304 [01:50<25:41,  5.73it/s]

2025-05-20 16:37:45,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 478/9304 [01:50<24:00,  6.13it/s]

2025-05-20 16:37:45,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 479/9304 [01:50<24:11,  6.08it/s]

2025-05-20 16:37:45,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 480/9304 [01:51<31:03,  4.74it/s]

2025-05-20 16:37:46,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 481/9304 [01:51<31:07,  4.72it/s]

2025-05-20 16:37:46,139 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:46,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 483/9304 [01:51<27:50,  5.28it/s]

2025-05-20 16:37:46,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:46,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 485/9304 [01:51<23:31,  6.25it/s]

2025-05-20 16:37:46,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:46,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:46,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 487/9304 [01:52<21:52,  6.72it/s]

2025-05-20 16:37:47,202 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 489/9304 [01:52<23:34,  6.23it/s]

2025-05-20 16:37:47,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:47,813 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 490/9304 [01:53<33:50,  4.34it/s]

2025-05-20 16:37:47,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 492/9304 [01:53<28:27,  5.16it/s]

2025-05-20 16:37:48,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:48,253 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 494/9304 [01:53<26:24,  5.56it/s]

2025-05-20 16:37:48,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:48,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 495/9304 [01:53<24:47,  5.92it/s]

2025-05-20 16:37:48,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 497/9304 [01:54<21:40,  6.77it/s]

2025-05-20 16:37:48,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:48,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 499/9304 [01:54<19:54,  7.37it/s]

2025-05-20 16:37:49,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:49,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 500/9304 [01:54<31:42,  4.63it/s]

2025-05-20 16:37:49,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:49,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 503/9304 [01:55<22:41,  6.47it/s]

2025-05-20 16:37:49,763 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:49,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 505/9304 [01:55<25:58,  5.65it/s]

2025-05-20 16:37:50,236 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 506/9304 [01:55<29:22,  4.99it/s]

2025-05-20 16:37:50,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 507/9304 [01:55<27:46,  5.28it/s]

2025-05-20 16:37:51,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 508/9304 [01:56<33:40,  4.35it/s]

2025-05-20 16:37:51,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:51,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  5%|▌         | 510/9304 [01:56<30:50,  4.75it/s]

2025-05-20 16:37:51,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:51,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 512/9304 [01:56<22:40,  6.46it/s]

2025-05-20 16:37:51,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 513/9304 [01:57<26:20,  5.56it/s]

2025-05-20 16:37:51,940 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 514/9304 [01:57<26:35,  5.51it/s]

2025-05-20 16:37:52,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 515/9304 [01:57<30:47,  4.76it/s]

2025-05-20 16:37:52,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:52,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 517/9304 [01:57<30:38,  4.78it/s]

2025-05-20 16:37:52,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:52,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 519/9304 [01:58<22:51,  6.41it/s]

2025-05-20 16:37:53,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 520/9304 [01:58<35:13,  4.16it/s]

2025-05-20 16:37:53,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:53,709 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 522/9304 [01:59<33:26,  4.38it/s]

2025-05-20 16:37:53,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:54,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 524/9304 [01:59<29:31,  4.96it/s]

2025-05-20 16:37:54,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:54,215 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 526/9304 [01:59<23:19,  6.27it/s]

2025-05-20 16:37:54,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:54,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 528/9304 [01:59<19:31,  7.49it/s]

2025-05-20 16:37:54,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 529/9304 [01:59<20:13,  7.23it/s]

2025-05-20 16:37:54,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 530/9304 [02:00<29:55,  4.89it/s]

2025-05-20 16:37:55,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 531/9304 [02:00<32:03,  4.56it/s]

2025-05-20 16:37:55,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 532/9304 [02:00<36:54,  3.96it/s]

2025-05-20 16:37:55,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:55,638 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:55,841 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 535/9304 [02:01<23:46,  6.15it/s]

2025-05-20 16:37:55,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:55,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:55,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 537/9304 [02:01<19:28,  7.51it/s]

2025-05-20 16:37:56,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 539/9304 [02:02<31:57,  4.57it/s]

2025-05-20 16:37:56,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 540/9304 [02:02<36:26,  4.01it/s]

2025-05-20 16:37:57,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 541/9304 [02:02<35:00,  4.17it/s]

2025-05-20 16:37:57,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:57,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:57,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 544/9304 [02:03<25:31,  5.72it/s]

2025-05-20 16:37:57,696 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:57,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:57,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 546/9304 [02:03<20:57,  6.96it/s]

2025-05-20 16:37:57,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 548/9304 [02:03<20:23,  7.15it/s]

2025-05-20 16:37:58,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 549/9304 [02:03<26:21,  5.53it/s]

2025-05-20 16:37:58,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 550/9304 [02:04<31:47,  4.59it/s]

2025-05-20 16:37:58,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:58,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:59,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 552/9304 [02:04<26:29,  5.51it/s]

2025-05-20 16:37:59,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:37:59,094 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 555/9304 [02:04<20:33,  7.09it/s]

2025-05-20 16:37:59,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 556/9304 [02:04<21:28,  6.79it/s]

2025-05-20 16:37:59,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 557/9304 [02:05<25:46,  5.65it/s]

2025-05-20 16:37:59,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:00,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 559/9304 [02:05<31:32,  4.62it/s]

2025-05-20 16:38:00,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 560/9304 [02:05<31:02,  4.70it/s]

2025-05-20 16:38:00,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:00,694 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 562/9304 [02:06<22:44,  6.41it/s]

2025-05-20 16:38:00,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:00,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 564/9304 [02:06<23:26,  6.22it/s]

2025-05-20 16:38:01,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:01,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:01,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 567/9304 [02:06<15:49,  9.21it/s]

2025-05-20 16:38:01,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:01,839 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 569/9304 [02:07<26:04,  5.58it/s]

2025-05-20 16:38:01,988 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:02,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 571/9304 [02:07<22:50,  6.37it/s]

2025-05-20 16:38:02,361 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:02,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 573/9304 [02:07<25:04,  5.80it/s]

2025-05-20 16:38:02,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 574/9304 [02:07<25:22,  5.73it/s]

2025-05-20 16:38:02,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:02,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 576/9304 [02:08<22:18,  6.52it/s]

2025-05-20 16:38:02,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:03,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:03,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 578/9304 [02:08<26:20,  5.52it/s]

2025-05-20 16:38:03,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 580/9304 [02:08<24:03,  6.04it/s]

2025-05-20 16:38:03,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:03,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▌         | 581/9304 [02:09<25:07,  5.79it/s]

2025-05-20 16:38:04,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 583/9304 [02:09<26:46,  5.43it/s]

2025-05-20 16:38:04,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:04,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 584/9304 [02:09<24:55,  5.83it/s]

2025-05-20 16:38:04,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:05,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 587/9304 [02:10<28:34,  5.08it/s]

2025-05-20 16:38:05,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:05,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 589/9304 [02:11<34:34,  4.20it/s]

2025-05-20 16:38:05,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 590/9304 [02:11<31:54,  4.55it/s]

2025-05-20 16:38:05,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:06,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 592/9304 [02:11<25:06,  5.78it/s]

2025-05-20 16:38:06,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:06,150 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 593/9304 [02:11<24:08,  6.01it/s]

2025-05-20 16:38:06,404 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 595/9304 [02:11<25:33,  5.68it/s]

2025-05-20 16:38:06,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 596/9304 [02:12<26:26,  5.49it/s]

2025-05-20 16:38:07,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 597/9304 [02:12<34:10,  4.25it/s]

2025-05-20 16:38:07,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 598/9304 [02:12<32:08,  4.52it/s]

2025-05-20 16:38:07,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:07,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 600/9304 [02:12<25:46,  5.63it/s]

2025-05-20 16:38:07,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:07,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 602/9304 [02:13<24:35,  5.90it/s]

2025-05-20 16:38:08,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  6%|▋         | 603/9304 [02:13<32:50,  4.42it/s]

2025-05-20 16:38:08,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:08,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:08,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 606/9304 [02:14<26:58,  5.37it/s]

2025-05-20 16:38:08,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 607/9304 [02:14<24:49,  5.84it/s]

2025-05-20 16:38:08,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 608/9304 [02:14<24:08,  6.00it/s]

2025-05-20 16:38:09,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 609/9304 [02:14<27:52,  5.20it/s]

2025-05-20 16:38:09,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:09,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 611/9304 [02:14<24:19,  5.96it/s]

2025-05-20 16:38:09,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:09,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 613/9304 [02:15<25:46,  5.62it/s]

2025-05-20 16:38:09,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:10,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 615/9304 [02:15<29:20,  4.94it/s]

2025-05-20 16:38:10,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:10,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:10,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:11,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 619/9304 [02:16<28:42,  5.04it/s]

2025-05-20 16:38:11,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 620/9304 [02:16<29:19,  4.94it/s]

2025-05-20 16:38:11,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 621/9304 [02:17<35:33,  4.07it/s]

2025-05-20 16:38:12,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:12,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 622/9304 [02:17<33:22,  4.33it/s]

2025-05-20 16:38:12,061 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:12,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:12,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 625/9304 [02:17<25:02,  5.78it/s]

2025-05-20 16:38:12,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 627/9304 [02:18<26:40,  5.42it/s]

2025-05-20 16:38:13,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:13,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 628/9304 [02:18<28:06,  5.14it/s]

2025-05-20 16:38:13,199 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 630/9304 [02:18<23:34,  6.13it/s]

2025-05-20 16:38:13,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 631/9304 [02:18<28:04,  5.15it/s]

2025-05-20 16:38:13,798 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 632/9304 [02:19<39:05,  3.70it/s]

2025-05-20 16:38:14,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:14,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:14,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 635/9304 [02:19<22:37,  6.38it/s]

2025-05-20 16:38:14,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:14,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 637/9304 [02:20<32:00,  4.51it/s]

2025-05-20 16:38:15,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 638/9304 [02:20<33:20,  4.33it/s]

2025-05-20 16:38:15,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 639/9304 [02:20<32:12,  4.48it/s]

2025-05-20 16:38:15,404 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:15,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 641/9304 [02:20<27:48,  5.19it/s]

2025-05-20 16:38:15,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:15,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 643/9304 [02:21<23:47,  6.07it/s]

2025-05-20 16:38:15,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:16,155 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 645/9304 [02:21<28:14,  5.11it/s]

2025-05-20 16:38:16,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 646/9304 [02:22<30:02,  4.80it/s]

2025-05-20 16:38:16,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:16,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 648/9304 [02:22<22:26,  6.43it/s]

2025-05-20 16:38:17,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 649/9304 [02:22<29:19,  4.92it/s]

2025-05-20 16:38:17,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 650/9304 [02:22<28:25,  5.08it/s]

2025-05-20 16:38:17,422 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:17,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 651/9304 [02:22<26:44,  5.39it/s]

2025-05-20 16:38:17,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 653/9304 [02:23<21:20,  6.75it/s]

2025-05-20 16:38:17,971 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 654/9304 [02:23<31:27,  4.58it/s]

2025-05-20 16:38:18,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 655/9304 [02:23<33:26,  4.31it/s]

2025-05-20 16:38:18,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:18,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 656/9304 [02:24<34:46,  4.14it/s]

2025-05-20 16:38:18,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:18,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:19,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 659/9304 [02:24<25:40,  5.61it/s]

2025-05-20 16:38:19,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 661/9304 [02:24<25:38,  5.62it/s]

2025-05-20 16:38:19,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:19,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:20,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 664/9304 [02:25<32:16,  4.46it/s]

2025-05-20 16:38:20,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:20,513 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 666/9304 [02:25<29:29,  4.88it/s]

2025-05-20 16:38:20,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:20,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:20,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 669/9304 [02:26<22:19,  6.45it/s]

2025-05-20 16:38:21,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 670/9304 [02:26<32:30,  4.43it/s]

2025-05-20 16:38:21,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 671/9304 [02:26<31:49,  4.52it/s]

2025-05-20 16:38:21,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:21,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:21,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 674/9304 [02:27<25:37,  5.61it/s]

2025-05-20 16:38:22,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:22,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 675/9304 [02:27<25:52,  5.56it/s]

2025-05-20 16:38:22,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 677/9304 [02:27<24:03,  5.98it/s]

2025-05-20 16:38:22,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 678/9304 [02:28<29:50,  4.82it/s]

2025-05-20 16:38:22,967 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 679/9304 [02:28<27:22,  5.25it/s]

2025-05-20 16:38:22,992 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:23,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:23,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 681/9304 [02:28<21:00,  6.84it/s]

2025-05-20 16:38:23,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 683/9304 [02:28<21:50,  6.58it/s]

2025-05-20 16:38:23,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 684/9304 [02:28<21:37,  6.64it/s]

2025-05-20 16:38:23,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:24,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 686/9304 [02:29<32:53,  4.37it/s]

2025-05-20 16:38:24,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 687/9304 [02:30<40:00,  3.59it/s]

2025-05-20 16:38:24,863 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:24,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:25,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 690/9304 [02:30<27:09,  5.29it/s]

2025-05-20 16:38:25,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:25,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:25,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 693/9304 [02:31<30:04,  4.77it/s]

2025-05-20 16:38:25,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 694/9304 [02:31<30:42,  4.67it/s]

2025-05-20 16:38:26,081 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 695/9304 [02:31<28:01,  5.12it/s]

2025-05-20 16:38:26,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 696/9304 [02:31<35:31,  4.04it/s]

2025-05-20 16:38:26,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  7%|▋         | 697/9304 [02:32<31:16,  4.59it/s]

2025-05-20 16:38:26,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 698/9304 [02:32<28:39,  5.01it/s]

2025-05-20 16:38:27,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:27,166 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 699/9304 [02:32<32:58,  4.35it/s]

2025-05-20 16:38:27,194 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 701/9304 [02:32<22:46,  6.29it/s]

2025-05-20 16:38:27,366 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 702/9304 [02:32<23:13,  6.17it/s]

2025-05-20 16:38:27,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 703/9304 [02:33<35:41,  4.02it/s]

2025-05-20 16:38:28,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:28,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 704/9304 [02:33<30:32,  4.69it/s]

2025-05-20 16:38:28,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 706/9304 [02:33<28:49,  4.97it/s]

2025-05-20 16:38:28,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:28,603 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 707/9304 [02:33<26:55,  5.32it/s]

2025-05-20 16:38:28,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 709/9304 [02:34<32:11,  4.45it/s]

2025-05-20 16:38:29,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 710/9304 [02:34<36:37,  3.91it/s]

2025-05-20 16:38:29,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 711/9304 [02:34<31:28,  4.55it/s]

2025-05-20 16:38:29,636 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:29,906 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:29,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 713/9304 [02:35<28:48,  4.97it/s]

2025-05-20 16:38:30,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 715/9304 [02:35<28:03,  5.10it/s]

2025-05-20 16:38:30,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:30,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 716/9304 [02:35<27:06,  5.28it/s]

2025-05-20 16:38:30,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 718/9304 [02:35<19:59,  7.16it/s]

2025-05-20 16:38:30,976 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 719/9304 [02:36<26:40,  5.36it/s]

2025-05-20 16:38:31,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 720/9304 [02:36<32:07,  4.45it/s]

2025-05-20 16:38:31,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:31,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 722/9304 [02:36<27:32,  5.19it/s]

2025-05-20 16:38:32,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 723/9304 [02:37<39:51,  3.59it/s]

2025-05-20 16:38:32,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:32,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:32,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 725/9304 [02:37<29:42,  4.81it/s]

2025-05-20 16:38:32,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 727/9304 [02:38<27:35,  5.18it/s]

2025-05-20 16:38:32,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 728/9304 [02:38<32:20,  4.42it/s]

2025-05-20 16:38:33,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:33,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 730/9304 [02:38<28:28,  5.02it/s]

2025-05-20 16:38:33,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 731/9304 [02:38<30:02,  4.76it/s]

2025-05-20 16:38:33,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 732/9304 [02:39<27:28,  5.20it/s]

2025-05-20 16:38:33,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 733/9304 [02:39<32:22,  4.41it/s]

2025-05-20 16:38:34,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:34,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:34,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:34,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 736/9304 [02:39<25:42,  5.55it/s]

2025-05-20 16:38:34,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:34,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 739/9304 [02:40<20:34,  6.94it/s]

2025-05-20 16:38:35,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:35,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 740/9304 [02:40<29:40,  4.81it/s]

2025-05-20 16:38:35,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 742/9304 [02:40<25:45,  5.54it/s]

2025-05-20 16:38:35,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:36,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 744/9304 [02:41<28:35,  4.99it/s]

2025-05-20 16:38:36,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:36,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:36,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:36,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 747/9304 [02:41<22:11,  6.43it/s]

2025-05-20 16:38:36,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 749/9304 [02:41<18:26,  7.73it/s]

2025-05-20 16:38:37,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:37,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 751/9304 [02:42<30:05,  4.74it/s]

2025-05-20 16:38:37,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:37,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:37,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 753/9304 [02:42<25:02,  5.69it/s]

2025-05-20 16:38:37,713 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 755/9304 [02:43<23:18,  6.11it/s]

2025-05-20 16:38:37,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:37,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 757/9304 [02:43<18:41,  7.62it/s]

2025-05-20 16:38:37,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:38,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 759/9304 [02:43<21:49,  6.52it/s]

2025-05-20 16:38:38,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 760/9304 [02:44<31:24,  4.53it/s]

2025-05-20 16:38:38,822 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:38,824 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:39,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 763/9304 [02:44<24:28,  5.82it/s]

2025-05-20 16:38:39,288 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 764/9304 [02:44<24:37,  5.78it/s]

2025-05-20 16:38:39,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:39,565 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 766/9304 [02:44<22:55,  6.21it/s]

2025-05-20 16:38:39,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:39,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 768/9304 [02:45<22:22,  6.36it/s]

2025-05-20 16:38:40,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:40,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 769/9304 [02:45<27:59,  5.08it/s]

2025-05-20 16:38:40,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:40,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 772/9304 [02:45<17:53,  7.95it/s]

2025-05-20 16:38:40,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:40,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 774/9304 [02:46<22:57,  6.19it/s]

2025-05-20 16:38:41,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:41,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 775/9304 [02:46<28:45,  4.94it/s]

2025-05-20 16:38:41,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 777/9304 [02:46<23:09,  6.14it/s]

2025-05-20 16:38:41,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:41,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 779/9304 [02:47<25:17,  5.62it/s]

2025-05-20 16:38:41,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:41,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:42,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 781/9304 [02:47<22:31,  6.30it/s]

2025-05-20 16:38:42,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 783/9304 [02:48<35:04,  4.05it/s]

2025-05-20 16:38:42,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:42,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:43,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 786/9304 [02:48<27:04,  5.24it/s]

2025-05-20 16:38:43,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:43,513 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  8%|▊         | 788/9304 [02:48<24:43,  5.74it/s]

2025-05-20 16:38:43,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:43,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:43,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 791/9304 [02:48<17:28,  8.12it/s]

2025-05-20 16:38:44,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:44,502 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 793/9304 [02:49<29:12,  4.86it/s]

2025-05-20 16:38:44,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 794/9304 [02:50<30:36,  4.63it/s]

2025-05-20 16:38:44,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:44,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 795/9304 [02:50<29:39,  4.78it/s]

2025-05-20 16:38:44,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:45,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 798/9304 [02:50<26:13,  5.41it/s]

2025-05-20 16:38:45,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 799/9304 [02:50<25:26,  5.57it/s]

2025-05-20 16:38:45,730 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 800/9304 [02:51<26:32,  5.34it/s]

2025-05-20 16:38:46,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:46,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 801/9304 [02:51<33:53,  4.18it/s]

2025-05-20 16:38:46,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 803/9304 [02:51<28:41,  4.94it/s]

2025-05-20 16:38:46,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:46,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 805/9304 [02:52<29:12,  4.85it/s]

2025-05-20 16:38:46,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 806/9304 [02:52<26:57,  5.25it/s]

2025-05-20 16:38:47,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 807/9304 [02:52<34:35,  4.09it/s]

2025-05-20 16:38:47,492 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:47,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 809/9304 [02:52<26:17,  5.39it/s]

2025-05-20 16:38:47,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:47,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:47,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 812/9304 [02:53<19:49,  7.14it/s]

2025-05-20 16:38:47,966 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▊         | 813/9304 [02:53<22:48,  6.21it/s]

2025-05-20 16:38:48,227 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:48,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 815/9304 [02:53<26:42,  5.30it/s]

2025-05-20 16:38:48,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 816/9304 [02:54<28:00,  5.05it/s]

2025-05-20 16:38:49,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 817/9304 [02:54<32:26,  4.36it/s]

2025-05-20 16:38:49,258 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:49,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:49,475 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 819/9304 [02:54<25:55,  5.45it/s]

2025-05-20 16:38:49,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:49,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 822/9304 [02:55<21:50,  6.47it/s]

2025-05-20 16:38:50,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 823/9304 [02:55<30:25,  4.64it/s]

2025-05-20 16:38:50,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:50,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:50,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:50,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 827/9304 [02:56<25:02,  5.64it/s]

2025-05-20 16:38:50,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 828/9304 [02:56<26:15,  5.38it/s]

2025-05-20 16:38:51,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:51,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:51,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 831/9304 [02:56<23:28,  6.01it/s]

2025-05-20 16:38:51,536 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:51,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:51,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 834/9304 [02:57<19:53,  7.10it/s]

2025-05-20 16:38:51,902 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:51,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 835/9304 [02:57<19:02,  7.41it/s]

2025-05-20 16:38:52,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 837/9304 [02:57<26:00,  5.43it/s]

2025-05-20 16:38:52,536 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:52,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 839/9304 [02:58<25:01,  5.64it/s]

2025-05-20 16:38:53,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 840/9304 [02:58<34:56,  4.04it/s]

2025-05-20 16:38:53,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:53,502 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 842/9304 [02:58<27:02,  5.22it/s]

2025-05-20 16:38:53,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:53,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:53,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 845/9304 [02:59<23:44,  5.94it/s]

2025-05-20 16:38:54,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 846/9304 [02:59<26:13,  5.38it/s]

2025-05-20 16:38:54,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 847/9304 [02:59<24:30,  5.75it/s]

2025-05-20 16:38:54,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 848/9304 [02:59<24:15,  5.81it/s]

2025-05-20 16:38:54,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 849/9304 [03:00<26:00,  5.42it/s]

2025-05-20 16:38:54,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:54,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 850/9304 [03:00<27:07,  5.20it/s]

2025-05-20 16:38:55,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 852/9304 [03:00<24:48,  5.68it/s]

2025-05-20 16:38:55,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:55,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 854/9304 [03:00<23:54,  5.89it/s]

2025-05-20 16:38:55,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 855/9304 [03:01<26:28,  5.32it/s]

2025-05-20 16:38:55,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:55,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 857/9304 [03:01<19:16,  7.31it/s]

2025-05-20 16:38:56,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 858/9304 [03:01<24:03,  5.85it/s]

2025-05-20 16:38:56,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 859/9304 [03:01<25:38,  5.49it/s]

2025-05-20 16:38:56,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:56,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 860/9304 [03:02<26:31,  5.31it/s]

2025-05-20 16:38:57,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 862/9304 [03:02<26:17,  5.35it/s]

2025-05-20 16:38:57,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:57,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:57,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:57,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:57,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 866/9304 [03:03<25:04,  5.61it/s]

2025-05-20 16:38:58,194 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:58,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 868/9304 [03:03<28:20,  4.96it/s]

2025-05-20 16:38:58,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:58,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 871/9304 [03:03<23:11,  6.06it/s]

2025-05-20 16:38:58,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:58,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 872/9304 [03:04<27:20,  5.14it/s]

2025-05-20 16:38:59,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 874/9304 [03:04<23:19,  6.02it/s]

2025-05-20 16:38:59,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:59,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:59,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 877/9304 [03:04<21:36,  6.50it/s]

2025-05-20 16:38:59,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:38:59,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 879/9304 [03:05<21:46,  6.45it/s]

2025-05-20 16:38:59,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 880/9304 [03:05<22:11,  6.33it/s]

2025-05-20 16:39:00,619 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 881/9304 [03:05<33:10,  4.23it/s]

2025-05-20 16:39:00,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  9%|▉         | 882/9304 [03:06<32:02,  4.38it/s]

2025-05-20 16:39:00,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:00,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 884/9304 [03:06<24:18,  5.77it/s]

2025-05-20 16:39:00,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:01,037 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 886/9304 [03:06<20:45,  6.76it/s]

2025-05-20 16:39:01,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:01,199 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:01,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 889/9304 [03:06<19:51,  7.06it/s]

2025-05-20 16:39:01,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:02,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 891/9304 [03:07<30:57,  4.53it/s]

2025-05-20 16:39:02,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:02,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:02,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 894/9304 [03:08<24:52,  5.63it/s]

2025-05-20 16:39:02,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:02,795 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:02,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 897/9304 [03:08<19:57,  7.02it/s]

2025-05-20 16:39:02,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:03,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 899/9304 [03:08<19:09,  7.31it/s]

2025-05-20 16:39:03,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:03,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:03,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 901/9304 [03:09<27:07,  5.16it/s]

2025-05-20 16:39:04,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 903/9304 [03:09<25:14,  5.55it/s]

2025-05-20 16:39:04,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 904/9304 [03:09<24:37,  5.69it/s]

2025-05-20 16:39:04,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:04,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:04,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 906/9304 [03:09<21:55,  6.39it/s]

2025-05-20 16:39:05,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 908/9304 [03:10<27:41,  5.05it/s]

2025-05-20 16:39:05,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:05,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 909/9304 [03:10<30:45,  4.55it/s]

2025-05-20 16:39:05,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 911/9304 [03:10<24:12,  5.78it/s]

2025-05-20 16:39:05,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:05,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 913/9304 [03:11<21:33,  6.49it/s]

2025-05-20 16:39:05,962 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 914/9304 [03:11<22:01,  6.35it/s]

2025-05-20 16:39:06,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:06,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 916/9304 [03:11<22:44,  6.15it/s]

2025-05-20 16:39:06,422 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 917/9304 [03:11<21:46,  6.42it/s]

2025-05-20 16:39:06,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:06,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 919/9304 [03:12<24:00,  5.82it/s]

2025-05-20 16:39:07,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:07,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 920/9304 [03:12<27:41,  5.04it/s]

2025-05-20 16:39:07,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:07,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 922/9304 [03:12<23:16,  6.00it/s]

2025-05-20 16:39:07,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 924/9304 [03:13<24:13,  5.77it/s]

2025-05-20 16:39:07,833 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:07,992 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 926/9304 [03:13<21:40,  6.44it/s]

2025-05-20 16:39:08,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 927/9304 [03:13<22:51,  6.11it/s]

2025-05-20 16:39:08,269 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:08,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:08,559 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|▉         | 929/9304 [03:13<21:57,  6.35it/s]

2025-05-20 16:39:08,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 931/9304 [03:14<23:37,  5.91it/s]

2025-05-20 16:39:08,974 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 932/9304 [03:14<24:39,  5.66it/s]

2025-05-20 16:39:09,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 933/9304 [03:14<26:37,  5.24it/s]

2025-05-20 16:39:09,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:09,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 934/9304 [03:14<25:47,  5.41it/s]

2025-05-20 16:39:09,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:09,760 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 936/9304 [03:15<21:00,  6.64it/s]

2025-05-20 16:39:09,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 938/9304 [03:15<16:05,  8.67it/s]

2025-05-20 16:39:10,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:10,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 940/9304 [03:15<15:17,  9.12it/s]

2025-05-20 16:39:10,324 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:10,902 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 942/9304 [03:16<30:09,  4.62it/s]

2025-05-20 16:39:11,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:11,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 943/9304 [03:16<28:13,  4.94it/s]

2025-05-20 16:39:11,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:11,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 945/9304 [03:16<24:03,  5.79it/s]

2025-05-20 16:39:11,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 947/9304 [03:17<27:00,  5.16it/s]

2025-05-20 16:39:11,789 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:11,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 949/9304 [03:17<21:04,  6.61it/s]

2025-05-20 16:39:12,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 950/9304 [03:17<22:34,  6.17it/s]

2025-05-20 16:39:12,153 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 951/9304 [03:17<23:37,  5.89it/s]

2025-05-20 16:39:12,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 952/9304 [03:17<26:28,  5.26it/s]

2025-05-20 16:39:12,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 953/9304 [03:18<23:51,  5.83it/s]

2025-05-20 16:39:12,700 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:12,714 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:12,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 956/9304 [03:18<15:11,  9.16it/s]

2025-05-20 16:39:13,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:13,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:13,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 958/9304 [03:18<23:41,  5.87it/s]

2025-05-20 16:39:13,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 960/9304 [03:19<23:38,  5.88it/s]

2025-05-20 16:39:14,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 961/9304 [03:19<26:35,  5.23it/s]

2025-05-20 16:39:14,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 962/9304 [03:19<27:54,  4.98it/s]

2025-05-20 16:39:14,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:14,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:14,410 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 964/9304 [03:19<20:38,  6.73it/s]

2025-05-20 16:39:14,748 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 966/9304 [03:20<21:38,  6.42it/s]

2025-05-20 16:39:15,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 967/9304 [03:20<29:15,  4.75it/s]

2025-05-20 16:39:15,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 968/9304 [03:20<30:00,  4.63it/s]

2025-05-20 16:39:15,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:15,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 969/9304 [03:21<35:47,  3.88it/s]

2025-05-20 16:39:15,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 971/9304 [03:21<24:55,  5.57it/s]

2025-05-20 16:39:15,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:16,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 973/9304 [03:21<25:21,  5.48it/s]

2025-05-20 16:39:16,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 974/9304 [03:21<24:55,  5.57it/s]

2025-05-20 16:39:16,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 975/9304 [03:21<25:11,  5.51it/s]

2025-05-20 16:39:17,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:17,172 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 10%|█         | 976/9304 [03:22<36:11,  3.84it/s]

2025-05-20 16:39:17,324 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:17,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 978/9304 [03:22<25:46,  5.39it/s]

2025-05-20 16:39:17,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 980/9304 [03:22<22:58,  6.04it/s]

2025-05-20 16:39:17,620 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 981/9304 [03:23<23:35,  5.88it/s]

2025-05-20 16:39:17,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:17,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 983/9304 [03:23<19:43,  7.03it/s]

2025-05-20 16:39:18,369 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 984/9304 [03:23<29:08,  4.76it/s]

2025-05-20 16:39:18,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:18,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 986/9304 [03:24<27:08,  5.11it/s]

2025-05-20 16:39:18,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 987/9304 [03:24<27:22,  5.06it/s]

2025-05-20 16:39:19,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:19,153 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 988/9304 [03:24<26:28,  5.24it/s]

2025-05-20 16:39:19,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:19,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 990/9304 [03:24<19:56,  6.95it/s]

2025-05-20 16:39:19,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 992/9304 [03:25<22:58,  6.03it/s]

2025-05-20 16:39:19,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 993/9304 [03:25<22:43,  6.10it/s]

2025-05-20 16:39:20,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 994/9304 [03:25<35:22,  3.92it/s]

2025-05-20 16:39:20,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:20,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 996/9304 [03:26<29:08,  4.75it/s]

2025-05-20 16:39:20,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:20,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 998/9304 [03:26<22:00,  6.29it/s]

2025-05-20 16:39:20,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 999/9304 [03:26<22:01,  6.29it/s]

2025-05-20 16:39:21,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:21,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1001/9304 [03:26<19:48,  6.99it/s]

2025-05-20 16:39:21,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:21,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1002/9304 [03:26<21:44,  6.36it/s]

2025-05-20 16:39:21,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1004/9304 [03:27<27:35,  5.01it/s]

2025-05-20 16:39:22,209 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1005/9304 [03:27<28:35,  4.84it/s]

2025-05-20 16:39:22,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:22,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1007/9304 [03:27<24:46,  5.58it/s]

2025-05-20 16:39:22,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:22,579 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:22,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1010/9304 [03:28<21:48,  6.34it/s]

2025-05-20 16:39:23,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1011/9304 [03:28<25:18,  5.46it/s]

2025-05-20 16:39:23,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1012/9304 [03:28<25:44,  5.37it/s]

2025-05-20 16:39:23,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1013/9304 [03:29<29:31,  4.68it/s]

2025-05-20 16:39:23,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1014/9304 [03:29<26:06,  5.29it/s]

2025-05-20 16:39:24,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1015/9304 [03:29<31:20,  4.41it/s]

2025-05-20 16:39:24,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:24,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:24,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1017/9304 [03:29<28:56,  4.77it/s]

2025-05-20 16:39:24,988 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1019/9304 [03:30<30:25,  4.54it/s]

2025-05-20 16:39:25,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1020/9304 [03:30<34:26,  4.01it/s]

2025-05-20 16:39:25,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:25,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1022/9304 [03:30<25:55,  5.33it/s]

2025-05-20 16:39:25,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:25,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1024/9304 [03:30<19:38,  7.03it/s]

2025-05-20 16:39:25,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1025/9304 [03:31<24:03,  5.74it/s]

2025-05-20 16:39:25,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:26,236 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1027/9304 [03:31<23:02,  5.99it/s]

2025-05-20 16:39:26,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:26,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1029/9304 [03:32<29:07,  4.73it/s]

2025-05-20 16:39:26,843 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:26,864 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:27,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:27,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1032/9304 [03:32<26:23,  5.22it/s]

2025-05-20 16:39:27,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1034/9304 [03:32<21:13,  6.49it/s]

2025-05-20 16:39:27,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:27,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1035/9304 [03:32<20:46,  6.64it/s]

2025-05-20 16:39:27,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:27,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1037/9304 [03:33<18:15,  7.55it/s]

2025-05-20 16:39:28,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1039/9304 [03:33<21:46,  6.33it/s]

2025-05-20 16:39:28,425 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1040/9304 [03:33<26:32,  5.19it/s]

2025-05-20 16:39:28,721 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1041/9304 [03:34<26:01,  5.29it/s]

2025-05-20 16:39:28,808 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:28,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1043/9304 [03:34<22:35,  6.09it/s]

2025-05-20 16:39:28,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:29,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1045/9304 [03:34<19:17,  7.14it/s]

2025-05-20 16:39:29,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█         | 1046/9304 [03:34<22:20,  6.16it/s]

2025-05-20 16:39:29,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:29,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1048/9304 [03:34<17:48,  7.73it/s]

2025-05-20 16:39:30,249 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1049/9304 [03:35<34:01,  4.04it/s]

2025-05-20 16:39:30,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:30,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1051/9304 [03:35<25:16,  5.44it/s]

2025-05-20 16:39:30,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1052/9304 [03:35<23:34,  5.83it/s]

2025-05-20 16:39:30,744 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1053/9304 [03:36<25:08,  5.47it/s]

2025-05-20 16:39:31,153 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1054/9304 [03:36<32:35,  4.22it/s]

2025-05-20 16:39:31,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:31,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1056/9304 [03:36<22:45,  6.04it/s]

2025-05-20 16:39:31,410 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1057/9304 [03:36<21:40,  6.34it/s]

2025-05-20 16:39:31,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1058/9304 [03:36<25:13,  5.45it/s]

2025-05-20 16:39:31,732 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1059/9304 [03:37<25:03,  5.48it/s]

2025-05-20 16:39:31,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1060/9304 [03:37<22:54,  6.00it/s]

2025-05-20 16:39:32,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1061/9304 [03:37<24:47,  5.54it/s]

2025-05-20 16:39:32,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:32,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1062/9304 [03:37<28:41,  4.79it/s]

2025-05-20 16:39:33,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1064/9304 [03:38<33:02,  4.16it/s]

2025-05-20 16:39:33,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1065/9304 [03:38<30:58,  4.43it/s]

2025-05-20 16:39:33,222 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:33,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:33,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1067/9304 [03:38<21:20,  6.43it/s]

2025-05-20 16:39:33,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 11%|█▏        | 1069/9304 [03:38<18:57,  7.24it/s]

2025-05-20 16:39:33,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1070/9304 [03:39<19:54,  6.89it/s]

2025-05-20 16:39:33,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1071/9304 [03:39<21:35,  6.36it/s]

2025-05-20 16:39:33,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:34,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1073/9304 [03:39<19:07,  7.17it/s]

2025-05-20 16:39:34,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1074/9304 [03:39<30:36,  4.48it/s]

2025-05-20 16:39:34,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:34,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:34,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1077/9304 [03:40<21:22,  6.42it/s]

2025-05-20 16:39:34,988 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:35,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1079/9304 [03:40<20:25,  6.71it/s]

2025-05-20 16:39:35,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:35,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1080/9304 [03:41<32:48,  4.18it/s]

2025-05-20 16:39:36,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1082/9304 [03:41<27:52,  4.91it/s]

2025-05-20 16:39:36,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:36,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1084/9304 [03:41<21:20,  6.42it/s]

2025-05-20 16:39:36,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:36,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:36,545 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1087/9304 [03:41<18:56,  7.23it/s]

2025-05-20 16:39:36,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:36,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1089/9304 [03:42<17:36,  7.77it/s]

2025-05-20 16:39:37,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1090/9304 [03:42<21:32,  6.35it/s]

2025-05-20 16:39:37,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1091/9304 [03:42<25:17,  5.41it/s]

2025-05-20 16:39:37,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1092/9304 [03:42<25:58,  5.27it/s]

2025-05-20 16:39:37,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:37,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1094/9304 [03:43<21:26,  6.38it/s]

2025-05-20 16:39:37,909 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1095/9304 [03:43<23:54,  5.72it/s]

2025-05-20 16:39:38,041 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:38,404 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1097/9304 [03:43<25:40,  5.33it/s]

2025-05-20 16:39:38,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:38,562 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1099/9304 [03:44<23:05,  5.92it/s]

2025-05-20 16:39:38,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:38,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1101/9304 [03:44<21:51,  6.25it/s]

2025-05-20 16:39:39,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:39,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1103/9304 [03:44<25:26,  5.37it/s]

2025-05-20 16:39:39,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1104/9304 [03:44<23:15,  5.88it/s]

2025-05-20 16:39:39,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1105/9304 [03:45<23:20,  5.86it/s]

2025-05-20 16:39:39,838 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1106/9304 [03:45<21:47,  6.27it/s]

2025-05-20 16:39:39,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1107/9304 [03:45<24:32,  5.57it/s]

2025-05-20 16:39:40,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1108/9304 [03:45<26:04,  5.24it/s]

2025-05-20 16:39:40,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:40,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1110/9304 [03:45<18:17,  7.47it/s]

2025-05-20 16:39:40,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:40,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1112/9304 [03:46<25:42,  5.31it/s]

2025-05-20 16:39:40,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:41,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1114/9304 [03:46<22:28,  6.07it/s]

2025-05-20 16:39:41,319 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1115/9304 [03:46<22:21,  6.10it/s]

2025-05-20 16:39:41,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:41,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1117/9304 [03:46<20:37,  6.62it/s]

2025-05-20 16:39:41,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:41,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1119/9304 [03:47<22:01,  6.19it/s]

2025-05-20 16:39:42,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1120/9304 [03:47<24:09,  5.65it/s]

2025-05-20 16:39:42,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:42,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1122/9304 [03:48<27:29,  4.96it/s]

2025-05-20 16:39:42,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1123/9304 [03:48<28:01,  4.87it/s]

2025-05-20 16:39:42,979 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:43,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:43,069 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1126/9304 [03:48<17:07,  7.96it/s]

2025-05-20 16:39:43,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:43,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1128/9304 [03:48<22:38,  6.02it/s]

2025-05-20 16:39:43,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:43,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1130/9304 [03:49<21:27,  6.35it/s]

2025-05-20 16:39:44,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1131/9304 [03:49<26:12,  5.20it/s]

2025-05-20 16:39:44,217 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:44,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1133/9304 [03:49<21:28,  6.34it/s]

2025-05-20 16:39:44,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:44,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1135/9304 [03:49<20:28,  6.65it/s]

2025-05-20 16:39:44,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1136/9304 [03:50<21:48,  6.24it/s]

2025-05-20 16:39:44,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:45,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1138/9304 [03:50<21:20,  6.38it/s]

2025-05-20 16:39:45,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1139/9304 [03:51<31:24,  4.33it/s]

2025-05-20 16:39:45,696 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:45,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1141/9304 [03:51<24:03,  5.65it/s]

2025-05-20 16:39:45,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1142/9304 [03:51<27:07,  5.01it/s]

2025-05-20 16:39:46,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:46,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1144/9304 [03:51<22:36,  6.02it/s]

2025-05-20 16:39:46,542 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1145/9304 [03:51<26:18,  5.17it/s]

2025-05-20 16:39:46,664 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:47,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:47,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1147/9304 [03:52<40:06,  3.39it/s]

2025-05-20 16:39:47,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:47,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1149/9304 [03:53<29:52,  4.55it/s]

2025-05-20 16:39:47,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1151/9304 [03:53<23:02,  5.90it/s]

2025-05-20 16:39:47,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:47,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1153/9304 [03:53<18:30,  7.34it/s]

2025-05-20 16:39:48,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:48,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:48,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1156/9304 [03:54<29:47,  4.56it/s]

2025-05-20 16:39:49,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:49,286 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:49,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1158/9304 [03:54<26:54,  5.04it/s]

2025-05-20 16:39:49,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:49,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1160/9304 [03:54<23:34,  5.76it/s]

2025-05-20 16:39:49,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 12%|█▏        | 1162/9304 [03:55<24:15,  5.60it/s]

2025-05-20 16:39:49,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:49,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:49,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:50,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1166/9304 [03:55<20:58,  6.47it/s]

2025-05-20 16:39:50,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1167/9304 [03:56<24:39,  5.50it/s]

2025-05-20 16:39:50,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:50,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1168/9304 [03:56<24:18,  5.58it/s]

2025-05-20 16:39:50,967 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:51,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1171/9304 [03:56<23:05,  5.87it/s]

2025-05-20 16:39:51,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1172/9304 [03:57<26:19,  5.15it/s]

2025-05-20 16:39:51,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:52,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1174/9304 [03:57<23:48,  5.69it/s]

2025-05-20 16:39:52,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1175/9304 [03:57<23:46,  5.70it/s]

2025-05-20 16:39:52,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:52,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1176/9304 [03:57<24:59,  5.42it/s]

2025-05-20 16:39:52,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:52,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:52,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1180/9304 [03:57<14:13,  9.52it/s]

2025-05-20 16:39:52,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:53,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1182/9304 [03:59<31:51,  4.25it/s]

2025-05-20 16:39:53,711 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:53,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:53,841 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1185/9304 [03:59<22:19,  6.06it/s]

2025-05-20 16:39:54,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:54,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1187/9304 [03:59<20:15,  6.68it/s]

2025-05-20 16:39:54,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:54,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1189/9304 [03:59<23:30,  5.75it/s]

2025-05-20 16:39:54,657 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1190/9304 [03:59<22:28,  6.02it/s]

2025-05-20 16:39:54,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1191/9304 [04:00<26:55,  5.02it/s]

2025-05-20 16:39:55,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1192/9304 [04:00<25:08,  5.38it/s]

2025-05-20 16:39:55,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1193/9304 [04:00<23:44,  5.69it/s]

2025-05-20 16:39:55,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1194/9304 [04:00<22:39,  5.97it/s]

2025-05-20 16:39:55,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:55,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1196/9304 [04:01<22:14,  6.08it/s]

2025-05-20 16:39:55,747 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:55,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1198/9304 [04:01<17:53,  7.55it/s]

2025-05-20 16:39:55,905 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:56,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1200/9304 [04:01<18:30,  7.30it/s]

2025-05-20 16:39:56,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1201/9304 [04:02<28:43,  4.70it/s]

2025-05-20 16:39:56,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:56,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1203/9304 [04:02<20:48,  6.49it/s]

2025-05-20 16:39:57,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:57,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1205/9304 [04:02<26:10,  5.16it/s]

2025-05-20 16:39:57,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:57,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1207/9304 [04:03<26:02,  5.18it/s]

2025-05-20 16:39:57,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:57,813 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1209/9304 [04:03<22:58,  5.87it/s]

2025-05-20 16:39:58,153 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1210/9304 [04:03<25:28,  5.30it/s]

2025-05-20 16:39:58,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:58,514 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1212/9304 [04:03<23:51,  5.65it/s]

2025-05-20 16:39:58,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:58,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1214/9304 [04:04<20:25,  6.60it/s]

2025-05-20 16:39:59,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:59,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1215/9304 [04:04<24:37,  5.47it/s]

2025-05-20 16:39:59,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:59,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1218/9304 [04:04<25:35,  5.26it/s]

2025-05-20 16:39:59,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1219/9304 [04:05<23:37,  5.70it/s]

2025-05-20 16:39:59,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:39:59,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1221/9304 [04:05<18:45,  7.18it/s]

2025-05-20 16:39:59,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:00,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1223/9304 [04:05<20:32,  6.55it/s]

2025-05-20 16:40:00,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1224/9304 [04:05<20:21,  6.62it/s]

2025-05-20 16:40:00,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1225/9304 [04:06<27:54,  4.82it/s]

2025-05-20 16:40:00,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:01,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:01,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1227/9304 [04:06<26:11,  5.14it/s]

2025-05-20 16:40:01,369 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1229/9304 [04:06<22:49,  5.90it/s]

2025-05-20 16:40:01,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1230/9304 [04:06<22:50,  5.89it/s]

2025-05-20 16:40:01,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:01,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1232/9304 [04:07<24:31,  5.49it/s]

2025-05-20 16:40:02,319 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1233/9304 [04:07<28:19,  4.75it/s]

2025-05-20 16:40:02,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1234/9304 [04:07<26:41,  5.04it/s]

2025-05-20 16:40:02,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1235/9304 [04:08<29:16,  4.59it/s]

2025-05-20 16:40:02,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:02,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:02,908 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1237/9304 [04:08<21:16,  6.32it/s]

2025-05-20 16:40:02,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:03,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1240/9304 [04:08<17:52,  7.52it/s]

2025-05-20 16:40:03,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1241/9304 [04:08<19:37,  6.85it/s]

2025-05-20 16:40:03,797 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1242/9304 [04:09<26:00,  5.17it/s]

2025-05-20 16:40:04,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1243/9304 [04:09<29:09,  4.61it/s]

2025-05-20 16:40:04,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:04,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1244/9304 [04:09<26:18,  5.10it/s]

2025-05-20 16:40:04,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1246/9304 [04:09<21:20,  6.29it/s]

2025-05-20 16:40:04,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:04,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1248/9304 [04:10<19:25,  6.91it/s]

2025-05-20 16:40:04,694 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:04,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1250/9304 [04:10<20:52,  6.43it/s]

2025-05-20 16:40:05,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1251/9304 [04:10<22:05,  6.07it/s]

2025-05-20 16:40:05,249 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:05,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:05,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1253/9304 [04:10<23:11,  5.79it/s]

2025-05-20 16:40:05,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:06,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 13%|█▎        | 1255/9304 [04:11<24:46,  5.41it/s]

2025-05-20 16:40:06,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1257/9304 [04:11<19:45,  6.79it/s]

2025-05-20 16:40:06,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:06,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:06,365 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1260/9304 [04:11<16:10,  8.29it/s]

2025-05-20 16:40:06,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1261/9304 [04:12<22:40,  5.91it/s]

2025-05-20 16:40:06,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1262/9304 [04:12<21:07,  6.34it/s]

2025-05-20 16:40:07,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:07,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1263/9304 [04:12<34:29,  3.89it/s]

2025-05-20 16:40:07,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1265/9304 [04:13<29:17,  4.57it/s]

2025-05-20 16:40:07,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:07,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:08,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1268/9304 [04:13<25:02,  5.35it/s]

2025-05-20 16:40:08,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:08,324 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:08,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:08,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:09,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:09,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1273/9304 [04:14<23:02,  5.81it/s]

2025-05-20 16:40:09,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1275/9304 [04:14<21:10,  6.32it/s]

2025-05-20 16:40:09,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:09,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1277/9304 [04:15<22:26,  5.96it/s]

2025-05-20 16:40:09,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:09,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▎        | 1279/9304 [04:15<20:43,  6.46it/s]

2025-05-20 16:40:09,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:10,085 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1281/9304 [04:15<18:55,  7.06it/s]

2025-05-20 16:40:10,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1282/9304 [04:15<21:30,  6.22it/s]

2025-05-20 16:40:10,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1283/9304 [04:16<27:35,  4.84it/s]

2025-05-20 16:40:11,041 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1284/9304 [04:16<27:51,  4.80it/s]

2025-05-20 16:40:11,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:11,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1286/9304 [04:16<22:44,  5.87it/s]

2025-05-20 16:40:11,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1287/9304 [04:16<22:03,  6.06it/s]

2025-05-20 16:40:11,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1288/9304 [04:16<23:35,  5.66it/s]

2025-05-20 16:40:11,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:11,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1290/9304 [04:17<20:50,  6.41it/s]

2025-05-20 16:40:11,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1291/9304 [04:17<19:40,  6.79it/s]

2025-05-20 16:40:12,085 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1292/9304 [04:17<18:11,  7.34it/s]

2025-05-20 16:40:12,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1293/9304 [04:17<23:02,  5.79it/s]

2025-05-20 16:40:12,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1294/9304 [04:17<20:44,  6.44it/s]

2025-05-20 16:40:12,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1295/9304 [04:18<26:00,  5.13it/s]

2025-05-20 16:40:13,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1296/9304 [04:18<29:44,  4.49it/s]

2025-05-20 16:40:13,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:13,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1298/9304 [04:18<22:53,  5.83it/s]

2025-05-20 16:40:13,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1299/9304 [04:19<34:11,  3.90it/s]

2025-05-20 16:40:13,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:14,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1301/9304 [04:19<30:39,  4.35it/s]

2025-05-20 16:40:14,215 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:14,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1303/9304 [04:19<26:52,  4.96it/s]

2025-05-20 16:40:14,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:14,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:14,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1305/9304 [04:19<20:03,  6.64it/s]

2025-05-20 16:40:14,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1307/9304 [04:20<20:23,  6.53it/s]

2025-05-20 16:40:15,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1308/9304 [04:20<23:42,  5.62it/s]

2025-05-20 16:40:15,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1309/9304 [04:20<28:19,  4.70it/s]

2025-05-20 16:40:15,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:15,743 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1310/9304 [04:21<28:00,  4.76it/s]

2025-05-20 16:40:15,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:15,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1312/9304 [04:21<20:33,  6.48it/s]

2025-05-20 16:40:15,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:16,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:16,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1315/9304 [04:21<22:46,  5.84it/s]

2025-05-20 16:40:16,566 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1317/9304 [04:21<18:00,  7.39it/s]

2025-05-20 16:40:16,579 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:16,960 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1319/9304 [04:22<23:15,  5.72it/s]

2025-05-20 16:40:17,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:17,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:17,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1321/9304 [04:22<23:44,  5.60it/s]

2025-05-20 16:40:17,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1323/9304 [04:22<19:50,  6.70it/s]

2025-05-20 16:40:17,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:17,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1325/9304 [04:23<18:20,  7.25it/s]

2025-05-20 16:40:17,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1326/9304 [04:23<18:51,  7.05it/s]

2025-05-20 16:40:18,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1327/9304 [04:23<28:06,  4.73it/s]

2025-05-20 16:40:18,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1328/9304 [04:24<29:09,  4.56it/s]

2025-05-20 16:40:18,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:18,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1329/9304 [04:24<26:53,  4.94it/s]

2025-05-20 16:40:18,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:19,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1332/9304 [04:24<21:02,  6.31it/s]

2025-05-20 16:40:19,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:19,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:19,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1334/9304 [04:24<19:16,  6.89it/s]

2025-05-20 16:40:20,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1336/9304 [04:25<24:37,  5.39it/s]

2025-05-20 16:40:20,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1337/9304 [04:25<29:31,  4.50it/s]

2025-05-20 16:40:20,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:20,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:20,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1339/9304 [04:25<22:22,  5.93it/s]

2025-05-20 16:40:20,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1341/9304 [04:26<18:40,  7.11it/s]

2025-05-20 16:40:20,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:20,820 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1343/9304 [04:26<15:21,  8.64it/s]

2025-05-20 16:40:21,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:21,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1345/9304 [04:26<24:23,  5.44it/s]

2025-05-20 16:40:21,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1346/9304 [04:27<25:53,  5.12it/s]

2025-05-20 16:40:21,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1347/9304 [04:27<25:36,  5.18it/s]

2025-05-20 16:40:21,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:22,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 14%|█▍        | 1349/9304 [04:27<19:34,  6.77it/s]

2025-05-20 16:40:22,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1350/9304 [04:27<23:56,  5.54it/s]

2025-05-20 16:40:22,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1351/9304 [04:27<22:38,  5.85it/s]

2025-05-20 16:40:22,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1352/9304 [04:28<26:21,  5.03it/s]

2025-05-20 16:40:22,867 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1353/9304 [04:28<24:01,  5.51it/s]

2025-05-20 16:40:22,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:23,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1354/9304 [04:28<25:23,  5.22it/s]

2025-05-20 16:40:23,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1356/9304 [04:28<25:51,  5.12it/s]

2025-05-20 16:40:23,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1357/9304 [04:29<26:44,  4.95it/s]

2025-05-20 16:40:23,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1358/9304 [04:29<25:44,  5.15it/s]

2025-05-20 16:40:24,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:24,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1359/9304 [04:29<22:56,  5.77it/s]

2025-05-20 16:40:24,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:24,503 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1362/9304 [04:29<21:15,  6.22it/s]

2025-05-20 16:40:24,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:24,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1364/9304 [04:30<20:57,  6.32it/s]

2025-05-20 16:40:24,847 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1365/9304 [04:30<20:19,  6.51it/s]

2025-05-20 16:40:24,964 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:25,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1367/9304 [04:30<28:31,  4.64it/s]

2025-05-20 16:40:25,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:25,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1369/9304 [04:31<22:38,  5.84it/s]

2025-05-20 16:40:25,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1370/9304 [04:31<21:51,  6.05it/s]

2025-05-20 16:40:26,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1371/9304 [04:31<24:40,  5.36it/s]

2025-05-20 16:40:26,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:26,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1373/9304 [04:31<19:38,  6.73it/s]

2025-05-20 16:40:26,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1374/9304 [04:31<19:01,  6.94it/s]

2025-05-20 16:40:26,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1375/9304 [04:32<21:04,  6.27it/s]

2025-05-20 16:40:26,979 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:27,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1376/9304 [04:32<25:45,  5.13it/s]

2025-05-20 16:40:27,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1378/9304 [04:32<18:46,  7.04it/s]

2025-05-20 16:40:27,661 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1379/9304 [04:32<30:54,  4.27it/s]

2025-05-20 16:40:27,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:27,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1381/9304 [04:33<22:23,  5.90it/s]

2025-05-20 16:40:27,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1382/9304 [04:33<24:30,  5.39it/s]

2025-05-20 16:40:28,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1383/9304 [04:33<24:18,  5.43it/s]

2025-05-20 16:40:28,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1384/9304 [04:33<23:31,  5.61it/s]

2025-05-20 16:40:28,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1385/9304 [04:33<21:42,  6.08it/s]

2025-05-20 16:40:28,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:28,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1387/9304 [04:34<17:25,  7.57it/s]

2025-05-20 16:40:28,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:29,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1389/9304 [04:34<22:38,  5.83it/s]

2025-05-20 16:40:29,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1390/9304 [04:34<23:49,  5.53it/s]

2025-05-20 16:40:29,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:29,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1391/9304 [04:34<23:06,  5.71it/s]

2025-05-20 16:40:29,565 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:29,838 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1394/9304 [04:35<17:51,  7.38it/s]

2025-05-20 16:40:30,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▍        | 1395/9304 [04:35<23:22,  5.64it/s]

2025-05-20 16:40:30,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:30,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1397/9304 [04:35<21:57,  6.00it/s]

2025-05-20 16:40:30,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:30,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1399/9304 [04:36<22:51,  5.77it/s]

2025-05-20 16:40:30,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1400/9304 [04:36<21:09,  6.23it/s]

2025-05-20 16:40:31,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1401/9304 [04:36<20:02,  6.57it/s]

2025-05-20 16:40:31,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1402/9304 [04:36<19:43,  6.68it/s]

2025-05-20 16:40:31,238 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:31,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1404/9304 [04:37<27:45,  4.74it/s]

2025-05-20 16:40:31,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:32,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1405/9304 [04:37<26:28,  4.97it/s]

2025-05-20 16:40:32,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1407/9304 [04:37<20:52,  6.31it/s]

2025-05-20 16:40:32,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:32,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1409/9304 [04:37<21:12,  6.20it/s]

2025-05-20 16:40:32,616 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1410/9304 [04:37<19:46,  6.65it/s]

2025-05-20 16:40:32,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:32,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:32,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1413/9304 [04:38<16:08,  8.15it/s]

2025-05-20 16:40:33,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1414/9304 [04:38<23:05,  5.70it/s]

2025-05-20 16:40:33,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1415/9304 [04:38<26:34,  4.95it/s]

2025-05-20 16:40:33,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:33,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:33,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1418/9304 [04:39<19:35,  6.71it/s]

2025-05-20 16:40:34,194 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:34,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1419/9304 [04:39<24:15,  5.42it/s]

2025-05-20 16:40:34,369 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1421/9304 [04:39<20:26,  6.43it/s]

2025-05-20 16:40:34,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1422/9304 [04:40<23:58,  5.48it/s]

2025-05-20 16:40:34,725 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:34,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1424/9304 [04:40<19:59,  6.57it/s]

2025-05-20 16:40:34,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:34,966 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1426/9304 [04:40<20:28,  6.41it/s]

2025-05-20 16:40:35,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1427/9304 [04:41<28:00,  4.69it/s]

2025-05-20 16:40:35,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:35,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1428/9304 [04:41<27:29,  4.77it/s]

2025-05-20 16:40:35,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:36,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:36,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1431/9304 [04:41<30:21,  4.32it/s]

2025-05-20 16:40:36,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:36,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1433/9304 [04:42<23:37,  5.55it/s]

2025-05-20 16:40:36,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:37,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1435/9304 [04:42<21:10,  6.19it/s]

2025-05-20 16:40:37,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1437/9304 [04:42<21:00,  6.24it/s]

2025-05-20 16:40:37,388 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:37,417 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:38,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1440/9304 [04:43<29:32,  4.44it/s]

2025-05-20 16:40:38,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1441/9304 [04:43<27:13,  4.81it/s]

2025-05-20 16:40:38,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 15%|█▌        | 1442/9304 [04:43<26:08,  5.01it/s]

2025-05-20 16:40:38,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:38,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1444/9304 [04:44<24:05,  5.44it/s]

2025-05-20 16:40:39,016 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1445/9304 [04:44<22:18,  5.87it/s]

2025-05-20 16:40:39,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:39,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:39,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1448/9304 [04:44<17:29,  7.48it/s]

2025-05-20 16:40:39,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:39,763 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1450/9304 [04:45<21:36,  6.06it/s]

2025-05-20 16:40:40,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1451/9304 [04:45<28:20,  4.62it/s]

2025-05-20 16:40:40,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:40,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1453/9304 [04:45<24:22,  5.37it/s]

2025-05-20 16:40:40,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:40,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:40,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:40,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:40,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1457/9304 [04:46<16:22,  7.98it/s]

2025-05-20 16:40:40,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1459/9304 [04:46<15:28,  8.45it/s]

2025-05-20 16:40:41,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1460/9304 [04:47<30:16,  4.32it/s]

2025-05-20 16:40:41,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:42,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1462/9304 [04:47<26:10,  4.99it/s]

2025-05-20 16:40:42,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:42,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:42,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1464/9304 [04:47<23:49,  5.48it/s]

2025-05-20 16:40:42,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1466/9304 [04:47<18:54,  6.91it/s]

2025-05-20 16:40:42,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:42,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1468/9304 [04:48<19:20,  6.75it/s]

2025-05-20 16:40:42,822 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:42,962 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1469/9304 [04:48<21:07,  6.18it/s]

2025-05-20 16:40:43,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1471/9304 [04:48<24:58,  5.23it/s]

2025-05-20 16:40:43,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1472/9304 [04:48<25:31,  5.12it/s]

2025-05-20 16:40:43,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1473/9304 [04:49<26:18,  4.96it/s]

2025-05-20 16:40:43,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:43,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1475/9304 [04:49<21:52,  5.97it/s]

2025-05-20 16:40:44,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1476/9304 [04:49<23:47,  5.48it/s]

2025-05-20 16:40:44,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:44,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1478/9304 [04:49<17:33,  7.43it/s]

2025-05-20 16:40:44,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1479/9304 [04:50<22:46,  5.73it/s]

2025-05-20 16:40:45,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1480/9304 [04:50<37:38,  3.46it/s]

2025-05-20 16:40:45,559 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:45,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1481/9304 [04:51<35:53,  3.63it/s]

2025-05-20 16:40:45,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1483/9304 [04:51<23:56,  5.45it/s]

2025-05-20 16:40:45,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:46,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1485/9304 [04:51<22:13,  5.87it/s]

2025-05-20 16:40:46,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:46,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1487/9304 [04:51<19:14,  6.77it/s]

2025-05-20 16:40:46,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1488/9304 [04:52<27:54,  4.67it/s]

2025-05-20 16:40:46,841 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:46,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:47,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:47,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1491/9304 [04:52<23:06,  5.63it/s]

2025-05-20 16:40:47,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1493/9304 [04:52<22:08,  5.88it/s]

2025-05-20 16:40:47,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:47,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1495/9304 [04:53<22:01,  5.91it/s]

2025-05-20 16:40:47,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:48,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1496/9304 [04:53<23:33,  5.52it/s]

2025-05-20 16:40:48,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1498/9304 [04:53<20:51,  6.24it/s]

2025-05-20 16:40:48,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:48,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1500/9304 [04:53<17:04,  7.62it/s]

2025-05-20 16:40:48,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1501/9304 [04:53<19:05,  6.81it/s]

2025-05-20 16:40:48,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1502/9304 [04:54<28:39,  4.54it/s]

2025-05-20 16:40:49,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1503/9304 [04:54<27:25,  4.74it/s]

2025-05-20 16:40:49,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:49,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1504/9304 [04:55<32:41,  3.98it/s]

2025-05-20 16:40:49,955 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1506/9304 [04:55<25:47,  5.04it/s]

2025-05-20 16:40:50,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1507/9304 [04:55<26:22,  4.93it/s]

2025-05-20 16:40:50,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:50,423 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1509/9304 [04:55<23:11,  5.60it/s]

2025-05-20 16:40:50,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▌        | 1510/9304 [04:56<24:49,  5.23it/s]

2025-05-20 16:40:50,700 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:50,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1512/9304 [04:56<20:36,  6.30it/s]

2025-05-20 16:40:51,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1513/9304 [04:56<28:40,  4.53it/s]

2025-05-20 16:40:51,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:51,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:51,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1515/9304 [04:56<20:47,  6.24it/s]

2025-05-20 16:40:51,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1517/9304 [04:57<24:04,  5.39it/s]

2025-05-20 16:40:51,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:52,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1518/9304 [04:57<22:17,  5.82it/s]

2025-05-20 16:40:52,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1520/9304 [04:57<25:36,  5.07it/s]

2025-05-20 16:40:52,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:52,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1521/9304 [04:57<22:59,  5.64it/s]

2025-05-20 16:40:52,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:52,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1524/9304 [04:58<17:42,  7.32it/s]

2025-05-20 16:40:53,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1525/9304 [04:58<22:03,  5.88it/s]

2025-05-20 16:40:53,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:53,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:53,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1528/9304 [04:59<21:31,  6.02it/s]

2025-05-20 16:40:53,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:54,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1529/9304 [04:59<25:38,  5.05it/s]

2025-05-20 16:40:54,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1531/9304 [04:59<23:00,  5.63it/s]

2025-05-20 16:40:54,608 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1532/9304 [04:59<25:46,  5.02it/s]

2025-05-20 16:40:54,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1533/9304 [05:00<28:28,  4.55it/s]

2025-05-20 16:40:55,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:55,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 16%|█▋        | 1534/9304 [05:00<24:52,  5.21it/s]

2025-05-20 16:40:55,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:55,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1537/9304 [05:00<19:20,  6.69it/s]

2025-05-20 16:40:55,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:55,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1538/9304 [05:00<21:18,  6.07it/s]

2025-05-20 16:40:55,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1540/9304 [05:01<17:58,  7.20it/s]

2025-05-20 16:40:55,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:56,332 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1542/9304 [05:01<24:19,  5.32it/s]

2025-05-20 16:40:56,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:56,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1543/9304 [05:01<26:08,  4.95it/s]

2025-05-20 16:40:56,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1545/9304 [05:02<22:11,  5.83it/s]

2025-05-20 16:40:56,839 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:56,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1547/9304 [05:02<19:03,  6.78it/s]

2025-05-20 16:40:57,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1548/9304 [05:02<22:31,  5.74it/s]

2025-05-20 16:40:57,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1549/9304 [05:02<21:23,  6.04it/s]

2025-05-20 16:40:57,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1550/9304 [05:03<29:36,  4.37it/s]

2025-05-20 16:40:57,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:58,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1552/9304 [05:03<27:58,  4.62it/s]

2025-05-20 16:40:58,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:58,319 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1554/9304 [05:03<20:40,  6.25it/s]

2025-05-20 16:40:58,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1555/9304 [05:04<25:26,  5.08it/s]

2025-05-20 16:40:58,760 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:58,766 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:40:58,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1558/9304 [05:04<19:30,  6.62it/s]

2025-05-20 16:40:59,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1559/9304 [05:04<29:07,  4.43it/s]

2025-05-20 16:40:59,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1560/9304 [05:05<26:40,  4.84it/s]

2025-05-20 16:40:59,817 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1561/9304 [05:05<24:12,  5.33it/s]

2025-05-20 16:41:00,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1562/9304 [05:05<27:04,  4.77it/s]

2025-05-20 16:41:00,142 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:00,148 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:00,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1565/9304 [05:05<16:11,  7.97it/s]

2025-05-20 16:41:00,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:00,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:00,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1567/9304 [05:06<20:25,  6.31it/s]

2025-05-20 16:41:01,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1569/9304 [05:06<23:55,  5.39it/s]

2025-05-20 16:41:01,720 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1570/9304 [05:07<33:19,  3.87it/s]

2025-05-20 16:41:01,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:02,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1571/9304 [05:07<34:51,  3.70it/s]

2025-05-20 16:41:02,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1573/9304 [05:07<25:23,  5.07it/s]

2025-05-20 16:41:02,310 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1574/9304 [05:07<23:58,  5.37it/s]

2025-05-20 16:41:02,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:02,401 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:02,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1577/9304 [05:07<17:34,  7.33it/s]

2025-05-20 16:41:02,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1578/9304 [05:08<23:23,  5.51it/s]

2025-05-20 16:41:03,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1579/9304 [05:08<26:56,  4.78it/s]

2025-05-20 16:41:03,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:03,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1580/9304 [05:08<30:12,  4.26it/s]

2025-05-20 16:41:03,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:04,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1583/9304 [05:09<24:11,  5.32it/s]

2025-05-20 16:41:04,155 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1584/9304 [05:09<23:05,  5.57it/s]

2025-05-20 16:41:04,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:04,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1586/9304 [05:09<24:49,  5.18it/s]

2025-05-20 16:41:04,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:04,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1588/9304 [05:10<22:07,  5.81it/s]

2025-05-20 16:41:04,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1589/9304 [05:10<23:39,  5.43it/s]

2025-05-20 16:41:05,154 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:05,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:05,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1592/9304 [05:10<14:53,  8.64it/s]

2025-05-20 16:41:05,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:05,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1594/9304 [05:10<17:29,  7.34it/s]

2025-05-20 16:41:05,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:06,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1596/9304 [05:11<25:54,  4.96it/s]

2025-05-20 16:41:06,336 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:06,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1598/9304 [05:11<21:21,  6.01it/s]

2025-05-20 16:41:06,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:06,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1600/9304 [05:12<21:12,  6.05it/s]

2025-05-20 16:41:06,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:06,971 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1601/9304 [05:12<21:08,  6.07it/s]

2025-05-20 16:41:06,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:07,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1604/9304 [05:13<26:59,  4.76it/s]

2025-05-20 16:41:07,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:07,915 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1606/9304 [05:13<24:14,  5.29it/s]

2025-05-20 16:41:08,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:08,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1607/9304 [05:13<24:43,  5.19it/s]

2025-05-20 16:41:08,566 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1609/9304 [05:13<23:13,  5.52it/s]

2025-05-20 16:41:08,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:08,613 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:08,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1612/9304 [05:14<22:00,  5.82it/s]

2025-05-20 16:41:09,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:09,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1614/9304 [05:15<26:59,  4.75it/s]

2025-05-20 16:41:09,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:09,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:09,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1617/9304 [05:15<21:42,  5.90it/s]

2025-05-20 16:41:09,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:10,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1619/9304 [05:15<20:25,  6.27it/s]

2025-05-20 16:41:10,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1620/9304 [05:15<21:50,  5.86it/s]

2025-05-20 16:41:10,639 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1621/9304 [05:15<21:53,  5.85it/s]

2025-05-20 16:41:10,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1622/9304 [05:16<21:55,  5.84it/s]

2025-05-20 16:41:11,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1623/9304 [05:16<23:42,  5.40it/s]

2025-05-20 16:41:11,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1624/9304 [05:16<25:05,  5.10it/s]

2025-05-20 16:41:11,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:11,501 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1626/9304 [05:16<21:41,  5.90it/s]

2025-05-20 16:41:12,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 17%|█▋        | 1627/9304 [05:17<32:24,  3.95it/s]

2025-05-20 16:41:12,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:12,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:12,259 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1629/9304 [05:17<23:52,  5.36it/s]

2025-05-20 16:41:12,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:12,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1631/9304 [05:17<18:13,  7.02it/s]

2025-05-20 16:41:12,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1633/9304 [05:18<21:07,  6.05it/s]

2025-05-20 16:41:12,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:12,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1634/9304 [05:18<19:36,  6.52it/s]

2025-05-20 16:41:13,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1636/9304 [05:18<25:18,  5.05it/s]

2025-05-20 16:41:13,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:13,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:13,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1638/9304 [05:18<19:41,  6.49it/s]

2025-05-20 16:41:13,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:13,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1640/9304 [05:19<20:52,  6.12it/s]

2025-05-20 16:41:14,180 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1642/9304 [05:19<20:14,  6.31it/s]

2025-05-20 16:41:14,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:14,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1644/9304 [05:20<24:15,  5.26it/s]

2025-05-20 16:41:15,139 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1645/9304 [05:20<28:36,  4.46it/s]

2025-05-20 16:41:15,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:15,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1647/9304 [05:20<26:13,  4.87it/s]

2025-05-20 16:41:15,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:15,808 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1648/9304 [05:21<28:47,  4.43it/s]

2025-05-20 16:41:16,080 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:16,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1650/9304 [05:21<24:48,  5.14it/s]

2025-05-20 16:41:16,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:16,446 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:16,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1653/9304 [05:21<20:46,  6.14it/s]

2025-05-20 16:41:16,678 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1655/9304 [05:22<21:24,  5.95it/s]

2025-05-20 16:41:16,818 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:17,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1657/9304 [05:22<24:23,  5.22it/s]

2025-05-20 16:41:17,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:17,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1658/9304 [05:22<24:38,  5.17it/s]

2025-05-20 16:41:17,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:17,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1661/9304 [05:22<15:57,  7.98it/s]

2025-05-20 16:41:17,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:17,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1663/9304 [05:23<17:20,  7.35it/s]

2025-05-20 16:41:18,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:18,807 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:18,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1665/9304 [05:24<31:15,  4.07it/s]

2025-05-20 16:41:19,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1667/9304 [05:24<25:58,  4.90it/s]

2025-05-20 16:41:19,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:19,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1669/9304 [05:24<22:05,  5.76it/s]

2025-05-20 16:41:19,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:19,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:19,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1672/9304 [05:24<18:17,  6.96it/s]

2025-05-20 16:41:19,764 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1673/9304 [05:25<21:32,  5.90it/s]

2025-05-20 16:41:20,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1674/9304 [05:25<25:07,  5.06it/s]

2025-05-20 16:41:20,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1675/9304 [05:25<22:54,  5.55it/s]

2025-05-20 16:41:20,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1676/9304 [05:25<20:46,  6.12it/s]

2025-05-20 16:41:20,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1677/9304 [05:26<21:17,  5.97it/s]

2025-05-20 16:41:20,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1678/9304 [05:26<20:47,  6.11it/s]

2025-05-20 16:41:20,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1679/9304 [05:26<19:38,  6.47it/s]

2025-05-20 16:41:20,979 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:21,194 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1681/9304 [05:26<18:44,  6.78it/s]

2025-05-20 16:41:21,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1682/9304 [05:26<19:11,  6.62it/s]

2025-05-20 16:41:21,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:21,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1684/9304 [05:27<25:52,  4.91it/s]

2025-05-20 16:41:21,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1685/9304 [05:27<23:24,  5.42it/s]

2025-05-20 16:41:22,181 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1686/9304 [05:27<20:54,  6.07it/s]

2025-05-20 16:41:22,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:22,378 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1688/9304 [05:27<24:34,  5.16it/s]

2025-05-20 16:41:22,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:22,686 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:22,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1691/9304 [05:28<15:58,  7.94it/s]

2025-05-20 16:41:22,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:22,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1693/9304 [05:28<13:34,  9.35it/s]

2025-05-20 16:41:23,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:23,667 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1695/9304 [05:29<23:48,  5.33it/s]

2025-05-20 16:41:23,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1696/9304 [05:29<23:49,  5.32it/s]

2025-05-20 16:41:24,190 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1697/9304 [05:29<28:04,  4.51it/s]

2025-05-20 16:41:24,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:24,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:24,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1700/9304 [05:30<25:52,  4.90it/s]

2025-05-20 16:41:24,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:25,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1701/9304 [05:30<26:34,  4.77it/s]

2025-05-20 16:41:25,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1703/9304 [05:30<21:05,  6.00it/s]

2025-05-20 16:41:25,244 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:25,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:25,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1706/9304 [05:30<20:06,  6.30it/s]

2025-05-20 16:41:25,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1707/9304 [05:31<20:00,  6.33it/s]

2025-05-20 16:41:25,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:25,915 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1709/9304 [05:31<19:07,  6.62it/s]

2025-05-20 16:41:26,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:26,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1710/9304 [05:31<22:23,  5.65it/s]

2025-05-20 16:41:26,423 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1712/9304 [05:32<22:24,  5.65it/s]

2025-05-20 16:41:26,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:26,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1713/9304 [05:32<21:14,  5.96it/s]

2025-05-20 16:41:27,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:27,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1715/9304 [05:32<26:57,  4.69it/s]

2025-05-20 16:41:27,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:27,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:27,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1717/9304 [05:33<23:38,  5.35it/s]

2025-05-20 16:41:27,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 18%|█▊        | 1720/9304 [05:33<16:23,  7.71it/s]

2025-05-20 16:41:27,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:28,112 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1722/9304 [05:33<17:36,  7.17it/s]

2025-05-20 16:41:28,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1723/9304 [05:33<19:45,  6.40it/s]

2025-05-20 16:41:28,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1724/9304 [05:34<24:03,  5.25it/s]

2025-05-20 16:41:28,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1725/9304 [05:34<21:59,  5.74it/s]

2025-05-20 16:41:28,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1726/9304 [05:34<20:44,  6.09it/s]

2025-05-20 16:41:29,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1727/9304 [05:34<31:00,  4.07it/s]

2025-05-20 16:41:29,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:29,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1729/9304 [05:35<24:15,  5.21it/s]

2025-05-20 16:41:29,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:29,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1731/9304 [05:35<19:22,  6.51it/s]

2025-05-20 16:41:30,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1732/9304 [05:35<24:00,  5.26it/s]

2025-05-20 16:41:30,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1733/9304 [05:35<23:03,  5.47it/s]

2025-05-20 16:41:30,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:30,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:30,820 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1735/9304 [05:36<25:09,  5.01it/s]

2025-05-20 16:41:30,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:31,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:31,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1738/9304 [05:36<24:52,  5.07it/s]

2025-05-20 16:41:31,429 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:31,639 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1740/9304 [05:36<21:51,  5.77it/s]

2025-05-20 16:41:31,725 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:31,742 - openai._base_client - INFO - Retrying request to /chat/completions in 0.464400 seconds
2025-05-20 16:41:31,867 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1743/9304 [05:37<17:34,  7.17it/s]

2025-05-20 16:41:32,824 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▊        | 1744/9304 [05:38<33:12,  3.79it/s]

2025-05-20 16:41:32,838 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:32,992 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:32,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1746/9304 [05:38<26:08,  4.82it/s]

2025-05-20 16:41:33,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:33,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:33,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:33,222 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1750/9304 [05:38<17:14,  7.30it/s]

2025-05-20 16:41:33,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1752/9304 [05:38<16:20,  7.70it/s]

2025-05-20 16:41:34,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:34,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1754/9304 [05:39<29:14,  4.30it/s]

2025-05-20 16:41:34,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:34,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:34,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:34,608 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:34,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1758/9304 [05:39<18:32,  6.78it/s]

2025-05-20 16:41:34,976 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1760/9304 [05:40<19:33,  6.43it/s]

2025-05-20 16:41:35,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:35,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1762/9304 [05:40<19:14,  6.53it/s]

2025-05-20 16:41:35,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:35,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1764/9304 [05:41<23:35,  5.33it/s]

2025-05-20 16:41:35,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1765/9304 [05:41<22:43,  5.53it/s]

2025-05-20 16:41:35,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:36,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1767/9304 [05:41<18:31,  6.78it/s]

2025-05-20 16:41:36,139 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:36,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1769/9304 [05:41<16:25,  7.64it/s]

2025-05-20 16:41:36,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1770/9304 [05:41<19:17,  6.51it/s]

2025-05-20 16:41:37,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1771/9304 [05:42<31:36,  3.97it/s]

2025-05-20 16:41:37,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:37,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1773/9304 [05:42<25:42,  4.88it/s]

2025-05-20 16:41:37,465 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:37,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:37,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1775/9304 [05:43<23:39,  5.30it/s]

2025-05-20 16:41:38,112 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1777/9304 [05:43<22:58,  5.46it/s]

2025-05-20 16:41:38,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1778/9304 [05:43<29:07,  4.31it/s]

2025-05-20 16:41:38,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:38,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1780/9304 [05:44<24:42,  5.08it/s]

2025-05-20 16:41:39,080 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1781/9304 [05:44<26:56,  4.65it/s]

2025-05-20 16:41:39,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:39,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1783/9304 [05:44<19:36,  6.39it/s]

2025-05-20 16:41:39,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:39,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1785/9304 [05:44<20:31,  6.11it/s]

2025-05-20 16:41:39,906 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1786/9304 [05:45<26:25,  4.74it/s]

2025-05-20 16:41:40,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1787/9304 [05:45<27:29,  4.56it/s]

2025-05-20 16:41:40,388 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1788/9304 [05:45<29:35,  4.23it/s]

2025-05-20 16:41:40,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1789/9304 [05:45<25:34,  4.90it/s]

2025-05-20 16:41:40,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:40,654 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:40,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1792/9304 [05:46<20:15,  6.18it/s]

2025-05-20 16:41:41,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:41,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:41,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1795/9304 [05:46<19:50,  6.31it/s]

2025-05-20 16:41:41,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1796/9304 [05:46<20:16,  6.17it/s]

2025-05-20 16:41:41,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1797/9304 [05:47<19:41,  6.35it/s]

2025-05-20 16:41:41,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1798/9304 [05:47<20:38,  6.06it/s]

2025-05-20 16:41:42,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:42,237 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1800/9304 [05:47<20:13,  6.18it/s]

2025-05-20 16:41:42,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1801/9304 [05:47<18:51,  6.63it/s]

2025-05-20 16:41:42,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1802/9304 [05:48<23:08,  5.40it/s]

2025-05-20 16:41:42,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1803/9304 [05:48<22:35,  5.53it/s]

2025-05-20 16:41:42,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:43,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1805/9304 [05:48<23:37,  5.29it/s]

2025-05-20 16:41:43,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:43,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1807/9304 [05:48<21:02,  5.94it/s]

2025-05-20 16:41:43,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1808/9304 [05:48<20:20,  6.14it/s]

2025-05-20 16:41:43,684 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:44,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1810/9304 [05:49<24:06,  5.18it/s]

2025-05-20 16:41:44,238 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:44,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1812/9304 [05:50<29:17,  4.26it/s]

2025-05-20 16:41:44,791 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:44,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 19%|█▉        | 1814/9304 [05:50<23:27,  5.32it/s]

2025-05-20 16:41:44,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:45,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:45,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1817/9304 [05:50<17:25,  7.16it/s]

2025-05-20 16:41:45,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:45,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1819/9304 [05:50<14:23,  8.67it/s]

2025-05-20 16:41:45,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:45,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1821/9304 [05:51<21:37,  5.77it/s]

2025-05-20 16:41:46,289 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1822/9304 [05:51<27:51,  4.48it/s]

2025-05-20 16:41:46,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:46,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1824/9304 [05:51<22:47,  5.47it/s]

2025-05-20 16:41:46,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:46,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1826/9304 [05:52<18:24,  6.77it/s]

2025-05-20 16:41:46,808 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:47,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1828/9304 [05:52<20:24,  6.10it/s]

2025-05-20 16:41:47,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1829/9304 [05:52<20:30,  6.07it/s]

2025-05-20 16:41:47,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1830/9304 [05:52<21:34,  5.77it/s]

2025-05-20 16:41:47,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1831/9304 [05:53<31:21,  3.97it/s]

2025-05-20 16:41:48,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:48,150 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:48,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1833/9304 [05:53<22:35,  5.51it/s]

2025-05-20 16:41:48,249 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1835/9304 [05:53<18:13,  6.83it/s]

2025-05-20 16:41:48,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:48,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1837/9304 [05:54<19:30,  6.38it/s]

2025-05-20 16:41:48,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1838/9304 [05:54<22:48,  5.45it/s]

2025-05-20 16:41:49,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:49,275 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1840/9304 [05:54<23:14,  5.35it/s]

2025-05-20 16:41:49,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:49,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1841/9304 [05:54<25:27,  4.88it/s]

2025-05-20 16:41:49,732 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:49,739 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1844/9304 [05:55<15:42,  7.91it/s]

2025-05-20 16:41:50,648 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:50,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1846/9304 [05:56<31:12,  3.98it/s]

2025-05-20 16:41:50,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:50,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:51,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1849/9304 [05:56<22:12,  5.59it/s]

2025-05-20 16:41:51,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:51,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1851/9304 [05:56<20:15,  6.13it/s]

2025-05-20 16:41:51,286 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:51,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1853/9304 [05:56<17:38,  7.04it/s]

2025-05-20 16:41:52,146 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:52,199 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:52,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1855/9304 [05:57<27:08,  4.57it/s]

2025-05-20 16:41:52,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:52,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1857/9304 [05:57<22:54,  5.42it/s]

2025-05-20 16:41:52,696 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|█▉        | 1859/9304 [05:58<20:28,  6.06it/s]

2025-05-20 16:41:52,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:53,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:53,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1861/9304 [05:58<20:44,  5.98it/s]

2025-05-20 16:41:53,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1863/9304 [05:58<19:35,  6.33it/s]

2025-05-20 16:41:53,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1864/9304 [05:59<24:29,  5.06it/s]

2025-05-20 16:41:53,709 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:53,824 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1866/9304 [05:59<19:25,  6.38it/s]

2025-05-20 16:41:54,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:54,134 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1867/9304 [05:59<22:13,  5.58it/s]

2025-05-20 16:41:54,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1869/9304 [05:59<25:28,  4.86it/s]

2025-05-20 16:41:54,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:54,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:54,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1872/9304 [06:00<22:32,  5.49it/s]

2025-05-20 16:41:55,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:55,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1873/9304 [06:00<24:11,  5.12it/s]

2025-05-20 16:41:55,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:55,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1875/9304 [06:00<19:09,  6.46it/s]

2025-05-20 16:41:55,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1877/9304 [06:01<19:07,  6.47it/s]

2025-05-20 16:41:56,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1878/9304 [06:01<24:54,  4.97it/s]

2025-05-20 16:41:56,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:56,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1880/9304 [06:01<20:13,  6.12it/s]

2025-05-20 16:41:56,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:56,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1882/9304 [06:01<17:56,  6.89it/s]

2025-05-20 16:41:56,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:56,688 - openai._base_client - INFO - Retrying request to /chat/completions in 0.448204 seconds
2025-05-20 16:41:57,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1884/9304 [06:02<21:56,  5.64it/s]

2025-05-20 16:41:57,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:57,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1885/9304 [06:02<24:49,  4.98it/s]

2025-05-20 16:41:57,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1887/9304 [06:03<24:35,  5.03it/s]

2025-05-20 16:41:57,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1888/9304 [06:03<27:01,  4.57it/s]

2025-05-20 16:41:58,145 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:58,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1890/9304 [06:03<19:38,  6.29it/s]

2025-05-20 16:41:58,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1891/9304 [06:03<21:00,  5.88it/s]

2025-05-20 16:41:58,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1892/9304 [06:03<20:24,  6.05it/s]

2025-05-20 16:41:58,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:58,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1894/9304 [06:04<21:36,  5.72it/s]

2025-05-20 16:41:59,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1895/9304 [06:04<20:35,  6.00it/s]

2025-05-20 16:41:59,257 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1896/9304 [06:04<29:06,  4.24it/s]

2025-05-20 16:41:59,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:59,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:41:59,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1898/9304 [06:05<22:10,  5.57it/s]

2025-05-20 16:41:59,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1900/9304 [06:05<22:27,  5.50it/s]

2025-05-20 16:42:00,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1901/9304 [06:05<23:55,  5.16it/s]

2025-05-20 16:42:00,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:00,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1903/9304 [06:06<24:02,  5.13it/s]

2025-05-20 16:42:00,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:00,847 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1905/9304 [06:06<21:23,  5.76it/s]

2025-05-20 16:42:01,177 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:01,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 20%|██        | 1906/9304 [06:06<23:05,  5.34it/s]

2025-05-20 16:42:01,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1908/9304 [06:07<24:43,  4.99it/s]

2025-05-20 16:42:01,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:01,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1910/9304 [06:07<19:14,  6.40it/s]

2025-05-20 16:42:01,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:01,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1912/9304 [06:07<14:59,  8.22it/s]

2025-05-20 16:42:02,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:02,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:02,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1914/9304 [06:08<27:50,  4.42it/s]

2025-05-20 16:42:03,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1916/9304 [06:08<27:08,  4.54it/s]

2025-05-20 16:42:03,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:03,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:03,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1918/9304 [06:08<20:41,  5.95it/s]

2025-05-20 16:42:03,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1920/9304 [06:09<24:14,  5.08it/s]

2025-05-20 16:42:03,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1921/9304 [06:09<24:29,  5.03it/s]

2025-05-20 16:42:04,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1922/9304 [06:09<29:57,  4.11it/s]

2025-05-20 16:42:04,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:04,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1924/9304 [06:10<26:57,  4.56it/s]

2025-05-20 16:42:04,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:04,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:05,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:05,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1927/9304 [06:10<20:07,  6.11it/s]

2025-05-20 16:42:05,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1929/9304 [06:11<24:17,  5.06it/s]

2025-05-20 16:42:06,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1930/9304 [06:11<28:37,  4.29it/s]

2025-05-20 16:42:06,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1931/9304 [06:11<26:33,  4.63it/s]

2025-05-20 16:42:06,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:06,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:06,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1934/9304 [06:11<16:12,  7.58it/s]

2025-05-20 16:42:06,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:06,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1936/9304 [06:11<16:02,  7.66it/s]

2025-05-20 16:42:06,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:07,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1938/9304 [06:12<30:54,  3.97it/s]

2025-05-20 16:42:07,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:07,739 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:07,748 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1941/9304 [06:13<20:21,  6.03it/s]

2025-05-20 16:42:08,021 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:08,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1943/9304 [06:13<21:01,  5.84it/s]

2025-05-20 16:42:08,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:08,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:08,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1945/9304 [06:13<23:01,  5.33it/s]

2025-05-20 16:42:08,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:08,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1947/9304 [06:14<23:16,  5.27it/s]

2025-05-20 16:42:09,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1949/9304 [06:14<22:53,  5.35it/s]

2025-05-20 16:42:09,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:09,415 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:09,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1952/9304 [06:15<23:37,  5.19it/s]

2025-05-20 16:42:09,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:10,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1954/9304 [06:15<21:46,  5.62it/s]

2025-05-20 16:42:10,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:10,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1956/9304 [06:15<22:03,  5.55it/s]

2025-05-20 16:42:10,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1957/9304 [06:16<20:41,  5.92it/s]

2025-05-20 16:42:10,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:10,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1959/9304 [06:16<19:43,  6.21it/s]

2025-05-20 16:42:11,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:11,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1961/9304 [06:16<16:08,  7.58it/s]

2025-05-20 16:42:11,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1962/9304 [06:16<25:08,  4.87it/s]

2025-05-20 16:42:11,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1963/9304 [06:17<25:17,  4.84it/s]

2025-05-20 16:42:11,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:12,254 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1965/9304 [06:17<24:34,  4.98it/s]

2025-05-20 16:42:12,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1966/9304 [06:17<23:58,  5.10it/s]

2025-05-20 16:42:12,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:12,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1968/9304 [06:17<19:25,  6.30it/s]

2025-05-20 16:42:12,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1969/9304 [06:18<23:09,  5.28it/s]

2025-05-20 16:42:12,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:13,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1971/9304 [06:18<25:56,  4.71it/s]

2025-05-20 16:42:13,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:13,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:13,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1973/9304 [06:18<21:01,  5.81it/s]

2025-05-20 16:42:13,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:14,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██        | 1976/9304 [06:19<19:53,  6.14it/s]

2025-05-20 16:42:14,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:14,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1978/9304 [06:19<19:09,  6.37it/s]

2025-05-20 16:42:14,369 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:14,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1980/9304 [06:20<25:43,  4.74it/s]

2025-05-20 16:42:15,359 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1981/9304 [06:20<28:39,  4.26it/s]

2025-05-20 16:42:15,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:15,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:15,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1984/9304 [06:20<20:30,  5.95it/s]

2025-05-20 16:42:15,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1985/9304 [06:21<21:14,  5.74it/s]

2025-05-20 16:42:15,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:15,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1987/9304 [06:21<17:08,  7.11it/s]

2025-05-20 16:42:15,987 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:16,024 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:16,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1990/9304 [06:22<25:30,  4.78it/s]

2025-05-20 16:42:17,094 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1991/9304 [06:22<27:53,  4.37it/s]

2025-05-20 16:42:17,251 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1992/9304 [06:22<25:07,  4.85it/s]

2025-05-20 16:42:17,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:17,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:17,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:17,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1995/9304 [06:22<18:43,  6.50it/s]

2025-05-20 16:42:17,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:17,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:18,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 1999/9304 [06:23<22:18,  5.46it/s]

2025-05-20 16:42:18,575 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 21%|██▏       | 2000/9304 [06:23<21:51,  5.57it/s]

2025-05-20 16:42:18,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2001/9304 [06:24<22:37,  5.38it/s]

2025-05-20 16:42:18,859 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:18,997 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2003/9304 [06:24<22:01,  5.53it/s]

2025-05-20 16:42:19,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:19,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:19,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2006/9304 [06:24<15:13,  7.99it/s]

2025-05-20 16:42:19,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:19,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:19,940 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:20,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2009/9304 [06:25<24:49,  4.90it/s]

2025-05-20 16:42:20,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:20,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2011/9304 [06:25<21:12,  5.73it/s]

2025-05-20 16:42:20,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:20,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2014/9304 [06:26<17:12,  7.06it/s]

2025-05-20 16:42:20,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:21,147 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2016/9304 [06:26<18:40,  6.50it/s]

2025-05-20 16:42:21,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:21,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:21,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2018/9304 [06:27<23:37,  5.14it/s]

2025-05-20 16:42:21,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:21,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:22,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2022/9304 [06:27<19:08,  6.34it/s]

2025-05-20 16:42:22,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:22,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:22,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2025/9304 [06:27<18:46,  6.46it/s]

2025-05-20 16:42:22,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2026/9304 [06:28<19:38,  6.17it/s]

2025-05-20 16:42:23,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2027/9304 [06:28<26:02,  4.66it/s]

2025-05-20 16:42:23,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:23,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:23,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2030/9304 [06:29<21:36,  5.61it/s]

2025-05-20 16:42:23,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:23,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2032/9304 [06:29<20:02,  6.05it/s]

2025-05-20 16:42:23,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:24,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2034/9304 [06:29<21:45,  5.57it/s]

2025-05-20 16:42:25,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2035/9304 [06:30<30:13,  4.01it/s]

2025-05-20 16:42:25,016 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:25,134 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2037/9304 [06:30<24:37,  4.92it/s]

2025-05-20 16:42:25,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2038/9304 [06:30<25:09,  4.81it/s]

2025-05-20 16:42:25,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2039/9304 [06:31<28:46,  4.21it/s]

2025-05-20 16:42:25,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:25,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2041/9304 [06:31<21:27,  5.64it/s]

2025-05-20 16:42:26,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:26,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2042/9304 [06:31<19:29,  6.21it/s]

2025-05-20 16:42:26,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2044/9304 [06:31<21:51,  5.53it/s]

2025-05-20 16:42:26,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:26,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2046/9304 [06:32<23:01,  5.26it/s]

2025-05-20 16:42:26,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:27,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2048/9304 [06:32<22:20,  5.41it/s]

2025-05-20 16:42:27,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:27,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2050/9304 [06:32<17:07,  7.06it/s]

2025-05-20 16:42:27,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:27,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2052/9304 [06:32<16:56,  7.13it/s]

2025-05-20 16:42:27,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:27,987 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2054/9304 [06:33<19:13,  6.28it/s]

2025-05-20 16:42:28,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:28,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:28,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2057/9304 [06:33<18:41,  6.46it/s]

2025-05-20 16:42:28,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:28,487 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:28,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2060/9304 [06:34<17:17,  6.98it/s]

2025-05-20 16:42:28,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2061/9304 [06:34<18:36,  6.48it/s]

2025-05-20 16:42:29,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2062/9304 [06:34<21:10,  5.70it/s]

2025-05-20 16:42:29,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:29,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:29,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2065/9304 [06:35<18:19,  6.58it/s]

2025-05-20 16:42:30,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:30,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2066/9304 [06:35<21:33,  5.60it/s]

2025-05-20 16:42:30,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2068/9304 [06:35<26:55,  4.48it/s]

2025-05-20 16:42:30,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2069/9304 [06:36<27:09,  4.44it/s]

2025-05-20 16:42:30,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:30,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:31,037 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2072/9304 [06:36<18:24,  6.55it/s]

2025-05-20 16:42:31,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2073/9304 [06:36<23:29,  5.13it/s]

2025-05-20 16:42:31,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:31,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2075/9304 [06:37<21:23,  5.63it/s]

2025-05-20 16:42:31,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:31,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2077/9304 [06:37<19:39,  6.13it/s]

2025-05-20 16:42:32,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2078/9304 [06:37<22:09,  5.44it/s]

2025-05-20 16:42:32,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2079/9304 [06:37<21:48,  5.52it/s]

2025-05-20 16:42:32,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2080/9304 [06:38<23:17,  5.17it/s]

2025-05-20 16:42:32,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:32,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2081/9304 [06:38<26:31,  4.54it/s]

2025-05-20 16:42:33,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:33,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2083/9304 [06:38<23:25,  5.14it/s]

2025-05-20 16:42:33,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2085/9304 [06:38<17:37,  6.83it/s]

2025-05-20 16:42:33,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:33,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:33,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2087/9304 [06:38<14:36,  8.23it/s]

2025-05-20 16:42:34,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2089/9304 [06:39<23:54,  5.03it/s]

2025-05-20 16:42:34,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:34,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2091/9304 [06:39<21:05,  5.70it/s]

2025-05-20 16:42:34,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:34,752 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 22%|██▏       | 2093/9304 [06:40<19:03,  6.30it/s]

2025-05-20 16:42:34,793 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:34,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:34,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2095/9304 [06:40<15:50,  7.58it/s]

2025-05-20 16:42:35,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2097/9304 [06:40<16:24,  7.32it/s]

2025-05-20 16:42:35,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2098/9304 [06:40<17:52,  6.72it/s]

2025-05-20 16:42:35,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2099/9304 [06:41<20:23,  5.89it/s]

2025-05-20 16:42:36,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2100/9304 [06:41<28:57,  4.15it/s]

2025-05-20 16:42:36,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:36,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2101/9304 [06:41<25:20,  4.74it/s]

2025-05-20 16:42:36,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:36,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:36,667 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2104/9304 [06:41<20:05,  5.97it/s]

2025-05-20 16:42:36,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2106/9304 [06:42<18:16,  6.56it/s]

2025-05-20 16:42:36,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:37,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2108/9304 [06:42<18:40,  6.42it/s]

2025-05-20 16:42:37,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2109/9304 [06:43<26:02,  4.60it/s]

2025-05-20 16:42:37,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:37,945 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2111/9304 [06:43<23:12,  5.16it/s]

2025-05-20 16:42:38,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:38,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:38,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2113/9304 [06:43<22:24,  5.35it/s]

2025-05-20 16:42:38,490 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:38,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2115/9304 [06:43<17:39,  6.78it/s]

2025-05-20 16:42:38,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:39,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2117/9304 [06:44<25:35,  4.68it/s]

2025-05-20 16:42:39,514 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2119/9304 [06:45<26:39,  4.49it/s]

2025-05-20 16:42:40,021 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:40,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2120/9304 [06:45<30:22,  3.94it/s]

2025-05-20 16:42:40,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:40,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2123/9304 [06:45<24:55,  4.80it/s]

2025-05-20 16:42:40,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:40,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:40,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2126/9304 [06:46<19:22,  6.17it/s]

2025-05-20 16:42:40,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2127/9304 [06:46<21:23,  5.59it/s]

2025-05-20 16:42:41,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2128/9304 [06:46<22:05,  5.41it/s]

2025-05-20 16:42:41,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2129/9304 [06:46<26:16,  4.55it/s]

2025-05-20 16:42:41,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2130/9304 [06:47<25:22,  4.71it/s]

2025-05-20 16:42:41,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:41,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:42,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2133/9304 [06:47<23:08,  5.17it/s]

2025-05-20 16:42:42,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:42,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2135/9304 [06:47<20:52,  5.72it/s]

2025-05-20 16:42:42,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:42,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2137/9304 [06:48<20:58,  5.69it/s]

2025-05-20 16:42:43,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2138/9304 [06:48<22:43,  5.26it/s]

2025-05-20 16:42:43,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:43,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2140/9304 [06:48<21:12,  5.63it/s]

2025-05-20 16:42:43,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2141/9304 [06:49<29:51,  4.00it/s]

2025-05-20 16:42:44,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:44,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2143/9304 [06:49<27:01,  4.42it/s]

2025-05-20 16:42:44,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:44,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2145/9304 [06:49<22:12,  5.37it/s]

2025-05-20 16:42:44,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:44,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:44,732 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2148/9304 [06:50<16:56,  7.04it/s]

2025-05-20 16:42:45,037 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2149/9304 [06:50<18:55,  6.30it/s]

2025-05-20 16:42:45,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2150/9304 [06:51<28:25,  4.19it/s]

2025-05-20 16:42:45,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:45,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2151/9304 [06:51<25:06,  4.75it/s]

2025-05-20 16:42:46,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2153/9304 [06:51<24:09,  4.93it/s]

2025-05-20 16:42:46,305 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:46,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:46,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2155/9304 [06:51<17:51,  6.67it/s]

2025-05-20 16:42:46,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2157/9304 [06:52<22:03,  5.40it/s]

2025-05-20 16:42:47,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2158/9304 [06:52<24:10,  4.93it/s]

2025-05-20 16:42:47,116 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:47,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2160/9304 [06:52<22:23,  5.32it/s]

2025-05-20 16:42:47,470 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2161/9304 [06:52<22:23,  5.32it/s]

2025-05-20 16:42:47,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2162/9304 [06:53<22:16,  5.35it/s]

2025-05-20 16:42:47,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:47,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:47,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2165/9304 [06:53<14:21,  8.28it/s]

2025-05-20 16:42:47,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2166/9304 [06:53<15:50,  7.51it/s]

2025-05-20 16:42:48,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2167/9304 [06:53<16:29,  7.21it/s]

2025-05-20 16:42:48,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2168/9304 [06:53<19:15,  6.17it/s]

2025-05-20 16:42:48,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2169/9304 [06:54<24:58,  4.76it/s]

2025-05-20 16:42:49,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2170/9304 [06:54<23:44,  5.01it/s]

2025-05-20 16:42:49,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2171/9304 [06:54<25:03,  4.74it/s]

2025-05-20 16:42:49,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2172/9304 [06:54<23:44,  5.00it/s]

2025-05-20 16:42:49,698 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2173/9304 [06:55<25:32,  4.65it/s]

2025-05-20 16:42:49,743 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:49,789 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:49,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2176/9304 [06:55<17:14,  6.89it/s]

2025-05-20 16:42:50,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:50,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2178/9304 [06:55<17:36,  6.75it/s]

2025-05-20 16:42:50,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2179/9304 [06:55<19:50,  5.99it/s]

2025-05-20 16:42:50,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2180/9304 [06:56<26:29,  4.48it/s]

2025-05-20 16:42:51,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:51,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2181/9304 [06:56<27:01,  4.39it/s]

2025-05-20 16:42:51,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2183/9304 [06:56<21:43,  5.46it/s]

2025-05-20 16:42:51,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:51,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2185/9304 [06:57<19:04,  6.22it/s]

2025-05-20 16:42:51,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 23%|██▎       | 2186/9304 [06:57<20:58,  5.66it/s]

2025-05-20 16:42:51,976 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:52,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2188/9304 [06:57<23:37,  5.02it/s]

2025-05-20 16:42:52,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2189/9304 [06:58<26:49,  4.42it/s]

2025-05-20 16:42:52,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:52,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:52,871 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2191/9304 [06:58<19:46,  5.99it/s]

2025-05-20 16:42:52,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:53,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2193/9304 [06:58<16:41,  7.10it/s]

2025-05-20 16:42:53,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2195/9304 [06:58<20:40,  5.73it/s]

2025-05-20 16:42:53,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2196/9304 [06:59<21:25,  5.53it/s]

2025-05-20 16:42:53,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:53,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2198/9304 [06:59<19:01,  6.22it/s]

2025-05-20 16:42:54,085 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2199/9304 [06:59<23:57,  4.94it/s]

2025-05-20 16:42:54,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:54,714 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2200/9304 [07:00<27:57,  4.24it/s]

2025-05-20 16:42:54,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2202/9304 [07:00<23:21,  5.07it/s]

2025-05-20 16:42:54,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:55,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:55,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:55,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2206/9304 [07:00<17:49,  6.64it/s]

2025-05-20 16:42:55,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2207/9304 [07:01<20:34,  5.75it/s]

2025-05-20 16:42:55,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:56,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▎       | 2208/9304 [07:01<25:33,  4.63it/s]

2025-05-20 16:42:56,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2210/9304 [07:01<20:17,  5.83it/s]

2025-05-20 16:42:56,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:56,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:56,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2213/9304 [07:01<16:32,  7.14it/s]

2025-05-20 16:42:56,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:56,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:57,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2216/9304 [07:02<21:05,  5.60it/s]

2025-05-20 16:42:57,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:57,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:57,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2218/9304 [07:03<22:43,  5.20it/s]

2025-05-20 16:42:57,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:57,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2220/9304 [07:03<20:14,  5.83it/s]

2025-05-20 16:42:58,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:58,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:58,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2224/9304 [07:03<15:45,  7.49it/s]

2025-05-20 16:42:58,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2225/9304 [07:03<18:26,  6.39it/s]

2025-05-20 16:42:58,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2226/9304 [07:04<24:51,  4.74it/s]

2025-05-20 16:42:59,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:59,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2227/9304 [07:04<22:56,  5.14it/s]

2025-05-20 16:42:59,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:59,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2230/9304 [07:04<14:58,  7.87it/s]

2025-05-20 16:42:59,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:42:59,797 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2232/9304 [07:05<17:41,  6.66it/s]

2025-05-20 16:42:59,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2233/9304 [07:05<19:50,  5.94it/s]

2025-05-20 16:43:00,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2234/9304 [07:05<22:09,  5.32it/s]

2025-05-20 16:43:00,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2235/9304 [07:05<25:32,  4.61it/s]

2025-05-20 16:43:00,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:00,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2237/9304 [07:06<19:51,  5.93it/s]

2025-05-20 16:43:00,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:00,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2238/9304 [07:06<18:12,  6.47it/s]

2025-05-20 16:43:01,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2240/9304 [07:06<15:24,  7.64it/s]

2025-05-20 16:43:01,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:01,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2242/9304 [07:06<20:34,  5.72it/s]

2025-05-20 16:43:01,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:02,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2243/9304 [07:07<26:24,  4.46it/s]

2025-05-20 16:43:02,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2245/9304 [07:07<22:58,  5.12it/s]

2025-05-20 16:43:02,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2246/9304 [07:07<25:32,  4.60it/s]

2025-05-20 16:43:02,843 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2247/9304 [07:08<31:32,  3.73it/s]

2025-05-20 16:43:03,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:03,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2248/9304 [07:08<31:34,  3.72it/s]

2025-05-20 16:43:03,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:03,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2251/9304 [07:08<17:52,  6.57it/s]

2025-05-20 16:43:03,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:03,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:03,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2254/9304 [07:09<14:51,  7.91it/s]

2025-05-20 16:43:03,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:04,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2256/9304 [07:09<15:29,  7.58it/s]

2025-05-20 16:43:04,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2257/9304 [07:10<28:42,  4.09it/s]

2025-05-20 16:43:04,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:05,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:05,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2259/9304 [07:10<27:35,  4.26it/s]

2025-05-20 16:43:05,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2261/9304 [07:10<21:54,  5.36it/s]

2025-05-20 16:43:05,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:05,539 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:05,565 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2263/9304 [07:10<17:30,  6.70it/s]

2025-05-20 16:43:05,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2265/9304 [07:11<18:19,  6.40it/s]

2025-05-20 16:43:06,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2266/9304 [07:11<23:30,  4.99it/s]

2025-05-20 16:43:06,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:06,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2267/9304 [07:11<26:13,  4.47it/s]

2025-05-20 16:43:06,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:06,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2270/9304 [07:12<18:54,  6.20it/s]

2025-05-20 16:43:06,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:07,024 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2272/9304 [07:12<15:48,  7.41it/s]

2025-05-20 16:43:07,240 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2273/9304 [07:12<19:05,  6.14it/s]

2025-05-20 16:43:07,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:07,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2275/9304 [07:13<20:14,  5.79it/s]

2025-05-20 16:43:07,820 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2276/9304 [07:13<21:12,  5.52it/s]

2025-05-20 16:43:08,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2277/9304 [07:13<25:45,  4.55it/s]

2025-05-20 16:43:08,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:08,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 24%|██▍       | 2279/9304 [07:13<20:25,  5.73it/s]

2025-05-20 16:43:08,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:08,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:08,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2282/9304 [07:14<15:35,  7.51it/s]

2025-05-20 16:43:08,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2283/9304 [07:14<15:10,  7.71it/s]

2025-05-20 16:43:08,863 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:09,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2285/9304 [07:14<22:04,  5.30it/s]

2025-05-20 16:43:09,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2286/9304 [07:15<24:44,  4.73it/s]

2025-05-20 16:43:09,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:09,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:09,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2289/9304 [07:15<17:02,  6.86it/s]

2025-05-20 16:43:09,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:10,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2291/9304 [07:15<15:37,  7.48it/s]

2025-05-20 16:43:10,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:10,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2293/9304 [07:15<17:35,  6.64it/s]

2025-05-20 16:43:10,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2294/9304 [07:16<22:44,  5.14it/s]

2025-05-20 16:43:11,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2295/9304 [07:16<23:58,  4.87it/s]

2025-05-20 16:43:11,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:11,410 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2297/9304 [07:16<20:17,  5.76it/s]

2025-05-20 16:43:11,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:11,523 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:11,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:11,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2300/9304 [07:17<18:14,  6.40it/s]

2025-05-20 16:43:12,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2302/9304 [07:17<23:14,  5.02it/s]

2025-05-20 16:43:12,523 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:12,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2303/9304 [07:17<22:13,  5.25it/s]

2025-05-20 16:43:12,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2305/9304 [07:18<20:33,  5.67it/s]

2025-05-20 16:43:12,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:12,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:13,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2308/9304 [07:18<18:47,  6.20it/s]

2025-05-20 16:43:13,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:13,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2310/9304 [07:19<24:03,  4.85it/s]

2025-05-20 16:43:14,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2311/9304 [07:19<23:11,  5.02it/s]

2025-05-20 16:43:14,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2312/9304 [07:19<23:23,  4.98it/s]

2025-05-20 16:43:14,345 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:14,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2314/9304 [07:19<19:33,  5.96it/s]

2025-05-20 16:43:14,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2315/9304 [07:20<20:55,  5.57it/s]

2025-05-20 16:43:14,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2316/9304 [07:20<20:55,  5.57it/s]

2025-05-20 16:43:14,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:15,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2318/9304 [07:21<31:08,  3.74it/s]

2025-05-20 16:43:15,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:15,818 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:15,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:16,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2322/9304 [07:21<21:49,  5.33it/s]

2025-05-20 16:43:16,454 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2323/9304 [07:21<22:34,  5.15it/s]

2025-05-20 16:43:16,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2324/9304 [07:22<26:29,  4.39it/s]

2025-05-20 16:43:17,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▍       | 2325/9304 [07:22<27:31,  4.23it/s]

2025-05-20 16:43:17,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2326/9304 [07:22<25:30,  4.56it/s]

2025-05-20 16:43:17,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:17,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2328/9304 [07:22<18:04,  6.43it/s]

2025-05-20 16:43:17,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:17,475 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2330/9304 [07:22<13:52,  8.38it/s]

2025-05-20 16:43:17,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:17,964 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2332/9304 [07:23<19:02,  6.10it/s]

2025-05-20 16:43:18,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2333/9304 [07:23<19:11,  6.05it/s]

2025-05-20 16:43:18,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2334/9304 [07:23<27:12,  4.27it/s]

2025-05-20 16:43:18,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:18,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2336/9304 [07:24<19:45,  5.88it/s]

2025-05-20 16:43:18,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:18,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2338/9304 [07:24<14:51,  7.81it/s]

2025-05-20 16:43:18,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:19,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2340/9304 [07:24<14:11,  8.18it/s]

2025-05-20 16:43:19,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:19,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2342/9304 [07:25<25:08,  4.61it/s]

2025-05-20 16:43:20,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2343/9304 [07:25<25:55,  4.48it/s]

2025-05-20 16:43:20,227 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:20,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2345/9304 [07:25<23:44,  4.88it/s]

2025-05-20 16:43:20,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:20,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2347/9304 [07:25<17:56,  6.46it/s]

2025-05-20 16:43:20,638 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:20,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2349/9304 [07:26<18:52,  6.14it/s]

2025-05-20 16:43:20,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:21,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:21,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2352/9304 [07:26<17:22,  6.67it/s]

2025-05-20 16:43:21,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2353/9304 [07:26<19:50,  5.84it/s]

2025-05-20 16:43:21,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2354/9304 [07:27<22:08,  5.23it/s]

2025-05-20 16:43:22,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:22,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2355/9304 [07:27<22:19,  5.19it/s]

2025-05-20 16:43:22,194 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:22,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2358/9304 [07:27<17:14,  6.71it/s]

2025-05-20 16:43:22,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2359/9304 [07:27<16:17,  7.10it/s]

2025-05-20 16:43:22,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2360/9304 [07:28<18:43,  6.18it/s]

2025-05-20 16:43:23,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2361/9304 [07:28<21:36,  5.36it/s]

2025-05-20 16:43:23,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:23,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2363/9304 [07:28<24:23,  4.74it/s]

2025-05-20 16:43:23,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2364/9304 [07:29<22:46,  5.08it/s]

2025-05-20 16:43:23,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:23,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2366/9304 [07:29<16:30,  7.00it/s]

2025-05-20 16:43:24,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2367/9304 [07:29<28:18,  4.08it/s]

2025-05-20 16:43:24,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:24,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2368/9304 [07:30<34:44,  3.33it/s]

2025-05-20 16:43:24,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:25,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:25,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 25%|██▌       | 2371/9304 [07:30<21:08,  5.46it/s]

2025-05-20 16:43:25,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:25,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:25,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2375/9304 [07:30<17:07,  6.74it/s]

2025-05-20 16:43:25,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2376/9304 [07:31<23:39,  4.88it/s]

2025-05-20 16:43:26,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2377/9304 [07:31<23:56,  4.82it/s]

2025-05-20 16:43:26,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2378/9304 [07:31<24:16,  4.75it/s]

2025-05-20 16:43:26,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:26,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:26,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:26,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2382/9304 [07:32<16:49,  6.86it/s]

2025-05-20 16:43:26,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:27,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:27,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2384/9304 [07:32<17:13,  6.69it/s]

2025-05-20 16:43:27,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2386/9304 [07:33<24:39,  4.68it/s]

2025-05-20 16:43:28,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2387/9304 [07:33<24:07,  4.78it/s]

2025-05-20 16:43:28,286 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2388/9304 [07:33<22:37,  5.09it/s]

2025-05-20 16:43:28,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:28,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2390/9304 [07:33<20:53,  5.52it/s]

2025-05-20 16:43:28,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:28,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2392/9304 [07:34<16:42,  6.89it/s]

2025-05-20 16:43:28,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:29,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2394/9304 [07:34<17:25,  6.61it/s]

2025-05-20 16:43:29,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2395/9304 [07:34<26:45,  4.30it/s]

2025-05-20 16:43:29,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:30,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2397/9304 [07:35<28:42,  4.01it/s]

2025-05-20 16:43:30,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:30,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2399/9304 [07:35<21:10,  5.44it/s]

2025-05-20 16:43:30,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:30,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2401/9304 [07:35<16:52,  6.82it/s]

2025-05-20 16:43:30,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:31,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2403/9304 [07:36<21:45,  5.29it/s]

2025-05-20 16:43:31,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:31,443 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2404/9304 [07:36<26:44,  4.30it/s]

2025-05-20 16:43:31,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2406/9304 [07:36<20:53,  5.50it/s]

2025-05-20 16:43:31,795 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2407/9304 [07:37<20:53,  5.50it/s]

2025-05-20 16:43:31,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:31,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:31,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:32,061 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2411/9304 [07:37<13:51,  8.29it/s]

2025-05-20 16:43:32,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:32,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2412/9304 [07:38<22:56,  5.01it/s]

2025-05-20 16:43:32,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2414/9304 [07:38<20:04,  5.72it/s]

2025-05-20 16:43:32,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:33,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:33,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2416/9304 [07:38<22:06,  5.19it/s]

2025-05-20 16:43:33,401 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:33,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2419/9304 [07:38<16:40,  6.88it/s]

2025-05-20 16:43:33,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2420/9304 [07:39<17:46,  6.46it/s]

2025-05-20 16:43:34,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:34,341 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2421/9304 [07:39<25:41,  4.47it/s]

2025-05-20 16:43:34,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2423/9304 [07:40<24:29,  4.68it/s]

2025-05-20 16:43:34,781 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:34,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2424/9304 [07:40<22:54,  5.01it/s]

2025-05-20 16:43:35,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2426/9304 [07:40<18:18,  6.26it/s]

2025-05-20 16:43:35,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2427/9304 [07:40<19:40,  5.83it/s]

2025-05-20 16:43:35,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:35,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2429/9304 [07:40<18:39,  6.14it/s]

2025-05-20 16:43:35,909 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2430/9304 [07:41<23:36,  4.85it/s]

2025-05-20 16:43:36,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2431/9304 [07:41<21:29,  5.33it/s]

2025-05-20 16:43:36,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2432/9304 [07:41<21:09,  5.41it/s]

2025-05-20 16:43:36,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2433/9304 [07:41<22:35,  5.07it/s]

2025-05-20 16:43:36,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:36,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:36,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2436/9304 [07:42<20:27,  5.60it/s]

2025-05-20 16:43:37,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2437/9304 [07:42<20:34,  5.56it/s]

2025-05-20 16:43:37,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:37,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2438/9304 [07:42<19:20,  5.92it/s]

2025-05-20 16:43:37,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▌       | 2440/9304 [07:43<25:52,  4.42it/s]

2025-05-20 16:43:37,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:37,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:38,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:38,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2443/9304 [07:43<16:04,  7.11it/s]

2025-05-20 16:43:38,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2445/9304 [07:43<18:41,  6.11it/s]

2025-05-20 16:43:38,752 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2446/9304 [07:44<21:31,  5.31it/s]

2025-05-20 16:43:38,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:38,790 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:39,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:39,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2449/9304 [07:44<18:59,  6.02it/s]

2025-05-20 16:43:39,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:39,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2451/9304 [07:44<20:17,  5.63it/s]

2025-05-20 16:43:39,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2453/9304 [07:45<17:00,  6.72it/s]

2025-05-20 16:43:39,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2454/9304 [07:45<20:39,  5.53it/s]

2025-05-20 16:43:40,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:40,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2456/9304 [07:45<18:08,  6.29it/s]

2025-05-20 16:43:40,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2457/9304 [07:46<23:46,  4.80it/s]

2025-05-20 16:43:40,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:40,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2458/9304 [07:46<21:43,  5.25it/s]

2025-05-20 16:43:41,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:41,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2460/9304 [07:46<24:02,  4.74it/s]

2025-05-20 16:43:41,630 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2462/9304 [07:46<21:45,  5.24it/s]

2025-05-20 16:43:41,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:41,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2463/9304 [07:47<20:07,  5.67it/s]

2025-05-20 16:43:42,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 26%|██▋       | 2465/9304 [07:47<20:59,  5.43it/s]

2025-05-20 16:43:42,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2466/9304 [07:47<20:51,  5.47it/s]

2025-05-20 16:43:42,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:42,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2467/9304 [07:48<33:13,  3.43it/s]

2025-05-20 16:43:43,170 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:43,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2469/9304 [07:48<24:20,  4.68it/s]

2025-05-20 16:43:43,251 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2471/9304 [07:48<19:40,  5.79it/s]

2025-05-20 16:43:43,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:43,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:43,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2473/9304 [07:48<15:51,  7.18it/s]

2025-05-20 16:43:43,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2475/9304 [07:49<18:45,  6.07it/s]

2025-05-20 16:43:44,401 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2476/9304 [07:49<24:47,  4.59it/s]

2025-05-20 16:43:44,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:44,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:44,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2479/9304 [07:49<17:22,  6.55it/s]

2025-05-20 16:43:44,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2480/9304 [07:50<19:30,  5.83it/s]

2025-05-20 16:43:44,884 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:44,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:45,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2483/9304 [07:50<16:13,  7.01it/s]

2025-05-20 16:43:45,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:45,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2485/9304 [07:50<15:19,  7.42it/s]

2025-05-20 16:43:45,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2486/9304 [07:51<21:41,  5.24it/s]

2025-05-20 16:43:46,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2487/9304 [07:51<24:22,  4.66it/s]

2025-05-20 16:43:46,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2488/9304 [07:51<22:01,  5.16it/s]

2025-05-20 16:43:46,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:46,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2490/9304 [07:51<19:38,  5.78it/s]

2025-05-20 16:43:46,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2491/9304 [07:52<20:14,  5.61it/s]

2025-05-20 16:43:46,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2492/9304 [07:52<20:30,  5.53it/s]

2025-05-20 16:43:46,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:47,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2494/9304 [07:52<17:49,  6.37it/s]

2025-05-20 16:43:47,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2495/9304 [07:52<16:30,  6.87it/s]

2025-05-20 16:43:47,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2496/9304 [07:52<15:19,  7.40it/s]

2025-05-20 16:43:47,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2497/9304 [07:53<24:01,  4.72it/s]

2025-05-20 16:43:47,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:48,013 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2499/9304 [07:53<18:39,  6.08it/s]

2025-05-20 16:43:48,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2500/9304 [07:53<25:29,  4.45it/s]

2025-05-20 16:43:48,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:48,684 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:48,752 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2502/9304 [07:54<21:18,  5.32it/s]

2025-05-20 16:43:48,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:48,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2505/9304 [07:54<14:23,  7.87it/s]

2025-05-20 16:43:48,974 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2506/9304 [07:54<13:56,  8.13it/s]

2025-05-20 16:43:49,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2507/9304 [07:54<23:36,  4.80it/s]

2025-05-20 16:43:49,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:49,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2508/9304 [07:55<27:53,  4.06it/s]

2025-05-20 16:43:49,955 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:50,336 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2511/9304 [07:55<21:32,  5.26it/s]

2025-05-20 16:43:50,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:50,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2512/9304 [07:55<23:53,  4.74it/s]

2025-05-20 16:43:50,807 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2514/9304 [07:56<19:21,  5.85it/s]

2025-05-20 16:43:51,179 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2515/9304 [07:56<23:59,  4.72it/s]

2025-05-20 16:43:51,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:51,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2516/9304 [07:56<23:07,  4.89it/s]

2025-05-20 16:43:51,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:51,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2519/9304 [07:56<16:39,  6.79it/s]

2025-05-20 16:43:51,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2520/9304 [07:57<22:30,  5.02it/s]

2025-05-20 16:43:52,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:52,305 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2522/9304 [07:57<19:14,  5.87it/s]

2025-05-20 16:43:52,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:52,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2523/9304 [07:57<17:39,  6.40it/s]

2025-05-20 16:43:52,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2525/9304 [07:58<19:02,  5.93it/s]

2025-05-20 16:43:52,795 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:52,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:52,953 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2528/9304 [07:58<17:34,  6.43it/s]

2025-05-20 16:43:53,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:53,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2530/9304 [07:58<19:05,  5.91it/s]

2025-05-20 16:43:53,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:53,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2532/9304 [07:59<19:56,  5.66it/s]

2025-05-20 16:43:54,134 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:54,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2533/9304 [07:59<22:11,  5.08it/s]

2025-05-20 16:43:54,332 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:54,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2535/9304 [07:59<17:56,  6.29it/s]

2025-05-20 16:43:54,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2537/9304 [08:00<17:17,  6.53it/s]

2025-05-20 16:43:55,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2538/9304 [08:00<20:24,  5.53it/s]

2025-05-20 16:43:55,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:55,119 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2540/9304 [08:00<17:12,  6.55it/s]

2025-05-20 16:43:55,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2541/9304 [08:01<25:21,  4.44it/s]

2025-05-20 16:43:55,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:56,061 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2543/9304 [08:01<22:26,  5.02it/s]

2025-05-20 16:43:56,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:56,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:56,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:56,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2546/9304 [08:02<22:48,  4.94it/s]

2025-05-20 16:43:56,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2548/9304 [08:02<19:22,  5.81it/s]

2025-05-20 16:43:56,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:57,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2550/9304 [08:02<22:07,  5.09it/s]

2025-05-20 16:43:57,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:57,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:57,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:57,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2554/9304 [08:02<13:53,  8.10it/s]

2025-05-20 16:43:57,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:58,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2556/9304 [08:03<17:45,  6.33it/s]

2025-05-20 16:43:58,514 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2557/9304 [08:03<22:40,  4.96it/s]

2025-05-20 16:43:58,694 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 27%|██▋       | 2558/9304 [08:04<25:36,  4.39it/s]

2025-05-20 16:43:58,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2559/9304 [08:04<24:32,  4.58it/s]

2025-05-20 16:43:59,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:59,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:59,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:59,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2562/9304 [08:04<17:33,  6.40it/s]

2025-05-20 16:43:59,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:43:59,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2565/9304 [08:04<14:08,  7.94it/s]

2025-05-20 16:44:00,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:00,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2566/9304 [08:05<25:51,  4.34it/s]

2025-05-20 16:44:00,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2568/9304 [08:05<20:57,  5.36it/s]

2025-05-20 16:44:00,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2569/9304 [08:05<19:17,  5.82it/s]

2025-05-20 16:44:00,613 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:00,841 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2571/9304 [08:06<17:38,  6.36it/s]

2025-05-20 16:44:01,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2572/9304 [08:06<19:19,  5.81it/s]

2025-05-20 16:44:01,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2573/9304 [08:06<21:28,  5.22it/s]

2025-05-20 16:44:01,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2574/9304 [08:07<29:39,  3.78it/s]

2025-05-20 16:44:02,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:02,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2575/9304 [08:07<26:35,  4.22it/s]

2025-05-20 16:44:02,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:02,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2578/9304 [08:07<18:15,  6.14it/s]

2025-05-20 16:44:02,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:02,310 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:02,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2581/9304 [08:08<17:45,  6.31it/s]

2025-05-20 16:44:02,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:03,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2583/9304 [08:08<19:31,  5.73it/s]

2025-05-20 16:44:03,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:03,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:03,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2585/9304 [08:08<18:57,  5.91it/s]

2025-05-20 16:44:03,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2587/9304 [08:09<18:18,  6.12it/s]

2025-05-20 16:44:03,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2588/9304 [08:09<21:06,  5.30it/s]

2025-05-20 16:44:04,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2589/9304 [08:09<22:16,  5.02it/s]

2025-05-20 16:44:04,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2590/9304 [08:09<22:28,  4.98it/s]

2025-05-20 16:44:04,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:04,820 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2592/9304 [08:10<19:37,  5.70it/s]

2025-05-20 16:44:04,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:04,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2594/9304 [08:10<14:43,  7.59it/s]

2025-05-20 16:44:05,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2595/9304 [08:10<16:19,  6.85it/s]

2025-05-20 16:44:05,421 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2596/9304 [08:10<20:05,  5.56it/s]

2025-05-20 16:44:05,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2597/9304 [08:11<26:42,  4.19it/s]

2025-05-20 16:44:06,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2598/9304 [08:11<27:54,  4.00it/s]

2025-05-20 16:44:06,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:06,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:06,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:06,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2601/9304 [08:11<19:51,  5.63it/s]

2025-05-20 16:44:06,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2603/9304 [08:12<18:53,  5.91it/s]

2025-05-20 16:44:06,817 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:06,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:07,177 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2606/9304 [08:12<17:21,  6.43it/s]

2025-05-20 16:44:07,305 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2607/9304 [08:12<20:41,  5.40it/s]

2025-05-20 16:44:07,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2608/9304 [08:13<29:08,  3.83it/s]

2025-05-20 16:44:08,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:08,198 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:08,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2610/9304 [08:13<22:26,  4.97it/s]

2025-05-20 16:44:08,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2612/9304 [08:14<22:48,  4.89it/s]

2025-05-20 16:44:08,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:08,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:08,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2614/9304 [08:14<17:19,  6.44it/s]

2025-05-20 16:44:08,866 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2616/9304 [08:14<16:39,  6.69it/s]

2025-05-20 16:44:09,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2617/9304 [08:14<25:35,  4.35it/s]

2025-05-20 16:44:09,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:09,817 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2619/9304 [08:15<20:23,  5.46it/s]

2025-05-20 16:44:10,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2620/9304 [08:15<22:00,  5.06it/s]

2025-05-20 16:44:10,259 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2621/9304 [08:15<21:13,  5.25it/s]

2025-05-20 16:44:10,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:10,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2623/9304 [08:15<17:47,  6.26it/s]

2025-05-20 16:44:10,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2624/9304 [08:15<17:50,  6.24it/s]

2025-05-20 16:44:10,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2625/9304 [08:16<21:08,  5.27it/s]

2025-05-20 16:44:11,142 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:11,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2626/9304 [08:16<27:19,  4.07it/s]

2025-05-20 16:44:11,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:11,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2629/9304 [08:17<20:23,  5.45it/s]

2025-05-20 16:44:12,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:12,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2630/9304 [08:17<23:10,  4.80it/s]

2025-05-20 16:44:12,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2632/9304 [08:17<17:50,  6.23it/s]

2025-05-20 16:44:12,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:12,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2634/9304 [08:17<19:09,  5.80it/s]

2025-05-20 16:44:12,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2635/9304 [08:18<19:59,  5.56it/s]

2025-05-20 16:44:13,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:13,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2636/9304 [08:18<22:11,  5.01it/s]

2025-05-20 16:44:13,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2638/9304 [08:18<23:10,  4.80it/s]

2025-05-20 16:44:13,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2639/9304 [08:19<26:33,  4.18it/s]

2025-05-20 16:44:14,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2640/9304 [08:19<32:33,  3.41it/s]

2025-05-20 16:44:14,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:14,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2641/9304 [08:19<29:56,  3.71it/s]

2025-05-20 16:44:14,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:14,657 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2643/9304 [08:19<20:18,  5.47it/s]

2025-05-20 16:44:14,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:15,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2645/9304 [08:20<20:47,  5.34it/s]

2025-05-20 16:44:15,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2647/9304 [08:20<17:20,  6.40it/s]

2025-05-20 16:44:15,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2648/9304 [08:20<18:33,  5.98it/s]

2025-05-20 16:44:15,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2649/9304 [08:21<22:02,  5.03it/s]

2025-05-20 16:44:16,069 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2650/9304 [08:21<24:53,  4.45it/s]

2025-05-20 16:44:16,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:16,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 28%|██▊       | 2651/9304 [08:21<22:08,  5.01it/s]

2025-05-20 16:44:16,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2653/9304 [08:21<17:28,  6.34it/s]

2025-05-20 16:44:16,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:16,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2655/9304 [08:22<20:08,  5.50it/s]

2025-05-20 16:44:17,139 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:17,310 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2656/9304 [08:22<26:54,  4.12it/s]

2025-05-20 16:44:17,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2658/9304 [08:22<21:46,  5.09it/s]

2025-05-20 16:44:17,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:17,863 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2660/9304 [08:23<20:40,  5.36it/s]

2025-05-20 16:44:17,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:17,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:18,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2663/9304 [08:23<19:00,  5.82it/s]

2025-05-20 16:44:18,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2664/9304 [08:23<18:46,  5.89it/s]

2025-05-20 16:44:18,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2665/9304 [08:24<24:54,  4.44it/s]

2025-05-20 16:44:19,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:19,032 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:19,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:19,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2668/9304 [08:24<20:09,  5.49it/s]

2025-05-20 16:44:19,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2670/9304 [08:24<18:03,  6.12it/s]

2025-05-20 16:44:19,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2671/9304 [08:25<19:21,  5.71it/s]

2025-05-20 16:44:20,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2672/9304 [08:25<20:59,  5.26it/s]

2025-05-20 16:44:20,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:20,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:20,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▊       | 2674/9304 [08:25<19:29,  5.67it/s]

2025-05-20 16:44:20,730 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2676/9304 [08:26<21:27,  5.15it/s]

2025-05-20 16:44:20,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:21,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2678/9304 [08:26<20:05,  5.49it/s]

2025-05-20 16:44:21,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:21,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2680/9304 [08:26<18:16,  6.04it/s]

2025-05-20 16:44:21,503 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2681/9304 [08:26<17:08,  6.44it/s]

2025-05-20 16:44:21,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:21,664 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2682/9304 [08:26<17:01,  6.48it/s]

2025-05-20 16:44:22,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2684/9304 [08:27<20:06,  5.49it/s]

2025-05-20 16:44:22,205 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2685/9304 [08:27<22:58,  4.80it/s]

2025-05-20 16:44:22,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2686/9304 [08:28<25:25,  4.34it/s]

2025-05-20 16:44:22,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2687/9304 [08:28<24:50,  4.44it/s]

2025-05-20 16:44:22,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:23,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2689/9304 [08:28<17:30,  6.30it/s]

2025-05-20 16:44:23,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:23,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2691/9304 [08:28<20:22,  5.41it/s]

2025-05-20 16:44:23,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2692/9304 [08:29<19:40,  5.60it/s]

2025-05-20 16:44:23,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:24,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2694/9304 [08:29<22:09,  4.97it/s]

2025-05-20 16:44:24,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:24,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:24,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2697/9304 [08:30<21:49,  5.05it/s]

2025-05-20 16:44:24,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2698/9304 [08:30<24:48,  4.44it/s]

2025-05-20 16:44:25,112 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:25,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:25,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2701/9304 [08:30<18:44,  5.87it/s]

2025-05-20 16:44:25,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:25,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2702/9304 [08:31<21:18,  5.16it/s]

2025-05-20 16:44:25,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:25,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2704/9304 [08:31<17:19,  6.35it/s]

2025-05-20 16:44:26,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2706/9304 [08:31<16:22,  6.72it/s]

2025-05-20 16:44:26,539 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:26,613 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2707/9304 [08:31<23:22,  4.70it/s]

2025-05-20 16:44:26,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2709/9304 [08:32<21:07,  5.20it/s]

2025-05-20 16:44:27,037 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2710/9304 [08:32<23:40,  4.64it/s]

2025-05-20 16:44:27,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:27,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:27,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:27,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2714/9304 [08:32<12:34,  8.73it/s]

2025-05-20 16:44:27,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:27,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2716/9304 [08:33<16:55,  6.48it/s]

2025-05-20 16:44:28,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:28,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2718/9304 [08:33<21:44,  5.05it/s]

2025-05-20 16:44:28,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2719/9304 [08:34<21:56,  5.00it/s]

2025-05-20 16:44:28,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:28,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2721/9304 [08:34<19:00,  5.77it/s]

2025-05-20 16:44:29,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2722/9304 [08:34<18:55,  5.80it/s]

2025-05-20 16:44:29,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2723/9304 [08:34<21:55,  5.00it/s]

2025-05-20 16:44:29,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2724/9304 [08:35<26:10,  4.19it/s]

2025-05-20 16:44:29,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2725/9304 [08:35<26:00,  4.22it/s]

2025-05-20 16:44:30,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2726/9304 [08:35<26:19,  4.16it/s]

2025-05-20 16:44:30,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:30,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2727/9304 [08:35<22:41,  4.83it/s]

2025-05-20 16:44:30,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:30,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2730/9304 [08:35<13:49,  7.92it/s]

2025-05-20 16:44:30,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2731/9304 [08:35<13:21,  8.20it/s]

2025-05-20 16:44:31,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2732/9304 [08:36<22:50,  4.80it/s]

2025-05-20 16:44:31,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2733/9304 [08:36<23:27,  4.67it/s]

2025-05-20 16:44:31,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:31,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2735/9304 [08:36<16:13,  6.75it/s]

2025-05-20 16:44:31,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:31,966 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:31,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2737/9304 [08:37<20:34,  5.32it/s]

2025-05-20 16:44:32,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2739/9304 [08:37<18:07,  6.04it/s]

2025-05-20 16:44:32,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2740/9304 [08:37<19:23,  5.64it/s]

2025-05-20 16:44:32,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2741/9304 [08:38<22:22,  4.89it/s]

2025-05-20 16:44:32,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:32,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 29%|██▉       | 2743/9304 [08:38<18:17,  5.98it/s]

2025-05-20 16:44:32,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:33,041 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2745/9304 [08:38<17:57,  6.08it/s]

2025-05-20 16:44:33,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2746/9304 [08:39<24:42,  4.42it/s]

2025-05-20 16:44:34,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2747/9304 [08:39<26:25,  4.13it/s]

2025-05-20 16:44:34,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:34,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2748/9304 [08:39<23:52,  4.58it/s]

2025-05-20 16:44:34,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2750/9304 [08:39<18:31,  5.90it/s]

2025-05-20 16:44:34,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:34,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2751/9304 [08:39<19:29,  5.60it/s]

2025-05-20 16:44:34,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2753/9304 [08:40<14:43,  7.42it/s]

2025-05-20 16:44:34,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:35,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2755/9304 [08:40<15:03,  7.25it/s]

2025-05-20 16:44:35,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2756/9304 [08:40<18:31,  5.89it/s]

2025-05-20 16:44:35,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2757/9304 [08:41<31:12,  3.50it/s]

2025-05-20 16:44:36,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:36,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:36,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:36,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2760/9304 [08:41<19:08,  5.70it/s]

2025-05-20 16:44:36,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2762/9304 [08:41<16:28,  6.62it/s]

2025-05-20 16:44:36,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2763/9304 [08:41<18:38,  5.85it/s]

2025-05-20 16:44:36,714 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2764/9304 [08:42<22:16,  4.89it/s]

2025-05-20 16:44:37,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:37,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:37,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:37,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2766/9304 [08:43<30:58,  3.52it/s]

2025-05-20 16:44:37,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:37,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:38,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2771/9304 [08:43<22:06,  4.92it/s]

2025-05-20 16:44:38,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2772/9304 [08:43<21:14,  5.13it/s]

2025-05-20 16:44:38,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:38,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:39,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:39,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2775/9304 [08:44<23:56,  4.55it/s]

2025-05-20 16:44:39,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2777/9304 [08:45<23:29,  4.63it/s]

2025-05-20 16:44:39,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:40,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2779/9304 [08:45<20:09,  5.40it/s]

2025-05-20 16:44:40,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:40,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2781/9304 [08:45<17:37,  6.17it/s]

2025-05-20 16:44:40,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:40,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2782/9304 [08:45<20:16,  5.36it/s]

2025-05-20 16:44:40,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2784/9304 [08:46<16:11,  6.71it/s]

2025-05-20 16:44:40,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:40,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:41,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:41,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2787/9304 [08:46<21:12,  5.12it/s]

2025-05-20 16:44:41,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:41,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2789/9304 [08:47<19:42,  5.51it/s]

2025-05-20 16:44:42,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|██▉       | 2791/9304 [08:47<20:36,  5.27it/s]

2025-05-20 16:44:42,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:42,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2792/9304 [08:47<19:40,  5.51it/s]

2025-05-20 16:44:42,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2794/9304 [08:47<16:20,  6.64it/s]

2025-05-20 16:44:42,955 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2795/9304 [08:48<21:39,  5.01it/s]

2025-05-20 16:44:43,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2796/9304 [08:48<28:53,  3.76it/s]

2025-05-20 16:44:43,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:43,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2797/9304 [08:48<26:49,  4.04it/s]

2025-05-20 16:44:43,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2799/9304 [08:49<23:11,  4.67it/s]

2025-05-20 16:44:44,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:44,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2800/9304 [08:49<20:58,  5.17it/s]

2025-05-20 16:44:44,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2802/9304 [08:49<15:23,  7.04it/s]

2025-05-20 16:44:44,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2803/9304 [08:49<16:42,  6.49it/s]

2025-05-20 16:44:44,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:44,721 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2805/9304 [08:50<16:30,  6.56it/s]

2025-05-20 16:44:45,185 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2806/9304 [08:50<27:01,  4.01it/s]

2025-05-20 16:44:45,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2807/9304 [08:50<26:42,  4.05it/s]

2025-05-20 16:44:45,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2808/9304 [08:51<23:51,  4.54it/s]

2025-05-20 16:44:45,713 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:45,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:45,791 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:46,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2811/9304 [08:51<17:08,  6.31it/s]

2025-05-20 16:44:46,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:46,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:46,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2814/9304 [08:51<16:50,  6.43it/s]

2025-05-20 16:44:47,275 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:47,305 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2816/9304 [08:52<24:58,  4.33it/s]

2025-05-20 16:44:47,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:47,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2817/9304 [08:52<27:01,  4.00it/s]

2025-05-20 16:44:47,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:47,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:47,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:47,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2823/9304 [08:53<16:07,  6.70it/s]

2025-05-20 16:44:48,237 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2824/9304 [08:53<18:23,  5.87it/s]

2025-05-20 16:44:48,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:48,855 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2826/9304 [08:54<20:19,  5.31it/s]

2025-05-20 16:44:49,134 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2827/9304 [08:54<21:23,  5.05it/s]

2025-05-20 16:44:49,258 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2828/9304 [08:54<21:43,  4.97it/s]

2025-05-20 16:44:49,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2829/9304 [08:54<23:01,  4.69it/s]

2025-05-20 16:44:49,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:49,696 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:49,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:49,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2833/9304 [08:55<15:03,  7.16it/s]

2025-05-20 16:44:50,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2834/9304 [08:55<19:20,  5.58it/s]

2025-05-20 16:44:50,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:50,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2835/9304 [08:56<24:05,  4.48it/s]

2025-05-20 16:44:51,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 30%|███       | 2837/9304 [08:56<25:55,  4.16it/s]

2025-05-20 16:44:51,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:51,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:51,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2839/9304 [08:56<20:48,  5.18it/s]

2025-05-20 16:44:51,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2841/9304 [08:56<16:14,  6.64it/s]

2025-05-20 16:44:51,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2842/9304 [08:57<21:11,  5.08it/s]

2025-05-20 16:44:52,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:52,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2843/9304 [08:57<22:48,  4.72it/s]

2025-05-20 16:44:52,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2845/9304 [08:57<18:33,  5.80it/s]

2025-05-20 16:44:52,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:52,793 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2847/9304 [08:58<17:45,  6.06it/s]

2025-05-20 16:44:52,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:53,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2848/9304 [08:58<22:55,  4.69it/s]

2025-05-20 16:44:53,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:53,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2851/9304 [08:59<21:06,  5.09it/s]

2025-05-20 16:44:53,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:53,843 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2853/9304 [08:59<16:30,  6.52it/s]

2025-05-20 16:44:54,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:54,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2854/9304 [08:59<22:56,  4.69it/s]

2025-05-20 16:44:54,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:54,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:54,542 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2857/9304 [08:59<16:13,  6.62it/s]

2025-05-20 16:44:54,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:54,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2859/9304 [09:00<17:55,  5.99it/s]

2025-05-20 16:44:55,155 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2861/9304 [09:00<15:47,  6.80it/s]

2025-05-20 16:44:55,855 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2862/9304 [09:01<26:08,  4.11it/s]

2025-05-20 16:44:55,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:55,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:56,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2864/9304 [09:01<19:59,  5.37it/s]

2025-05-20 16:44:56,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:56,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2867/9304 [09:01<13:26,  7.98it/s]

2025-05-20 16:44:56,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:56,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2869/9304 [09:02<20:23,  5.26it/s]

2025-05-20 16:44:56,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:56,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2871/9304 [09:02<18:35,  5.77it/s]

2025-05-20 16:44:57,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2872/9304 [09:02<23:04,  4.64it/s]

2025-05-20 16:44:57,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2873/9304 [09:02<20:40,  5.18it/s]

2025-05-20 16:44:57,813 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2874/9304 [09:03<20:57,  5.11it/s]

2025-05-20 16:44:57,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:57,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2876/9304 [09:03<14:59,  7.14it/s]

2025-05-20 16:44:58,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:58,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2878/9304 [09:03<13:58,  7.67it/s]

2025-05-20 16:44:58,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:58,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2880/9304 [09:03<14:14,  7.52it/s]

2025-05-20 16:44:59,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2881/9304 [09:04<24:49,  4.31it/s]

2025-05-20 16:44:59,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:59,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2882/9304 [09:04<27:02,  3.96it/s]

2025-05-20 16:44:59,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2884/9304 [09:04<19:09,  5.59it/s]

2025-05-20 16:44:59,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:59,621 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:59,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:44:59,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2886/9304 [09:05<19:27,  5.50it/s]

2025-05-20 16:45:00,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2889/9304 [09:05<20:06,  5.32it/s]

2025-05-20 16:45:00,678 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2890/9304 [09:06<20:34,  5.20it/s]

2025-05-20 16:45:00,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2891/9304 [09:06<19:35,  5.45it/s]

2025-05-20 16:45:00,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2892/9304 [09:06<18:20,  5.83it/s]

2025-05-20 16:45:00,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:01,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2894/9304 [09:06<18:11,  5.87it/s]

2025-05-20 16:45:01,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2895/9304 [09:06<19:11,  5.56it/s]

2025-05-20 16:45:01,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:01,545 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:01,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:02,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2899/9304 [09:07<18:45,  5.69it/s]

2025-05-20 16:45:02,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:02,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2901/9304 [09:07<18:19,  5.82it/s]

2025-05-20 16:45:02,732 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2902/9304 [09:08<18:58,  5.62it/s]

2025-05-20 16:45:02,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:02,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███       | 2903/9304 [09:08<19:16,  5.54it/s]

2025-05-20 16:45:02,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:02,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:03,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:03,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2908/9304 [09:08<12:10,  8.76it/s]

2025-05-20 16:45:03,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2909/9304 [09:08<16:01,  6.65it/s]

2025-05-20 16:45:03,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2910/9304 [09:09<18:44,  5.69it/s]

2025-05-20 16:45:04,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2911/9304 [09:09<19:08,  5.57it/s]

2025-05-20 16:45:04,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:04,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2912/9304 [09:09<22:35,  4.72it/s]

2025-05-20 16:45:04,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:04,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:04,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2916/9304 [09:09<11:39,  9.13it/s]

2025-05-20 16:45:04,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:04,744 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2918/9304 [09:10<11:10,  9.52it/s]

2025-05-20 16:45:05,153 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:05,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2920/9304 [09:10<18:43,  5.68it/s]

2025-05-20 16:45:05,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:05,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2922/9304 [09:11<21:49,  4.87it/s]

2025-05-20 16:45:06,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:06,085 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:06,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:06,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2925/9304 [09:11<19:51,  5.35it/s]

2025-05-20 16:45:06,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:06,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2928/9304 [09:12<17:07,  6.21it/s]

2025-05-20 16:45:06,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:07,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 31%|███▏      | 2930/9304 [09:12<19:04,  5.57it/s]

2025-05-20 16:45:07,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2931/9304 [09:12<18:17,  5.81it/s]

2025-05-20 16:45:07,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:07,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2933/9304 [09:13<17:26,  6.09it/s]

2025-05-20 16:45:08,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2934/9304 [09:13<20:04,  5.29it/s]

2025-05-20 16:45:08,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:08,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2935/9304 [09:13<20:30,  5.18it/s]

2025-05-20 16:45:08,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2937/9304 [09:13<15:20,  6.92it/s]

2025-05-20 16:45:08,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:08,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2938/9304 [09:13<18:31,  5.73it/s]

2025-05-20 16:45:08,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2940/9304 [09:14<15:29,  6.85it/s]

2025-05-20 16:45:09,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2941/9304 [09:14<18:51,  5.62it/s]

2025-05-20 16:45:09,332 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2942/9304 [09:14<19:35,  5.41it/s]

2025-05-20 16:45:09,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2943/9304 [09:15<28:15,  3.75it/s]

2025-05-20 16:45:09,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:10,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2944/9304 [09:15<26:54,  3.94it/s]

2025-05-20 16:45:10,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:10,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2947/9304 [09:15<17:19,  6.12it/s]

2025-05-20 16:45:10,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:10,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:10,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:10,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2950/9304 [09:15<15:21,  6.90it/s]

2025-05-20 16:45:11,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2952/9304 [09:16<17:59,  5.89it/s]

2025-05-20 16:45:11,142 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:11,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2954/9304 [09:16<19:56,  5.31it/s]

2025-05-20 16:45:11,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:11,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2956/9304 [09:17<16:26,  6.43it/s]

2025-05-20 16:45:11,760 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:11,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2958/9304 [09:17<14:16,  7.41it/s]

2025-05-20 16:45:11,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:12,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2960/9304 [09:17<13:18,  7.94it/s]

2025-05-20 16:45:12,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2961/9304 [09:18<21:32,  4.91it/s]

2025-05-20 16:45:12,730 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2962/9304 [09:18<23:52,  4.43it/s]

2025-05-20 16:45:13,227 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:13,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2963/9304 [09:18<23:33,  4.49it/s]

2025-05-20 16:45:13,240 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:13,366 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2966/9304 [09:18<14:24,  7.33it/s]

2025-05-20 16:45:13,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:13,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:14,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2969/9304 [09:19<18:50,  5.60it/s]

2025-05-20 16:45:14,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2970/9304 [09:19<23:43,  4.45it/s]

2025-05-20 16:45:14,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2971/9304 [09:20<24:25,  4.32it/s]

2025-05-20 16:45:14,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:14,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:14,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:14,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2974/9304 [09:20<15:36,  6.76it/s]

2025-05-20 16:45:15,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2976/9304 [09:20<14:16,  7.39it/s]

2025-05-20 16:45:15,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:15,470 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2978/9304 [09:20<15:14,  6.92it/s]

2025-05-20 16:45:15,766 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2979/9304 [09:21<17:48,  5.92it/s]

2025-05-20 16:45:16,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:16,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2980/9304 [09:21<27:14,  3.87it/s]

2025-05-20 16:45:16,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2982/9304 [09:22<23:03,  4.57it/s]

2025-05-20 16:45:16,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:16,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:16,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2984/9304 [09:22<19:56,  5.28it/s]

2025-05-20 16:45:16,962 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:17,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2987/9304 [09:22<14:30,  7.26it/s]

2025-05-20 16:45:17,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:17,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:17,821 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2990/9304 [09:23<17:56,  5.86it/s]

2025-05-20 16:45:18,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2991/9304 [09:23<24:52,  4.23it/s]

2025-05-20 16:45:18,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:18,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:18,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2994/9304 [09:24<18:58,  5.54it/s]

2025-05-20 16:45:18,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:18,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:19,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 2997/9304 [09:24<21:15,  4.95it/s]

2025-05-20 16:45:19,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:19,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:19,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3000/9304 [09:24<15:17,  6.87it/s]

2025-05-20 16:45:20,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:20,094 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3002/9304 [09:25<18:56,  5.54it/s]

2025-05-20 16:45:20,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:20,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:20,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3005/9304 [09:25<15:31,  6.76it/s]

2025-05-20 16:45:20,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:20,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3007/9304 [09:26<19:50,  5.29it/s]

2025-05-20 16:45:21,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:21,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3009/9304 [09:26<16:23,  6.40it/s]

2025-05-20 16:45:21,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:21,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3011/9304 [09:27<21:30,  4.88it/s]

2025-05-20 16:45:21,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:22,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3013/9304 [09:27<19:37,  5.34it/s]

2025-05-20 16:45:22,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:22,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:22,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3015/9304 [09:27<16:52,  6.21it/s]

2025-05-20 16:45:22,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3017/9304 [09:27<14:29,  7.23it/s]

2025-05-20 16:45:22,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3018/9304 [09:28<17:04,  6.14it/s]

2025-05-20 16:45:22,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3019/9304 [09:28<19:33,  5.36it/s]

2025-05-20 16:45:23,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3020/9304 [09:28<21:20,  4.91it/s]

2025-05-20 16:45:23,289 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:23,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3022/9304 [09:28<20:11,  5.18it/s]

2025-05-20 16:45:23,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:23,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 32%|███▏      | 3023/9304 [09:29<21:01,  4.98it/s]

2025-05-20 16:45:23,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:23,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:24,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3027/9304 [09:29<12:48,  8.17it/s]

2025-05-20 16:45:24,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:24,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3029/9304 [09:29<14:28,  7.23it/s]

2025-05-20 16:45:24,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3030/9304 [09:30<23:19,  4.48it/s]

2025-05-20 16:45:25,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:25,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3031/9304 [09:30<25:20,  4.13it/s]

2025-05-20 16:45:25,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:25,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3033/9304 [09:30<19:06,  5.47it/s]

2025-05-20 16:45:25,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:25,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:25,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:25,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3037/9304 [09:31<11:40,  8.95it/s]

2025-05-20 16:45:26,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3039/9304 [09:32<22:56,  4.55it/s]

2025-05-20 16:45:27,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3040/9304 [09:32<23:40,  4.41it/s]

2025-05-20 16:45:27,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:27,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3042/9304 [09:32<18:01,  5.79it/s]

2025-05-20 16:45:27,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:27,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:27,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3045/9304 [09:32<13:00,  8.02it/s]

2025-05-20 16:45:27,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:27,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3047/9304 [09:33<17:26,  5.98it/s]

2025-05-20 16:45:27,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:28,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:28,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3049/9304 [09:33<23:03,  4.52it/s]

2025-05-20 16:45:28,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:28,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:28,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3053/9304 [09:34<17:21,  6.00it/s]

2025-05-20 16:45:29,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3054/9304 [09:34<17:34,  5.93it/s]

2025-05-20 16:45:29,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:29,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3055/9304 [09:34<19:50,  5.25it/s]

2025-05-20 16:45:29,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3057/9304 [09:35<19:01,  5.47it/s]

2025-05-20 16:45:29,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3058/9304 [09:35<19:51,  5.24it/s]

2025-05-20 16:45:30,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3059/9304 [09:35<20:10,  5.16it/s]

2025-05-20 16:45:30,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3060/9304 [09:35<21:19,  4.88it/s]

2025-05-20 16:45:30,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3061/9304 [09:35<19:26,  5.35it/s]

2025-05-20 16:45:30,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3062/9304 [09:36<19:22,  5.37it/s]

2025-05-20 16:45:30,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3063/9304 [09:36<17:41,  5.88it/s]

2025-05-20 16:45:31,021 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3064/9304 [09:36<17:01,  6.11it/s]

2025-05-20 16:45:31,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:31,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3066/9304 [09:36<18:35,  5.59it/s]

2025-05-20 16:45:31,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3067/9304 [09:36<17:29,  5.95it/s]

2025-05-20 16:45:31,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3068/9304 [09:37<23:22,  4.45it/s]

2025-05-20 16:45:32,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:32,257 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3069/9304 [09:37<25:05,  4.14it/s]

2025-05-20 16:45:32,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:32,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:32,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3072/9304 [09:37<17:00,  6.11it/s]

2025-05-20 16:45:32,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3074/9304 [09:38<18:47,  5.52it/s]

2025-05-20 16:45:33,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3075/9304 [09:38<21:21,  4.86it/s]

2025-05-20 16:45:33,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3076/9304 [09:38<24:12,  4.29it/s]

2025-05-20 16:45:33,620 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:33,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:33,798 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3078/9304 [09:39<18:34,  5.59it/s]

2025-05-20 16:45:34,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:34,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3080/9304 [09:39<16:26,  6.31it/s]

2025-05-20 16:45:34,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3082/9304 [09:39<15:37,  6.64it/s]

2025-05-20 16:45:34,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3083/9304 [09:39<18:12,  5.69it/s]

2025-05-20 16:45:34,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:34,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3085/9304 [09:40<14:01,  7.39it/s]

2025-05-20 16:45:35,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3086/9304 [09:40<22:48,  4.55it/s]

2025-05-20 16:45:35,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:35,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3088/9304 [09:40<18:54,  5.48it/s]

2025-05-20 16:45:35,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:35,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:35,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3091/9304 [09:41<16:31,  6.27it/s]

2025-05-20 16:45:35,964 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:36,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3093/9304 [09:41<14:44,  7.02it/s]

2025-05-20 16:45:36,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3094/9304 [09:41<14:04,  7.35it/s]

2025-05-20 16:45:36,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:36,498 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3096/9304 [09:41<16:16,  6.36it/s]

2025-05-20 16:45:36,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3097/9304 [09:42<17:51,  5.79it/s]

2025-05-20 16:45:37,227 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:37,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3098/9304 [09:42<23:33,  4.39it/s]

2025-05-20 16:45:37,275 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:37,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3101/9304 [09:42<15:47,  6.55it/s]

2025-05-20 16:45:37,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:37,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3102/9304 [09:43<17:42,  5.83it/s]

2025-05-20 16:45:38,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:38,198 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3104/9304 [09:43<19:53,  5.19it/s]

2025-05-20 16:45:38,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3106/9304 [09:43<15:20,  6.73it/s]

2025-05-20 16:45:38,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3107/9304 [09:43<18:25,  5.61it/s]

2025-05-20 16:45:38,785 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:38,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3108/9304 [09:44<19:28,  5.30it/s]

2025-05-20 16:45:38,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:38,987 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3110/9304 [09:44<14:46,  6.99it/s]

2025-05-20 16:45:39,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3112/9304 [09:44<15:39,  6.59it/s]

2025-05-20 16:45:39,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3113/9304 [09:44<18:31,  5.57it/s]

2025-05-20 16:45:39,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:40,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 33%|███▎      | 3114/9304 [09:45<24:22,  4.23it/s]

2025-05-20 16:45:40,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:40,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:40,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3117/9304 [09:45<15:36,  6.61it/s]

2025-05-20 16:45:40,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3119/9304 [09:45<12:47,  8.05it/s]

2025-05-20 16:45:40,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:40,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:40,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3121/9304 [09:46<15:25,  6.68it/s]

2025-05-20 16:45:41,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:41,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3123/9304 [09:46<19:04,  5.40it/s]

2025-05-20 16:45:41,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:41,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3125/9304 [09:47<21:00,  4.90it/s]

2025-05-20 16:45:41,807 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:42,108 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3128/9304 [09:47<16:51,  6.10it/s]

2025-05-20 16:45:42,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3129/9304 [09:47<16:40,  6.17it/s]

2025-05-20 16:45:42,379 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3130/9304 [09:47<15:50,  6.50it/s]

2025-05-20 16:45:42,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3131/9304 [09:47<15:34,  6.61it/s]

2025-05-20 16:45:42,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3132/9304 [09:48<16:23,  6.27it/s]

2025-05-20 16:45:42,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3133/9304 [09:48<16:55,  6.07it/s]

2025-05-20 16:45:43,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:43,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3134/9304 [09:48<22:17,  4.61it/s]

2025-05-20 16:45:43,422 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:43,657 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3136/9304 [09:48<21:39,  4.75it/s]

2025-05-20 16:45:43,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:43,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3138/9304 [09:49<19:44,  5.21it/s]

2025-05-20 16:45:44,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▎      | 3140/9304 [09:49<15:32,  6.61it/s]

2025-05-20 16:45:44,180 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:44,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3141/9304 [09:49<15:00,  6.85it/s]

2025-05-20 16:45:44,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3143/9304 [09:50<23:27,  4.38it/s]

2025-05-20 16:45:45,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:45,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3145/9304 [09:50<20:20,  5.05it/s]

2025-05-20 16:45:45,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:45,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:45,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3148/9304 [09:50<14:05,  7.28it/s]

2025-05-20 16:45:45,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:45,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3150/9304 [09:51<17:15,  5.95it/s]

2025-05-20 16:45:45,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:46,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3151/9304 [09:51<19:28,  5.26it/s]

2025-05-20 16:45:46,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3153/9304 [09:51<20:11,  5.08it/s]

2025-05-20 16:45:46,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:46,766 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3155/9304 [09:52<18:41,  5.48it/s]

2025-05-20 16:45:46,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:47,116 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:47,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3157/9304 [09:52<20:56,  4.89it/s]

2025-05-20 16:45:47,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:48,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:48,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:48,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3160/9304 [09:53<21:03,  4.86it/s]

2025-05-20 16:45:48,388 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3163/9304 [09:53<17:10,  5.96it/s]

2025-05-20 16:45:48,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:48,433 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:48,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3166/9304 [09:53<13:39,  7.49it/s]

2025-05-20 16:45:49,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:49,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3167/9304 [09:54<18:50,  5.43it/s]

2025-05-20 16:45:49,145 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3169/9304 [09:54<16:04,  6.36it/s]

2025-05-20 16:45:49,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:49,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3170/9304 [09:55<20:36,  4.96it/s]

2025-05-20 16:45:49,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3172/9304 [09:55<17:55,  5.70it/s]

2025-05-20 16:45:49,992 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3173/9304 [09:55<17:45,  5.75it/s]

2025-05-20 16:45:50,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:50,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3175/9304 [09:55<17:44,  5.76it/s]

2025-05-20 16:45:50,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:50,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3177/9304 [09:55<15:21,  6.65it/s]

2025-05-20 16:45:50,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:51,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3179/9304 [09:56<20:31,  4.97it/s]

2025-05-20 16:45:51,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3180/9304 [09:56<24:30,  4.17it/s]

2025-05-20 16:45:51,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:51,988 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3182/9304 [09:57<21:32,  4.74it/s]

2025-05-20 16:45:51,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:52,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:52,118 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3185/9304 [09:57<14:39,  6.95it/s]

2025-05-20 16:45:52,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:52,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3187/9304 [09:58<18:28,  5.52it/s]

2025-05-20 16:45:52,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:53,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3189/9304 [09:58<19:18,  5.28it/s]

2025-05-20 16:45:53,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3190/9304 [09:58<18:20,  5.56it/s]

2025-05-20 16:45:53,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:53,291 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:53,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:53,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3194/9304 [09:58<12:54,  7.89it/s]

2025-05-20 16:45:53,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:54,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3196/9304 [09:59<19:34,  5.20it/s]

2025-05-20 16:45:54,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:54,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3197/9304 [09:59<22:08,  4.60it/s]

2025-05-20 16:45:54,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3199/9304 [10:00<18:23,  5.53it/s]

2025-05-20 16:45:54,871 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:54,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:54,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3202/9304 [10:00<12:27,  8.16it/s]

2025-05-20 16:45:54,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:54,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:55,251 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3205/9304 [10:00<11:37,  8.74it/s]

2025-05-20 16:45:56,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:56,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3207/9304 [10:01<24:21,  4.17it/s]

2025-05-20 16:45:56,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 34%|███▍      | 3208/9304 [10:02<24:10,  4.20it/s]

2025-05-20 16:45:56,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:56,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:56,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:56,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:56,908 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3212/9304 [10:02<15:25,  6.58it/s]

2025-05-20 16:45:57,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3214/9304 [10:02<19:13,  5.28it/s]

2025-05-20 16:45:57,579 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:57,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3216/9304 [10:03<20:16,  5.00it/s]

2025-05-20 16:45:57,974 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:58,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:58,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3218/9304 [10:03<20:27,  4.96it/s]

2025-05-20 16:45:58,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:58,503 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3220/9304 [10:03<16:30,  6.14it/s]

2025-05-20 16:45:58,565 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:58,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3223/9304 [10:03<11:37,  8.72it/s]

2025-05-20 16:45:59,126 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:59,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3225/9304 [10:04<19:01,  5.33it/s]

2025-05-20 16:45:59,657 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:59,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3227/9304 [10:05<21:21,  4.74it/s]

2025-05-20 16:45:59,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:59,953 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:45:59,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:00,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:00,152 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3232/9304 [10:05<15:08,  6.69it/s]

2025-05-20 16:46:00,374 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:00,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3234/9304 [10:06<15:54,  6.36it/s]

2025-05-20 16:46:01,244 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3235/9304 [10:06<20:48,  4.86it/s]

2025-05-20 16:46:01,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3236/9304 [10:06<20:15,  4.99it/s]

2025-05-20 16:46:01,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3237/9304 [10:06<19:09,  5.28it/s]

2025-05-20 16:46:01,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:01,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:01,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3240/9304 [10:07<17:29,  5.78it/s]

2025-05-20 16:46:02,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:02,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3242/9304 [10:07<15:54,  6.35it/s]

2025-05-20 16:46:02,475 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3243/9304 [10:07<16:53,  5.98it/s]

2025-05-20 16:46:02,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:02,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3245/9304 [10:08<16:59,  5.94it/s]

2025-05-20 16:46:03,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3246/9304 [10:08<19:02,  5.30it/s]

2025-05-20 16:46:03,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:03,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3247/9304 [10:08<22:21,  4.52it/s]

2025-05-20 16:46:03,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3249/9304 [10:08<17:04,  5.91it/s]

2025-05-20 16:46:03,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:03,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3250/9304 [10:09<20:31,  4.92it/s]

2025-05-20 16:46:03,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:04,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3253/9304 [10:09<17:26,  5.78it/s]

2025-05-20 16:46:04,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3254/9304 [10:09<16:23,  6.15it/s]

2025-05-20 16:46:04,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:04,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:04,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▍      | 3256/9304 [10:10<18:22,  5.48it/s]

2025-05-20 16:46:04,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3258/9304 [10:10<18:13,  5.53it/s]

2025-05-20 16:46:05,573 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3259/9304 [10:10<20:48,  4.84it/s]

2025-05-20 16:46:05,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:05,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3261/9304 [10:11<15:20,  6.57it/s]

2025-05-20 16:46:06,023 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:06,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3262/9304 [10:11<19:15,  5.23it/s]

2025-05-20 16:46:06,291 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:06,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3264/9304 [10:11<17:04,  5.90it/s]

2025-05-20 16:46:06,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3266/9304 [10:11<16:27,  6.11it/s]

2025-05-20 16:46:06,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:06,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3268/9304 [10:12<16:00,  6.29it/s]

2025-05-20 16:46:06,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:07,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:07,419 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3270/9304 [10:12<19:10,  5.24it/s]

2025-05-20 16:46:07,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:07,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3272/9304 [10:13<19:42,  5.10it/s]

2025-05-20 16:46:08,032 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3274/9304 [10:13<16:44,  6.00it/s]

2025-05-20 16:46:08,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:08,443 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3275/9304 [10:13<21:11,  4.74it/s]

2025-05-20 16:46:08,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3277/9304 [10:14<18:38,  5.39it/s]

2025-05-20 16:46:08,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:09,094 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:09,257 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3279/9304 [10:14<21:25,  4.69it/s]

2025-05-20 16:46:09,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:09,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3281/9304 [10:14<19:27,  5.16it/s]

2025-05-20 16:46:10,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3283/9304 [10:15<20:53,  4.80it/s]

2025-05-20 16:46:10,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:10,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3285/9304 [10:15<19:53,  5.04it/s]

2025-05-20 16:46:10,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:10,492 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3287/9304 [10:15<16:26,  6.10it/s]

2025-05-20 16:46:10,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:10,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3289/9304 [10:16<16:25,  6.11it/s]

2025-05-20 16:46:11,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3290/9304 [10:16<19:40,  5.09it/s]

2025-05-20 16:46:11,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3291/9304 [10:17<25:14,  3.97it/s]

2025-05-20 16:46:11,721 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:11,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:12,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3294/9304 [10:17<18:16,  5.48it/s]

2025-05-20 16:46:12,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:12,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3296/9304 [10:17<18:58,  5.28it/s]

2025-05-20 16:46:12,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:12,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:12,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3299/9304 [10:18<19:38,  5.10it/s]

2025-05-20 16:46:13,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:13,154 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3300/9304 [10:18<18:47,  5.32it/s]

2025-05-20 16:46:13,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 35%|███▌      | 3302/9304 [10:18<16:45,  5.97it/s]

2025-05-20 16:46:13,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:13,721 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3304/9304 [10:19<15:59,  6.25it/s]

2025-05-20 16:46:14,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:14,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3305/9304 [10:19<19:39,  5.08it/s]

2025-05-20 16:46:14,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:14,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3307/9304 [10:19<19:30,  5.12it/s]

2025-05-20 16:46:14,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:14,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3309/9304 [10:20<18:08,  5.51it/s]

2025-05-20 16:46:15,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3311/9304 [10:20<17:13,  5.80it/s]

2025-05-20 16:46:15,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3312/9304 [10:20<18:32,  5.39it/s]

2025-05-20 16:46:15,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3313/9304 [10:20<21:04,  4.74it/s]

2025-05-20 16:46:15,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:15,684 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:16,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3316/9304 [10:21<16:56,  5.89it/s]

2025-05-20 16:46:16,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3317/9304 [10:21<17:35,  5.67it/s]

2025-05-20 16:46:16,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:16,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3319/9304 [10:21<14:30,  6.87it/s]

2025-05-20 16:46:16,616 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:16,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3320/9304 [10:21<16:17,  6.12it/s]

2025-05-20 16:46:17,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:17,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3322/9304 [10:22<19:36,  5.08it/s]

2025-05-20 16:46:17,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:17,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3324/9304 [10:22<17:16,  5.77it/s]

2025-05-20 16:46:17,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3326/9304 [10:23<17:23,  5.73it/s]

2025-05-20 16:46:17,748 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:17,953 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3328/9304 [10:23<15:14,  6.54it/s]

2025-05-20 16:46:18,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:18,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3330/9304 [10:23<12:10,  8.18it/s]

2025-05-20 16:46:18,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:18,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3332/9304 [10:24<18:25,  5.40it/s]

2025-05-20 16:46:18,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:19,274 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3334/9304 [10:24<21:16,  4.68it/s]

2025-05-20 16:46:19,371 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3335/9304 [10:24<19:17,  5.16it/s]

2025-05-20 16:46:19,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:19,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3337/9304 [10:24<14:54,  6.67it/s]

2025-05-20 16:46:19,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:19,661 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3339/9304 [10:24<12:35,  7.90it/s]

2025-05-20 16:46:19,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:20,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:20,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3341/9304 [10:25<17:05,  5.82it/s]

2025-05-20 16:46:20,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3343/9304 [10:25<15:39,  6.34it/s]

2025-05-20 16:46:20,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3344/9304 [10:26<17:22,  5.72it/s]

2025-05-20 16:46:20,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:21,319 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:21,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3346/9304 [10:26<21:58,  4.52it/s]

2025-05-20 16:46:21,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:21,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3348/9304 [10:26<19:40,  5.04it/s]

2025-05-20 16:46:21,678 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:21,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:22,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3352/9304 [10:27<15:20,  6.46it/s]

2025-05-20 16:46:22,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3353/9304 [10:27<15:42,  6.31it/s]

2025-05-20 16:46:22,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:22,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3355/9304 [10:28<20:00,  4.95it/s]

2025-05-20 16:46:22,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:22,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3357/9304 [10:28<15:39,  6.33it/s]

2025-05-20 16:46:23,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:23,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3358/9304 [10:28<20:04,  4.93it/s]

2025-05-20 16:46:23,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:23,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:23,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3361/9304 [10:28<15:42,  6.30it/s]

2025-05-20 16:46:23,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:24,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3364/9304 [10:29<16:22,  6.05it/s]

2025-05-20 16:46:24,305 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3365/9304 [10:29<15:48,  6.26it/s]

2025-05-20 16:46:24,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:24,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3367/9304 [10:30<16:25,  6.03it/s]

2025-05-20 16:46:24,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:25,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3369/9304 [10:30<16:16,  6.08it/s]

2025-05-20 16:46:25,037 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:25,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:25,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▌      | 3372/9304 [10:30<16:30,  5.99it/s]

2025-05-20 16:46:25,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3373/9304 [10:31<19:03,  5.19it/s]

2025-05-20 16:46:25,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:25,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:26,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:26,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3376/9304 [10:31<14:56,  6.61it/s]

2025-05-20 16:46:26,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:26,433 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3378/9304 [10:31<15:01,  6.57it/s]

2025-05-20 16:46:26,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:26,637 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3380/9304 [10:31<13:38,  7.24it/s]

2025-05-20 16:46:27,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3382/9304 [10:32<15:25,  6.40it/s]

2025-05-20 16:46:27,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:27,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3383/9304 [10:32<21:27,  4.60it/s]

2025-05-20 16:46:27,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:27,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:27,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3386/9304 [10:33<16:38,  5.93it/s]

2025-05-20 16:46:27,974 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3388/9304 [10:33<13:30,  7.30it/s]

2025-05-20 16:46:28,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3389/9304 [10:33<17:47,  5.54it/s]

2025-05-20 16:46:28,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:28,575 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3391/9304 [10:33<15:16,  6.45it/s]

2025-05-20 16:46:28,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3392/9304 [10:34<17:10,  5.74it/s]

2025-05-20 16:46:28,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3393/9304 [10:34<16:41,  5.90it/s]

2025-05-20 16:46:29,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:29,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 36%|███▋      | 3394/9304 [10:34<22:17,  4.42it/s]

2025-05-20 16:46:29,418 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:29,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3397/9304 [10:34<14:28,  6.80it/s]

2025-05-20 16:46:29,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:29,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3398/9304 [10:35<15:33,  6.33it/s]

2025-05-20 16:46:30,007 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3400/9304 [10:35<13:32,  7.27it/s]

2025-05-20 16:46:30,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:30,417 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3402/9304 [10:35<15:46,  6.23it/s]

2025-05-20 16:46:30,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3403/9304 [10:36<18:35,  5.29it/s]

2025-05-20 16:46:30,836 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3404/9304 [10:36<16:58,  5.79it/s]

2025-05-20 16:46:30,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:31,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3406/9304 [10:36<16:26,  5.98it/s]

2025-05-20 16:46:31,441 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3407/9304 [10:36<18:56,  5.19it/s]

2025-05-20 16:46:31,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:31,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:31,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3410/9304 [10:37<16:16,  6.03it/s]

2025-05-20 16:46:31,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:32,359 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3412/9304 [10:37<19:04,  5.15it/s]

2025-05-20 16:46:32,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3413/9304 [10:37<21:11,  4.63it/s]

2025-05-20 16:46:33,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3414/9304 [10:38<24:59,  3.93it/s]

2025-05-20 16:46:33,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:33,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:33,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3416/9304 [10:38<19:06,  5.14it/s]

2025-05-20 16:46:33,422 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3418/9304 [10:38<15:17,  6.42it/s]

2025-05-20 16:46:33,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3419/9304 [10:38<15:21,  6.39it/s]

2025-05-20 16:46:33,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3420/9304 [10:39<18:24,  5.33it/s]

2025-05-20 16:46:34,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:34,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3421/9304 [10:39<28:14,  3.47it/s]

2025-05-20 16:46:34,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:34,565 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:34,644 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3425/9304 [10:39<14:00,  6.99it/s]

2025-05-20 16:46:34,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:34,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3427/9304 [10:40<12:53,  7.60it/s]

2025-05-20 16:46:34,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:35,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3429/9304 [10:40<12:58,  7.55it/s]

2025-05-20 16:46:35,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3430/9304 [10:40<14:37,  6.69it/s]

2025-05-20 16:46:36,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3431/9304 [10:41<25:42,  3.81it/s]

2025-05-20 16:46:36,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:36,118 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:36,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3434/9304 [10:41<16:24,  5.96it/s]

2025-05-20 16:46:36,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:36,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:36,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3437/9304 [10:41<14:28,  6.75it/s]

2025-05-20 16:46:36,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:37,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3439/9304 [10:42<17:56,  5.45it/s]

2025-05-20 16:46:37,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3440/9304 [10:42<18:07,  5.39it/s]

2025-05-20 16:46:37,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3441/9304 [10:42<17:30,  5.58it/s]

2025-05-20 16:46:37,678 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3442/9304 [10:42<17:32,  5.57it/s]

2025-05-20 16:46:37,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3443/9304 [10:43<19:57,  4.89it/s]

2025-05-20 16:46:37,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:38,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:38,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3446/9304 [10:43<13:48,  7.07it/s]

2025-05-20 16:46:38,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3447/9304 [10:43<14:49,  6.59it/s]

2025-05-20 16:46:38,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:38,709 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3448/9304 [10:44<18:36,  5.24it/s]

2025-05-20 16:46:38,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:38,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3451/9304 [10:44<11:52,  8.21it/s]

2025-05-20 16:46:39,417 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:39,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3453/9304 [10:45<22:57,  4.25it/s]

2025-05-20 16:46:39,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:39,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3455/9304 [10:45<17:45,  5.49it/s]

2025-05-20 16:46:40,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:40,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:40,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3457/9304 [10:45<19:44,  4.94it/s]

2025-05-20 16:46:40,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:41,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3460/9304 [10:46<19:49,  4.91it/s]

2025-05-20 16:46:41,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3461/9304 [10:46<21:26,  4.54it/s]

2025-05-20 16:46:41,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3462/9304 [10:46<21:08,  4.61it/s]

2025-05-20 16:46:41,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:41,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3464/9304 [10:47<16:52,  5.77it/s]

2025-05-20 16:46:41,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3465/9304 [10:47<15:45,  6.18it/s]

2025-05-20 16:46:41,976 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3466/9304 [10:47<14:27,  6.73it/s]

2025-05-20 16:46:42,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3467/9304 [10:47<18:24,  5.28it/s]

2025-05-20 16:46:42,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3468/9304 [10:47<20:06,  4.84it/s]

2025-05-20 16:46:42,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3469/9304 [10:48<19:52,  4.89it/s]

2025-05-20 16:46:42,976 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3470/9304 [10:48<20:16,  4.80it/s]

2025-05-20 16:46:43,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3471/9304 [10:48<21:23,  4.55it/s]

2025-05-20 16:46:43,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3472/9304 [10:48<21:05,  4.61it/s]

2025-05-20 16:46:43,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:43,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3474/9304 [10:49<18:16,  5.32it/s]

2025-05-20 16:46:43,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:43,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:43,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3477/9304 [10:49<11:37,  8.36it/s]

2025-05-20 16:46:44,441 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3478/9304 [10:49<19:36,  4.95it/s]

2025-05-20 16:46:44,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3479/9304 [10:50<22:18,  4.35it/s]

2025-05-20 16:46:44,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3480/9304 [10:50<21:37,  4.49it/s]

2025-05-20 16:46:45,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3481/9304 [10:50<19:28,  4.98it/s]

2025-05-20 16:46:45,126 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:45,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3483/9304 [10:50<15:30,  6.26it/s]

2025-05-20 16:46:45,324 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:45,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3485/9304 [10:50<12:16,  7.91it/s]

2025-05-20 16:46:45,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3486/9304 [10:51<16:40,  5.81it/s]

2025-05-20 16:46:46,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:46,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 37%|███▋      | 3487/9304 [10:51<20:52,  4.65it/s]

2025-05-20 16:46:46,836 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:46,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3489/9304 [10:52<25:40,  3.77it/s]

2025-05-20 16:46:47,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3491/9304 [10:52<19:46,  4.90it/s]

2025-05-20 16:46:47,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:47,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:47,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3493/9304 [10:52<18:19,  5.29it/s]

2025-05-20 16:46:47,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:47,797 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3495/9304 [10:53<19:44,  4.90it/s]

2025-05-20 16:46:48,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:48,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3497/9304 [10:53<22:06,  4.38it/s]

2025-05-20 16:46:48,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3499/9304 [10:53<18:21,  5.27it/s]

2025-05-20 16:46:48,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:48,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3501/9304 [10:54<15:04,  6.42it/s]

2025-05-20 16:46:48,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:49,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3503/9304 [10:54<19:21,  5.00it/s]

2025-05-20 16:46:49,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:49,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3505/9304 [10:54<18:12,  5.31it/s]

2025-05-20 16:46:49,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:49,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3507/9304 [10:55<16:29,  5.86it/s]

2025-05-20 16:46:50,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3508/9304 [10:55<18:42,  5.17it/s]

2025-05-20 16:46:50,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:50,292 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:50,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3511/9304 [10:55<14:02,  6.88it/s]

2025-05-20 16:46:50,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3512/9304 [10:56<19:32,  4.94it/s]

2025-05-20 16:46:51,050 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:51,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3514/9304 [10:56<16:43,  5.77it/s]

2025-05-20 16:46:51,568 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:51,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3515/9304 [10:56<20:38,  4.68it/s]

2025-05-20 16:46:51,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:51,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3518/9304 [10:57<14:34,  6.62it/s]

2025-05-20 16:46:51,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:52,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:52,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:52,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3520/9304 [10:57<21:53,  4.40it/s]

2025-05-20 16:46:52,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:52,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3524/9304 [10:58<15:31,  6.20it/s]

2025-05-20 16:46:53,412 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3525/9304 [10:58<19:43,  4.89it/s]

2025-05-20 16:46:53,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:53,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3526/9304 [10:58<19:55,  4.83it/s]

2025-05-20 16:46:53,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:53,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3528/9304 [10:59<16:39,  5.78it/s]

2025-05-20 16:46:53,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:54,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:54,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3531/9304 [10:59<15:15,  6.30it/s]

2025-05-20 16:46:54,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:54,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3534/9304 [10:59<14:27,  6.65it/s]

2025-05-20 16:46:55,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3535/9304 [11:00<18:12,  5.28it/s]

2025-05-20 16:46:55,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:55,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3537/9304 [11:00<15:33,  6.17it/s]

2025-05-20 16:46:55,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3538/9304 [11:00<14:40,  6.55it/s]

2025-05-20 16:46:55,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:55,789 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3539/9304 [11:01<19:46,  4.86it/s]

2025-05-20 16:46:55,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:55,987 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3542/9304 [11:01<13:33,  7.08it/s]

2025-05-20 16:46:56,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3543/9304 [11:01<16:24,  5.85it/s]

2025-05-20 16:46:56,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3544/9304 [11:01<19:09,  5.01it/s]

2025-05-20 16:46:56,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3545/9304 [11:02<22:22,  4.29it/s]

2025-05-20 16:46:57,080 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3546/9304 [11:02<19:58,  4.80it/s]

2025-05-20 16:46:57,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3547/9304 [11:02<17:35,  5.45it/s]

2025-05-20 16:46:57,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:57,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:57,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3550/9304 [11:02<10:51,  8.83it/s]

2025-05-20 16:46:57,361 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:57,721 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3552/9304 [11:03<13:15,  7.23it/s]

2025-05-20 16:46:57,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3553/9304 [11:03<14:40,  6.53it/s]

2025-05-20 16:46:58,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3554/9304 [11:03<23:51,  4.02it/s]

2025-05-20 16:46:58,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:58,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3556/9304 [11:03<16:45,  5.72it/s]

2025-05-20 16:46:58,676 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:58,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3558/9304 [11:04<13:39,  7.01it/s]

2025-05-20 16:46:59,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:46:59,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3560/9304 [11:04<17:53,  5.35it/s]

2025-05-20 16:46:59,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3561/9304 [11:04<18:09,  5.27it/s]

2025-05-20 16:46:59,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3562/9304 [11:05<18:19,  5.22it/s]

2025-05-20 16:47:00,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:00,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3563/9304 [11:05<21:44,  4.40it/s]

2025-05-20 16:47:00,150 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:00,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:00,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3567/9304 [11:05<12:55,  7.40it/s]

2025-05-20 16:47:00,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3568/9304 [11:05<13:13,  7.23it/s]

2025-05-20 16:47:00,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:00,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:01,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3571/9304 [11:06<16:39,  5.74it/s]

2025-05-20 16:47:01,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3572/9304 [11:06<17:12,  5.55it/s]

2025-05-20 16:47:01,714 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3573/9304 [11:07<19:48,  4.82it/s]

2025-05-20 16:47:01,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:01,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3575/9304 [11:07<14:52,  6.42it/s]

2025-05-20 16:47:01,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:01,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3577/9304 [11:07<11:42,  8.15it/s]

2025-05-20 16:47:02,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:02,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3579/9304 [11:07<09:47,  9.75it/s]

2025-05-20 16:47:02,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:02,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3581/9304 [11:08<20:28,  4.66it/s]

2025-05-20 16:47:03,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:03,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 38%|███▊      | 3582/9304 [11:08<22:52,  4.17it/s]

2025-05-20 16:47:03,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:03,431 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:03,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3586/9304 [11:08<12:52,  7.41it/s]

2025-05-20 16:47:03,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:03,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3588/9304 [11:09<12:33,  7.59it/s]

2025-05-20 16:47:03,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:03,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3590/9304 [11:09<11:06,  8.57it/s]

2025-05-20 16:47:04,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:04,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:04,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3592/9304 [11:10<20:14,  4.70it/s]

2025-05-20 16:47:05,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:05,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3594/9304 [11:10<18:17,  5.20it/s]

2025-05-20 16:47:05,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:05,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3597/9304 [11:10<13:45,  6.92it/s]

2025-05-20 16:47:05,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:05,608 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3599/9304 [11:10<14:05,  6.74it/s]

2025-05-20 16:47:06,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3600/9304 [11:11<18:00,  5.28it/s]

2025-05-20 16:47:06,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3601/9304 [11:11<16:52,  5.63it/s]

2025-05-20 16:47:06,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:06,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3603/9304 [11:11<19:01,  5.00it/s]

2025-05-20 16:47:06,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3604/9304 [11:12<17:22,  5.47it/s]

2025-05-20 16:47:06,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▊      | 3605/9304 [11:12<17:21,  5.47it/s]

2025-05-20 16:47:07,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:07,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3606/9304 [11:12<22:30,  4.22it/s]

2025-05-20 16:47:07,638 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3608/9304 [11:12<19:20,  4.91it/s]

2025-05-20 16:47:07,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3609/9304 [11:13<17:22,  5.46it/s]

2025-05-20 16:47:07,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:07,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:07,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3611/9304 [11:13<14:05,  6.74it/s]

2025-05-20 16:47:08,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3613/9304 [11:13<11:16,  8.41it/s]

2025-05-20 16:47:08,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:09,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3615/9304 [11:14<25:01,  3.79it/s]

2025-05-20 16:47:09,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:09,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3617/9304 [11:14<18:38,  5.08it/s]

2025-05-20 16:47:09,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:09,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:09,576 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:09,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3620/9304 [11:14<14:49,  6.39it/s]

2025-05-20 16:47:09,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:09,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3623/9304 [11:15<14:05,  6.72it/s]

2025-05-20 16:47:10,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3624/9304 [11:15<19:54,  4.75it/s]

2025-05-20 16:47:10,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:10,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3626/9304 [11:16<19:05,  4.96it/s]

2025-05-20 16:47:10,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:11,081 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:11,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3628/9304 [11:16<16:10,  5.85it/s]

2025-05-20 16:47:11,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:11,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3631/9304 [11:16<14:57,  6.32it/s]

2025-05-20 16:47:11,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:11,931 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3633/9304 [11:17<16:11,  5.84it/s]

2025-05-20 16:47:12,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:12,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3634/9304 [11:17<21:24,  4.41it/s]

2025-05-20 16:47:12,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:12,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3636/9304 [11:18<18:55,  4.99it/s]

2025-05-20 16:47:12,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3638/9304 [11:18<14:56,  6.32it/s]

2025-05-20 16:47:12,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:12,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3640/9304 [11:18<12:10,  7.75it/s]

2025-05-20 16:47:13,146 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:13,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:13,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3642/9304 [11:18<17:52,  5.28it/s]

2025-05-20 16:47:13,836 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3644/9304 [11:19<15:15,  6.18it/s]

2025-05-20 16:47:14,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3645/9304 [11:19<21:09,  4.46it/s]

2025-05-20 16:47:14,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3646/9304 [11:19<20:44,  4.54it/s]

2025-05-20 16:47:14,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3647/9304 [11:20<20:28,  4.61it/s]

2025-05-20 16:47:14,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:14,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3649/9304 [11:20<16:31,  5.71it/s]

2025-05-20 16:47:15,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:15,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:15,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3650/9304 [11:20<19:03,  4.94it/s]

2025-05-20 16:47:15,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:15,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:15,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3654/9304 [11:21<16:29,  5.71it/s]

2025-05-20 16:47:15,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:16,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3657/9304 [11:21<18:43,  5.03it/s]

2025-05-20 16:47:16,676 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:16,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3659/9304 [11:22<15:33,  6.04it/s]

2025-05-20 16:47:16,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:16,808 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:17,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3662/9304 [11:22<12:57,  7.26it/s]

2025-05-20 16:47:17,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:17,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3663/9304 [11:22<15:16,  6.15it/s]

2025-05-20 16:47:17,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3665/9304 [11:22<15:01,  6.25it/s]

2025-05-20 16:47:17,940 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:17,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3666/9304 [11:23<17:27,  5.38it/s]

2025-05-20 16:47:18,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3668/9304 [11:23<16:26,  5.71it/s]

2025-05-20 16:47:18,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3669/9304 [11:23<15:05,  6.22it/s]

2025-05-20 16:47:18,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3670/9304 [11:24<21:28,  4.37it/s]

2025-05-20 16:47:18,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:18,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3672/9304 [11:24<15:10,  6.19it/s]

2025-05-20 16:47:18,940 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:18,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:19,378 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:19,379 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 39%|███▉      | 3675/9304 [11:24<14:38,  6.41it/s]

2025-05-20 16:47:19,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3677/9304 [11:25<15:53,  5.90it/s]

2025-05-20 16:47:20,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:20,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3678/9304 [11:25<21:39,  4.33it/s]

2025-05-20 16:47:20,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:20,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:20,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3682/9304 [11:25<14:20,  6.54it/s]

2025-05-20 16:47:20,766 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3683/9304 [11:26<14:30,  6.46it/s]

2025-05-20 16:47:21,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:21,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3684/9304 [11:26<17:44,  5.28it/s]

2025-05-20 16:47:21,118 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:21,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3687/9304 [11:26<16:08,  5.80it/s]

2025-05-20 16:47:21,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3688/9304 [11:27<17:23,  5.38it/s]

2025-05-20 16:47:21,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3689/9304 [11:27<16:32,  5.66it/s]

2025-05-20 16:47:22,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3690/9304 [11:27<15:26,  6.06it/s]

2025-05-20 16:47:22,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:22,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3692/9304 [11:27<12:15,  7.63it/s]

2025-05-20 16:47:22,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:22,621 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3694/9304 [11:27<14:23,  6.49it/s]

2025-05-20 16:47:22,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3695/9304 [11:28<15:48,  5.91it/s]

2025-05-20 16:47:23,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3696/9304 [11:28<18:41,  5.00it/s]

2025-05-20 16:47:23,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:23,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3698/9304 [11:28<15:07,  6.18it/s]

2025-05-20 16:47:23,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3699/9304 [11:28<16:00,  5.84it/s]

2025-05-20 16:47:23,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3700/9304 [11:29<14:59,  6.23it/s]

2025-05-20 16:47:23,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:24,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3702/9304 [11:29<18:06,  5.15it/s]

2025-05-20 16:47:24,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:24,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3704/9304 [11:29<14:32,  6.42it/s]

2025-05-20 16:47:24,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3705/9304 [11:30<17:56,  5.20it/s]

2025-05-20 16:47:25,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:25,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3706/9304 [11:30<20:24,  4.57it/s]

2025-05-20 16:47:25,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:25,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:25,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3710/9304 [11:30<14:13,  6.56it/s]

2025-05-20 16:47:25,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:25,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:25,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:25,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3712/9304 [11:31<17:03,  5.46it/s]

2025-05-20 16:47:26,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3715/9304 [11:31<17:44,  5.25it/s]

2025-05-20 16:47:26,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:26,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3717/9304 [11:31<14:25,  6.46it/s]

2025-05-20 16:47:26,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:26,945 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3719/9304 [11:32<14:17,  6.51it/s]

2025-05-20 16:47:27,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:27,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|███▉      | 3721/9304 [11:32<15:37,  5.96it/s]

2025-05-20 16:47:27,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:27,474 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3723/9304 [11:32<12:42,  7.32it/s]

2025-05-20 16:47:27,661 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:28,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3725/9304 [11:33<17:04,  5.44it/s]

2025-05-20 16:47:28,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:28,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3726/9304 [11:33<20:42,  4.49it/s]

2025-05-20 16:47:28,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:28,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3729/9304 [11:33<13:31,  6.87it/s]

2025-05-20 16:47:28,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:28,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3731/9304 [11:34<14:11,  6.55it/s]

2025-05-20 16:47:29,215 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:29,259 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3733/9304 [11:34<14:17,  6.50it/s]

2025-05-20 16:47:29,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3734/9304 [11:34<17:35,  5.28it/s]

2025-05-20 16:47:29,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3735/9304 [11:35<19:23,  4.79it/s]

2025-05-20 16:47:30,116 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:30,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3736/9304 [11:35<19:28,  4.76it/s]

2025-05-20 16:47:30,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:30,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:30,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3740/9304 [11:35<10:43,  8.65it/s]

2025-05-20 16:47:30,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:30,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3742/9304 [11:36<14:12,  6.52it/s]

2025-05-20 16:47:30,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3743/9304 [11:36<13:34,  6.83it/s]

2025-05-20 16:47:31,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3744/9304 [11:36<17:16,  5.37it/s]

2025-05-20 16:47:31,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:31,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3745/9304 [11:36<21:44,  4.26it/s]

2025-05-20 16:47:31,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:31,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3748/9304 [11:37<14:34,  6.35it/s]

2025-05-20 16:47:32,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3749/9304 [11:37<16:27,  5.63it/s]

2025-05-20 16:47:32,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:32,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3751/9304 [11:37<17:40,  5.24it/s]

2025-05-20 16:47:32,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3752/9304 [11:38<19:43,  4.69it/s]

2025-05-20 16:47:33,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3753/9304 [11:38<21:56,  4.22it/s]

2025-05-20 16:47:33,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3754/9304 [11:38<19:00,  4.87it/s]

2025-05-20 16:47:33,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:33,579 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3756/9304 [11:38<16:33,  5.59it/s]

2025-05-20 16:47:33,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3757/9304 [11:39<15:19,  6.03it/s]

2025-05-20 16:47:33,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:33,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3759/9304 [11:39<12:22,  7.47it/s]

2025-05-20 16:47:34,412 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3760/9304 [11:39<20:35,  4.49it/s]

2025-05-20 16:47:34,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:34,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3762/9304 [11:40<18:06,  5.10it/s]

2025-05-20 16:47:35,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3763/9304 [11:40<22:41,  4.07it/s]

2025-05-20 16:47:35,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:35,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3765/9304 [11:40<16:15,  5.68it/s]

2025-05-20 16:47:35,291 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:35,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 40%|████      | 3767/9304 [11:40<16:32,  5.58it/s]

2025-05-20 16:47:35,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:35,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3769/9304 [11:41<16:24,  5.62it/s]

2025-05-20 16:47:36,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3770/9304 [11:41<15:42,  5.87it/s]

2025-05-20 16:47:36,179 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:36,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3772/9304 [11:42<20:22,  4.52it/s]

2025-05-20 16:47:36,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:36,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:36,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3775/9304 [11:42<13:06,  7.03it/s]

2025-05-20 16:47:36,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:37,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3777/9304 [11:42<16:07,  5.71it/s]

2025-05-20 16:47:37,433 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:37,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3779/9304 [11:42<13:29,  6.83it/s]

2025-05-20 16:47:37,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:38,614 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:38,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3781/9304 [11:43<24:10,  3.81it/s]

2025-05-20 16:47:38,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3783/9304 [11:44<18:46,  4.90it/s]

2025-05-20 16:47:38,798 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:38,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3785/9304 [11:44<15:11,  6.06it/s]

2025-05-20 16:47:39,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:39,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3787/9304 [11:44<13:56,  6.60it/s]

2025-05-20 16:47:39,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:39,536 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3789/9304 [11:44<15:16,  6.02it/s]

2025-05-20 16:47:40,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3790/9304 [11:45<21:13,  4.33it/s]

2025-05-20 16:47:40,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:40,465 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:40,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3792/9304 [11:45<20:11,  4.55it/s]

2025-05-20 16:47:40,502 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:40,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:40,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3796/9304 [11:45<12:16,  7.48it/s]

2025-05-20 16:47:41,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:41,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3798/9304 [11:46<17:41,  5.19it/s]

2025-05-20 16:47:41,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3799/9304 [11:46<16:24,  5.59it/s]

2025-05-20 16:47:41,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3800/9304 [11:47<20:59,  4.37it/s]

2025-05-20 16:47:42,016 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:42,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3802/9304 [11:47<15:56,  5.75it/s]

2025-05-20 16:47:42,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3803/9304 [11:47<21:12,  4.32it/s]

2025-05-20 16:47:42,614 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:42,644 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3805/9304 [11:47<15:34,  5.88it/s]

2025-05-20 16:47:42,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3806/9304 [11:48<17:34,  5.21it/s]

2025-05-20 16:47:43,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3807/9304 [11:48<15:49,  5.79it/s]

2025-05-20 16:47:43,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3808/9304 [11:48<16:21,  5.60it/s]

2025-05-20 16:47:43,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:43,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3810/9304 [11:48<15:29,  5.91it/s]

2025-05-20 16:47:43,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3811/9304 [11:49<16:10,  5.66it/s]

2025-05-20 16:47:44,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3812/9304 [11:49<19:45,  4.63it/s]

2025-05-20 16:47:44,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3813/9304 [11:49<17:03,  5.37it/s]

2025-05-20 16:47:44,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:44,763 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3815/9304 [11:50<21:12,  4.31it/s]

2025-05-20 16:47:44,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:44,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3817/9304 [11:50<16:21,  5.59it/s]

2025-05-20 16:47:45,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3818/9304 [11:50<17:44,  5.16it/s]

2025-05-20 16:47:45,254 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:45,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:45,906 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3821/9304 [11:51<19:36,  4.66it/s]

2025-05-20 16:47:46,095 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3822/9304 [11:51<19:08,  4.77it/s]

2025-05-20 16:47:46,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3823/9304 [11:51<21:01,  4.34it/s]

2025-05-20 16:47:46,417 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:46,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:46,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3826/9304 [11:52<17:05,  5.34it/s]

2025-05-20 16:47:46,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:46,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:47,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3829/9304 [11:53<21:28,  4.25it/s]

2025-05-20 16:47:47,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3830/9304 [11:53<19:37,  4.65it/s]

2025-05-20 16:47:47,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:47,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:47,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3833/9304 [11:53<13:18,  6.85it/s]

2025-05-20 16:47:48,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:48,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:48,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████      | 3835/9304 [11:53<14:29,  6.29it/s]

2025-05-20 16:47:48,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:48,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3838/9304 [11:54<15:02,  6.05it/s]

2025-05-20 16:47:49,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3839/9304 [11:54<19:31,  4.66it/s]

2025-05-20 16:47:49,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3840/9304 [11:55<21:25,  4.25it/s]

2025-05-20 16:47:49,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:49,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:49,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3841/9304 [11:55<20:33,  4.43it/s]

2025-05-20 16:47:49,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:50,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3845/9304 [11:55<11:17,  8.06it/s]

2025-05-20 16:47:50,116 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:50,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:51,013 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3848/9304 [11:56<17:48,  5.11it/s]

2025-05-20 16:47:51,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:51,259 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3850/9304 [11:56<16:03,  5.66it/s]

2025-05-20 16:47:51,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3851/9304 [11:56<15:23,  5.90it/s]

2025-05-20 16:47:51,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3852/9304 [11:56<14:17,  6.36it/s]

2025-05-20 16:47:51,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:51,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3854/9304 [11:56<11:58,  7.58it/s]

2025-05-20 16:47:51,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:52,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3856/9304 [11:57<20:19,  4.47it/s]

2025-05-20 16:47:52,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:52,678 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3858/9304 [11:58<16:39,  5.45it/s]

2025-05-20 16:47:52,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:53,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 41%|████▏     | 3860/9304 [11:58<16:18,  5.57it/s]

2025-05-20 16:47:53,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:53,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3862/9304 [11:58<12:46,  7.10it/s]

2025-05-20 16:47:53,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:53,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3864/9304 [11:58<12:59,  6.98it/s]

2025-05-20 16:47:53,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:53,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3866/9304 [11:59<15:52,  5.71it/s]

2025-05-20 16:47:54,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3867/9304 [11:59<19:46,  4.58it/s]

2025-05-20 16:47:54,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:54,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3869/9304 [11:59<15:25,  5.87it/s]

2025-05-20 16:47:55,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3870/9304 [12:00<22:24,  4.04it/s]

2025-05-20 16:47:55,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3871/9304 [12:00<23:47,  3.81it/s]

2025-05-20 16:47:55,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3872/9304 [12:00<22:19,  4.06it/s]

2025-05-20 16:47:55,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:55,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3874/9304 [12:00<15:08,  5.98it/s]

2025-05-20 16:47:55,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:55,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3876/9304 [12:01<13:02,  6.94it/s]

2025-05-20 16:47:56,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3877/9304 [12:01<14:12,  6.36it/s]

2025-05-20 16:47:56,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3878/9304 [12:01<13:19,  6.78it/s]

2025-05-20 16:47:56,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3879/9304 [12:01<14:21,  6.30it/s]

2025-05-20 16:47:56,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3880/9304 [12:02<20:22,  4.44it/s]

2025-05-20 16:47:57,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:57,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3881/9304 [12:02<24:58,  3.62it/s]

2025-05-20 16:47:57,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:57,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3884/9304 [12:03<19:53,  4.54it/s]

2025-05-20 16:47:57,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:57,839 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3886/9304 [12:03<14:42,  6.14it/s]

2025-05-20 16:47:58,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3887/9304 [12:03<17:09,  5.26it/s]

2025-05-20 16:47:58,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3888/9304 [12:03<19:29,  4.63it/s]

2025-05-20 16:47:58,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:58,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3889/9304 [12:04<23:57,  3.77it/s]

2025-05-20 16:47:58,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:59,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3892/9304 [12:04<16:25,  5.49it/s]

2025-05-20 16:47:59,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:59,487 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3893/9304 [12:04<18:37,  4.84it/s]

2025-05-20 16:47:59,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:59,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3896/9304 [12:04<12:10,  7.41it/s]

2025-05-20 16:47:59,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:47:59,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3898/9304 [12:05<11:41,  7.70it/s]

2025-05-20 16:48:00,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3899/9304 [12:05<18:00,  5.00it/s]

2025-05-20 16:48:00,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:00,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3900/9304 [12:06<21:58,  4.10it/s]

2025-05-20 16:48:00,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3902/9304 [12:06<15:50,  5.68it/s]

2025-05-20 16:48:01,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:01,425 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3903/9304 [12:06<21:52,  4.12it/s]

2025-05-20 16:48:01,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:01,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:01,495 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:01,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:01,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3909/9304 [12:07<13:01,  6.91it/s]

2025-05-20 16:48:02,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3910/9304 [12:07<16:56,  5.30it/s]

2025-05-20 16:48:02,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3911/9304 [12:07<15:58,  5.63it/s]

2025-05-20 16:48:02,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3912/9304 [12:08<17:57,  5.00it/s]

2025-05-20 16:48:02,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:03,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:03,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3914/9304 [12:08<16:30,  5.44it/s]

2025-05-20 16:48:03,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3916/9304 [12:08<12:55,  6.95it/s]

2025-05-20 16:48:03,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3917/9304 [12:08<15:19,  5.86it/s]

2025-05-20 16:48:03,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:03,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3919/9304 [12:09<11:42,  7.67it/s]

2025-05-20 16:48:03,763 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:03,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3921/9304 [12:09<11:43,  7.65it/s]

2025-05-20 16:48:04,492 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3922/9304 [12:09<18:49,  4.77it/s]

2025-05-20 16:48:04,709 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3923/9304 [12:10<19:05,  4.70it/s]

2025-05-20 16:48:04,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3924/9304 [12:10<18:15,  4.91it/s]

2025-05-20 16:48:04,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:05,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3926/9304 [12:10<16:49,  5.33it/s]

2025-05-20 16:48:05,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:05,244 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:05,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:05,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3929/9304 [12:11<16:05,  5.56it/s]

2025-05-20 16:48:05,908 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3931/9304 [12:11<13:38,  6.56it/s]

2025-05-20 16:48:06,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3932/9304 [12:11<16:23,  5.46it/s]

2025-05-20 16:48:06,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:06,542 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3934/9304 [12:11<15:32,  5.76it/s]

2025-05-20 16:48:06,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3935/9304 [12:12<16:04,  5.57it/s]

2025-05-20 16:48:06,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3936/9304 [12:12<14:45,  6.06it/s]

2025-05-20 16:48:06,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:06,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:07,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3939/9304 [12:12<18:08,  4.93it/s]

2025-05-20 16:48:07,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:07,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3941/9304 [12:13<14:06,  6.33it/s]

2025-05-20 16:48:07,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3942/9304 [12:13<14:12,  6.29it/s]

2025-05-20 16:48:07,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:08,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:08,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3944/9304 [12:13<15:38,  5.71it/s]

2025-05-20 16:48:08,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:08,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3946/9304 [12:13<15:14,  5.86it/s]

2025-05-20 16:48:08,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:09,097 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3949/9304 [12:14<14:57,  5.96it/s]

2025-05-20 16:48:09,415 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3950/9304 [12:14<17:09,  5.20it/s]

2025-05-20 16:48:09,454 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:09,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3952/9304 [12:15<17:20,  5.14it/s]

2025-05-20 16:48:09,821 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:10,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 42%|████▏     | 3954/9304 [12:15<16:20,  5.46it/s]

2025-05-20 16:48:10,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:10,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:10,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3957/9304 [12:15<10:58,  8.12it/s]

2025-05-20 16:48:10,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:10,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3959/9304 [12:16<15:18,  5.82it/s]

2025-05-20 16:48:10,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:11,422 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3961/9304 [12:16<18:27,  4.82it/s]

2025-05-20 16:48:11,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:11,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:11,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3964/9304 [12:17<15:06,  5.89it/s]

2025-05-20 16:48:11,992 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3965/9304 [12:17<16:08,  5.51it/s]

2025-05-20 16:48:12,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:12,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3967/9304 [12:17<13:12,  6.74it/s]

2025-05-20 16:48:12,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:12,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3968/9304 [12:17<14:23,  6.18it/s]

2025-05-20 16:48:12,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3970/9304 [12:17<12:11,  7.30it/s]

2025-05-20 16:48:12,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3971/9304 [12:18<17:30,  5.08it/s]

2025-05-20 16:48:13,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:13,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3973/9304 [12:18<17:29,  5.08it/s]

2025-05-20 16:48:13,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3974/9304 [12:18<16:54,  5.26it/s]

2025-05-20 16:48:13,630 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:13,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3976/9304 [12:19<13:30,  6.57it/s]

2025-05-20 16:48:13,825 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3977/9304 [12:19<14:34,  6.09it/s]

2025-05-20 16:48:13,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:13,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:14,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3980/9304 [12:19<13:01,  6.81it/s]

2025-05-20 16:48:14,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3981/9304 [12:19<13:10,  6.73it/s]

2025-05-20 16:48:15,016 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3982/9304 [12:20<20:37,  4.30it/s]

2025-05-20 16:48:15,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:15,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:15,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:15,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3985/9304 [12:20<16:46,  5.29it/s]

2025-05-20 16:48:15,474 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:15,785 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3988/9304 [12:21<14:30,  6.11it/s]

2025-05-20 16:48:15,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3989/9304 [12:21<13:46,  6.43it/s]

2025-05-20 16:48:16,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:16,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:16,654 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3991/9304 [12:21<19:32,  4.53it/s]

2025-05-20 16:48:16,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3993/9304 [12:22<15:04,  5.87it/s]

2025-05-20 16:48:17,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3994/9304 [12:22<16:58,  5.21it/s]

2025-05-20 16:48:17,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3995/9304 [12:22<17:28,  5.06it/s]

2025-05-20 16:48:17,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:17,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:17,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3998/9304 [12:22<13:21,  6.62it/s]

2025-05-20 16:48:18,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 3999/9304 [12:24<29:02,  3.04it/s]

2025-05-20 16:48:18,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:18,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4001/9304 [12:24<20:47,  4.25it/s]

2025-05-20 16:48:18,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:18,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4003/9304 [12:24<15:39,  5.64it/s]

2025-05-20 16:48:19,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:19,249 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4005/9304 [12:24<15:12,  5.81it/s]

2025-05-20 16:48:19,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:19,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4006/9304 [12:24<19:09,  4.61it/s]

2025-05-20 16:48:19,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4008/9304 [12:25<16:33,  5.33it/s]

2025-05-20 16:48:20,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4009/9304 [12:25<15:01,  5.87it/s]

2025-05-20 16:48:20,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4010/9304 [12:25<17:40,  4.99it/s]

2025-05-20 16:48:20,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4011/9304 [12:25<19:44,  4.47it/s]

2025-05-20 16:48:20,713 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:20,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4013/9304 [12:26<14:47,  5.96it/s]

2025-05-20 16:48:21,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4014/9304 [12:26<18:07,  4.86it/s]

2025-05-20 16:48:21,152 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:21,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:21,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4017/9304 [12:26<11:36,  7.59it/s]

2025-05-20 16:48:21,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:21,813 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4019/9304 [12:27<15:01,  5.86it/s]

2025-05-20 16:48:21,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:22,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4021/9304 [12:27<15:27,  5.70it/s]

2025-05-20 16:48:22,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4022/9304 [12:27<14:27,  6.09it/s]

2025-05-20 16:48:22,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4023/9304 [12:27<16:33,  5.32it/s]

2025-05-20 16:48:22,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4024/9304 [12:28<14:56,  5.89it/s]

2025-05-20 16:48:23,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:23,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4025/9304 [12:28<24:20,  3.61it/s]

2025-05-20 16:48:23,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4027/9304 [12:28<17:57,  4.90it/s]

2025-05-20 16:48:23,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:23,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:23,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:24,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4031/9304 [12:29<15:41,  5.60it/s]

2025-05-20 16:48:24,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:24,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4033/9304 [12:29<16:13,  5.41it/s]

2025-05-20 16:48:24,654 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4034/9304 [12:29<15:25,  5.70it/s]

2025-05-20 16:48:24,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:24,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4035/9304 [12:30<16:49,  5.22it/s]

2025-05-20 16:48:24,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:25,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4038/9304 [12:30<10:46,  8.14it/s]

2025-05-20 16:48:25,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:25,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4040/9304 [12:30<12:25,  7.06it/s]

2025-05-20 16:48:25,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4041/9304 [12:31<16:46,  5.23it/s]

2025-05-20 16:48:25,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4042/9304 [12:31<15:10,  5.78it/s]

2025-05-20 16:48:26,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 43%|████▎     | 4043/9304 [12:31<23:43,  3.70it/s]

2025-05-20 16:48:26,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:26,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:26,567 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:26,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:26,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:26,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4049/9304 [12:32<12:23,  7.07it/s]

2025-05-20 16:48:27,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:27,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4051/9304 [12:32<16:34,  5.28it/s]

2025-05-20 16:48:27,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4052/9304 [12:33<17:09,  5.10it/s]

2025-05-20 16:48:28,097 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4053/9304 [12:33<17:11,  5.09it/s]

2025-05-20 16:48:28,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:28,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:28,378 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4056/9304 [12:33<13:29,  6.48it/s]

2025-05-20 16:48:28,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:28,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4058/9304 [12:33<11:22,  7.69it/s]

2025-05-20 16:48:28,686 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4059/9304 [12:34<11:46,  7.43it/s]

2025-05-20 16:48:28,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4060/9304 [12:34<14:09,  6.17it/s]

2025-05-20 16:48:29,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:29,608 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4061/9304 [12:34<23:26,  3.73it/s]

2025-05-20 16:48:29,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:29,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:29,915 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4064/9304 [12:35<16:26,  5.31it/s]

2025-05-20 16:48:29,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:29,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:30,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4068/9304 [12:35<13:54,  6.28it/s]

2025-05-20 16:48:30,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:30,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▎     | 4070/9304 [12:36<16:02,  5.44it/s]

2025-05-20 16:48:31,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4071/9304 [12:36<16:52,  5.17it/s]

2025-05-20 16:48:31,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:31,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:31,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4073/9304 [12:36<15:16,  5.71it/s]

2025-05-20 16:48:31,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:31,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4076/9304 [12:37<13:03,  6.67it/s]

2025-05-20 16:48:31,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:31,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4078/9304 [12:37<11:37,  7.49it/s]

2025-05-20 16:48:32,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4079/9304 [12:37<13:06,  6.64it/s]

2025-05-20 16:48:32,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:32,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4080/9304 [12:38<20:11,  4.31it/s]

2025-05-20 16:48:32,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:32,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:33,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4084/9304 [12:38<14:21,  6.06it/s]

2025-05-20 16:48:33,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:33,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4085/9304 [12:38<14:59,  5.81it/s]

2025-05-20 16:48:33,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:33,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4088/9304 [12:38<10:23,  8.37it/s]

2025-05-20 16:48:33,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:34,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4090/9304 [12:39<15:35,  5.58it/s]

2025-05-20 16:48:34,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4091/9304 [12:39<19:29,  4.46it/s]

2025-05-20 16:48:34,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:34,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4093/9304 [12:40<17:25,  4.99it/s]

2025-05-20 16:48:35,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:35,024 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:35,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:35,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:35,095 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4098/9304 [12:40<09:25,  9.20it/s]

2025-05-20 16:48:35,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:35,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4100/9304 [12:41<13:53,  6.24it/s]

2025-05-20 16:48:36,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:36,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4102/9304 [12:41<16:53,  5.13it/s]

2025-05-20 16:48:36,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:36,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4104/9304 [12:41<13:59,  6.19it/s]

2025-05-20 16:48:36,637 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:36,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4106/9304 [12:42<13:30,  6.41it/s]

2025-05-20 16:48:36,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4107/9304 [12:42<13:00,  6.66it/s]

2025-05-20 16:48:36,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:37,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4109/9304 [12:42<15:47,  5.48it/s]

2025-05-20 16:48:37,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:37,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4110/9304 [12:43<19:24,  4.46it/s]

2025-05-20 16:48:38,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4112/9304 [12:43<17:18,  5.00it/s]

2025-05-20 16:48:38,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:38,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4113/9304 [12:43<17:20,  4.99it/s]

2025-05-20 16:48:38,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:38,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:38,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4117/9304 [12:43<11:48,  7.32it/s]

2025-05-20 16:48:38,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:39,338 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4119/9304 [12:44<16:55,  5.11it/s]

2025-05-20 16:48:39,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:39,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4121/9304 [12:44<13:22,  6.46it/s]

2025-05-20 16:48:39,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:39,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4123/9304 [12:45<16:27,  5.24it/s]

2025-05-20 16:48:40,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:40,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:40,213 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4126/9304 [12:45<12:32,  6.88it/s]

2025-05-20 16:48:40,236 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:40,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4128/9304 [12:46<16:09,  5.34it/s]

2025-05-20 16:48:41,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:41,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4129/9304 [12:46<19:59,  4.31it/s]

2025-05-20 16:48:41,490 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4131/9304 [12:46<16:29,  5.23it/s]

2025-05-20 16:48:41,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:41,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:41,568 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:41,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4135/9304 [12:46<09:50,  8.75it/s]

2025-05-20 16:48:41,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:41,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4137/9304 [12:47<10:14,  8.41it/s]

2025-05-20 16:48:42,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:42,790 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 44%|████▍     | 4139/9304 [12:48<18:08,  4.75it/s]

2025-05-20 16:48:42,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:42,928 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4141/9304 [12:48<14:53,  5.78it/s]

2025-05-20 16:48:42,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:43,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4143/9304 [12:48<12:09,  7.07it/s]

2025-05-20 16:48:43,237 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:43,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4145/9304 [12:48<12:22,  6.95it/s]

2025-05-20 16:48:43,639 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:44,152 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:44,153 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4147/9304 [12:49<18:35,  4.62it/s]

2025-05-20 16:48:44,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4149/9304 [12:49<15:28,  5.55it/s]

2025-05-20 16:48:44,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4150/9304 [12:49<17:37,  4.88it/s]

2025-05-20 16:48:44,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:44,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4151/9304 [12:50<17:43,  4.85it/s]

2025-05-20 16:48:44,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:44,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:45,007 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4155/9304 [12:50<09:48,  8.74it/s]

2025-05-20 16:48:45,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:45,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4157/9304 [12:50<13:23,  6.41it/s]

2025-05-20 16:48:45,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:45,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4159/9304 [12:51<15:06,  5.67it/s]

2025-05-20 16:48:46,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4160/9304 [12:51<16:57,  5.06it/s]

2025-05-20 16:48:46,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:46,608 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:46,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4162/9304 [12:51<15:44,  5.44it/s]

2025-05-20 16:48:46,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:47,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4165/9304 [12:52<14:11,  6.04it/s]

2025-05-20 16:48:47,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:47,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:47,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4166/9304 [12:52<18:58,  4.51it/s]

2025-05-20 16:48:47,552 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:48,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4170/9304 [12:53<15:02,  5.69it/s]

2025-05-20 16:48:48,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4171/9304 [12:53<16:42,  5.12it/s]

2025-05-20 16:48:48,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4172/9304 [12:53<16:49,  5.08it/s]

2025-05-20 16:48:48,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:48,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4174/9304 [12:54<13:00,  6.58it/s]

2025-05-20 16:48:48,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4175/9304 [12:54<14:47,  5.78it/s]

2025-05-20 16:48:49,013 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:49,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4177/9304 [12:54<16:06,  5.30it/s]

2025-05-20 16:48:49,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4178/9304 [12:54<14:46,  5.78it/s]

2025-05-20 16:48:49,902 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4179/9304 [12:55<19:27,  4.39it/s]

2025-05-20 16:48:49,971 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:50,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4181/9304 [12:55<14:15,  5.99it/s]

2025-05-20 16:48:50,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4182/9304 [12:55<13:18,  6.41it/s]

2025-05-20 16:48:50,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:50,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4184/9304 [12:55<11:04,  7.70it/s]

2025-05-20 16:48:50,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4185/9304 [12:55<13:07,  6.50it/s]

2025-05-20 16:48:51,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▍     | 4186/9304 [12:56<26:59,  3.16it/s]

2025-05-20 16:48:51,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:51,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4187/9304 [12:56<24:38,  3.46it/s]

2025-05-20 16:48:51,676 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:51,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:51,797 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4191/9304 [12:57<12:10,  7.00it/s]

2025-05-20 16:48:51,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:51,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4193/9304 [12:57<10:51,  7.85it/s]

2025-05-20 16:48:51,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:52,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4195/9304 [12:57<12:09,  7.00it/s]

2025-05-20 16:48:52,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4196/9304 [12:58<18:14,  4.67it/s]

2025-05-20 16:48:52,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:52,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:53,181 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4199/9304 [12:58<13:58,  6.09it/s]

2025-05-20 16:48:53,262 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4200/9304 [12:58<13:07,  6.48it/s]

2025-05-20 16:48:53,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:53,694 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:53,694 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4202/9304 [12:59<14:30,  5.86it/s]

2025-05-20 16:48:53,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:53,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4205/9304 [12:59<10:10,  8.36it/s]

2025-05-20 16:48:54,172 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:54,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4207/9304 [12:59<12:36,  6.74it/s]

2025-05-20 16:48:54,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:54,730 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4208/9304 [13:00<16:53,  5.03it/s]

2025-05-20 16:48:55,250 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4210/9304 [13:00<18:34,  4.57it/s]

2025-05-20 16:48:55,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:55,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:55,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4212/9304 [13:00<14:36,  5.81it/s]

2025-05-20 16:48:55,539 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4214/9304 [13:00<12:08,  6.99it/s]

2025-05-20 16:48:55,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:55,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4216/9304 [13:01<13:53,  6.10it/s]

2025-05-20 16:48:56,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4217/9304 [13:01<15:30,  5.47it/s]

2025-05-20 16:48:56,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4218/9304 [13:01<16:26,  5.15it/s]

2025-05-20 16:48:56,908 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4219/9304 [13:02<20:57,  4.04it/s]

2025-05-20 16:48:57,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:57,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4220/9304 [13:02<20:07,  4.21it/s]

2025-05-20 16:48:57,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:57,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:57,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4222/9304 [13:02<15:08,  5.60it/s]

2025-05-20 16:48:57,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:57,470 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4226/9304 [13:02<08:50,  9.57it/s]

2025-05-20 16:48:58,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:58,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4228/9304 [13:03<16:24,  5.16it/s]

2025-05-20 16:48:58,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4229/9304 [13:03<16:53,  5.01it/s]

2025-05-20 16:48:58,567 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:58,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4231/9304 [13:03<12:52,  6.57it/s]

2025-05-20 16:48:58,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:59,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 45%|████▌     | 4233/9304 [13:04<14:03,  6.01it/s]

2025-05-20 16:48:59,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:59,603 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4235/9304 [13:04<16:57,  4.98it/s]

2025-05-20 16:48:59,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4236/9304 [13:05<15:32,  5.43it/s]

2025-05-20 16:48:59,730 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:48:59,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:00,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4239/9304 [13:05<15:27,  5.46it/s]

2025-05-20 16:49:00,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:00,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:00,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:00,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:00,599 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4244/9304 [13:06<13:16,  6.36it/s]

2025-05-20 16:49:01,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4245/9304 [13:06<15:43,  5.36it/s]

2025-05-20 16:49:01,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:01,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4246/9304 [13:06<17:48,  4.73it/s]

2025-05-20 16:49:01,573 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:01,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4249/9304 [13:06<11:17,  7.46it/s]

2025-05-20 16:49:02,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:02,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:02,032 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4251/9304 [13:07<13:05,  6.43it/s]

2025-05-20 16:49:02,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4253/9304 [13:07<16:02,  5.25it/s]

2025-05-20 16:49:02,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:02,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4255/9304 [13:08<14:31,  5.80it/s]

2025-05-20 16:49:03,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:03,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4256/9304 [13:08<16:32,  5.09it/s]

2025-05-20 16:49:03,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:03,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4259/9304 [13:08<13:06,  6.42it/s]

2025-05-20 16:49:03,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4260/9304 [13:08<13:49,  6.08it/s]

2025-05-20 16:49:03,864 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4261/9304 [13:09<14:16,  5.89it/s]

2025-05-20 16:49:03,967 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4262/9304 [13:09<12:59,  6.47it/s]

2025-05-20 16:49:03,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:04,696 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4264/9304 [13:10<19:46,  4.25it/s]

2025-05-20 16:49:04,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:04,808 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4266/9304 [13:10<14:23,  5.83it/s]

2025-05-20 16:49:04,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:04,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4268/9304 [13:10<11:06,  7.56it/s]

2025-05-20 16:49:04,945 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:05,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4270/9304 [13:10<12:08,  6.91it/s]

2025-05-20 16:49:05,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:05,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4272/9304 [13:10<13:18,  6.30it/s]

2025-05-20 16:49:05,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4273/9304 [13:11<15:21,  5.46it/s]

2025-05-20 16:49:06,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4274/9304 [13:11<14:51,  5.64it/s]

2025-05-20 16:49:06,429 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4275/9304 [13:11<18:07,  4.63it/s]

2025-05-20 16:49:06,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:06,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4277/9304 [13:11<12:47,  6.55it/s]

2025-05-20 16:49:06,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4278/9304 [13:12<13:31,  6.20it/s]

2025-05-20 16:49:07,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4279/9304 [13:12<18:40,  4.48it/s]

2025-05-20 16:49:07,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:07,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4280/9304 [13:12<18:06,  4.62it/s]

2025-05-20 16:49:07,454 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4282/9304 [13:12<12:21,  6.77it/s]

2025-05-20 16:49:07,502 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:08,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4284/9304 [13:13<17:18,  4.84it/s]

2025-05-20 16:49:08,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4285/9304 [13:13<15:54,  5.26it/s]

2025-05-20 16:49:08,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:08,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4287/9304 [13:13<13:07,  6.37it/s]

2025-05-20 16:49:08,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4288/9304 [13:13<15:14,  5.49it/s]

2025-05-20 16:49:08,789 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4289/9304 [13:14<13:57,  5.98it/s]

2025-05-20 16:49:08,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4290/9304 [13:14<15:35,  5.36it/s]

2025-05-20 16:49:09,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4291/9304 [13:14<16:49,  4.97it/s]

2025-05-20 16:49:09,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4292/9304 [13:14<14:39,  5.70it/s]

2025-05-20 16:49:09,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:09,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4294/9304 [13:14<11:08,  7.49it/s]

2025-05-20 16:49:09,575 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:09,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4296/9304 [13:15<11:02,  7.56it/s]

2025-05-20 16:49:10,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4297/9304 [13:15<16:18,  5.12it/s]

2025-05-20 16:49:10,539 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4298/9304 [13:15<18:37,  4.48it/s]

2025-05-20 16:49:10,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:11,041 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:11,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4300/9304 [13:16<19:31,  4.27it/s]

2025-05-20 16:49:11,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:11,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▌     | 4302/9304 [13:16<17:09,  4.86it/s]

2025-05-20 16:49:11,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4304/9304 [13:16<14:03,  5.92it/s]

2025-05-20 16:49:11,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:11,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4306/9304 [13:17<11:22,  7.32it/s]

2025-05-20 16:49:12,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4307/9304 [13:17<15:12,  5.48it/s]

2025-05-20 16:49:12,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4308/9304 [13:17<17:07,  4.86it/s]

2025-05-20 16:49:12,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4309/9304 [13:18<21:04,  3.95it/s]

2025-05-20 16:49:12,841 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:12,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:13,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4312/9304 [13:18<16:07,  5.16it/s]

2025-05-20 16:49:13,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:13,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4313/9304 [13:18<19:10,  4.34it/s]

2025-05-20 16:49:13,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:13,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4316/9304 [13:19<14:55,  5.57it/s]

2025-05-20 16:49:14,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4317/9304 [13:19<15:12,  5.47it/s]

2025-05-20 16:49:14,404 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:14,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4318/9304 [13:19<17:23,  4.78it/s]

2025-05-20 16:49:14,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:14,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4321/9304 [13:19<10:59,  7.56it/s]

2025-05-20 16:49:15,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:15,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4323/9304 [13:20<14:15,  5.82it/s]

2025-05-20 16:49:15,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4324/9304 [13:20<16:45,  4.96it/s]

2025-05-20 16:49:15,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:15,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 46%|████▋     | 4326/9304 [13:20<12:32,  6.62it/s]

2025-05-20 16:49:15,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:16,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4328/9304 [13:21<18:04,  4.59it/s]

2025-05-20 16:49:16,319 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:16,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:16,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4330/9304 [13:22<19:06,  4.34it/s]

2025-05-20 16:49:16,817 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:17,050 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4333/9304 [13:22<14:47,  5.60it/s]

2025-05-20 16:49:17,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:17,148 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:17,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4336/9304 [13:22<10:29,  7.89it/s]

2025-05-20 16:49:18,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:18,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4338/9304 [13:23<17:25,  4.75it/s]

2025-05-20 16:49:18,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:18,244 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4340/9304 [13:23<14:43,  5.62it/s]

2025-05-20 16:49:18,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:18,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4342/9304 [13:24<15:58,  5.18it/s]

2025-05-20 16:49:18,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4343/9304 [13:24<14:42,  5.62it/s]

2025-05-20 16:49:19,108 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4344/9304 [13:24<16:36,  4.98it/s]

2025-05-20 16:49:19,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4345/9304 [13:24<18:31,  4.46it/s]

2025-05-20 16:49:19,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:19,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4347/9304 [13:24<13:22,  6.18it/s]

2025-05-20 16:49:19,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4348/9304 [13:25<17:11,  4.80it/s]

2025-05-20 16:49:19,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:20,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4350/9304 [13:25<15:27,  5.34it/s]

2025-05-20 16:49:20,379 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4351/9304 [13:25<14:56,  5.52it/s]

2025-05-20 16:49:20,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4352/9304 [13:26<18:17,  4.51it/s]

2025-05-20 16:49:20,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:20,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:20,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:21,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:21,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4356/9304 [13:26<15:00,  5.49it/s]

2025-05-20 16:49:21,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4358/9304 [13:26<14:22,  5.73it/s]

2025-05-20 16:49:21,909 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4359/9304 [13:27<15:28,  5.33it/s]

2025-05-20 16:49:21,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:22,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4361/9304 [13:27<16:28,  5.00it/s]

2025-05-20 16:49:22,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:22,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:22,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4363/9304 [13:28<16:35,  4.97it/s]

2025-05-20 16:49:22,820 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:22,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:22,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4367/9304 [13:28<10:02,  8.19it/s]

2025-05-20 16:49:23,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:23,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4369/9304 [13:28<12:17,  6.69it/s]

2025-05-20 16:49:23,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:24,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4371/9304 [13:29<16:38,  4.94it/s]

2025-05-20 16:49:24,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:24,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4373/9304 [13:29<13:29,  6.09it/s]

2025-05-20 16:49:24,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:24,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4375/9304 [13:29<11:25,  7.19it/s]

2025-05-20 16:49:24,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:24,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4377/9304 [13:30<13:33,  6.06it/s]

2025-05-20 16:49:25,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4378/9304 [13:30<15:45,  5.21it/s]

2025-05-20 16:49:25,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4379/9304 [13:30<16:02,  5.12it/s]

2025-05-20 16:49:25,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4380/9304 [13:31<19:44,  4.16it/s]

2025-05-20 16:49:26,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4381/9304 [13:31<20:59,  3.91it/s]

2025-05-20 16:49:26,051 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:26,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:26,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4384/9304 [13:31<11:54,  6.89it/s]

2025-05-20 16:49:26,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:26,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:26,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4387/9304 [13:31<11:49,  6.93it/s]

2025-05-20 16:49:27,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:27,388 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4389/9304 [13:32<17:51,  4.59it/s]

2025-05-20 16:49:27,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:27,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:27,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:27,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4392/9304 [13:33<15:15,  5.37it/s]

2025-05-20 16:49:27,789 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:27,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4395/9304 [13:33<11:39,  7.02it/s]

2025-05-20 16:49:28,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:28,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4397/9304 [13:33<11:42,  6.98it/s]

2025-05-20 16:49:28,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4398/9304 [13:34<16:05,  5.08it/s]

2025-05-20 16:49:28,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:28,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4400/9304 [13:34<13:14,  6.17it/s]

2025-05-20 16:49:29,217 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4401/9304 [13:34<15:06,  5.41it/s]

2025-05-20 16:49:29,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:29,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4403/9304 [13:34<11:29,  7.11it/s]

2025-05-20 16:49:29,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:29,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4405/9304 [13:34<11:44,  6.95it/s]

2025-05-20 16:49:30,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4406/9304 [13:35<21:14,  3.84it/s]

2025-05-20 16:49:30,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:30,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:30,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4408/9304 [13:35<17:39,  4.62it/s]

2025-05-20 16:49:30,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:30,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:30,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4412/9304 [13:36<10:19,  7.89it/s]

2025-05-20 16:49:31,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:31,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4414/9304 [13:36<10:39,  7.64it/s]

2025-05-20 16:49:31,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:31,966 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4416/9304 [13:37<17:29,  4.66it/s]

2025-05-20 16:49:32,061 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:32,152 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4418/9304 [13:37<14:41,  5.55it/s]

2025-05-20 16:49:32,361 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 47%|████▋     | 4419/9304 [13:37<15:24,  5.28it/s]

2025-05-20 16:49:32,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:32,793 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4421/9304 [13:38<15:49,  5.14it/s]

2025-05-20 16:49:33,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:33,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4422/9304 [13:38<17:32,  4.64it/s]

2025-05-20 16:49:33,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:33,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4425/9304 [13:38<14:05,  5.77it/s]

2025-05-20 16:49:33,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4426/9304 [13:38<13:17,  6.12it/s]

2025-05-20 16:49:33,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:33,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4428/9304 [13:39<14:22,  5.65it/s]

2025-05-20 16:49:34,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4429/9304 [13:39<13:25,  6.06it/s]

2025-05-20 16:49:34,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4430/9304 [13:39<14:29,  5.61it/s]

2025-05-20 16:49:34,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4431/9304 [13:39<13:58,  5.81it/s]

2025-05-20 16:49:34,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4432/9304 [13:39<12:48,  6.34it/s]

2025-05-20 16:49:34,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:34,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4434/9304 [13:40<11:35,  7.01it/s]

2025-05-20 16:49:35,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:35,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4435/9304 [13:40<12:46,  6.35it/s]

2025-05-20 16:49:35,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:35,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4438/9304 [13:40<08:19,  9.75it/s]

2025-05-20 16:49:35,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:35,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4440/9304 [13:41<16:07,  5.03it/s]

2025-05-20 16:49:36,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:36,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4441/9304 [13:41<14:44,  5.50it/s]

2025-05-20 16:49:36,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:36,713 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4444/9304 [13:42<15:33,  5.21it/s]

2025-05-20 16:49:36,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:36,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4446/9304 [13:42<13:05,  6.19it/s]

2025-05-20 16:49:37,007 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4447/9304 [13:42<12:21,  6.55it/s]

2025-05-20 16:49:37,119 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4448/9304 [13:42<11:39,  6.94it/s]

2025-05-20 16:49:37,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:37,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4450/9304 [13:42<14:35,  5.55it/s]

2025-05-20 16:49:37,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:37,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4452/9304 [13:43<12:57,  6.24it/s]

2025-05-20 16:49:37,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:38,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4454/9304 [13:43<15:04,  5.36it/s]

2025-05-20 16:49:38,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:38,421 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:38,465 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4457/9304 [13:43<10:23,  7.77it/s]

2025-05-20 16:49:39,145 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:39,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:39,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4459/9304 [13:44<17:39,  4.57it/s]

2025-05-20 16:49:39,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:39,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4462/9304 [13:44<12:56,  6.23it/s]

2025-05-20 16:49:39,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:39,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4464/9304 [13:45<11:33,  6.97it/s]

2025-05-20 16:49:39,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:40,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4466/9304 [13:45<13:03,  6.17it/s]

2025-05-20 16:49:40,446 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4467/9304 [13:45<14:36,  5.52it/s]

2025-05-20 16:49:40,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4468/9304 [13:46<15:44,  5.12it/s]

2025-05-20 16:49:40,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4469/9304 [13:46<17:15,  4.67it/s]

2025-05-20 16:49:41,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:41,118 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4471/9304 [13:46<13:14,  6.09it/s]

2025-05-20 16:49:41,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:41,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4473/9304 [13:46<10:09,  7.93it/s]

2025-05-20 16:49:41,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:41,797 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4475/9304 [13:47<13:58,  5.76it/s]

2025-05-20 16:49:41,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:42,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4477/9304 [13:47<19:07,  4.21it/s]

2025-05-20 16:49:42,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4478/9304 [13:48<18:24,  4.37it/s]

2025-05-20 16:49:42,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:42,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:42,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:42,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4482/9304 [13:48<10:32,  7.62it/s]

2025-05-20 16:49:43,202 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:43,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4484/9304 [13:48<12:13,  6.57it/s]

2025-05-20 16:49:44,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4485/9304 [13:49<19:31,  4.11it/s]

2025-05-20 16:49:44,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:44,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:44,253 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4488/9304 [13:49<14:01,  5.73it/s]

2025-05-20 16:49:44,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:44,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:44,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4491/9304 [13:49<12:52,  6.23it/s]

2025-05-20 16:49:45,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4492/9304 [13:50<19:27,  4.12it/s]

2025-05-20 16:49:45,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:45,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4494/9304 [13:50<14:59,  5.35it/s]

2025-05-20 16:49:45,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:45,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:45,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4497/9304 [13:51<11:50,  6.77it/s]

2025-05-20 16:49:45,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:46,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4499/9304 [13:51<12:52,  6.22it/s]

2025-05-20 16:49:47,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4500/9304 [13:52<22:05,  3.62it/s]

2025-05-20 16:49:47,020 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:47,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:47,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:47,185 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4504/9304 [13:52<13:11,  6.07it/s]

2025-05-20 16:49:47,257 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:47,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4506/9304 [13:52<11:24,  7.01it/s]

2025-05-20 16:49:47,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:47,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4508/9304 [13:52<10:53,  7.33it/s]

2025-05-20 16:49:47,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:48,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4510/9304 [13:53<15:27,  5.17it/s]

2025-05-20 16:49:48,545 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4511/9304 [13:53<16:32,  4.83it/s]

2025-05-20 16:49:48,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 48%|████▊     | 4512/9304 [13:53<14:54,  5.36it/s]

2025-05-20 16:49:48,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:48,824 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4514/9304 [13:54<12:08,  6.58it/s]

2025-05-20 16:49:48,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:49,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4516/9304 [13:54<11:23,  7.00it/s]

2025-05-20 16:49:49,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:49,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:49,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4517/9304 [13:54<15:55,  5.01it/s]

2025-05-20 16:49:50,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4520/9304 [13:55<15:30,  5.14it/s]

2025-05-20 16:49:50,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4521/9304 [13:55<15:01,  5.31it/s]

2025-05-20 16:49:50,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:50,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4523/9304 [13:55<13:37,  5.85it/s]

2025-05-20 16:49:50,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4524/9304 [13:56<13:58,  5.70it/s]

2025-05-20 16:49:50,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:50,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4525/9304 [13:56<13:44,  5.79it/s]

2025-05-20 16:49:50,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:50,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:51,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4529/9304 [13:56<13:03,  6.09it/s]

2025-05-20 16:49:51,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4530/9304 [13:57<15:22,  5.18it/s]

2025-05-20 16:49:51,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4531/9304 [13:57<14:44,  5.40it/s]

2025-05-20 16:49:52,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4532/9304 [13:57<13:56,  5.71it/s]

2025-05-20 16:49:52,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4533/9304 [13:57<13:40,  5.82it/s]

2025-05-20 16:49:52,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▊     | 4534/9304 [13:57<12:29,  6.36it/s]

2025-05-20 16:49:52,470 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:52,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4536/9304 [13:57<11:37,  6.83it/s]

2025-05-20 16:49:52,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:52,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4538/9304 [13:58<12:03,  6.59it/s]

2025-05-20 16:49:53,594 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4539/9304 [13:58<19:46,  4.02it/s]

2025-05-20 16:49:53,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:53,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:53,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4541/9304 [13:59<15:56,  4.98it/s]

2025-05-20 16:49:54,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4543/9304 [13:59<13:17,  5.97it/s]

2025-05-20 16:49:54,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4544/9304 [13:59<13:15,  5.99it/s]

2025-05-20 16:49:54,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4545/9304 [13:59<15:42,  5.05it/s]

2025-05-20 16:49:54,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4546/9304 [14:00<17:23,  4.56it/s]

2025-05-20 16:49:55,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4547/9304 [14:00<19:23,  4.09it/s]

2025-05-20 16:49:55,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:55,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4549/9304 [14:00<14:40,  5.40it/s]

2025-05-20 16:49:55,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4550/9304 [14:00<14:40,  5.40it/s]

2025-05-20 16:49:55,684 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4551/9304 [14:01<14:18,  5.54it/s]

2025-05-20 16:49:55,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:56,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4553/9304 [14:01<15:57,  4.96it/s]

2025-05-20 16:49:56,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4554/9304 [14:01<16:18,  4.85it/s]

2025-05-20 16:49:56,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4555/9304 [14:01<16:43,  4.73it/s]

2025-05-20 16:49:56,621 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:56,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4557/9304 [14:02<12:28,  6.34it/s]

2025-05-20 16:49:56,781 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:56,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:57,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4560/9304 [14:02<11:07,  7.10it/s]

2025-05-20 16:49:57,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:57,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4562/9304 [14:02<13:03,  6.05it/s]

2025-05-20 16:49:57,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:57,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4564/9304 [14:03<11:25,  6.91it/s]

2025-05-20 16:49:58,155 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4565/9304 [14:03<15:13,  5.19it/s]

2025-05-20 16:49:58,190 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:58,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:58,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4568/9304 [14:03<12:19,  6.41it/s]

2025-05-20 16:49:58,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:58,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4570/9304 [14:03<10:39,  7.40it/s]

2025-05-20 16:49:58,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4571/9304 [14:04<12:09,  6.49it/s]

2025-05-20 16:49:59,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4572/9304 [14:04<12:47,  6.16it/s]

2025-05-20 16:49:59,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:49:59,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4574/9304 [14:04<11:47,  6.69it/s]

2025-05-20 16:49:59,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4575/9304 [14:05<18:07,  4.35it/s]

2025-05-20 16:50:00,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4576/9304 [14:05<15:52,  4.96it/s]

2025-05-20 16:50:00,190 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4577/9304 [14:05<15:33,  5.06it/s]

2025-05-20 16:50:00,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4578/9304 [14:05<13:59,  5.63it/s]

2025-05-20 16:50:00,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4579/9304 [14:05<13:03,  6.03it/s]

2025-05-20 16:50:00,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:00,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:00,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4582/9304 [14:06<10:25,  7.55it/s]

2025-05-20 16:50:00,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:00,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:01,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4585/9304 [14:07<18:20,  4.29it/s]

2025-05-20 16:50:01,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4586/9304 [14:07<16:48,  4.68it/s]

2025-05-20 16:50:02,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4587/9304 [14:07<15:31,  5.06it/s]

2025-05-20 16:50:02,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:02,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:02,275 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4590/9304 [14:07<10:32,  7.46it/s]

2025-05-20 16:50:02,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:02,418 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4592/9304 [14:07<09:01,  8.70it/s]

2025-05-20 16:50:02,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:03,446 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4594/9304 [14:08<18:28,  4.25it/s]

2025-05-20 16:50:03,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:03,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4596/9304 [14:08<14:34,  5.39it/s]

2025-05-20 16:50:03,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:03,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4598/9304 [14:09<13:19,  5.88it/s]

2025-05-20 16:50:03,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:03,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4600/9304 [14:09<10:46,  7.28it/s]

2025-05-20 16:50:04,170 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:04,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4602/9304 [14:09<12:04,  6.49it/s]

2025-05-20 16:50:04,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4603/9304 [14:10<15:41,  4.99it/s]

2025-05-20 16:50:05,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4604/9304 [14:10<17:34,  4.46it/s]

2025-05-20 16:50:05,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 49%|████▉     | 4605/9304 [14:10<17:21,  4.51it/s]

2025-05-20 16:50:05,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:05,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4607/9304 [14:10<12:31,  6.25it/s]

2025-05-20 16:50:05,503 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:05,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:05,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4609/9304 [14:10<10:34,  7.40it/s]

2025-05-20 16:50:05,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4611/9304 [14:11<09:08,  8.56it/s]

2025-05-20 16:50:05,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:06,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4613/9304 [14:11<15:11,  5.15it/s]

2025-05-20 16:50:06,714 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4614/9304 [14:12<15:36,  5.01it/s]

2025-05-20 16:50:06,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4615/9304 [14:12<14:32,  5.38it/s]

2025-05-20 16:50:06,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:06,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:07,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4618/9304 [14:12<10:02,  7.77it/s]

2025-05-20 16:50:07,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4619/9304 [14:12<10:13,  7.64it/s]

2025-05-20 16:50:07,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4620/9304 [14:12<11:17,  6.92it/s]

2025-05-20 16:50:07,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:08,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4622/9304 [14:13<17:56,  4.35it/s]

2025-05-20 16:50:08,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:08,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4624/9304 [14:13<16:43,  4.66it/s]

2025-05-20 16:50:08,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:08,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:08,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4627/9304 [14:14<14:06,  5.52it/s]

2025-05-20 16:50:08,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:09,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4629/9304 [14:14<12:49,  6.07it/s]

2025-05-20 16:50:09,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4630/9304 [14:14<16:55,  4.60it/s]

2025-05-20 16:50:09,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:09,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4632/9304 [14:15<14:17,  5.45it/s]

2025-05-20 16:50:09,905 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:09,908 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:10,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4635/9304 [14:15<15:08,  5.14it/s]

2025-05-20 16:50:10,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4636/9304 [14:16<16:26,  4.73it/s]

2025-05-20 16:50:10,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4637/9304 [14:16<16:09,  4.81it/s]

2025-05-20 16:50:11,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4638/9304 [14:16<16:08,  4.82it/s]

2025-05-20 16:50:11,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:11,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4640/9304 [14:16<13:56,  5.58it/s]

2025-05-20 16:50:11,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4641/9304 [14:16<12:46,  6.09it/s]

2025-05-20 16:50:11,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:11,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4643/9304 [14:17<11:08,  6.97it/s]

2025-05-20 16:50:11,908 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4644/9304 [14:17<10:55,  7.11it/s]

2025-05-20 16:50:12,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4645/9304 [14:17<16:32,  4.70it/s]

2025-05-20 16:50:12,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4646/9304 [14:18<19:53,  3.90it/s]

2025-05-20 16:50:12,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:12,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:12,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|████▉     | 4649/9304 [14:18<12:02,  6.44it/s]

2025-05-20 16:50:12,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:13,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:13,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4652/9304 [14:18<11:38,  6.66it/s]

2025-05-20 16:50:13,501 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4653/9304 [14:18<11:34,  6.70it/s]

2025-05-20 16:50:13,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4654/9304 [14:19<12:04,  6.42it/s]

2025-05-20 16:50:13,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:14,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4656/9304 [14:19<13:48,  5.61it/s]

2025-05-20 16:50:14,404 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4657/9304 [14:19<15:26,  5.02it/s]

2025-05-20 16:50:14,716 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4658/9304 [14:20<17:24,  4.45it/s]

2025-05-20 16:50:14,847 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4659/9304 [14:20<15:41,  4.93it/s]

2025-05-20 16:50:14,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:14,908 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:15,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4662/9304 [14:20<12:53,  6.00it/s]

2025-05-20 16:50:15,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:15,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4664/9304 [14:21<15:42,  4.93it/s]

2025-05-20 16:50:15,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:16,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4666/9304 [14:21<16:51,  4.59it/s]

2025-05-20 16:50:16,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:16,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4668/9304 [14:21<15:43,  4.91it/s]

2025-05-20 16:50:16,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:16,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:16,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4671/9304 [14:22<12:15,  6.30it/s]

2025-05-20 16:50:17,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4672/9304 [14:22<11:51,  6.51it/s]

2025-05-20 16:50:17,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:17,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4674/9304 [14:22<10:01,  7.70it/s]

2025-05-20 16:50:17,224 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:17,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4676/9304 [14:23<12:33,  6.14it/s]

2025-05-20 16:50:18,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4677/9304 [14:23<15:19,  5.03it/s]

2025-05-20 16:50:18,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4678/9304 [14:23<17:39,  4.37it/s]

2025-05-20 16:50:18,490 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4679/9304 [14:23<15:30,  4.97it/s]

2025-05-20 16:50:18,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:18,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4681/9304 [14:23<12:02,  6.40it/s]

2025-05-20 16:50:18,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4682/9304 [14:24<14:31,  5.31it/s]

2025-05-20 16:50:18,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:19,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:19,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4685/9304 [14:24<12:22,  6.22it/s]

2025-05-20 16:50:19,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4686/9304 [14:24<12:34,  6.12it/s]

2025-05-20 16:50:19,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4687/9304 [14:24<11:46,  6.54it/s]

2025-05-20 16:50:20,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4688/9304 [14:25<21:53,  3.51it/s]

2025-05-20 16:50:20,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:20,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4690/9304 [14:25<16:39,  4.62it/s]

2025-05-20 16:50:21,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4691/9304 [14:26<19:58,  3.85it/s]

2025-05-20 16:50:21,190 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4692/9304 [14:26<18:33,  4.14it/s]

2025-05-20 16:50:21,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:21,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4694/9304 [14:26<12:54,  5.95it/s]

2025-05-20 16:50:21,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:21,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4696/9304 [14:27<14:52,  5.16it/s]

2025-05-20 16:50:21,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4697/9304 [14:27<13:31,  5.68it/s]

2025-05-20 16:50:22,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:22,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 50%|█████     | 4698/9304 [14:27<17:53,  4.29it/s]

2025-05-20 16:50:22,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4700/9304 [14:27<15:27,  4.96it/s]

2025-05-20 16:50:22,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4701/9304 [14:28<14:56,  5.13it/s]

2025-05-20 16:50:23,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4702/9304 [14:28<15:38,  4.90it/s]

2025-05-20 16:50:23,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:23,217 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4704/9304 [14:28<12:07,  6.33it/s]

2025-05-20 16:50:23,292 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:23,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4706/9304 [14:28<10:12,  7.51it/s]

2025-05-20 16:50:23,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4707/9304 [14:29<15:38,  4.90it/s]

2025-05-20 16:50:23,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:24,332 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4709/9304 [14:29<16:17,  4.70it/s]

2025-05-20 16:50:24,795 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4710/9304 [14:30<20:26,  3.75it/s]

2025-05-20 16:50:24,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:24,886 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:25,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4713/9304 [14:30<13:32,  5.65it/s]

2025-05-20 16:50:25,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4714/9304 [14:30<13:29,  5.67it/s]

2025-05-20 16:50:25,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4715/9304 [14:30<13:03,  5.86it/s]

2025-05-20 16:50:25,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:25,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4717/9304 [14:30<10:58,  6.96it/s]

2025-05-20 16:50:25,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4718/9304 [14:31<11:11,  6.83it/s]

2025-05-20 16:50:26,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4719/9304 [14:31<18:45,  4.07it/s]

2025-05-20 16:50:26,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4720/9304 [14:31<16:27,  4.64it/s]

2025-05-20 16:50:26,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:26,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4722/9304 [14:31<11:15,  6.79it/s]

2025-05-20 16:50:26,575 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:26,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4724/9304 [14:31<08:43,  8.75it/s]

2025-05-20 16:50:26,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:26,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4726/9304 [14:32<09:35,  7.96it/s]

2025-05-20 16:50:27,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:27,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4728/9304 [14:32<10:35,  7.20it/s]

2025-05-20 16:50:27,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4729/9304 [14:33<18:00,  4.23it/s]

2025-05-20 16:50:27,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:28,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4731/9304 [14:33<15:52,  4.80it/s]

2025-05-20 16:50:28,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:28,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4733/9304 [14:33<11:56,  6.38it/s]

2025-05-20 16:50:28,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:28,576 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4735/9304 [14:33<11:12,  6.80it/s]

2025-05-20 16:50:28,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:28,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4737/9304 [14:34<09:49,  7.75it/s]

2025-05-20 16:50:28,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4738/9304 [14:34<10:00,  7.60it/s]

2025-05-20 16:50:29,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4739/9304 [14:34<19:43,  3.86it/s]

2025-05-20 16:50:29,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:29,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:29,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4742/9304 [14:35<11:59,  6.34it/s]

2025-05-20 16:50:29,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:30,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4744/9304 [14:35<11:00,  6.91it/s]

2025-05-20 16:50:30,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:30,289 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4746/9304 [14:35<10:58,  6.92it/s]

2025-05-20 16:50:30,545 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4747/9304 [14:35<12:50,  5.91it/s]

2025-05-20 16:50:30,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:31,112 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4749/9304 [14:36<15:25,  4.92it/s]

2025-05-20 16:50:31,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:31,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4751/9304 [14:36<12:24,  6.12it/s]

2025-05-20 16:50:31,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:31,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4753/9304 [14:36<11:41,  6.49it/s]

2025-05-20 16:50:31,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4754/9304 [14:37<12:29,  6.07it/s]

2025-05-20 16:50:31,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:31,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4756/9304 [14:37<09:44,  7.77it/s]

2025-05-20 16:50:32,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4757/9304 [14:37<10:25,  7.26it/s]

2025-05-20 16:50:32,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4758/9304 [14:37<15:44,  4.81it/s]

2025-05-20 16:50:32,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4759/9304 [14:37<14:52,  5.10it/s]

2025-05-20 16:50:32,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:32,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:32,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4761/9304 [14:38<13:39,  5.54it/s]

2025-05-20 16:50:33,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4763/9304 [14:38<11:54,  6.35it/s]

2025-05-20 16:50:33,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:33,270 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:33,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4766/9304 [14:38<09:07,  8.29it/s]

2025-05-20 16:50:33,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4767/9304 [14:38<09:31,  7.93it/s]

2025-05-20 16:50:34,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:34,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████     | 4768/9304 [14:39<17:06,  4.42it/s]

2025-05-20 16:50:34,336 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4770/9304 [14:39<12:29,  6.05it/s]

2025-05-20 16:50:34,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4771/9304 [14:39<12:43,  5.94it/s]

2025-05-20 16:50:34,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:34,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:34,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4774/9304 [14:39<08:23,  9.00it/s]

2025-05-20 16:50:34,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:35,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4776/9304 [14:40<10:07,  7.45it/s]

2025-05-20 16:50:35,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:35,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4778/9304 [14:41<15:47,  4.78it/s]

2025-05-20 16:50:35,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:35,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:35,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4781/9304 [14:41<11:25,  6.60it/s]

2025-05-20 16:50:36,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:36,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4783/9304 [14:41<10:46,  6.99it/s]

2025-05-20 16:50:36,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:36,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4785/9304 [14:41<09:33,  7.88it/s]

2025-05-20 16:50:36,523 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:36,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4787/9304 [14:42<12:33,  6.00it/s]

2025-05-20 16:50:37,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4788/9304 [14:42<14:17,  5.27it/s]

2025-05-20 16:50:37,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4789/9304 [14:43<18:26,  4.08it/s]

2025-05-20 16:50:37,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:37,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:37,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 51%|█████▏    | 4791/9304 [14:43<13:49,  5.44it/s]

2025-05-20 16:50:37,971 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4793/9304 [14:43<10:43,  7.00it/s]

2025-05-20 16:50:38,236 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:38,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4795/9304 [14:43<13:23,  5.61it/s]

2025-05-20 16:50:38,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4796/9304 [14:44<16:38,  4.51it/s]

2025-05-20 16:50:39,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4797/9304 [14:44<16:50,  4.46it/s]

2025-05-20 16:50:39,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4798/9304 [14:44<16:15,  4.62it/s]

2025-05-20 16:50:39,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:39,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4800/9304 [14:44<14:12,  5.29it/s]

2025-05-20 16:50:39,732 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4801/9304 [14:45<13:12,  5.68it/s]

2025-05-20 16:50:39,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4802/9304 [14:45<12:18,  6.09it/s]

2025-05-20 16:50:39,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:39,931 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:40,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4805/9304 [14:45<07:52,  9.52it/s]

2025-05-20 16:50:40,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:40,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4807/9304 [14:45<12:51,  5.83it/s]

2025-05-20 16:50:40,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4808/9304 [14:46<14:55,  5.02it/s]

2025-05-20 16:50:41,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4809/9304 [14:46<13:36,  5.51it/s]

2025-05-20 16:50:41,095 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:41,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4811/9304 [14:46<12:39,  5.92it/s]

2025-05-20 16:50:41,492 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4812/9304 [14:46<12:11,  6.14it/s]

2025-05-20 16:50:41,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4813/9304 [14:46<11:45,  6.37it/s]

2025-05-20 16:50:41,676 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:41,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:42,041 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4816/9304 [14:47<10:59,  6.81it/s]

2025-05-20 16:50:42,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4817/9304 [14:47<12:23,  6.03it/s]

2025-05-20 16:50:42,429 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4818/9304 [14:47<12:00,  6.23it/s]

2025-05-20 16:50:42,716 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4819/9304 [14:48<14:15,  5.25it/s]

2025-05-20 16:50:42,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:42,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:42,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4822/9304 [14:48<09:24,  7.94it/s]

2025-05-20 16:50:43,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4823/9304 [14:48<09:42,  7.69it/s]

2025-05-20 16:50:43,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4824/9304 [14:48<09:59,  7.47it/s]

2025-05-20 16:50:43,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4825/9304 [14:48<09:25,  7.93it/s]

2025-05-20 16:50:43,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4826/9304 [14:48<11:11,  6.67it/s]

2025-05-20 16:50:43,797 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4827/9304 [14:49<13:45,  5.42it/s]

2025-05-20 16:50:44,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4828/9304 [14:49<17:22,  4.29it/s]

2025-05-20 16:50:44,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4829/9304 [14:49<17:13,  4.33it/s]

2025-05-20 16:50:44,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:44,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4831/9304 [14:49<13:28,  5.53it/s]

2025-05-20 16:50:44,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:44,793 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4833/9304 [14:50<10:46,  6.92it/s]

2025-05-20 16:50:44,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4834/9304 [14:50<10:34,  7.04it/s]

2025-05-20 16:50:45,495 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4835/9304 [14:50<18:10,  4.10it/s]

2025-05-20 16:50:45,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:45,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:45,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4838/9304 [14:51<13:55,  5.34it/s]

2025-05-20 16:50:45,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:45,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:46,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4841/9304 [14:51<09:48,  7.58it/s]

2025-05-20 16:50:46,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:46,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4843/9304 [14:51<09:42,  7.65it/s]

2025-05-20 16:50:46,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4844/9304 [14:52<13:46,  5.39it/s]

2025-05-20 16:50:46,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:47,150 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4846/9304 [14:52<13:52,  5.36it/s]

2025-05-20 16:50:47,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:47,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4848/9304 [14:52<11:30,  6.45it/s]

2025-05-20 16:50:47,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:47,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4850/9304 [14:52<09:11,  8.08it/s]

2025-05-20 16:50:47,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:47,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4852/9304 [14:53<11:54,  6.23it/s]

2025-05-20 16:50:47,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:48,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4854/9304 [14:53<10:56,  6.78it/s]

2025-05-20 16:50:48,764 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4855/9304 [14:54<17:05,  4.34it/s]

2025-05-20 16:50:48,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:48,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4857/9304 [14:54<12:44,  5.82it/s]

2025-05-20 16:50:48,979 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:49,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4859/9304 [14:54<10:52,  6.81it/s]

2025-05-20 16:50:49,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:49,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4861/9304 [14:54<10:44,  6.89it/s]

2025-05-20 16:50:49,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:49,886 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4863/9304 [14:55<13:33,  5.46it/s]

2025-05-20 16:50:50,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4864/9304 [14:55<13:52,  5.33it/s]

2025-05-20 16:50:50,236 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4865/9304 [14:55<13:12,  5.60it/s]

2025-05-20 16:50:50,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4866/9304 [14:55<16:10,  4.57it/s]

2025-05-20 16:50:50,905 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4867/9304 [14:56<17:51,  4.14it/s]

2025-05-20 16:50:50,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:50,931 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:51,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4870/9304 [14:56<11:38,  6.35it/s]

2025-05-20 16:50:51,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:51,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4872/9304 [14:56<09:03,  8.16it/s]

2025-05-20 16:50:51,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:51,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4874/9304 [14:57<12:29,  5.91it/s]

2025-05-20 16:50:51,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:52,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4876/9304 [14:57<12:46,  5.78it/s]

2025-05-20 16:50:52,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4877/9304 [14:57<15:02,  4.91it/s]

2025-05-20 16:50:52,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4878/9304 [14:58<16:11,  4.55it/s]

2025-05-20 16:50:52,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4879/9304 [14:58<15:49,  4.66it/s]

2025-05-20 16:50:52,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:53,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4881/9304 [14:58<11:43,  6.29it/s]

2025-05-20 16:50:53,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4882/9304 [14:58<10:51,  6.79it/s]

2025-05-20 16:50:53,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4883/9304 [14:58<11:04,  6.65it/s]

2025-05-20 16:50:53,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 52%|█████▏    | 4884/9304 [14:58<12:33,  5.87it/s]

2025-05-20 16:50:53,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:54,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4886/9304 [14:59<13:55,  5.29it/s]

2025-05-20 16:50:54,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4887/9304 [14:59<17:58,  4.10it/s]

2025-05-20 16:50:54,539 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:54,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4889/9304 [14:59<13:26,  5.48it/s]

2025-05-20 16:50:54,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:54,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4891/9304 [15:00<10:03,  7.31it/s]

2025-05-20 16:50:54,928 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:55,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4893/9304 [15:00<10:32,  6.98it/s]

2025-05-20 16:50:55,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:55,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4894/9304 [15:00<10:51,  6.77it/s]

2025-05-20 16:50:55,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4896/9304 [15:00<10:14,  7.17it/s]

2025-05-20 16:50:55,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4897/9304 [15:01<13:45,  5.34it/s]

2025-05-20 16:50:55,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:56,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:56,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4899/9304 [15:01<14:40,  5.00it/s]

2025-05-20 16:50:56,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:56,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:56,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4902/9304 [15:01<10:11,  7.20it/s]

2025-05-20 16:50:56,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4904/9304 [15:01<09:04,  8.08it/s]

2025-05-20 16:50:56,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4905/9304 [15:02<09:01,  8.12it/s]

2025-05-20 16:50:56,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:57,716 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4907/9304 [15:03<17:30,  4.18it/s]

2025-05-20 16:50:57,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:57,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:57,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4910/9304 [15:03<11:39,  6.28it/s]

2025-05-20 16:50:58,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:58,250 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:58,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4912/9304 [15:03<12:34,  5.82it/s]

2025-05-20 16:50:58,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4914/9304 [15:03<10:28,  6.98it/s]

2025-05-20 16:50:58,931 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:59,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4916/9304 [15:04<14:33,  5.02it/s]

2025-05-20 16:50:59,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4917/9304 [15:04<14:22,  5.08it/s]

2025-05-20 16:50:59,371 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4918/9304 [15:04<13:03,  5.60it/s]

2025-05-20 16:50:59,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4919/9304 [15:04<11:50,  6.17it/s]

2025-05-20 16:50:59,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:50:59,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4921/9304 [15:05<13:11,  5.54it/s]

2025-05-20 16:51:00,198 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4922/9304 [15:05<15:15,  4.78it/s]

2025-05-20 16:51:00,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4923/9304 [15:05<14:11,  5.15it/s]

2025-05-20 16:51:00,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:00,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4925/9304 [15:06<14:49,  4.92it/s]

2025-05-20 16:51:00,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:00,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:00,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4928/9304 [15:06<09:48,  7.43it/s]

2025-05-20 16:51:01,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4929/9304 [15:06<16:27,  4.43it/s]

2025-05-20 16:51:01,739 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:01,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4930/9304 [15:07<15:43,  4.64it/s]

2025-05-20 16:51:01,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:01,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4932/9304 [15:07<11:49,  6.16it/s]

2025-05-20 16:51:02,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4934/9304 [15:07<15:51,  4.59it/s]

2025-05-20 16:51:02,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4935/9304 [15:08<16:17,  4.47it/s]

2025-05-20 16:51:02,813 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:02,855 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:02,866 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:02,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:03,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4940/9304 [15:08<10:24,  6.99it/s]

2025-05-20 16:51:03,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4941/9304 [15:08<12:07,  6.00it/s]

2025-05-20 16:51:03,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4942/9304 [15:09<15:26,  4.71it/s]

2025-05-20 16:51:04,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4943/9304 [15:09<15:17,  4.75it/s]

2025-05-20 16:51:04,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:04,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4944/9304 [15:09<16:13,  4.48it/s]

2025-05-20 16:51:04,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:04,612 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4947/9304 [15:09<10:25,  6.96it/s]

2025-05-20 16:51:04,808 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4948/9304 [15:10<11:13,  6.47it/s]

2025-05-20 16:51:05,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4949/9304 [15:10<13:05,  5.54it/s]

2025-05-20 16:51:05,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4950/9304 [15:10<13:05,  5.54it/s]

2025-05-20 16:51:05,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:05,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4952/9304 [15:10<11:49,  6.13it/s]

2025-05-20 16:51:05,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4953/9304 [15:11<12:32,  5.79it/s]

2025-05-20 16:51:06,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4954/9304 [15:11<21:29,  3.37it/s]

2025-05-20 16:51:06,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4955/9304 [15:11<19:59,  3.63it/s]

2025-05-20 16:51:06,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:06,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4957/9304 [15:12<15:03,  4.81it/s]

2025-05-20 16:51:07,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4958/9304 [15:12<13:56,  5.19it/s]

2025-05-20 16:51:07,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:07,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4960/9304 [15:12<11:19,  6.40it/s]

2025-05-20 16:51:07,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4961/9304 [15:12<10:37,  6.82it/s]

2025-05-20 16:51:07,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4962/9304 [15:12<11:42,  6.18it/s]

2025-05-20 16:51:07,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4963/9304 [15:13<16:14,  4.45it/s]

2025-05-20 16:51:08,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4964/9304 [15:13<16:54,  4.28it/s]

2025-05-20 16:51:08,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4965/9304 [15:13<14:24,  5.02it/s]

2025-05-20 16:51:08,404 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:08,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4967/9304 [15:13<10:46,  6.71it/s]

2025-05-20 16:51:08,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4968/9304 [15:14<11:37,  6.22it/s]

2025-05-20 16:51:08,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4969/9304 [15:14<13:47,  5.24it/s]

2025-05-20 16:51:09,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:09,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4971/9304 [15:14<11:53,  6.07it/s]

2025-05-20 16:51:09,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4972/9304 [15:14<14:48,  4.88it/s]

2025-05-20 16:51:09,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4973/9304 [15:15<14:22,  5.02it/s]

2025-05-20 16:51:09,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4974/9304 [15:15<12:53,  5.60it/s]

2025-05-20 16:51:10,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4975/9304 [15:15<12:44,  5.66it/s]

2025-05-20 16:51:10,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4976/9304 [15:15<12:53,  5.59it/s]

2025-05-20 16:51:10,412 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 53%|█████▎    | 4977/9304 [15:15<12:49,  5.63it/s]

2025-05-20 16:51:10,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:10,514 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4979/9304 [15:15<08:41,  8.30it/s]

2025-05-20 16:51:11,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:11,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4981/9304 [15:16<13:46,  5.23it/s]

2025-05-20 16:51:11,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4982/9304 [15:16<12:45,  5.65it/s]

2025-05-20 16:51:11,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:11,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4984/9304 [15:16<09:27,  7.61it/s]

2025-05-20 16:51:11,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:11,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4986/9304 [15:16<08:43,  8.24it/s]

2025-05-20 16:51:11,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:12,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4988/9304 [15:17<11:23,  6.31it/s]

2025-05-20 16:51:12,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4989/9304 [15:17<14:11,  5.07it/s]

2025-05-20 16:51:12,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:12,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:12,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4992/9304 [15:18<12:13,  5.88it/s]

2025-05-20 16:51:13,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4993/9304 [15:18<13:13,  5.44it/s]

2025-05-20 16:51:13,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:13,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4995/9304 [15:18<10:13,  7.02it/s]

2025-05-20 16:51:13,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4996/9304 [15:18<10:43,  6.70it/s]

2025-05-20 16:51:13,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4997/9304 [15:18<12:32,  5.73it/s]

2025-05-20 16:51:13,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 4998/9304 [15:19<14:31,  4.94it/s]

2025-05-20 16:51:13,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:14,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▎    | 5000/9304 [15:19<11:27,  6.26it/s]

2025-05-20 16:51:14,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5001/9304 [15:19<14:47,  4.85it/s]

2025-05-20 16:51:14,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5002/9304 [15:20<17:26,  4.11it/s]

2025-05-20 16:51:14,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:14,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:15,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5005/9304 [15:20<10:52,  6.59it/s]

2025-05-20 16:51:15,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5006/9304 [15:20<10:19,  6.93it/s]

2025-05-20 16:51:15,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5007/9304 [15:20<11:34,  6.19it/s]

2025-05-20 16:51:15,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5008/9304 [15:20<11:20,  6.31it/s]

2025-05-20 16:51:15,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5009/9304 [15:20<10:38,  6.73it/s]

2025-05-20 16:51:15,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5010/9304 [15:21<12:09,  5.88it/s]

2025-05-20 16:51:16,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5011/9304 [15:21<15:15,  4.69it/s]

2025-05-20 16:51:16,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5012/9304 [15:21<15:57,  4.48it/s]

2025-05-20 16:51:16,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5013/9304 [15:21<13:33,  5.27it/s]

2025-05-20 16:51:16,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:16,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5015/9304 [15:22<13:06,  5.45it/s]

2025-05-20 16:51:16,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:17,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5017/9304 [15:22<10:59,  6.50it/s]

2025-05-20 16:51:17,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:17,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5019/9304 [15:22<13:13,  5.40it/s]

2025-05-20 16:51:17,664 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:17,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5021/9304 [15:23<11:05,  6.44it/s]

2025-05-20 16:51:17,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5022/9304 [15:23<11:01,  6.47it/s]

2025-05-20 16:51:18,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:18,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:18,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5023/9304 [15:23<14:41,  4.86it/s]

2025-05-20 16:51:18,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:18,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5027/9304 [15:23<09:14,  7.71it/s]

2025-05-20 16:51:18,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:18,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5028/9304 [15:24<13:30,  5.28it/s]

2025-05-20 16:51:19,474 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5030/9304 [15:24<13:37,  5.23it/s]

2025-05-20 16:51:19,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:19,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5032/9304 [15:24<10:30,  6.78it/s]

2025-05-20 16:51:19,748 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:19,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5034/9304 [15:25<10:03,  7.08it/s]

2025-05-20 16:51:19,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:19,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:20,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5037/9304 [15:25<10:08,  7.02it/s]

2025-05-20 16:51:20,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5038/9304 [15:25<11:44,  6.06it/s]

2025-05-20 16:51:20,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:21,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:21,116 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5040/9304 [15:26<15:12,  4.67it/s]

2025-05-20 16:51:21,199 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:21,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5043/9304 [15:26<10:03,  7.07it/s]

2025-05-20 16:51:21,310 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:21,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:21,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5046/9304 [15:26<08:33,  8.29it/s]

2025-05-20 16:51:22,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:22,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5048/9304 [15:27<15:09,  4.68it/s]

2025-05-20 16:51:22,524 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:22,559 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:22,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5051/9304 [15:27<10:46,  6.58it/s]

2025-05-20 16:51:22,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:22,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5053/9304 [15:28<09:37,  7.36it/s]

2025-05-20 16:51:22,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:22,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5055/9304 [15:28<08:36,  8.23it/s]

2025-05-20 16:51:23,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:23,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5057/9304 [15:28<12:59,  5.45it/s]

2025-05-20 16:51:23,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5058/9304 [15:29<14:17,  4.95it/s]

2025-05-20 16:51:24,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5059/9304 [15:29<14:28,  4.89it/s]

2025-05-20 16:51:24,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:24,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:24,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:24,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5063/9304 [15:29<07:54,  8.94it/s]

2025-05-20 16:51:24,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:24,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5065/9304 [15:29<07:50,  9.01it/s]

2025-05-20 16:51:24,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:25,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5067/9304 [15:30<12:40,  5.57it/s]

2025-05-20 16:51:25,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:25,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5069/9304 [15:30<12:39,  5.57it/s]

2025-05-20 16:51:25,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:25,791 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 54%|█████▍    | 5070/9304 [15:31<13:24,  5.26it/s]

2025-05-20 16:51:25,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:26,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5073/9304 [15:31<10:43,  6.57it/s]

2025-05-20 16:51:26,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:26,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:26,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5076/9304 [15:31<11:15,  6.26it/s]

2025-05-20 16:51:27,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5077/9304 [15:32<13:50,  5.09it/s]

2025-05-20 16:51:27,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5078/9304 [15:32<12:57,  5.43it/s]

2025-05-20 16:51:27,180 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:27,270 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5080/9304 [15:32<09:58,  7.05it/s]

2025-05-20 16:51:27,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:27,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5081/9304 [15:32<11:01,  6.38it/s]

2025-05-20 16:51:27,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5083/9304 [15:32<09:16,  7.59it/s]

2025-05-20 16:51:27,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5084/9304 [15:33<10:25,  6.74it/s]

2025-05-20 16:51:28,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5085/9304 [15:33<12:01,  5.84it/s]

2025-05-20 16:51:28,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5086/9304 [15:33<14:48,  4.75it/s]

2025-05-20 16:51:28,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:28,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5087/9304 [15:34<18:34,  3.78it/s]

2025-05-20 16:51:29,023 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5089/9304 [15:34<12:54,  5.44it/s]

2025-05-20 16:51:29,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:29,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:29,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5091/9304 [15:34<12:24,  5.66it/s]

2025-05-20 16:51:29,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5093/9304 [15:34<09:52,  7.11it/s]

2025-05-20 16:51:29,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:29,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5094/9304 [15:35<11:54,  5.89it/s]

2025-05-20 16:51:30,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5096/9304 [15:35<13:59,  5.01it/s]

2025-05-20 16:51:30,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5097/9304 [15:35<14:02,  4.99it/s]

2025-05-20 16:51:30,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:30,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5099/9304 [15:36<11:54,  5.89it/s]

2025-05-20 16:51:30,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5100/9304 [15:36<12:22,  5.66it/s]

2025-05-20 16:51:30,953 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:31,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5102/9304 [15:36<11:33,  6.06it/s]

2025-05-20 16:51:31,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5103/9304 [15:36<13:31,  5.17it/s]

2025-05-20 16:51:31,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5104/9304 [15:37<14:16,  4.90it/s]

2025-05-20 16:51:31,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5105/9304 [15:37<14:13,  4.92it/s]

2025-05-20 16:51:32,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:32,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5107/9304 [15:37<09:58,  7.01it/s]

2025-05-20 16:51:32,418 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:32,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5108/9304 [15:37<13:28,  5.19it/s]

2025-05-20 16:51:32,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5110/9304 [15:38<12:39,  5.52it/s]

2025-05-20 16:51:32,790 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:32,871 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:33,147 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5113/9304 [15:38<10:49,  6.45it/s]

2025-05-20 16:51:33,359 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5114/9304 [15:38<11:35,  6.03it/s]

2025-05-20 16:51:33,423 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:33,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5116/9304 [15:39<11:48,  5.91it/s]

2025-05-20 16:51:33,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▍    | 5117/9304 [15:39<12:02,  5.79it/s]

2025-05-20 16:51:33,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:34,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5119/9304 [15:39<10:40,  6.53it/s]

2025-05-20 16:51:34,249 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5120/9304 [15:39<10:03,  6.93it/s]

2025-05-20 16:51:34,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5121/9304 [15:40<17:30,  3.98it/s]

2025-05-20 16:51:34,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:35,050 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:35,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5123/9304 [15:40<13:14,  5.26it/s]

2025-05-20 16:51:35,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:35,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:35,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5127/9304 [15:40<09:45,  7.13it/s]

2025-05-20 16:51:35,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:35,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5129/9304 [15:41<10:26,  6.67it/s]

2025-05-20 16:51:36,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5130/9304 [15:41<14:23,  4.83it/s]

2025-05-20 16:51:36,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:36,371 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:36,513 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5133/9304 [15:41<10:38,  6.53it/s]

2025-05-20 16:51:36,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5134/9304 [15:42<10:57,  6.34it/s]

2025-05-20 16:51:36,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5135/9304 [15:42<10:57,  6.34it/s]

2025-05-20 16:51:37,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:37,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:37,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5137/9304 [15:42<13:44,  5.05it/s]

2025-05-20 16:51:37,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:37,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5140/9304 [15:42<08:21,  8.31it/s]

2025-05-20 16:51:37,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:38,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5142/9304 [15:43<10:56,  6.34it/s]

2025-05-20 16:51:38,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5143/9304 [15:43<11:13,  6.18it/s]

2025-05-20 16:51:38,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:38,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5145/9304 [15:43<11:26,  6.06it/s]

2025-05-20 16:51:38,864 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:38,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5146/9304 [15:44<15:57,  4.34it/s]

2025-05-20 16:51:39,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:39,288 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5147/9304 [15:44<16:52,  4.11it/s]

2025-05-20 16:51:39,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:39,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5149/9304 [15:44<13:42,  5.05it/s]

2025-05-20 16:51:39,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5151/9304 [15:45<11:30,  6.01it/s]

2025-05-20 16:51:39,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5153/9304 [15:45<08:17,  8.34it/s]

2025-05-20 16:51:39,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:40,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5155/9304 [15:45<09:00,  7.68it/s]

2025-05-20 16:51:41,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:41,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5156/9304 [15:46<23:42,  2.91it/s]

2025-05-20 16:51:41,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:41,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5158/9304 [15:47<23:09,  2.98it/s]

2025-05-20 16:51:41,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:41,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5159/9304 [15:47<22:50,  3.02it/s]

2025-05-20 16:51:41,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5160/9304 [15:47<19:25,  3.55it/s]

2025-05-20 16:51:41,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:41,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5161/9304 [15:48<18:55,  3.65it/s]

2025-05-20 16:51:42,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 55%|█████▌    | 5163/9304 [15:49<26:14,  2.63it/s]

2025-05-20 16:51:43,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:43,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5164/9304 [15:49<21:12,  3.25it/s]

2025-05-20 16:51:43,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5167/9304 [15:50<20:38,  3.34it/s]

2025-05-20 16:51:44,841 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:44,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5169/9304 [15:50<15:40,  4.40it/s]

2025-05-20 16:51:45,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:45,369 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5170/9304 [15:50<16:57,  4.06it/s]

2025-05-20 16:51:45,401 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5171/9304 [15:50<14:56,  4.61it/s]

2025-05-20 16:51:45,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5174/9304 [15:50<08:22,  8.22it/s]

2025-05-20 16:51:45,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:46,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5176/9304 [15:51<11:55,  5.77it/s]

2025-05-20 16:51:46,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5177/9304 [15:51<12:25,  5.54it/s]

2025-05-20 16:51:46,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:46,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5179/9304 [15:52<12:31,  5.49it/s]

2025-05-20 16:51:47,051 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:47,108 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5180/9304 [15:52<14:16,  4.81it/s]

2025-05-20 16:51:47,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:47,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5183/9304 [15:52<10:28,  6.56it/s]

2025-05-20 16:51:47,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:48,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5185/9304 [15:53<18:11,  3.77it/s]

2025-05-20 16:51:48,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:48,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5187/9304 [15:53<14:18,  4.79it/s]

2025-05-20 16:51:48,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:48,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5188/9304 [15:54<13:11,  5.20it/s]

2025-05-20 16:51:48,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:48,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:48,807 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5191/9304 [15:54<08:39,  7.92it/s]

2025-05-20 16:51:48,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5193/9304 [15:54<07:36,  9.00it/s]

2025-05-20 16:51:48,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:50,037 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5195/9304 [15:55<16:23,  4.18it/s]

2025-05-20 16:51:50,253 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5196/9304 [15:55<15:55,  4.30it/s]

2025-05-20 16:51:50,361 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5197/9304 [15:55<14:17,  4.79it/s]

2025-05-20 16:51:50,419 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:50,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5199/9304 [15:55<10:41,  6.39it/s]

2025-05-20 16:51:50,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:50,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5201/9304 [15:56<09:29,  7.21it/s]

2025-05-20 16:51:50,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:50,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5203/9304 [15:56<09:44,  7.02it/s]

2025-05-20 16:51:51,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5204/9304 [15:56<12:12,  5.60it/s]

2025-05-20 16:51:51,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:51,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5205/9304 [15:57<16:51,  4.05it/s]

2025-05-20 16:51:51,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:52,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5206/9304 [15:57<19:10,  3.56it/s]

2025-05-20 16:51:52,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5208/9304 [15:57<16:37,  4.10it/s]

2025-05-20 16:51:52,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:52,425 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5209/9304 [15:58<23:02,  2.96it/s]

2025-05-20 16:51:52,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5210/9304 [15:59<38:40,  1.76it/s]

2025-05-20 16:51:53,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5211/9304 [16:00<38:16,  1.78it/s]

2025-05-20 16:51:53,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5212/9304 [16:00<32:22,  2.11it/s]

2025-05-20 16:51:53,818 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:54,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5213/9304 [16:00<30:35,  2.23it/s]

2025-05-20 16:51:54,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5214/9304 [16:01<39:05,  1.74it/s]

2025-05-20 16:51:55,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5215/9304 [16:02<36:17,  1.88it/s]

2025-05-20 16:51:56,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5217/9304 [16:04<48:28,  1.41it/s]

2025-05-20 16:51:56,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:57,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5219/9304 [16:04<29:37,  2.30it/s]

2025-05-20 16:51:57,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5220/9304 [16:04<32:16,  2.11it/s]

2025-05-20 16:51:58,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5221/9304 [16:05<36:46,  1.85it/s]

2025-05-20 16:51:58,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:51:59,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5222/9304 [16:06<45:31,  1.49it/s]

2025-05-20 16:52:00,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:00,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:00,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5224/9304 [16:07<35:04,  1.94it/s]

2025-05-20 16:52:00,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5227/9304 [16:07<19:25,  3.50it/s]

2025-05-20 16:52:01,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5229/9304 [16:07<14:27,  4.70it/s]

2025-05-20 16:52:02,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5231/9304 [16:07<11:27,  5.92it/s]

2025-05-20 16:52:02,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:02,825 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▌    | 5233/9304 [16:08<13:42,  4.95it/s]

2025-05-20 16:52:03,678 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5234/9304 [16:09<21:40,  3.13it/s]

2025-05-20 16:52:03,730 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:03,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5235/9304 [16:09<20:09,  3.36it/s]

2025-05-20 16:52:03,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:04,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5238/9304 [16:09<13:58,  4.85it/s]

2025-05-20 16:52:04,250 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:04,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:04,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5240/9304 [16:09<12:31,  5.41it/s]

2025-05-20 16:52:04,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:04,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5243/9304 [16:10<09:39,  7.01it/s]

2025-05-20 16:52:05,431 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5244/9304 [16:10<15:57,  4.24it/s]

2025-05-20 16:52:05,616 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5245/9304 [16:10<15:13,  4.44it/s]

2025-05-20 16:52:05,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:05,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5247/9304 [16:11<11:28,  5.89it/s]

2025-05-20 16:52:05,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5248/9304 [16:11<11:23,  5.94it/s]

2025-05-20 16:52:05,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:06,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5250/9304 [16:11<11:20,  5.95it/s]

2025-05-20 16:52:06,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:06,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5252/9304 [16:11<09:01,  7.48it/s]

2025-05-20 16:52:06,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:06,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5254/9304 [16:12<11:12,  6.02it/s]

2025-05-20 16:52:07,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5255/9304 [16:12<11:41,  5.77it/s]

2025-05-20 16:52:07,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 56%|█████▋    | 5256/9304 [16:12<11:22,  5.94it/s]

2025-05-20 16:52:07,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5257/9304 [16:12<14:31,  4.64it/s]

2025-05-20 16:52:07,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:07,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5259/9304 [16:13<14:19,  4.71it/s]

2025-05-20 16:52:08,051 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:08,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:08,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5262/9304 [16:13<11:43,  5.75it/s]

2025-05-20 16:52:08,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5263/9304 [16:14<16:10,  4.17it/s]

2025-05-20 16:52:08,979 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:09,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:09,269 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5266/9304 [16:14<12:52,  5.23it/s]

2025-05-20 16:52:09,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:09,421 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5268/9304 [16:14<10:13,  6.58it/s]

2025-05-20 16:52:09,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:09,596 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5270/9304 [16:14<09:02,  7.43it/s]

2025-05-20 16:52:09,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5271/9304 [16:15<11:44,  5.73it/s]

2025-05-20 16:52:10,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:10,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5273/9304 [16:15<11:30,  5.84it/s]

2025-05-20 16:52:10,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5274/9304 [16:15<13:55,  4.83it/s]

2025-05-20 16:52:10,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:10,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:10,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5277/9304 [16:16<10:41,  6.28it/s]

2025-05-20 16:52:11,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:11,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5279/9304 [16:16<08:31,  7.87it/s]

2025-05-20 16:52:11,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:11,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:11,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5282/9304 [16:17<11:13,  5.97it/s]

2025-05-20 16:52:11,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5283/9304 [16:17<12:03,  5.56it/s]

2025-05-20 16:52:12,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:12,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5285/9304 [16:17<11:13,  5.97it/s]

2025-05-20 16:52:12,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:12,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5287/9304 [16:17<10:20,  6.47it/s]

2025-05-20 16:52:12,700 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5288/9304 [16:18<10:29,  6.37it/s]

2025-05-20 16:52:12,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:12,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5290/9304 [16:18<09:13,  7.26it/s]

2025-05-20 16:52:12,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:13,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5292/9304 [16:18<07:43,  8.65it/s]

2025-05-20 16:52:13,433 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5293/9304 [16:18<11:14,  5.95it/s]

2025-05-20 16:52:13,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5294/9304 [16:19<15:49,  4.22it/s]

2025-05-20 16:52:14,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5295/9304 [16:19<14:33,  4.59it/s]

2025-05-20 16:52:14,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:14,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:14,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:14,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5298/9304 [16:19<08:45,  7.62it/s]

2025-05-20 16:52:14,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5300/9304 [16:19<07:11,  9.29it/s]

2025-05-20 16:52:14,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:14,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5302/9304 [16:20<10:37,  6.28it/s]

2025-05-20 16:52:15,032 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:15,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5304/9304 [16:20<12:39,  5.26it/s]

2025-05-20 16:52:15,576 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5305/9304 [16:20<12:35,  5.29it/s]

2025-05-20 16:52:15,637 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:15,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:15,696 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5308/9304 [16:21<08:13,  8.10it/s]

2025-05-20 16:52:15,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:15,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5310/9304 [16:21<07:36,  8.75it/s]

2025-05-20 16:52:15,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:16,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5312/9304 [16:21<10:03,  6.62it/s]

2025-05-20 16:52:16,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5313/9304 [16:22<12:22,  5.37it/s]

2025-05-20 16:52:17,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5314/9304 [16:22<13:51,  4.80it/s]

2025-05-20 16:52:17,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5315/9304 [16:22<13:09,  5.05it/s]

2025-05-20 16:52:17,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:17,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5317/9304 [16:22<11:37,  5.72it/s]

2025-05-20 16:52:17,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:17,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5319/9304 [16:22<09:12,  7.21it/s]

2025-05-20 16:52:17,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:17,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5321/9304 [16:23<07:48,  8.50it/s]

2025-05-20 16:52:17,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:18,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5323/9304 [16:23<10:38,  6.23it/s]

2025-05-20 16:52:18,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5324/9304 [16:23<11:53,  5.58it/s]

2025-05-20 16:52:18,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5325/9304 [16:24<12:37,  5.25it/s]

2025-05-20 16:52:19,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5326/9304 [16:24<14:03,  4.72it/s]

2025-05-20 16:52:19,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:19,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:19,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:19,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:19,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5329/9304 [16:24<08:19,  7.95it/s]

2025-05-20 16:52:19,172 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:19,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5333/9304 [16:25<09:18,  7.12it/s]

2025-05-20 16:52:19,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5334/9304 [16:25<09:03,  7.30it/s]

2025-05-20 16:52:20,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5335/9304 [16:25<10:50,  6.11it/s]

2025-05-20 16:52:20,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5336/9304 [16:25<11:59,  5.51it/s]

2025-05-20 16:52:20,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:20,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5337/9304 [16:25<11:51,  5.58it/s]

2025-05-20 16:52:20,612 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:20,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5340/9304 [16:26<07:49,  8.44it/s]

2025-05-20 16:52:20,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:21,209 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5342/9304 [16:26<10:13,  6.46it/s]

2025-05-20 16:52:21,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5343/9304 [16:26<09:37,  6.86it/s]

2025-05-20 16:52:21,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:21,821 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5345/9304 [16:27<11:57,  5.52it/s]

2025-05-20 16:52:21,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:22,118 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:22,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5347/9304 [16:27<11:21,  5.81it/s]

2025-05-20 16:52:22,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 57%|█████▋    | 5349/9304 [16:27<08:52,  7.43it/s]

2025-05-20 16:52:22,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:22,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5351/9304 [16:27<07:57,  8.28it/s]

2025-05-20 16:52:22,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:22,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5353/9304 [16:28<09:42,  6.78it/s]

2025-05-20 16:52:23,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5354/9304 [16:28<10:09,  6.48it/s]

2025-05-20 16:52:23,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5355/9304 [16:28<11:53,  5.53it/s]

2025-05-20 16:52:23,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:23,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5357/9304 [16:28<10:41,  6.16it/s]

2025-05-20 16:52:23,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:23,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5359/9304 [16:29<09:36,  6.84it/s]

2025-05-20 16:52:23,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:24,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5361/9304 [16:29<08:51,  7.42it/s]

2025-05-20 16:52:24,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5362/9304 [16:29<12:27,  5.27it/s]

2025-05-20 16:52:24,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:24,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5364/9304 [16:29<09:52,  6.66it/s]

2025-05-20 16:52:24,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:24,700 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5366/9304 [16:30<07:44,  8.48it/s]

2025-05-20 16:52:25,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:25,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5368/9304 [16:30<14:59,  4.38it/s]

2025-05-20 16:52:25,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:25,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5370/9304 [16:31<12:03,  5.44it/s]

2025-05-20 16:52:25,866 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:26,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5372/9304 [16:31<12:40,  5.17it/s]

2025-05-20 16:52:26,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5373/9304 [16:31<13:01,  5.03it/s]

2025-05-20 16:52:26,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:26,772 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5375/9304 [16:32<12:11,  5.37it/s]

2025-05-20 16:52:27,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:27,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5376/9304 [16:32<14:17,  4.58it/s]

2025-05-20 16:52:27,172 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:27,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:27,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5380/9304 [16:32<08:43,  7.49it/s]

2025-05-20 16:52:27,599 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5381/9304 [16:32<09:50,  6.65it/s]

2025-05-20 16:52:28,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5382/9304 [16:33<12:51,  5.08it/s]

2025-05-20 16:52:28,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:28,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5384/9304 [16:33<14:14,  4.59it/s]

2025-05-20 16:52:28,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:28,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:28,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5387/9304 [16:34<09:41,  6.74it/s]

2025-05-20 16:52:28,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:29,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5389/9304 [16:34<10:43,  6.08it/s]

2025-05-20 16:52:29,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:29,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5391/9304 [16:34<11:09,  5.84it/s]

2025-05-20 16:52:29,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:29,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5393/9304 [16:34<09:26,  6.91it/s]

2025-05-20 16:52:30,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5394/9304 [16:35<13:00,  5.01it/s]

2025-05-20 16:52:30,388 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5395/9304 [16:35<14:20,  4.54it/s]

2025-05-20 16:52:30,412 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:30,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:30,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5398/9304 [16:35<08:48,  7.40it/s]

2025-05-20 16:52:30,711 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:30,871 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5400/9304 [16:36<09:51,  6.60it/s]

2025-05-20 16:52:31,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:31,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:31,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5402/9304 [16:36<08:59,  7.23it/s]

2025-05-20 16:52:31,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5404/9304 [16:36<10:06,  6.43it/s]

2025-05-20 16:52:31,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5405/9304 [16:36<09:36,  6.77it/s]

2025-05-20 16:52:31,730 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5406/9304 [16:37<09:28,  6.85it/s]

2025-05-20 16:52:31,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5407/9304 [16:37<10:52,  5.97it/s]

2025-05-20 16:52:32,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5408/9304 [16:37<11:21,  5.72it/s]

2025-05-20 16:52:32,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5409/9304 [16:37<10:18,  6.30it/s]

2025-05-20 16:52:32,567 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5410/9304 [16:37<12:34,  5.16it/s]

2025-05-20 16:52:32,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5411/9304 [16:38<14:03,  4.62it/s]

2025-05-20 16:52:32,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:33,250 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5413/9304 [16:38<13:37,  4.76it/s]

2025-05-20 16:52:33,415 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5414/9304 [16:38<13:01,  4.98it/s]

2025-05-20 16:52:33,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:33,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5415/9304 [16:38<11:35,  5.59it/s]

2025-05-20 16:52:33,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5417/9304 [16:39<09:56,  6.52it/s]

2025-05-20 16:52:33,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5418/9304 [16:39<10:44,  6.03it/s]

2025-05-20 16:52:34,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5419/9304 [16:39<12:26,  5.21it/s]

2025-05-20 16:52:34,292 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:34,365 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5421/9304 [16:39<08:52,  7.29it/s]

2025-05-20 16:52:34,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5422/9304 [16:40<11:58,  5.40it/s]

2025-05-20 16:52:34,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:34,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5424/9304 [16:40<09:15,  6.99it/s]

2025-05-20 16:52:35,269 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5425/9304 [16:40<12:54,  5.01it/s]

2025-05-20 16:52:35,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5426/9304 [16:40<13:11,  4.90it/s]

2025-05-20 16:52:35,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5427/9304 [16:41<13:23,  4.82it/s]

2025-05-20 16:52:35,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:35,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5429/9304 [16:41<10:43,  6.02it/s]

2025-05-20 16:52:36,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5430/9304 [16:41<10:45,  6.00it/s]

2025-05-20 16:52:36,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:36,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5432/9304 [16:41<08:17,  7.78it/s]

2025-05-20 16:52:36,275 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:36,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5434/9304 [16:41<09:53,  6.52it/s]

2025-05-20 16:52:37,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5435/9304 [16:42<12:47,  5.04it/s]

2025-05-20 16:52:37,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:37,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5437/9304 [16:42<10:45,  5.99it/s]

2025-05-20 16:52:37,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5438/9304 [16:42<10:44,  6.00it/s]

2025-05-20 16:52:37,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:37,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5440/9304 [16:43<10:36,  6.07it/s]

2025-05-20 16:52:37,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:37,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 58%|█████▊    | 5442/9304 [16:43<09:23,  6.85it/s]

2025-05-20 16:52:37,967 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:38,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5444/9304 [16:43<12:30,  5.14it/s]

2025-05-20 16:52:38,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:38,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5446/9304 [16:44<10:50,  5.93it/s]

2025-05-20 16:52:38,906 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5447/9304 [16:44<10:36,  6.06it/s]

2025-05-20 16:52:39,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5448/9304 [16:44<10:33,  6.09it/s]

2025-05-20 16:52:39,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:39,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5450/9304 [16:44<08:14,  7.80it/s]

2025-05-20 16:52:39,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5451/9304 [16:44<10:14,  6.27it/s]

2025-05-20 16:52:39,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:39,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:39,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5454/9304 [16:45<08:11,  7.83it/s]

2025-05-20 16:52:40,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:40,262 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:40,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5456/9304 [16:45<12:12,  5.25it/s]

2025-05-20 16:52:40,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5457/9304 [16:46<14:17,  4.49it/s]

2025-05-20 16:52:40,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:40,974 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5460/9304 [16:46<09:17,  6.89it/s]

2025-05-20 16:52:41,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:41,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5462/9304 [16:46<10:34,  6.06it/s]

2025-05-20 16:52:41,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5463/9304 [16:47<12:08,  5.27it/s]

2025-05-20 16:52:41,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5464/9304 [16:47<12:09,  5.27it/s]

2025-05-20 16:52:41,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:42,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▊    | 5466/9304 [16:47<13:18,  4.81it/s]

2025-05-20 16:52:42,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:42,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:42,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5468/9304 [16:48<12:17,  5.20it/s]

2025-05-20 16:52:42,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:42,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5471/9304 [16:48<08:16,  7.72it/s]

2025-05-20 16:52:43,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:43,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5473/9304 [16:48<10:09,  6.28it/s]

2025-05-20 16:52:43,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:43,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5475/9304 [16:49<13:55,  4.59it/s]

2025-05-20 16:52:44,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:44,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5477/9304 [16:49<11:03,  5.76it/s]

2025-05-20 16:52:44,172 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:44,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5479/9304 [16:49<09:14,  6.89it/s]

2025-05-20 16:52:44,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:44,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5481/9304 [16:49<09:52,  6.45it/s]

2025-05-20 16:52:44,747 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5482/9304 [16:50<09:17,  6.86it/s]

2025-05-20 16:52:44,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5483/9304 [16:50<09:17,  6.86it/s]

2025-05-20 16:52:44,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:45,423 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5485/9304 [16:50<12:09,  5.24it/s]

2025-05-20 16:52:45,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:45,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5487/9304 [16:50<09:29,  6.70it/s]

2025-05-20 16:52:45,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5488/9304 [16:51<11:35,  5.48it/s]

2025-05-20 16:52:45,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5489/9304 [16:51<10:41,  5.95it/s]

2025-05-20 16:52:46,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:46,108 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5491/9304 [16:51<08:04,  7.88it/s]

2025-05-20 16:52:46,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:46,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5493/9304 [16:51<09:38,  6.59it/s]

2025-05-20 16:52:46,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5494/9304 [16:52<09:47,  6.49it/s]

2025-05-20 16:52:47,126 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5495/9304 [16:52<14:13,  4.46it/s]

2025-05-20 16:52:47,336 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5496/9304 [16:52<13:36,  4.66it/s]

2025-05-20 16:52:47,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5497/9304 [16:52<12:06,  5.24it/s]

2025-05-20 16:52:47,492 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:47,576 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5499/9304 [16:52<08:35,  7.38it/s]

2025-05-20 16:52:47,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5500/9304 [16:53<10:53,  5.82it/s]

2025-05-20 16:52:48,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5501/9304 [16:53<11:35,  5.47it/s]

2025-05-20 16:52:48,150 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:48,209 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5503/9304 [16:53<09:19,  6.80it/s]

2025-05-20 16:52:48,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5504/9304 [16:53<10:25,  6.07it/s]

2025-05-20 16:52:48,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5505/9304 [16:54<13:37,  4.65it/s]

2025-05-20 16:52:48,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:48,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:48,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5507/9304 [16:54<09:20,  6.77it/s]

2025-05-20 16:52:49,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5509/9304 [16:54<07:27,  8.47it/s]

2025-05-20 16:52:49,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:49,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5511/9304 [16:54<10:19,  6.13it/s]

2025-05-20 16:52:49,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:49,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:49,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5514/9304 [16:55<08:17,  7.63it/s]

2025-05-20 16:52:50,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5515/9304 [16:55<12:27,  5.07it/s]

2025-05-20 16:52:50,418 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:50,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:50,852 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5518/9304 [16:56<11:10,  5.64it/s]

2025-05-20 16:52:50,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5519/9304 [16:56<10:24,  6.06it/s]

2025-05-20 16:52:51,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5520/9304 [16:56<09:38,  6.54it/s]

2025-05-20 16:52:51,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:51,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:51,094 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:51,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:51,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5525/9304 [16:57<08:43,  7.22it/s]

2025-05-20 16:52:51,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5526/9304 [16:57<09:36,  6.55it/s]

2025-05-20 16:52:52,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5527/9304 [16:57<09:18,  6.77it/s]

2025-05-20 16:52:52,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:52,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5529/9304 [16:57<07:52,  7.98it/s]

2025-05-20 16:52:52,417 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5530/9304 [16:57<08:50,  7.11it/s]

2025-05-20 16:52:52,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5531/9304 [16:57<08:19,  7.55it/s]

2025-05-20 16:52:52,621 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5532/9304 [16:57<07:52,  7.99it/s]

2025-05-20 16:52:52,684 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:53,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5534/9304 [16:58<12:54,  4.87it/s]

2025-05-20 16:52:53,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 59%|█████▉    | 5535/9304 [16:58<11:56,  5.26it/s]

2025-05-20 16:52:53,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5536/9304 [16:58<11:48,  5.32it/s]

2025-05-20 16:52:53,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5537/9304 [16:59<11:50,  5.30it/s]

2025-05-20 16:52:53,859 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:54,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5539/9304 [16:59<12:02,  5.21it/s]

2025-05-20 16:52:54,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5540/9304 [17:00<19:13,  3.26it/s]

2025-05-20 16:52:54,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:55,078 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:55,097 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5542/9304 [17:00<14:30,  4.32it/s]

2025-05-20 16:52:55,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:55,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5545/9304 [17:00<10:59,  5.70it/s]

2025-05-20 16:52:55,536 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:55,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5546/9304 [17:00<10:18,  6.07it/s]

2025-05-20 16:52:55,833 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5548/9304 [17:01<09:57,  6.28it/s]

2025-05-20 16:52:56,021 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5549/9304 [17:01<10:19,  6.07it/s]

2025-05-20 16:52:56,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:56,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5550/9304 [17:01<13:12,  4.73it/s]

2025-05-20 16:52:56,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:56,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5553/9304 [17:02<11:37,  5.38it/s]

2025-05-20 16:52:56,966 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:56,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5555/9304 [17:02<09:05,  6.88it/s]

2025-05-20 16:52:57,179 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5556/9304 [17:02<09:31,  6.56it/s]

2025-05-20 16:52:57,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5557/9304 [17:02<12:08,  5.14it/s]

2025-05-20 16:52:57,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:57,763 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5559/9304 [17:03<10:15,  6.09it/s]

2025-05-20 16:52:58,024 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5560/9304 [17:03<11:28,  5.44it/s]

2025-05-20 16:52:58,244 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5561/9304 [17:03<12:00,  5.19it/s]

2025-05-20 16:52:58,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:58,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5563/9304 [17:03<08:55,  6.98it/s]

2025-05-20 16:52:58,431 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:58,822 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5565/9304 [17:04<10:40,  5.83it/s]

2025-05-20 16:52:58,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:58,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5567/9304 [17:04<08:08,  7.65it/s]

2025-05-20 16:52:59,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:59,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5569/9304 [17:04<12:38,  4.93it/s]

2025-05-20 16:52:59,859 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5570/9304 [17:05<12:56,  4.81it/s]

2025-05-20 16:52:59,926 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:52:59,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5572/9304 [17:05<09:51,  6.30it/s]

2025-05-20 16:53:00,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:00,180 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5574/9304 [17:05<08:30,  7.31it/s]

2025-05-20 16:53:00,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:00,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5576/9304 [17:05<07:03,  8.80it/s]

2025-05-20 16:53:00,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:00,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5578/9304 [17:06<10:30,  5.91it/s]

2025-05-20 16:53:01,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5579/9304 [17:06<10:36,  5.85it/s]

2025-05-20 16:53:01,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5580/9304 [17:06<12:27,  4.98it/s]

2025-05-20 16:53:01,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:01,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|█████▉    | 5582/9304 [17:06<09:09,  6.77it/s]

2025-05-20 16:53:01,545 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:01,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5584/9304 [17:07<08:03,  7.69it/s]

2025-05-20 16:53:01,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:02,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5586/9304 [17:07<08:38,  7.17it/s]

2025-05-20 16:53:02,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5587/9304 [17:07<12:36,  4.91it/s]

2025-05-20 16:53:02,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:02,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5589/9304 [17:07<09:17,  6.66it/s]

2025-05-20 16:53:02,711 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:02,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5591/9304 [17:08<09:31,  6.50it/s]

2025-05-20 16:53:03,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5592/9304 [17:08<09:36,  6.44it/s]

2025-05-20 16:53:03,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:03,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:03,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:03,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5595/9304 [17:08<09:10,  6.74it/s]

2025-05-20 16:53:03,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5597/9304 [17:09<09:25,  6.56it/s]

2025-05-20 16:53:04,198 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5598/9304 [17:09<11:56,  5.17it/s]

2025-05-20 16:53:04,262 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:04,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:04,412 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5601/9304 [17:09<08:40,  7.11it/s]

2025-05-20 16:53:04,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5602/9304 [17:09<08:36,  7.17it/s]

2025-05-20 16:53:04,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:04,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5604/9304 [17:09<06:57,  8.86it/s]

2025-05-20 16:53:05,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:05,359 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5606/9304 [17:10<11:42,  5.27it/s]

2025-05-20 16:53:05,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5607/9304 [17:10<12:41,  4.85it/s]

2025-05-20 16:53:05,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5608/9304 [17:11<11:35,  5.31it/s]

2025-05-20 16:53:05,785 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:06,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5610/9304 [17:11<10:04,  6.11it/s]

2025-05-20 16:53:06,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5611/9304 [17:11<09:50,  6.25it/s]

2025-05-20 16:53:06,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:06,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5613/9304 [17:11<10:01,  6.13it/s]

2025-05-20 16:53:06,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5614/9304 [17:12<13:18,  4.62it/s]

2025-05-20 16:53:07,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5615/9304 [17:12<12:27,  4.93it/s]

2025-05-20 16:53:07,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:07,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5617/9304 [17:12<09:33,  6.43it/s]

2025-05-20 16:53:07,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:07,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:07,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5620/9304 [17:12<06:07, 10.04it/s]

2025-05-20 16:53:07,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:07,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5622/9304 [17:13<08:22,  7.32it/s]

2025-05-20 16:53:08,021 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:08,237 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5624/9304 [17:13<10:08,  6.04it/s]

2025-05-20 16:53:08,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:08,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5626/9304 [17:13<09:50,  6.23it/s]

2025-05-20 16:53:08,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:08,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 60%|██████    | 5628/9304 [17:14<08:11,  7.49it/s]

2025-05-20 16:53:09,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:09,630 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5630/9304 [17:14<14:22,  4.26it/s]

2025-05-20 16:53:09,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:09,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5631/9304 [17:15<13:16,  4.61it/s]

2025-05-20 16:53:09,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5633/9304 [17:15<09:57,  6.15it/s]

2025-05-20 16:53:09,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:10,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5635/9304 [17:15<08:26,  7.25it/s]

2025-05-20 16:53:10,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:10,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5637/9304 [17:16<13:41,  4.46it/s]

2025-05-20 16:53:10,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5638/9304 [17:16<12:33,  4.87it/s]

2025-05-20 16:53:11,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:11,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5640/9304 [17:16<11:05,  5.51it/s]

2025-05-20 16:53:11,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:11,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:11,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5643/9304 [17:16<07:31,  8.10it/s]

2025-05-20 16:53:11,468 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:12,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5645/9304 [17:17<11:16,  5.41it/s]

2025-05-20 16:53:12,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5646/9304 [17:17<10:34,  5.77it/s]

2025-05-20 16:53:12,490 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5647/9304 [17:17<12:08,  5.02it/s]

2025-05-20 16:53:12,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5648/9304 [17:18<12:05,  5.04it/s]

2025-05-20 16:53:12,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5649/9304 [17:18<10:59,  5.54it/s]

2025-05-20 16:53:12,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:13,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:13,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5651/9304 [17:18<09:20,  6.51it/s]

2025-05-20 16:53:13,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:13,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5654/9304 [17:18<08:47,  6.92it/s]

2025-05-20 16:53:13,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5655/9304 [17:19<10:03,  6.05it/s]

2025-05-20 16:53:13,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5656/9304 [17:19<10:44,  5.66it/s]

2025-05-20 16:53:13,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:14,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5658/9304 [17:19<13:55,  4.37it/s]

2025-05-20 16:53:14,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:14,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:14,700 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5661/9304 [17:20<09:04,  6.69it/s]

2025-05-20 16:53:14,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:15,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:15,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5663/9304 [17:20<11:08,  5.45it/s]

2025-05-20 16:53:15,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5665/9304 [17:20<09:57,  6.09it/s]

2025-05-20 16:53:15,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:15,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5667/9304 [17:21<10:27,  5.79it/s]

2025-05-20 16:53:15,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:16,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5669/9304 [17:21<09:52,  6.13it/s]

2025-05-20 16:53:16,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5670/9304 [17:21<09:38,  6.28it/s]

2025-05-20 16:53:16,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5671/9304 [17:22<13:05,  4.63it/s]

2025-05-20 16:53:16,867 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5672/9304 [17:22<13:24,  4.51it/s]

2025-05-20 16:53:17,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5673/9304 [17:22<13:51,  4.37it/s]

2025-05-20 16:53:17,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:17,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5675/9304 [17:22<09:27,  6.40it/s]

2025-05-20 16:53:17,576 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5676/9304 [17:22<12:00,  5.03it/s]

2025-05-20 16:53:17,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5677/9304 [17:23<12:06,  4.99it/s]

2025-05-20 16:53:17,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5678/9304 [17:23<11:03,  5.47it/s]

2025-05-20 16:53:18,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:18,235 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5680/9304 [17:23<09:28,  6.38it/s]

2025-05-20 16:53:18,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5681/9304 [17:24<13:43,  4.40it/s]

2025-05-20 16:53:18,743 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:18,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5683/9304 [17:24<11:08,  5.42it/s]

2025-05-20 16:53:18,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:19,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5685/9304 [17:24<09:13,  6.54it/s]

2025-05-20 16:53:19,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5686/9304 [17:24<09:42,  6.21it/s]

2025-05-20 16:53:19,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5687/9304 [17:24<09:04,  6.64it/s]

2025-05-20 16:53:19,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:19,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5688/9304 [17:24<09:29,  6.35it/s]

2025-05-20 16:53:19,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:20,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:20,213 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5691/9304 [17:25<10:49,  5.57it/s]

2025-05-20 16:53:20,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:20,454 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5694/9304 [17:25<08:13,  7.31it/s]

2025-05-20 16:53:20,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5695/9304 [17:25<08:20,  7.22it/s]

2025-05-20 16:53:20,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5696/9304 [17:26<10:12,  5.90it/s]

2025-05-20 16:53:21,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████    | 5697/9304 [17:26<10:42,  5.61it/s]

2025-05-20 16:53:21,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:21,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5699/9304 [17:26<07:54,  7.60it/s]

2025-05-20 16:53:21,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5700/9304 [17:26<07:53,  7.61it/s]

2025-05-20 16:53:21,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5701/9304 [17:26<08:30,  7.05it/s]

2025-05-20 16:53:21,713 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5702/9304 [17:27<09:05,  6.61it/s]

2025-05-20 16:53:21,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5703/9304 [17:27<10:33,  5.69it/s]

2025-05-20 16:53:22,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:22,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5704/9304 [17:27<12:10,  4.93it/s]

2025-05-20 16:53:22,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5706/9304 [17:27<08:36,  6.96it/s]

2025-05-20 16:53:22,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5707/9304 [17:27<08:48,  6.80it/s]

2025-05-20 16:53:22,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5708/9304 [17:28<10:49,  5.53it/s]

2025-05-20 16:53:22,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5709/9304 [17:28<10:03,  5.96it/s]

2025-05-20 16:53:23,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5710/9304 [17:28<10:08,  5.90it/s]

2025-05-20 16:53:23,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:23,452 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5712/9304 [17:28<10:13,  5.85it/s]

2025-05-20 16:53:23,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:23,664 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5714/9304 [17:28<08:40,  6.90it/s]

2025-05-20 16:53:23,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:24,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5716/9304 [17:29<10:27,  5.72it/s]

2025-05-20 16:53:24,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:24,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5718/9304 [17:29<08:22,  7.13it/s]

2025-05-20 16:53:24,341 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:24,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5720/9304 [17:29<09:17,  6.43it/s]

2025-05-20 16:53:24,772 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 61%|██████▏   | 5721/9304 [17:30<09:06,  6.56it/s]

2025-05-20 16:53:24,886 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5722/9304 [17:30<08:28,  7.04it/s]

2025-05-20 16:53:24,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:24,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:25,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5725/9304 [17:30<05:56, 10.05it/s]

2025-05-20 16:53:25,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:25,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5727/9304 [17:31<11:50,  5.03it/s]

2025-05-20 16:53:25,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:26,150 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5729/9304 [17:31<10:46,  5.53it/s]

2025-05-20 16:53:26,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:26,237 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:26,401 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5732/9304 [17:31<08:24,  7.08it/s]

2025-05-20 16:53:26,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5733/9304 [17:31<08:11,  7.27it/s]

2025-05-20 16:53:26,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:27,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5735/9304 [17:32<10:12,  5.83it/s]

2025-05-20 16:53:27,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5736/9304 [17:32<13:44,  4.33it/s]

2025-05-20 16:53:27,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:27,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:27,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5739/9304 [17:32<08:57,  6.64it/s]

2025-05-20 16:53:27,797 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:27,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:27,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5741/9304 [17:33<08:11,  7.25it/s]

2025-05-20 16:53:27,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:27,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:28,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:28,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5745/9304 [17:34<11:15,  5.27it/s]

2025-05-20 16:53:29,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5747/9304 [17:34<10:32,  5.62it/s]

2025-05-20 16:53:29,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:29,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5749/9304 [17:34<08:35,  6.90it/s]

2025-05-20 16:53:29,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:29,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5751/9304 [17:35<10:11,  5.81it/s]

2025-05-20 16:53:29,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:29,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5753/9304 [17:35<08:20,  7.09it/s]

2025-05-20 16:53:29,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:30,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5755/9304 [17:35<10:22,  5.70it/s]

2025-05-20 16:53:30,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:30,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5757/9304 [17:36<10:54,  5.42it/s]

2025-05-20 16:53:30,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:30,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5759/9304 [17:36<09:01,  6.55it/s]

2025-05-20 16:53:31,181 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5760/9304 [17:36<09:41,  6.09it/s]

2025-05-20 16:53:31,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:31,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5762/9304 [17:36<09:21,  6.31it/s]

2025-05-20 16:53:31,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5763/9304 [17:37<12:07,  4.86it/s]

2025-05-20 16:53:32,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5764/9304 [17:37<11:10,  5.28it/s]

2025-05-20 16:53:32,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5765/9304 [17:37<11:00,  5.36it/s]

2025-05-20 16:53:32,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5766/9304 [17:37<09:50,  6.00it/s]

2025-05-20 16:53:32,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5767/9304 [17:37<11:21,  5.19it/s]

2025-05-20 16:53:32,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:32,764 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5769/9304 [17:38<09:06,  6.47it/s]

2025-05-20 16:53:32,833 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:33,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5771/9304 [17:38<08:52,  6.63it/s]

2025-05-20 16:53:33,069 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:33,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5773/9304 [17:38<09:12,  6.39it/s]

2025-05-20 16:53:33,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5774/9304 [17:38<10:37,  5.53it/s]

2025-05-20 16:53:33,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5775/9304 [17:39<11:14,  5.23it/s]

2025-05-20 16:53:34,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5776/9304 [17:39<10:44,  5.48it/s]

2025-05-20 16:53:34,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5777/9304 [17:39<09:40,  6.08it/s]

2025-05-20 16:53:34,215 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:34,670 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5779/9304 [17:39<11:52,  4.95it/s]

2025-05-20 16:53:34,698 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:34,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:34,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5782/9304 [17:40<08:32,  6.88it/s]

2025-05-20 16:53:35,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5783/9304 [17:40<10:48,  5.43it/s]

2025-05-20 16:53:35,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5784/9304 [17:40<11:34,  5.07it/s]

2025-05-20 16:53:35,575 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:35,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5786/9304 [17:40<08:21,  7.02it/s]

2025-05-20 16:53:35,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5787/9304 [17:41<07:55,  7.40it/s]

2025-05-20 16:53:35,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:36,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5789/9304 [17:41<10:09,  5.76it/s]

2025-05-20 16:53:36,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5790/9304 [17:41<09:45,  6.00it/s]

2025-05-20 16:53:36,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5791/9304 [17:41<11:55,  4.91it/s]

2025-05-20 16:53:36,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5792/9304 [17:42<10:56,  5.35it/s]

2025-05-20 16:53:37,013 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:37,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5793/9304 [17:42<11:14,  5.21it/s]

2025-05-20 16:53:37,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5795/9304 [17:42<08:37,  6.78it/s]

2025-05-20 16:53:37,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5796/9304 [17:42<09:30,  6.14it/s]

2025-05-20 16:53:37,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5797/9304 [17:43<11:44,  4.98it/s]

2025-05-20 16:53:38,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5798/9304 [17:43<12:59,  4.50it/s]

2025-05-20 16:53:38,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:38,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:38,262 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5801/9304 [17:43<08:48,  6.63it/s]

2025-05-20 16:53:38,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5802/9304 [17:43<11:14,  5.19it/s]

2025-05-20 16:53:38,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:38,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5804/9304 [17:44<09:12,  6.34it/s]

2025-05-20 16:53:39,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5805/9304 [17:44<09:40,  6.03it/s]

2025-05-20 16:53:39,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:39,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5807/9304 [17:44<08:18,  7.02it/s]

2025-05-20 16:53:39,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5808/9304 [17:44<10:27,  5.57it/s]

2025-05-20 16:53:39,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:39,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5810/9304 [17:45<08:09,  7.14it/s]

2025-05-20 16:53:39,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5811/9304 [17:45<08:59,  6.48it/s]

2025-05-20 16:53:40,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5812/9304 [17:45<11:45,  4.95it/s]

2025-05-20 16:53:40,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:40,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 62%|██████▏   | 5814/9304 [17:45<10:28,  5.55it/s]

2025-05-20 16:53:40,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:40,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5816/9304 [17:46<08:49,  6.59it/s]

2025-05-20 16:53:40,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:40,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5817/9304 [17:46<08:27,  6.87it/s]

2025-05-20 16:53:41,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5819/9304 [17:46<09:21,  6.21it/s]

2025-05-20 16:53:41,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:41,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:41,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5821/9304 [17:47<12:58,  4.47it/s]

2025-05-20 16:53:41,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:42,213 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5824/9304 [17:47<09:47,  5.93it/s]

2025-05-20 16:53:42,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:42,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5826/9304 [17:47<07:50,  7.39it/s]

2025-05-20 16:53:42,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:42,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5828/9304 [17:48<08:40,  6.67it/s]

2025-05-20 16:53:42,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5829/9304 [17:48<08:12,  7.06it/s]

2025-05-20 16:53:42,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5830/9304 [17:48<07:53,  7.34it/s]

2025-05-20 16:53:43,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5831/9304 [17:48<12:34,  4.60it/s]

2025-05-20 16:53:43,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5832/9304 [17:49<13:29,  4.29it/s]

2025-05-20 16:53:43,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5833/9304 [17:49<11:58,  4.83it/s]

2025-05-20 16:53:43,901 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:43,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:44,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5836/9304 [17:49<08:20,  6.93it/s]

2025-05-20 16:53:44,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5837/9304 [17:49<09:45,  5.92it/s]

2025-05-20 16:53:44,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:44,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:44,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5840/9304 [17:50<08:11,  7.04it/s]

2025-05-20 16:53:45,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5841/9304 [17:50<13:57,  4.14it/s]

2025-05-20 16:53:45,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:45,536 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5843/9304 [17:50<10:49,  5.33it/s]

2025-05-20 16:53:45,619 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:45,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5845/9304 [17:50<08:16,  6.96it/s]

2025-05-20 16:53:45,739 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:45,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5847/9304 [17:51<06:48,  8.47it/s]

2025-05-20 16:53:45,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:45,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5849/9304 [17:51<06:07,  9.39it/s]

2025-05-20 16:53:46,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:47,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5851/9304 [17:52<15:11,  3.79it/s]

2025-05-20 16:53:47,338 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5852/9304 [17:52<14:05,  4.08it/s]

2025-05-20 16:53:47,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5853/9304 [17:52<13:05,  4.39it/s]

2025-05-20 16:53:47,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:47,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:47,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5856/9304 [17:52<08:13,  6.99it/s]

2025-05-20 16:53:47,648 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:47,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:48,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5859/9304 [17:53<08:32,  6.73it/s]

2025-05-20 16:53:48,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:48,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:48,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5861/9304 [17:54<12:53,  4.45it/s]

2025-05-20 16:53:49,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5863/9304 [17:54<10:36,  5.41it/s]

2025-05-20 16:53:49,147 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:49,277 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5865/9304 [17:54<08:52,  6.46it/s]

2025-05-20 16:53:49,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:50,071 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5867/9304 [17:55<12:53,  4.45it/s]

2025-05-20 16:53:50,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:50,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5869/9304 [17:55<10:17,  5.57it/s]

2025-05-20 16:53:50,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5870/9304 [17:55<11:41,  4.89it/s]

2025-05-20 16:53:50,562 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:50,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:50,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5873/9304 [17:56<09:31,  6.01it/s]

2025-05-20 16:53:51,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5874/9304 [17:56<09:29,  6.03it/s]

2025-05-20 16:53:51,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:51,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5876/9304 [17:56<09:23,  6.09it/s]

2025-05-20 16:53:51,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5877/9304 [17:56<10:15,  5.57it/s]

2025-05-20 16:53:51,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5878/9304 [17:57<10:21,  5.51it/s]

2025-05-20 16:53:51,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:52,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5880/9304 [17:57<09:23,  6.08it/s]

2025-05-20 16:53:52,095 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:52,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5882/9304 [17:57<09:05,  6.27it/s]

2025-05-20 16:53:52,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5883/9304 [17:57<08:55,  6.39it/s]

2025-05-20 16:53:53,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5884/9304 [17:58<15:02,  3.79it/s]

2025-05-20 16:53:53,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:53,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5886/9304 [17:58<13:28,  4.23it/s]

2025-05-20 16:53:53,603 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:53,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:53,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:53,962 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5890/9304 [17:59<09:29,  6.00it/s]

2025-05-20 16:53:54,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:54,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5891/9304 [17:59<09:40,  5.88it/s]

2025-05-20 16:53:54,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5893/9304 [17:59<09:23,  6.06it/s]

2025-05-20 16:53:54,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5894/9304 [18:00<11:30,  4.94it/s]

2025-05-20 16:53:54,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5895/9304 [18:00<10:57,  5.18it/s]

2025-05-20 16:53:55,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:55,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5897/9304 [18:00<09:15,  6.14it/s]

2025-05-20 16:53:55,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:55,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5899/9304 [18:00<10:20,  5.49it/s]

2025-05-20 16:53:55,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:55,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:55,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:55,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5903/9304 [18:01<06:36,  8.57it/s]

2025-05-20 16:53:56,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:56,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5905/9304 [18:01<08:57,  6.32it/s]

2025-05-20 16:53:56,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5906/9304 [18:02<10:43,  5.28it/s]

2025-05-20 16:53:57,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 63%|██████▎   | 5907/9304 [18:02<11:43,  4.83it/s]

2025-05-20 16:53:57,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:57,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:57,310 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5910/9304 [18:02<08:49,  6.41it/s]

2025-05-20 16:53:57,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:57,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5912/9304 [18:03<09:27,  5.98it/s]

2025-05-20 16:53:57,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5913/9304 [18:03<09:16,  6.10it/s]

2025-05-20 16:53:57,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:58,195 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5915/9304 [18:03<09:26,  5.98it/s]

2025-05-20 16:53:58,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5916/9304 [18:03<11:22,  4.96it/s]

2025-05-20 16:53:58,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:58,720 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5918/9304 [18:04<09:04,  6.22it/s]

2025-05-20 16:53:58,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5919/9304 [18:04<09:50,  5.74it/s]

2025-05-20 16:53:58,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:53:59,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5921/9304 [18:04<07:33,  7.46it/s]

2025-05-20 16:53:59,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5922/9304 [18:04<08:19,  6.78it/s]

2025-05-20 16:53:59,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5923/9304 [18:04<09:09,  6.15it/s]

2025-05-20 16:53:59,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5924/9304 [18:05<12:59,  4.33it/s]

2025-05-20 16:54:00,257 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5925/9304 [18:05<14:32,  3.87it/s]

2025-05-20 16:54:00,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:00,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5926/9304 [18:05<12:36,  4.46it/s]

2025-05-20 16:54:00,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:00,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:00,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5930/9304 [18:05<06:52,  8.18it/s]

2025-05-20 16:54:00,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▎   | 5931/9304 [18:06<06:59,  8.05it/s]

2025-05-20 16:54:01,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5932/9304 [18:06<10:42,  5.24it/s]

2025-05-20 16:54:01,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:01,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5934/9304 [18:06<11:15,  4.99it/s]

2025-05-20 16:54:01,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:01,945 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5936/9304 [18:07<10:20,  5.43it/s]

2025-05-20 16:54:02,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:02,142 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5938/9304 [18:07<08:43,  6.43it/s]

2025-05-20 16:54:02,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5939/9304 [18:07<08:24,  6.66it/s]

2025-05-20 16:54:02,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:02,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:02,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5941/9304 [18:07<07:56,  7.06it/s]

2025-05-20 16:54:02,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5943/9304 [18:08<07:36,  7.36it/s]

2025-05-20 16:54:03,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5944/9304 [18:08<09:33,  5.86it/s]

2025-05-20 16:54:03,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5945/9304 [18:08<11:59,  4.67it/s]

2025-05-20 16:54:03,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:03,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5947/9304 [18:08<09:26,  5.93it/s]

2025-05-20 16:54:04,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5948/9304 [18:09<12:16,  4.55it/s]

2025-05-20 16:54:04,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:04,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5950/9304 [18:09<11:58,  4.67it/s]

2025-05-20 16:54:04,545 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:04,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5952/9304 [18:10<10:47,  5.18it/s]

2025-05-20 16:54:04,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:04,825 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:04,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:04,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5956/9304 [18:10<06:56,  8.04it/s]

2025-05-20 16:54:05,224 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5957/9304 [18:10<07:50,  7.11it/s]

2025-05-20 16:54:05,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5958/9304 [18:10<10:15,  5.44it/s]

2025-05-20 16:54:05,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5959/9304 [18:11<10:28,  5.32it/s]

2025-05-20 16:54:06,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5960/9304 [18:11<10:32,  5.29it/s]

2025-05-20 16:54:06,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5961/9304 [18:11<09:20,  5.96it/s]

2025-05-20 16:54:06,379 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5962/9304 [18:11<10:51,  5.13it/s]

2025-05-20 16:54:06,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5963/9304 [18:11<09:49,  5.67it/s]

2025-05-20 16:54:06,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5964/9304 [18:11<09:01,  6.17it/s]

2025-05-20 16:54:06,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:06,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5966/9304 [18:12<08:17,  6.70it/s]

2025-05-20 16:54:06,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:07,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5968/9304 [18:12<11:10,  4.98it/s]

2025-05-20 16:54:07,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:07,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5970/9304 [18:13<09:25,  5.90it/s]

2025-05-20 16:54:07,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:07,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:08,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5973/9304 [18:13<08:15,  6.72it/s]

2025-05-20 16:54:08,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5974/9304 [18:13<09:07,  6.08it/s]

2025-05-20 16:54:08,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5975/9304 [18:13<09:03,  6.12it/s]

2025-05-20 16:54:08,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:08,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5976/9304 [18:13<08:36,  6.45it/s]

2025-05-20 16:54:09,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5978/9304 [18:14<10:50,  5.11it/s]

2025-05-20 16:54:09,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:09,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:09,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5981/9304 [18:14<07:36,  7.28it/s]

2025-05-20 16:54:09,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5982/9304 [18:14<09:52,  5.60it/s]

2025-05-20 16:54:09,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:09,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5984/9304 [18:15<08:29,  6.52it/s]

2025-05-20 16:54:10,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5985/9304 [18:15<08:15,  6.69it/s]

2025-05-20 16:54:10,139 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5986/9304 [18:15<08:01,  6.89it/s]

2025-05-20 16:54:10,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5987/9304 [18:15<08:37,  6.41it/s]

2025-05-20 16:54:10,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5988/9304 [18:15<10:37,  5.20it/s]

2025-05-20 16:54:10,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:11,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5990/9304 [18:16<10:24,  5.30it/s]

2025-05-20 16:54:11,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:11,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:11,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5993/9304 [18:16<08:20,  6.62it/s]

2025-05-20 16:54:11,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:11,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5995/9304 [18:16<08:24,  6.55it/s]

2025-05-20 16:54:11,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5996/9304 [18:17<08:46,  6.28it/s]

2025-05-20 16:54:12,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5997/9304 [18:17<10:05,  5.46it/s]

2025-05-20 16:54:12,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5998/9304 [18:17<09:14,  5.96it/s]

2025-05-20 16:54:12,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 5999/9304 [18:17<08:39,  6.36it/s]

2025-05-20 16:54:12,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 6000/9304 [18:17<09:20,  5.90it/s]

2025-05-20 16:54:12,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 64%|██████▍   | 6001/9304 [18:18<10:04,  5.46it/s]

2025-05-20 16:54:12,824 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:12,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:12,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6004/9304 [18:18<06:55,  7.94it/s]

2025-05-20 16:54:13,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6005/9304 [18:18<10:27,  5.26it/s]

2025-05-20 16:54:13,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6006/9304 [18:18<09:36,  5.72it/s]

2025-05-20 16:54:13,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:13,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6008/9304 [18:19<08:09,  6.73it/s]

2025-05-20 16:54:13,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6009/9304 [18:19<08:40,  6.32it/s]

2025-05-20 16:54:14,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6010/9304 [18:19<11:41,  4.70it/s]

2025-05-20 16:54:14,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:14,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6012/9304 [18:19<08:19,  6.59it/s]

2025-05-20 16:54:14,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:14,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6014/9304 [18:19<06:25,  8.53it/s]

2025-05-20 16:54:14,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:15,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6016/9304 [18:20<08:42,  6.30it/s]

2025-05-20 16:54:15,446 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6017/9304 [18:20<11:03,  4.96it/s]

2025-05-20 16:54:15,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:15,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6019/9304 [18:21<12:33,  4.36it/s]

2025-05-20 16:54:16,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:16,180 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6021/9304 [18:21<09:55,  5.51it/s]

2025-05-20 16:54:16,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:16,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6023/9304 [18:21<07:54,  6.92it/s]

2025-05-20 16:54:16,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6024/9304 [18:21<08:11,  6.67it/s]

2025-05-20 16:54:16,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6025/9304 [18:21<08:17,  6.58it/s]

2025-05-20 16:54:16,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:17,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6027/9304 [18:22<10:39,  5.13it/s]

2025-05-20 16:54:17,336 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6028/9304 [18:22<10:15,  5.33it/s]

2025-05-20 16:54:17,576 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6029/9304 [18:22<10:49,  5.04it/s]

2025-05-20 16:54:17,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6030/9304 [18:23<09:35,  5.69it/s]

2025-05-20 16:54:17,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:18,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6032/9304 [18:23<13:06,  4.16it/s]

2025-05-20 16:54:18,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:18,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6034/9304 [18:23<10:15,  5.31it/s]

2025-05-20 16:54:18,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6035/9304 [18:24<11:40,  4.67it/s]

2025-05-20 16:54:18,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:19,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6037/9304 [18:24<09:22,  5.81it/s]

2025-05-20 16:54:19,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:19,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6039/9304 [18:24<07:10,  7.59it/s]

2025-05-20 16:54:19,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:19,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6041/9304 [18:24<09:08,  5.95it/s]

2025-05-20 16:54:19,791 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6042/9304 [18:25<08:48,  6.17it/s]

2025-05-20 16:54:19,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:20,061 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6044/9304 [18:25<08:20,  6.51it/s]

2025-05-20 16:54:20,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6045/9304 [18:25<08:37,  6.29it/s]

2025-05-20 16:54:20,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:20,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▍   | 6046/9304 [18:26<12:36,  4.31it/s]

2025-05-20 16:54:20,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:21,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6049/9304 [18:26<09:50,  5.51it/s]

2025-05-20 16:54:21,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6050/9304 [18:26<10:30,  5.16it/s]

2025-05-20 16:54:21,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:21,763 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6052/9304 [18:27<10:32,  5.14it/s]

2025-05-20 16:54:21,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:21,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6054/9304 [18:27<08:39,  6.25it/s]

2025-05-20 16:54:22,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6055/9304 [18:27<09:42,  5.58it/s]

2025-05-20 16:54:22,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6056/9304 [18:27<09:15,  5.84it/s]

2025-05-20 16:54:22,503 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6057/9304 [18:27<09:08,  5.92it/s]

2025-05-20 16:54:22,955 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6058/9304 [18:28<12:51,  4.21it/s]

2025-05-20 16:54:22,967 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:22,997 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:23,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:23,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6062/9304 [18:28<06:46,  7.97it/s]

2025-05-20 16:54:23,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6063/9304 [18:28<07:26,  7.26it/s]

2025-05-20 16:54:23,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6064/9304 [18:29<09:42,  5.56it/s]

2025-05-20 16:54:23,749 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:23,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6066/9304 [18:29<07:27,  7.24it/s]

2025-05-20 16:54:24,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6067/9304 [18:29<13:51,  3.89it/s]

2025-05-20 16:54:24,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6068/9304 [18:29<12:03,  4.48it/s]

2025-05-20 16:54:24,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:24,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6069/9304 [18:30<10:35,  5.09it/s]

2025-05-20 16:54:24,798 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:25,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6072/9304 [18:30<09:52,  5.46it/s]

2025-05-20 16:54:25,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:25,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:25,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6075/9304 [18:30<06:43,  8.01it/s]

2025-05-20 16:54:25,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:26,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6077/9304 [18:31<11:00,  4.89it/s]

2025-05-20 16:54:26,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:26,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:26,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6080/9304 [18:31<08:38,  6.21it/s]

2025-05-20 16:54:26,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:27,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6082/9304 [18:32<10:06,  5.31it/s]

2025-05-20 16:54:27,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:27,240 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6083/9304 [18:32<10:26,  5.14it/s]

2025-05-20 16:54:27,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:27,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6086/9304 [18:32<08:32,  6.28it/s]

2025-05-20 16:54:27,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:27,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:27,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6089/9304 [18:33<06:43,  7.96it/s]

2025-05-20 16:54:28,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:28,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6090/9304 [18:33<08:17,  6.46it/s]

2025-05-20 16:54:28,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6092/9304 [18:33<10:32,  5.08it/s]

2025-05-20 16:54:28,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6093/9304 [18:34<10:34,  5.06it/s]

2025-05-20 16:54:29,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 65%|██████▌   | 6094/9304 [18:34<13:16,  4.03it/s]

2025-05-20 16:54:29,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:29,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:29,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6097/9304 [18:34<08:03,  6.64it/s]

2025-05-20 16:54:29,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:29,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:29,915 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6099/9304 [18:35<09:29,  5.62it/s]

2025-05-20 16:54:30,081 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6101/9304 [18:35<07:56,  6.72it/s]

2025-05-20 16:54:30,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:30,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6103/9304 [18:36<10:41,  4.99it/s]

2025-05-20 16:54:31,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6104/9304 [18:36<11:29,  4.64it/s]

2025-05-20 16:54:31,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:31,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6106/9304 [18:36<10:00,  5.33it/s]

2025-05-20 16:54:31,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6107/9304 [18:36<09:33,  5.57it/s]

2025-05-20 16:54:31,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6108/9304 [18:36<09:06,  5.84it/s]

2025-05-20 16:54:31,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6109/9304 [18:37<11:55,  4.46it/s]

2025-05-20 16:54:32,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:32,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6111/9304 [18:37<10:26,  5.10it/s]

2025-05-20 16:54:32,274 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:32,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6113/9304 [18:38<11:09,  4.76it/s]

2025-05-20 16:54:32,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:32,934 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6115/9304 [18:38<09:11,  5.78it/s]

2025-05-20 16:54:32,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:33,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6117/9304 [18:38<07:05,  7.49it/s]

2025-05-20 16:54:33,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:33,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6119/9304 [18:39<10:18,  5.15it/s]

2025-05-20 16:54:33,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:33,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6121/9304 [18:39<08:27,  6.27it/s]

2025-05-20 16:54:33,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:34,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6123/9304 [18:39<07:09,  7.41it/s]

2025-05-20 16:54:34,258 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:34,374 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6125/9304 [18:39<07:52,  6.72it/s]

2025-05-20 16:54:34,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6126/9304 [18:39<08:13,  6.44it/s]

2025-05-20 16:54:34,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:34,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6128/9304 [18:40<08:15,  6.41it/s]

2025-05-20 16:54:35,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6129/9304 [18:40<08:02,  6.58it/s]

2025-05-20 16:54:35,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6130/9304 [18:40<08:11,  6.45it/s]

2025-05-20 16:54:35,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:35,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6132/9304 [18:40<07:52,  6.71it/s]

2025-05-20 16:54:35,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6133/9304 [18:41<08:50,  5.98it/s]

2025-05-20 16:54:35,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6134/9304 [18:41<10:35,  4.99it/s]

2025-05-20 16:54:36,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:36,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:36,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6137/9304 [18:41<06:53,  7.67it/s]

2025-05-20 16:54:36,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6138/9304 [18:41<09:26,  5.59it/s]

2025-05-20 16:54:36,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6139/9304 [18:42<09:14,  5.70it/s]

2025-05-20 16:54:37,007 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6140/9304 [18:42<10:41,  4.93it/s]

2025-05-20 16:54:37,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6141/9304 [18:42<11:28,  4.59it/s]

2025-05-20 16:54:37,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:37,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6143/9304 [18:42<08:46,  6.00it/s]

2025-05-20 16:54:37,513 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:37,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6145/9304 [18:42<06:39,  7.91it/s]

2025-05-20 16:54:37,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6146/9304 [18:43<06:43,  7.83it/s]

2025-05-20 16:54:37,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6147/9304 [18:43<06:40,  7.87it/s]

2025-05-20 16:54:37,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:38,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6149/9304 [18:43<08:32,  6.16it/s]

2025-05-20 16:54:38,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6150/9304 [18:44<13:28,  3.90it/s]

2025-05-20 16:54:38,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:39,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6152/9304 [18:44<10:20,  5.08it/s]

2025-05-20 16:54:39,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:39,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6154/9304 [18:44<08:57,  5.86it/s]

2025-05-20 16:54:39,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6155/9304 [18:44<08:45,  5.99it/s]

2025-05-20 16:54:39,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:39,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6157/9304 [18:44<07:00,  7.49it/s]

2025-05-20 16:54:39,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6158/9304 [18:45<07:07,  7.35it/s]

2025-05-20 16:54:39,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6159/9304 [18:45<07:09,  7.32it/s]

2025-05-20 16:54:40,454 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6160/9304 [18:45<12:37,  4.15it/s]

2025-05-20 16:54:40,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:40,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:40,863 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▌   | 6163/9304 [18:46<09:47,  5.35it/s]

2025-05-20 16:54:41,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:41,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6164/9304 [18:46<09:31,  5.50it/s]

2025-05-20 16:54:41,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6166/9304 [18:46<07:34,  6.90it/s]

2025-05-20 16:54:41,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6167/9304 [18:46<07:21,  7.10it/s]

2025-05-20 16:54:41,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6168/9304 [18:46<09:06,  5.73it/s]

2025-05-20 16:54:42,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:42,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6169/9304 [18:47<13:12,  3.95it/s]

2025-05-20 16:54:42,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6171/9304 [18:47<10:37,  4.92it/s]

2025-05-20 16:54:42,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6172/9304 [18:47<09:51,  5.29it/s]

2025-05-20 16:54:42,603 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6173/9304 [18:47<08:45,  5.96it/s]

2025-05-20 16:54:42,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:42,764 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6175/9304 [18:48<06:54,  7.55it/s]

2025-05-20 16:54:43,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6176/9304 [18:48<10:06,  5.16it/s]

2025-05-20 16:54:43,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6177/9304 [18:48<11:57,  4.36it/s]

2025-05-20 16:54:43,822 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6178/9304 [18:49<13:03,  3.99it/s]

2025-05-20 16:54:44,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6179/9304 [18:49<13:17,  3.92it/s]

2025-05-20 16:54:44,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6180/9304 [18:49<13:07,  3.97it/s]

2025-05-20 16:54:44,341 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:44,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6182/9304 [18:49<10:58,  4.74it/s]

2025-05-20 16:54:44,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:44,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6184/9304 [18:50<07:44,  6.72it/s]

2025-05-20 16:54:44,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:44,909 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 66%|██████▋   | 6186/9304 [18:50<06:29,  8.00it/s]

2025-05-20 16:54:45,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:45,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6188/9304 [18:50<07:48,  6.65it/s]

2025-05-20 16:54:46,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6189/9304 [18:51<13:40,  3.79it/s]

2025-05-20 16:54:46,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:46,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6191/9304 [18:51<10:19,  5.03it/s]

2025-05-20 16:54:46,235 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:46,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:46,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:46,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6194/9304 [18:51<07:51,  6.59it/s]

2025-05-20 16:54:46,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:46,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:47,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:47,664 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:47,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6198/9304 [18:52<11:14,  4.61it/s]

2025-05-20 16:54:47,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:47,905 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:47,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6202/9304 [18:53<08:01,  6.44it/s]

2025-05-20 16:54:47,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:48,016 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6205/9304 [18:53<06:12,  8.31it/s]

2025-05-20 16:54:48,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:48,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6207/9304 [18:54<09:03,  5.70it/s]

2025-05-20 16:54:49,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:49,291 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6209/9304 [18:54<10:11,  5.06it/s]

2025-05-20 16:54:49,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:49,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:49,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:49,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6213/9304 [18:54<07:36,  6.77it/s]

2025-05-20 16:54:50,139 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:50,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6215/9304 [18:55<10:32,  4.88it/s]

2025-05-20 16:54:50,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6216/9304 [18:56<11:43,  4.39it/s]

2025-05-20 16:54:50,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6217/9304 [18:56<11:14,  4.58it/s]

2025-05-20 16:54:50,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:51,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6219/9304 [18:56<09:54,  5.19it/s]

2025-05-20 16:54:51,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:51,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6221/9304 [18:56<08:35,  5.98it/s]

2025-05-20 16:54:51,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6222/9304 [18:56<08:00,  6.41it/s]

2025-05-20 16:54:51,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6223/9304 [18:57<10:17,  4.99it/s]

2025-05-20 16:54:52,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6224/9304 [18:57<09:42,  5.28it/s]

2025-05-20 16:54:52,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6225/9304 [18:57<12:13,  4.20it/s]

2025-05-20 16:54:52,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6226/9304 [18:58<12:51,  3.99it/s]

2025-05-20 16:54:52,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6227/9304 [18:58<12:22,  4.15it/s]

2025-05-20 16:54:52,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:53,199 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:53,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6229/9304 [18:58<09:43,  5.27it/s]

2025-05-20 16:54:53,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:53,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6232/9304 [18:58<07:01,  7.29it/s]

2025-05-20 16:54:53,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6233/9304 [18:58<06:58,  7.33it/s]

2025-05-20 16:54:53,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6234/9304 [18:59<10:02,  5.10it/s]

2025-05-20 16:54:54,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6235/9304 [18:59<09:13,  5.54it/s]

2025-05-20 16:54:54,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6236/9304 [18:59<10:27,  4.89it/s]

2025-05-20 16:54:54,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:54,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6238/9304 [18:59<07:13,  7.07it/s]

2025-05-20 16:54:54,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6239/9304 [19:00<07:41,  6.64it/s]

2025-05-20 16:54:54,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6240/9304 [19:00<09:01,  5.65it/s]

2025-05-20 16:54:54,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:55,069 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6242/9304 [19:00<06:32,  7.79it/s]

2025-05-20 16:54:55,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:55,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6244/9304 [19:00<08:25,  6.05it/s]

2025-05-20 16:54:55,942 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:55,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6245/9304 [19:01<11:09,  4.57it/s]

2025-05-20 16:54:56,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6247/9304 [19:01<08:21,  6.10it/s]

2025-05-20 16:54:56,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:56,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6249/9304 [19:01<07:03,  7.21it/s]

2025-05-20 16:54:56,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6250/9304 [19:01<06:50,  7.44it/s]

2025-05-20 16:54:56,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6251/9304 [19:02<08:40,  5.87it/s]

2025-05-20 16:54:57,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6252/9304 [19:02<11:13,  4.53it/s]

2025-05-20 16:54:57,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6253/9304 [19:02<10:30,  4.84it/s]

2025-05-20 16:54:57,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6254/9304 [19:02<12:50,  3.96it/s]

2025-05-20 16:54:57,630 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:57,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:57,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6257/9304 [19:03<07:29,  6.78it/s]

2025-05-20 16:54:57,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:58,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6259/9304 [19:03<09:25,  5.38it/s]

2025-05-20 16:54:58,348 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:58,743 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6261/9304 [19:04<10:00,  5.07it/s]

2025-05-20 16:54:59,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6262/9304 [19:04<11:05,  4.57it/s]

2025-05-20 16:54:59,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:59,119 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:59,470 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6265/9304 [19:04<09:15,  5.47it/s]

2025-05-20 16:54:59,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6266/9304 [19:04<08:39,  5.85it/s]

2025-05-20 16:54:59,630 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:54:59,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6268/9304 [19:05<07:40,  6.60it/s]

2025-05-20 16:54:59,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6269/9304 [19:05<07:09,  7.06it/s]

2025-05-20 16:55:00,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6270/9304 [19:05<10:47,  4.69it/s]

2025-05-20 16:55:00,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:00,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6272/9304 [19:06<10:07,  4.99it/s]

2025-05-20 16:55:00,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:00,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6274/9304 [19:06<07:30,  6.72it/s]

2025-05-20 16:55:00,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:00,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6276/9304 [19:06<05:58,  8.45it/s]

2025-05-20 16:55:01,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:01,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6278/9304 [19:06<09:05,  5.54it/s]

2025-05-20 16:55:01,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:02,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 67%|██████▋   | 6280/9304 [19:07<10:04,  5.00it/s]

2025-05-20 16:55:02,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:02,240 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6282/9304 [19:07<08:58,  5.61it/s]

2025-05-20 16:55:02,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6283/9304 [19:07<09:13,  5.46it/s]

2025-05-20 16:55:02,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:02,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6285/9304 [19:07<07:02,  7.14it/s]

2025-05-20 16:55:02,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:02,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6287/9304 [19:08<05:51,  8.57it/s]

2025-05-20 16:55:02,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:02,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6289/9304 [19:08<05:39,  8.89it/s]

2025-05-20 16:55:03,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:03,822 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6291/9304 [19:09<10:23,  4.84it/s]

2025-05-20 16:55:03,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6292/9304 [19:09<09:59,  5.02it/s]

2025-05-20 16:55:04,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6293/9304 [19:09<11:19,  4.43it/s]

2025-05-20 16:55:04,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:04,338 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:04,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6296/9304 [19:09<06:52,  7.28it/s]

2025-05-20 16:55:04,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:04,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6298/9304 [19:09<05:58,  8.38it/s]

2025-05-20 16:55:04,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:05,181 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6300/9304 [19:10<08:43,  5.74it/s]

2025-05-20 16:55:05,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6301/9304 [19:11<12:46,  3.92it/s]

2025-05-20 16:55:05,855 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:05,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:05,915 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6304/9304 [19:11<08:03,  6.21it/s]

2025-05-20 16:55:06,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:06,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6306/9304 [19:11<06:50,  7.31it/s]

2025-05-20 16:55:06,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:06,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6308/9304 [19:11<06:42,  7.45it/s]

2025-05-20 16:55:07,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:07,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6310/9304 [19:12<10:37,  4.70it/s]

2025-05-20 16:55:07,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6311/9304 [19:12<11:12,  4.45it/s]

2025-05-20 16:55:07,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:07,560 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6313/9304 [19:12<08:41,  5.74it/s]

2025-05-20 16:55:07,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:07,661 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6315/9304 [19:12<06:41,  7.44it/s]

2025-05-20 16:55:07,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:07,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6317/9304 [19:13<05:46,  8.61it/s]

2025-05-20 16:55:07,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:08,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6319/9304 [19:14<11:14,  4.43it/s]

2025-05-20 16:55:08,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:08,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6321/9304 [19:14<09:24,  5.28it/s]

2025-05-20 16:55:09,080 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6322/9304 [19:14<08:41,  5.72it/s]

2025-05-20 16:55:09,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:09,177 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:09,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6325/9304 [19:14<05:47,  8.57it/s]

2025-05-20 16:55:09,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:09,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6327/9304 [19:14<06:17,  7.89it/s]

2025-05-20 16:55:09,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:10,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6329/9304 [19:15<10:25,  4.76it/s]

2025-05-20 16:55:10,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:10,720 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6331/9304 [19:16<10:16,  4.83it/s]

2025-05-20 16:55:10,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6332/9304 [19:16<10:19,  4.80it/s]

2025-05-20 16:55:10,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:11,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:11,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6335/9304 [19:16<06:39,  7.44it/s]

2025-05-20 16:55:11,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:11,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6337/9304 [19:16<08:07,  6.09it/s]

2025-05-20 16:55:11,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:11,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6339/9304 [19:17<08:32,  5.78it/s]

2025-05-20 16:55:12,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6340/9304 [19:17<08:33,  5.77it/s]

2025-05-20 16:55:12,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6341/9304 [19:17<09:54,  4.98it/s]

2025-05-20 16:55:12,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6342/9304 [19:17<09:50,  5.01it/s]

2025-05-20 16:55:12,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:12,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6344/9304 [19:18<08:06,  6.09it/s]

2025-05-20 16:55:12,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:12,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:13,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6347/9304 [19:18<06:52,  7.17it/s]

2025-05-20 16:55:13,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:13,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6349/9304 [19:18<06:13,  7.91it/s]

2025-05-20 16:55:13,536 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6350/9304 [19:18<06:59,  7.05it/s]

2025-05-20 16:55:14,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6351/9304 [19:19<11:16,  4.37it/s]

2025-05-20 16:55:14,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6352/9304 [19:19<10:09,  4.84it/s]

2025-05-20 16:55:14,378 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:14,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6353/9304 [19:19<09:27,  5.20it/s]

2025-05-20 16:55:14,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6355/9304 [19:20<09:32,  5.15it/s]

2025-05-20 16:55:14,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:15,235 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6357/9304 [19:20<10:05,  4.86it/s]

2025-05-20 16:55:15,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:15,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6359/9304 [19:20<08:57,  5.48it/s]

2025-05-20 16:55:15,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6360/9304 [19:20<08:24,  5.83it/s]

2025-05-20 16:55:15,725 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6361/9304 [19:21<08:15,  5.94it/s]

2025-05-20 16:55:15,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:15,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6363/9304 [19:21<06:50,  7.17it/s]

2025-05-20 16:55:16,514 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6364/9304 [19:21<10:58,  4.47it/s]

2025-05-20 16:55:16,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6365/9304 [19:22<11:31,  4.25it/s]

2025-05-20 16:55:16,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:16,824 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:16,886 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6368/9304 [19:22<06:42,  7.29it/s]

2025-05-20 16:55:17,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:17,278 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:17,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6370/9304 [19:22<07:32,  6.49it/s]

2025-05-20 16:55:17,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6372/9304 [19:22<07:50,  6.23it/s]

2025-05-20 16:55:17,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 68%|██████▊   | 6373/9304 [19:23<08:20,  5.86it/s]

2025-05-20 16:55:18,004 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6374/9304 [19:23<08:09,  5.98it/s]

2025-05-20 16:55:18,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6375/9304 [19:23<12:23,  3.94it/s]

2025-05-20 16:55:18,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:18,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6377/9304 [19:24<09:03,  5.38it/s]

2025-05-20 16:55:18,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6378/9304 [19:24<09:16,  5.26it/s]

2025-05-20 16:55:18,945 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:19,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6380/9304 [19:24<08:25,  5.79it/s]

2025-05-20 16:55:19,291 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:20,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6382/9304 [19:25<12:42,  3.83it/s]

2025-05-20 16:55:20,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:20,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6383/9304 [19:25<12:16,  3.97it/s]

2025-05-20 16:55:20,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:20,573 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6386/9304 [19:25<08:51,  5.49it/s]

2025-05-20 16:55:20,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:20,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6388/9304 [19:26<07:16,  6.68it/s]

2025-05-20 16:55:20,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:21,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6390/9304 [19:26<08:21,  5.81it/s]

2025-05-20 16:55:21,501 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6391/9304 [19:26<09:47,  4.96it/s]

2025-05-20 16:55:21,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6392/9304 [19:27<10:35,  4.58it/s]

2025-05-20 16:55:21,822 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:22,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6394/9304 [19:27<08:57,  5.41it/s]

2025-05-20 16:55:22,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:22,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▊   | 6396/9304 [19:27<06:44,  7.19it/s]

2025-05-20 16:55:22,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:22,417 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6398/9304 [19:27<06:39,  7.28it/s]

2025-05-20 16:55:22,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:22,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6400/9304 [19:27<05:22,  9.01it/s]

2025-05-20 16:55:23,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:23,698 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6402/9304 [19:29<12:32,  3.86it/s]

2025-05-20 16:55:23,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:23,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6404/9304 [19:29<09:52,  4.89it/s]

2025-05-20 16:55:23,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:23,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:24,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6407/9304 [19:29<07:53,  6.12it/s]

2025-05-20 16:55:24,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:24,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6409/9304 [19:29<06:43,  7.18it/s]

2025-05-20 16:55:24,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:24,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6411/9304 [19:30<09:11,  5.24it/s]

2025-05-20 16:55:25,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6412/9304 [19:30<12:21,  3.90it/s]

2025-05-20 16:55:25,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:25,582 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:25,619 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:25,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6416/9304 [19:31<07:38,  6.30it/s]

2025-05-20 16:55:25,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6417/9304 [19:31<07:23,  6.51it/s]

2025-05-20 16:55:25,934 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:26,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6419/9304 [19:31<07:02,  6.83it/s]

2025-05-20 16:55:26,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6420/9304 [19:32<10:25,  4.61it/s]

2025-05-20 16:55:26,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6421/9304 [19:32<11:04,  4.34it/s]

2025-05-20 16:55:27,069 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:27,198 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6423/9304 [19:32<08:54,  5.39it/s]

2025-05-20 16:55:27,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6424/9304 [19:32<08:10,  5.87it/s]

2025-05-20 16:55:27,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:27,562 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6426/9304 [19:32<07:22,  6.51it/s]

2025-05-20 16:55:27,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:27,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6428/9304 [19:33<06:18,  7.60it/s]

2025-05-20 16:55:27,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:28,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6430/9304 [19:33<08:23,  5.71it/s]

2025-05-20 16:55:28,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6431/9304 [19:33<08:43,  5.49it/s]

2025-05-20 16:55:28,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6432/9304 [19:33<08:04,  5.93it/s]

2025-05-20 16:55:29,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6433/9304 [19:34<10:43,  4.46it/s]

2025-05-20 16:55:29,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:29,166 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6435/9304 [19:34<08:02,  5.95it/s]

2025-05-20 16:55:29,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6436/9304 [19:34<07:46,  6.14it/s]

2025-05-20 16:55:29,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6437/9304 [19:34<08:52,  5.38it/s]

2025-05-20 16:55:29,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:29,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6439/9304 [19:35<07:31,  6.35it/s]

2025-05-20 16:55:29,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6440/9304 [19:35<07:49,  6.10it/s]

2025-05-20 16:55:30,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:30,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6442/9304 [19:35<07:56,  6.00it/s]

2025-05-20 16:55:30,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6443/9304 [19:35<08:51,  5.38it/s]

2025-05-20 16:55:30,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6444/9304 [19:36<11:11,  4.26it/s]

2025-05-20 16:55:30,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:31,126 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6446/9304 [19:36<08:04,  5.89it/s]

2025-05-20 16:55:31,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:31,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6448/9304 [19:36<06:46,  7.02it/s]

2025-05-20 16:55:31,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:31,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:31,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6451/9304 [19:36<06:08,  7.73it/s]

2025-05-20 16:55:31,872 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6452/9304 [19:37<06:52,  6.91it/s]

2025-05-20 16:55:32,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6453/9304 [19:37<08:52,  5.35it/s]

2025-05-20 16:55:32,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:32,864 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6455/9304 [19:38<11:05,  4.28it/s]

2025-05-20 16:55:32,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6456/9304 [19:38<10:08,  4.68it/s]

2025-05-20 16:55:33,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:33,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:33,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:33,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6460/9304 [19:38<05:29,  8.63it/s]

2025-05-20 16:55:33,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:33,410 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6462/9304 [19:38<05:50,  8.12it/s]

2025-05-20 16:55:33,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:33,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6464/9304 [19:39<08:03,  5.87it/s]

2025-05-20 16:55:34,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 69%|██████▉   | 6465/9304 [19:39<09:38,  4.91it/s]

2025-05-20 16:55:34,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:34,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:34,559 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6468/9304 [19:39<06:55,  6.83it/s]

2025-05-20 16:55:34,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6469/9304 [19:40<07:25,  6.37it/s]

2025-05-20 16:55:34,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:34,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:35,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6472/9304 [19:40<06:04,  7.77it/s]

2025-05-20 16:55:35,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6473/9304 [19:40<05:55,  7.97it/s]

2025-05-20 16:55:35,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6474/9304 [19:41<11:07,  4.24it/s]

2025-05-20 16:55:35,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:35,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6476/9304 [19:41<08:08,  5.79it/s]

2025-05-20 16:55:36,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:36,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6478/9304 [19:41<07:10,  6.56it/s]

2025-05-20 16:55:36,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6479/9304 [19:41<07:51,  5.99it/s]

2025-05-20 16:55:36,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:36,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6481/9304 [19:41<06:50,  6.88it/s]

2025-05-20 16:55:36,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:36,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6483/9304 [19:42<06:53,  6.83it/s]

2025-05-20 16:55:37,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:37,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6485/9304 [19:42<07:00,  6.70it/s]

2025-05-20 16:55:37,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6486/9304 [19:42<06:59,  6.72it/s]

2025-05-20 16:55:37,905 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6487/9304 [19:43<10:42,  4.38it/s]

2025-05-20 16:55:37,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:38,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6489/9304 [19:43<08:30,  5.51it/s]

2025-05-20 16:55:38,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:38,401 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6491/9304 [19:43<07:53,  5.94it/s]

2025-05-20 16:55:38,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:38,608 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6493/9304 [19:43<06:53,  6.80it/s]

2025-05-20 16:55:38,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6494/9304 [19:44<08:50,  5.30it/s]

2025-05-20 16:55:39,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6495/9304 [19:44<09:35,  4.88it/s]

2025-05-20 16:55:39,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:39,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6497/9304 [19:44<06:59,  6.70it/s]

2025-05-20 16:55:39,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6498/9304 [19:45<10:48,  4.32it/s]

2025-05-20 16:55:40,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6499/9304 [19:45<09:50,  4.75it/s]

2025-05-20 16:55:40,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:40,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:40,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6502/9304 [19:45<05:52,  7.95it/s]

2025-05-20 16:55:40,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:40,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6504/9304 [19:45<07:21,  6.35it/s]

2025-05-20 16:55:40,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6505/9304 [19:46<09:17,  5.02it/s]

2025-05-20 16:55:41,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6506/9304 [19:46<08:44,  5.34it/s]

2025-05-20 16:55:41,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6507/9304 [19:46<08:54,  5.23it/s]

2025-05-20 16:55:41,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6508/9304 [19:46<08:39,  5.38it/s]

2025-05-20 16:55:41,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6509/9304 [19:47<10:37,  4.39it/s]

2025-05-20 16:55:41,931 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:41,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6511/9304 [19:47<07:03,  6.59it/s]

2025-05-20 16:55:42,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|██████▉   | 6512/9304 [19:47<07:24,  6.29it/s]

2025-05-20 16:55:42,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6513/9304 [19:47<07:30,  6.19it/s]

2025-05-20 16:55:42,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6514/9304 [19:47<07:33,  6.15it/s]

2025-05-20 16:55:42,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6515/9304 [19:47<07:07,  6.52it/s]

2025-05-20 16:55:42,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6516/9304 [19:48<10:12,  4.56it/s]

2025-05-20 16:55:43,047 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:43,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6518/9304 [19:48<07:50,  5.92it/s]

2025-05-20 16:55:43,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6519/9304 [19:48<07:36,  6.10it/s]

2025-05-20 16:55:43,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:43,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:43,732 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6522/9304 [19:49<06:45,  6.87it/s]

2025-05-20 16:55:43,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:44,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6524/9304 [19:49<07:12,  6.43it/s]

2025-05-20 16:55:44,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6525/9304 [19:49<07:29,  6.18it/s]

2025-05-20 16:55:44,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:44,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6526/9304 [19:50<10:58,  4.22it/s]

2025-05-20 16:55:44,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:44,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:44,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6530/9304 [19:50<05:58,  7.74it/s]

2025-05-20 16:55:44,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:45,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6532/9304 [19:50<07:03,  6.55it/s]

2025-05-20 16:55:45,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6533/9304 [19:50<06:47,  6.79it/s]

2025-05-20 16:55:46,412 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6534/9304 [19:51<13:40,  3.38it/s]

2025-05-20 16:55:46,433 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:46,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:46,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6537/9304 [19:51<08:18,  5.55it/s]

2025-05-20 16:55:46,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:46,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:46,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6539/9304 [19:52<07:16,  6.33it/s]

2025-05-20 16:55:46,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:46,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6542/9304 [19:52<05:28,  8.40it/s]

2025-05-20 16:55:47,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:47,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6544/9304 [19:52<08:41,  5.30it/s]

2025-05-20 16:55:47,854 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6545/9304 [19:53<08:39,  5.32it/s]

2025-05-20 16:55:47,866 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:48,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6547/9304 [19:53<07:29,  6.14it/s]

2025-05-20 16:55:48,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6548/9304 [19:53<07:23,  6.22it/s]

2025-05-20 16:55:48,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:48,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6550/9304 [19:53<06:47,  6.76it/s]

2025-05-20 16:55:48,575 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6551/9304 [19:53<06:25,  7.13it/s]

2025-05-20 16:55:48,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6552/9304 [19:54<07:56,  5.77it/s]

2025-05-20 16:55:49,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6553/9304 [19:54<07:53,  5.81it/s]

2025-05-20 16:55:49,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:49,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6554/9304 [19:54<08:43,  5.25it/s]

2025-05-20 16:55:49,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:49,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6557/9304 [19:54<05:12,  8.78it/s]

2025-05-20 16:55:49,429 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:49,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 70%|███████   | 6559/9304 [19:55<07:51,  5.82it/s]

2025-05-20 16:55:50,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6560/9304 [19:55<08:26,  5.41it/s]

2025-05-20 16:55:50,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6561/9304 [19:55<10:15,  4.46it/s]

2025-05-20 16:55:50,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:50,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:50,821 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6564/9304 [19:56<07:04,  6.46it/s]

2025-05-20 16:55:50,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:50,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:51,240 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:51,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6567/9304 [19:56<06:41,  6.81it/s]

2025-05-20 16:55:51,495 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6569/9304 [19:56<06:28,  7.04it/s]

2025-05-20 16:55:51,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6570/9304 [19:57<07:46,  5.87it/s]

2025-05-20 16:55:52,097 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6571/9304 [19:57<08:45,  5.20it/s]

2025-05-20 16:55:52,194 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:52,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6573/9304 [19:57<07:53,  5.77it/s]

2025-05-20 16:55:52,388 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:52,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:52,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:52,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6577/9304 [19:57<05:34,  8.15it/s]

2025-05-20 16:55:52,748 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:53,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6579/9304 [19:58<06:46,  6.71it/s]

2025-05-20 16:55:53,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6580/9304 [19:58<09:16,  4.90it/s]

2025-05-20 16:55:53,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:53,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6582/9304 [19:59<07:15,  6.25it/s]

2025-05-20 16:55:53,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6583/9304 [19:59<07:25,  6.11it/s]

2025-05-20 16:55:54,085 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6584/9304 [19:59<07:31,  6.02it/s]

2025-05-20 16:55:54,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:54,341 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6586/9304 [19:59<06:53,  6.57it/s]

2025-05-20 16:55:54,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6587/9304 [19:59<07:49,  5.79it/s]

2025-05-20 16:55:54,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:54,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6589/9304 [20:00<07:47,  5.81it/s]

2025-05-20 16:55:55,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6590/9304 [20:00<08:00,  5.65it/s]

2025-05-20 16:55:55,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6591/9304 [20:00<10:18,  4.39it/s]

2025-05-20 16:55:55,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:55,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:55,637 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:55,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6594/9304 [20:00<06:03,  7.46it/s]

2025-05-20 16:55:55,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:56,154 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6597/9304 [20:01<06:42,  6.73it/s]

2025-05-20 16:55:56,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6598/9304 [20:01<07:45,  5.81it/s]

2025-05-20 16:55:56,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6599/9304 [20:01<07:23,  6.11it/s]

2025-05-20 16:55:56,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6600/9304 [20:02<09:29,  4.75it/s]

2025-05-20 16:55:57,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:57,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6602/9304 [20:02<06:52,  6.55it/s]

2025-05-20 16:55:57,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6603/9304 [20:02<06:57,  6.47it/s]

2025-05-20 16:55:57,251 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:57,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6605/9304 [20:02<05:11,  8.66it/s]

2025-05-20 16:55:58,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:58,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6607/9304 [20:03<11:08,  4.03it/s]

2025-05-20 16:55:58,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:58,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6609/9304 [20:03<08:29,  5.29it/s]

2025-05-20 16:55:58,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:58,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6611/9304 [20:04<08:25,  5.32it/s]

2025-05-20 16:55:59,167 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6612/9304 [20:04<09:37,  4.66it/s]

2025-05-20 16:55:59,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:55:59,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6614/9304 [20:04<09:15,  4.84it/s]

2025-05-20 16:55:59,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6615/9304 [20:05<08:42,  5.14it/s]

2025-05-20 16:55:59,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:00,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6617/9304 [20:05<09:59,  4.48it/s]

2025-05-20 16:56:00,369 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6618/9304 [20:05<09:03,  4.94it/s]

2025-05-20 16:56:00,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:00,648 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:00,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6620/9304 [20:05<08:08,  5.50it/s]

2025-05-20 16:56:00,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:00,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6623/9304 [20:06<06:15,  7.14it/s]

2025-05-20 16:56:01,081 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6624/9304 [20:06<06:24,  6.97it/s]

2025-05-20 16:56:01,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6625/9304 [20:06<09:48,  4.55it/s]

2025-05-20 16:56:01,676 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:01,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████   | 6627/9304 [20:07<08:42,  5.12it/s]

2025-05-20 16:56:01,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:01,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:02,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6630/9304 [20:07<05:47,  7.69it/s]

2025-05-20 16:56:02,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:02,244 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6632/9304 [20:07<05:23,  8.25it/s]

2025-05-20 16:56:02,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:02,946 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6634/9304 [20:08<08:22,  5.31it/s]

2025-05-20 16:56:03,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6635/9304 [20:08<07:59,  5.56it/s]

2025-05-20 16:56:03,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6636/9304 [20:08<08:10,  5.44it/s]

2025-05-20 16:56:03,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:03,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6638/9304 [20:09<08:45,  5.08it/s]

2025-05-20 16:56:03,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6639/9304 [20:09<08:20,  5.33it/s]

2025-05-20 16:56:03,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:04,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6641/9304 [20:09<06:35,  6.73it/s]

2025-05-20 16:56:04,069 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:04,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6643/9304 [20:09<06:38,  6.67it/s]

2025-05-20 16:56:04,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:04,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6645/9304 [20:09<06:16,  7.06it/s]

2025-05-20 16:56:04,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6646/9304 [20:10<07:34,  5.85it/s]

2025-05-20 16:56:04,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:05,145 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6648/9304 [20:10<06:52,  6.44it/s]

2025-05-20 16:56:05,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6649/9304 [20:10<06:29,  6.82it/s]

2025-05-20 16:56:05,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6650/9304 [20:10<08:51,  4.99it/s]

2025-05-20 16:56:06,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 71%|███████▏  | 6651/9304 [20:11<13:18,  3.32it/s]

2025-05-20 16:56:06,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:06,315 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:06,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6654/9304 [20:11<07:52,  5.61it/s]

2025-05-20 16:56:06,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:06,545 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6656/9304 [20:11<06:04,  7.26it/s]

2025-05-20 16:56:06,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:06,686 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6658/9304 [20:12<05:06,  8.62it/s]

2025-05-20 16:56:06,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:07,711 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6660/9304 [20:13<10:33,  4.18it/s]

2025-05-20 16:56:08,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6661/9304 [20:13<11:10,  3.94it/s]

2025-05-20 16:56:08,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6662/9304 [20:13<09:50,  4.47it/s]

2025-05-20 16:56:08,177 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:08,199 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:08,229 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:08,298 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6666/9304 [20:13<05:30,  7.98it/s]

2025-05-20 16:56:08,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:08,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6668/9304 [20:14<06:25,  6.84it/s]

2025-05-20 16:56:09,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:09,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6670/9304 [20:14<09:21,  4.69it/s]

2025-05-20 16:56:09,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:09,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:09,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6673/9304 [20:14<06:47,  6.45it/s]

2025-05-20 16:56:09,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:09,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6675/9304 [20:15<06:20,  6.91it/s]

2025-05-20 16:56:10,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:10,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6677/9304 [20:15<06:35,  6.64it/s]

2025-05-20 16:56:10,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6678/9304 [20:15<08:10,  5.35it/s]

2025-05-20 16:56:10,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6679/9304 [20:16<09:01,  4.85it/s]

2025-05-20 16:56:11,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6680/9304 [20:16<09:47,  4.46it/s]

2025-05-20 16:56:11,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:11,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6682/9304 [20:16<08:17,  5.27it/s]

2025-05-20 16:56:11,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:11,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:11,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6684/9304 [20:16<06:21,  6.86it/s]

2025-05-20 16:56:11,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6686/9304 [20:17<07:09,  6.09it/s]

2025-05-20 16:56:12,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6687/9304 [20:17<09:20,  4.67it/s]

2025-05-20 16:56:12,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6688/9304 [20:17<08:37,  5.06it/s]

2025-05-20 16:56:12,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6689/9304 [20:18<08:50,  4.93it/s]

2025-05-20 16:56:12,902 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6690/9304 [20:18<08:34,  5.08it/s]

2025-05-20 16:56:12,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:13,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:13,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6693/9304 [20:18<08:16,  5.26it/s]

2025-05-20 16:56:13,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:13,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6695/9304 [20:18<06:56,  6.27it/s]

2025-05-20 16:56:13,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:13,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6697/9304 [20:19<05:56,  7.32it/s]

2025-05-20 16:56:13,871 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:14,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6699/9304 [20:19<08:28,  5.13it/s]

2025-05-20 16:56:14,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:14,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6701/9304 [20:20<07:18,  5.93it/s]

2025-05-20 16:56:15,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6702/9304 [20:20<08:50,  4.90it/s]

2025-05-20 16:56:15,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:15,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6704/9304 [20:20<07:58,  5.43it/s]

2025-05-20 16:56:15,415 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:15,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6706/9304 [20:20<06:12,  6.98it/s]

2025-05-20 16:56:15,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:15,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6708/9304 [20:21<05:46,  7.50it/s]

2025-05-20 16:56:15,715 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:16,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6710/9304 [20:21<06:12,  6.97it/s]

2025-05-20 16:56:16,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:16,423 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6711/9304 [20:21<08:06,  5.33it/s]

2025-05-20 16:56:16,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6713/9304 [20:21<06:03,  7.12it/s]

2025-05-20 16:56:16,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:16,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6715/9304 [20:22<07:05,  6.09it/s]

2025-05-20 16:56:17,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:17,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6717/9304 [20:22<05:47,  7.45it/s]

2025-05-20 16:56:17,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:17,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6719/9304 [20:22<07:19,  5.88it/s]

2025-05-20 16:56:18,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6720/9304 [20:23<09:16,  4.64it/s]

2025-05-20 16:56:18,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:18,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:18,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:18,425 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6724/9304 [20:23<06:50,  6.29it/s]

2025-05-20 16:56:18,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:18,491 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:18,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6727/9304 [20:23<05:27,  7.87it/s]

2025-05-20 16:56:18,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:19,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6729/9304 [20:24<07:50,  5.47it/s]

2025-05-20 16:56:19,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6730/9304 [20:24<07:59,  5.37it/s]

2025-05-20 16:56:19,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6731/9304 [20:25<08:39,  4.96it/s]

2025-05-20 16:56:19,843 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:19,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:20,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6734/9304 [20:25<07:14,  5.92it/s]

2025-05-20 16:56:20,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:20,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:20,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6737/9304 [20:25<05:54,  7.24it/s]

2025-05-20 16:56:20,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6738/9304 [20:26<07:28,  5.72it/s]

2025-05-20 16:56:21,021 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6739/9304 [20:26<07:38,  5.59it/s]

2025-05-20 16:56:21,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:21,474 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6741/9304 [20:26<08:19,  5.13it/s]

2025-05-20 16:56:21,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6742/9304 [20:26<07:41,  5.56it/s]

2025-05-20 16:56:21,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:21,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6744/9304 [20:27<06:37,  6.44it/s]

2025-05-20 16:56:22,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 72%|███████▏  | 6745/9304 [20:27<08:24,  5.07it/s]

2025-05-20 16:56:22,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6746/9304 [20:27<07:48,  5.46it/s]

2025-05-20 16:56:22,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6747/9304 [20:27<07:34,  5.63it/s]

2025-05-20 16:56:22,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:22,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6749/9304 [20:28<06:30,  6.54it/s]

2025-05-20 16:56:22,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:22,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6751/9304 [20:28<06:21,  6.70it/s]

2025-05-20 16:56:23,366 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6752/9304 [20:28<08:19,  5.11it/s]

2025-05-20 16:56:23,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6753/9304 [20:29<10:57,  3.88it/s]

2025-05-20 16:56:23,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:23,934 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6755/9304 [20:29<07:28,  5.68it/s]

2025-05-20 16:56:23,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:24,147 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6757/9304 [20:29<06:24,  6.63it/s]

2025-05-20 16:56:24,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6758/9304 [20:29<06:12,  6.84it/s]

2025-05-20 16:56:24,380 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6759/9304 [20:29<05:49,  7.28it/s]

2025-05-20 16:56:24,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6760/9304 [20:29<06:12,  6.83it/s]

2025-05-20 16:56:24,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:25,050 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6762/9304 [20:30<07:58,  5.31it/s]

2025-05-20 16:56:25,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6763/9304 [20:30<08:56,  4.73it/s]

2025-05-20 16:56:25,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6764/9304 [20:30<07:56,  5.33it/s]

2025-05-20 16:56:25,820 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6765/9304 [20:31<09:52,  4.29it/s]

2025-05-20 16:56:25,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:25,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:25,979 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6768/9304 [20:31<05:53,  7.17it/s]

2025-05-20 16:56:26,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6769/9304 [20:31<06:51,  6.16it/s]

2025-05-20 16:56:26,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6770/9304 [20:31<06:42,  6.29it/s]

2025-05-20 16:56:26,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6771/9304 [20:31<06:21,  6.64it/s]

2025-05-20 16:56:26,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6772/9304 [20:32<06:58,  6.05it/s]

2025-05-20 16:56:26,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:27,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6774/9304 [20:32<08:48,  4.79it/s]

2025-05-20 16:56:27,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:27,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6776/9304 [20:32<07:58,  5.29it/s]

2025-05-20 16:56:27,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6777/9304 [20:33<08:19,  5.06it/s]

2025-05-20 16:56:27,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:27,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6779/9304 [20:33<06:16,  6.71it/s]

2025-05-20 16:56:28,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:28,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6781/9304 [20:33<07:40,  5.48it/s]

2025-05-20 16:56:28,587 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6782/9304 [20:33<07:32,  5.57it/s]

2025-05-20 16:56:28,900 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6783/9304 [20:34<08:45,  4.79it/s]

2025-05-20 16:56:29,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6784/9304 [20:34<09:54,  4.24it/s]

2025-05-20 16:56:29,524 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6785/9304 [20:34<10:36,  3.96it/s]

2025-05-20 16:56:29,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6786/9304 [20:34<09:13,  4.55it/s]

2025-05-20 16:56:29,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:29,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:29,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6789/9304 [20:35<05:31,  7.58it/s]

2025-05-20 16:56:29,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:30,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6791/9304 [20:35<07:27,  5.62it/s]

2025-05-20 16:56:30,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:30,721 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6793/9304 [20:36<07:30,  5.58it/s]

2025-05-20 16:56:30,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6794/9304 [20:36<07:01,  5.96it/s]

2025-05-20 16:56:31,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6795/9304 [20:36<08:39,  4.83it/s]

2025-05-20 16:56:31,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:31,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6797/9304 [20:36<06:20,  6.58it/s]

2025-05-20 16:56:31,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6798/9304 [20:36<06:17,  6.63it/s]

2025-05-20 16:56:31,836 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6799/9304 [20:37<08:28,  4.92it/s]

2025-05-20 16:56:31,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:31,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:32,146 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6802/9304 [20:37<06:24,  6.51it/s]

2025-05-20 16:56:32,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6803/9304 [20:37<08:32,  4.88it/s]

2025-05-20 16:56:32,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:32,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6805/9304 [20:38<08:12,  5.07it/s]

2025-05-20 16:56:32,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:33,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6807/9304 [20:38<06:49,  6.09it/s]

2025-05-20 16:56:33,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:33,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6809/9304 [20:38<06:16,  6.63it/s]

2025-05-20 16:56:33,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:33,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6811/9304 [20:39<07:01,  5.91it/s]

2025-05-20 16:56:33,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:34,366 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6813/9304 [20:39<08:32,  4.86it/s]

2025-05-20 16:56:34,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6814/9304 [20:39<08:37,  4.81it/s]

2025-05-20 16:56:34,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:34,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:34,725 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6817/9304 [20:40<05:40,  7.31it/s]

2025-05-20 16:56:34,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:35,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6819/9304 [20:40<06:31,  6.34it/s]

2025-05-20 16:56:35,612 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6820/9304 [20:40<08:47,  4.71it/s]

2025-05-20 16:56:35,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:35,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6822/9304 [20:41<07:27,  5.55it/s]

2025-05-20 16:56:35,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6823/9304 [20:41<06:52,  6.01it/s]

2025-05-20 16:56:35,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:36,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:36,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6826/9304 [20:41<05:21,  7.72it/s]

2025-05-20 16:56:36,414 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6827/9304 [20:41<05:59,  6.89it/s]

2025-05-20 16:56:36,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:37,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6829/9304 [20:42<10:25,  3.96it/s]

2025-05-20 16:56:37,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:37,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:37,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6832/9304 [20:42<06:44,  6.11it/s]

2025-05-20 16:56:37,886 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:37,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6834/9304 [20:43<07:25,  5.55it/s]

2025-05-20 16:56:37,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:38,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:38,259 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6837/9304 [20:43<06:22,  6.44it/s]

2025-05-20 16:56:38,579 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 73%|███████▎  | 6838/9304 [20:43<07:25,  5.54it/s]

2025-05-20 16:56:38,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6839/9304 [20:44<07:11,  5.71it/s]

2025-05-20 16:56:38,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:39,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6841/9304 [20:44<06:44,  6.10it/s]

2025-05-20 16:56:39,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6842/9304 [20:44<09:11,  4.46it/s]

2025-05-20 16:56:39,500 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:39,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:39,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6845/9304 [20:44<06:05,  6.72it/s]

2025-05-20 16:56:39,711 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:39,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6847/9304 [20:45<05:00,  8.16it/s]

2025-05-20 16:56:40,107 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:40,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6849/9304 [20:45<06:12,  6.58it/s]

2025-05-20 16:56:40,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:40,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6851/9304 [20:45<07:04,  5.78it/s]

2025-05-20 16:56:41,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6852/9304 [20:46<09:37,  4.25it/s]

2025-05-20 16:56:41,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:41,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:41,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6855/9304 [20:46<06:05,  6.70it/s]

2025-05-20 16:56:41,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:41,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6857/9304 [20:47<06:46,  6.01it/s]

2025-05-20 16:56:41,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:42,059 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6859/9304 [20:47<06:50,  5.96it/s]

2025-05-20 16:56:42,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6860/9304 [20:47<06:44,  6.04it/s]

2025-05-20 16:56:42,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▎  | 6861/9304 [20:47<06:53,  5.92it/s]

2025-05-20 16:56:42,470 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:42,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6863/9304 [20:48<06:52,  5.92it/s]

2025-05-20 16:56:42,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:42,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6865/9304 [20:48<05:20,  7.62it/s]

2025-05-20 16:56:43,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6866/9304 [20:48<06:59,  5.81it/s]

2025-05-20 16:56:43,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6867/9304 [20:48<09:31,  4.27it/s]

2025-05-20 16:56:43,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:43,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6869/9304 [20:49<07:50,  5.17it/s]

2025-05-20 16:56:43,960 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:43,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:44,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6872/9304 [20:49<06:15,  6.48it/s]

2025-05-20 16:56:44,345 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6873/9304 [20:49<06:00,  6.75it/s]

2025-05-20 16:56:44,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6874/9304 [20:50<08:53,  4.56it/s]

2025-05-20 16:56:44,857 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:44,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:45,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6877/9304 [20:50<08:53,  4.55it/s]

2025-05-20 16:56:45,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:45,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6879/9304 [20:50<06:55,  5.84it/s]

2025-05-20 16:56:45,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6880/9304 [20:51<06:42,  6.02it/s]

2025-05-20 16:56:45,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:45,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6882/9304 [20:51<05:25,  7.44it/s]

2025-05-20 16:56:45,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:46,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6884/9304 [20:51<07:26,  5.42it/s]

2025-05-20 16:56:46,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:46,603 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6886/9304 [20:51<05:47,  6.97it/s]

2025-05-20 16:56:46,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:47,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6888/9304 [20:52<07:04,  5.68it/s]

2025-05-20 16:56:47,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6889/9304 [20:52<07:54,  5.09it/s]

2025-05-20 16:56:47,418 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:47,431 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:47,552 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6892/9304 [20:52<05:29,  7.32it/s]

2025-05-20 16:56:47,912 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:48,116 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6894/9304 [20:53<07:06,  5.66it/s]

2025-05-20 16:56:48,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6895/9304 [20:53<07:24,  5.41it/s]

2025-05-20 16:56:48,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6896/9304 [20:53<07:02,  5.70it/s]

2025-05-20 16:56:48,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:48,928 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6898/9304 [20:54<07:47,  5.15it/s]

2025-05-20 16:56:49,108 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6899/9304 [20:54<07:38,  5.24it/s]

2025-05-20 16:56:49,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:49,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6901/9304 [20:54<06:54,  5.80it/s]

2025-05-20 16:56:49,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6902/9304 [20:54<07:28,  5.36it/s]

2025-05-20 16:56:49,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6903/9304 [20:55<08:24,  4.76it/s]

2025-05-20 16:56:49,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:50,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:50,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6905/9304 [20:55<08:14,  4.85it/s]

2025-05-20 16:56:50,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6907/9304 [20:55<06:17,  6.35it/s]

2025-05-20 16:56:50,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:50,599 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6909/9304 [20:55<05:07,  7.79it/s]

2025-05-20 16:56:50,905 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6910/9304 [20:56<06:27,  6.18it/s]

2025-05-20 16:56:51,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6911/9304 [20:56<06:35,  6.05it/s]

2025-05-20 16:56:51,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6912/9304 [20:56<07:06,  5.61it/s]

2025-05-20 16:56:51,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6913/9304 [20:57<09:12,  4.32it/s]

2025-05-20 16:56:51,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:51,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6915/9304 [20:57<06:50,  5.82it/s]

2025-05-20 16:56:52,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6916/9304 [20:57<06:38,  6.00it/s]

2025-05-20 16:56:52,097 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:52,259 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6918/9304 [20:57<05:55,  6.72it/s]

2025-05-20 16:56:52,369 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6919/9304 [20:57<05:34,  7.13it/s]

2025-05-20 16:56:52,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6920/9304 [20:57<05:48,  6.83it/s]

2025-05-20 16:56:52,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6921/9304 [20:58<06:43,  5.91it/s]

2025-05-20 16:56:53,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6922/9304 [20:58<07:42,  5.16it/s]

2025-05-20 16:56:53,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6923/9304 [20:58<07:35,  5.23it/s]

2025-05-20 16:56:53,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6924/9304 [20:58<06:48,  5.83it/s]

2025-05-20 16:56:53,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6925/9304 [20:58<06:29,  6.10it/s]

2025-05-20 16:56:53,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6926/9304 [20:58<05:49,  6.81it/s]

2025-05-20 16:56:53,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:53,709 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6927/9304 [20:59<05:32,  7.16it/s]

2025-05-20 16:56:53,711 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:53,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 74%|███████▍  | 6930/9304 [20:59<04:11,  9.43it/s]

2025-05-20 16:56:53,991 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:54,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6932/9304 [20:59<06:58,  5.67it/s]

2025-05-20 16:56:54,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6933/9304 [21:00<07:38,  5.17it/s]

2025-05-20 16:56:54,953 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6934/9304 [21:00<07:01,  5.62it/s]

2025-05-20 16:56:55,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6935/9304 [21:00<07:18,  5.40it/s]

2025-05-20 16:56:55,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:55,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6937/9304 [21:00<05:12,  7.57it/s]

2025-05-20 16:56:55,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:55,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6939/9304 [21:00<05:19,  7.41it/s]

2025-05-20 16:56:55,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6940/9304 [21:01<06:42,  5.88it/s]

2025-05-20 16:56:56,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6941/9304 [21:01<07:23,  5.33it/s]

2025-05-20 16:56:56,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6942/9304 [21:01<08:29,  4.63it/s]

2025-05-20 16:56:56,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6943/9304 [21:02<09:29,  4.15it/s]

2025-05-20 16:56:56,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6944/9304 [21:02<08:47,  4.47it/s]

2025-05-20 16:56:56,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:57,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6946/9304 [21:02<06:45,  5.81it/s]

2025-05-20 16:56:57,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6947/9304 [21:02<07:09,  5.48it/s]

2025-05-20 16:56:57,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:57,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6949/9304 [21:03<07:07,  5.51it/s]

2025-05-20 16:56:58,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6950/9304 [21:03<09:44,  4.03it/s]

2025-05-20 16:56:58,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:58,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6952/9304 [21:03<07:42,  5.09it/s]

2025-05-20 16:56:58,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6953/9304 [21:03<07:13,  5.42it/s]

2025-05-20 16:56:58,616 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:58,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:58,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6955/9304 [21:04<06:39,  5.89it/s]

2025-05-20 16:56:59,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6957/9304 [21:04<05:42,  6.85it/s]

2025-05-20 16:56:59,042 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:59,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6959/9304 [21:04<07:05,  5.52it/s]

2025-05-20 16:56:59,590 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:56:59,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6961/9304 [21:05<06:51,  5.69it/s]

2025-05-20 16:57:00,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6962/9304 [21:05<07:26,  5.24it/s]

2025-05-20 16:57:00,365 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6963/9304 [21:05<07:55,  4.93it/s]

2025-05-20 16:57:00,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:00,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6965/9304 [21:05<05:43,  6.82it/s]

2025-05-20 16:57:00,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6966/9304 [21:05<05:57,  6.55it/s]

2025-05-20 16:57:00,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:00,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6968/9304 [21:06<04:36,  8.44it/s]

2025-05-20 16:57:01,324 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:01,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6970/9304 [21:06<08:33,  4.54it/s]

2025-05-20 16:57:01,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6971/9304 [21:07<07:47,  4.99it/s]

2025-05-20 16:57:01,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6972/9304 [21:07<07:38,  5.08it/s]

2025-05-20 16:57:02,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6973/9304 [21:07<07:29,  5.19it/s]

2025-05-20 16:57:02,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:02,146 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:02,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▍  | 6976/9304 [21:07<04:34,  8.49it/s]

2025-05-20 16:57:02,639 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:02,739 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6978/9304 [21:08<06:26,  6.02it/s]

2025-05-20 16:57:02,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:03,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6980/9304 [21:08<07:26,  5.20it/s]

2025-05-20 16:57:03,399 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6981/9304 [21:08<07:17,  5.31it/s]

2025-05-20 16:57:03,419 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:03,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6983/9304 [21:08<05:28,  7.06it/s]

2025-05-20 16:57:03,747 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:03,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6985/9304 [21:09<06:11,  6.24it/s]

2025-05-20 16:57:04,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6986/9304 [21:09<06:52,  5.61it/s]

2025-05-20 16:57:04,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6987/9304 [21:09<06:49,  5.65it/s]

2025-05-20 16:57:04,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6988/9304 [21:09<06:20,  6.08it/s]

2025-05-20 16:57:04,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6989/9304 [21:10<08:48,  4.38it/s]

2025-05-20 16:57:04,971 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:05,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6991/9304 [21:10<08:30,  4.53it/s]

2025-05-20 16:57:05,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:05,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:05,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6994/9304 [21:10<05:09,  7.47it/s]

2025-05-20 16:57:05,620 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:05,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6996/9304 [21:10<05:00,  7.67it/s]

2025-05-20 16:57:05,874 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:06,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 6998/9304 [21:11<09:04,  4.24it/s]

2025-05-20 16:57:06,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:06,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7000/9304 [21:12<07:46,  4.94it/s]

2025-05-20 16:57:07,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:07,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7001/9304 [21:12<07:49,  4.90it/s]

2025-05-20 16:57:07,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:07,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7004/9304 [21:12<05:14,  7.32it/s]

2025-05-20 16:57:07,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:08,097 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7006/9304 [21:13<08:40,  4.41it/s]

2025-05-20 16:57:08,365 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:08,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7007/9304 [21:13<08:56,  4.28it/s]

2025-05-20 16:57:08,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:08,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7010/9304 [21:13<06:33,  5.83it/s]

2025-05-20 16:57:08,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:08,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:08,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7013/9304 [21:14<05:04,  7.53it/s]

2025-05-20 16:57:09,139 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:09,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7015/9304 [21:15<08:23,  4.54it/s]

2025-05-20 16:57:09,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:09,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:10,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7018/9304 [21:15<06:32,  5.83it/s]

2025-05-20 16:57:10,129 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7019/9304 [21:15<06:09,  6.19it/s]

2025-05-20 16:57:10,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7020/9304 [21:15<06:28,  5.87it/s]

2025-05-20 16:57:10,612 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7021/9304 [21:15<07:16,  5.24it/s]

2025-05-20 16:57:11,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7022/9304 [21:16<10:45,  3.54it/s]

2025-05-20 16:57:11,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 75%|███████▌  | 7023/9304 [21:16<09:36,  3.96it/s]

2025-05-20 16:57:11,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:11,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7025/9304 [21:16<06:51,  5.54it/s]

2025-05-20 16:57:11,744 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7026/9304 [21:17<07:11,  5.28it/s]

2025-05-20 16:57:11,833 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:11,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7028/9304 [21:17<05:19,  7.13it/s]

2025-05-20 16:57:12,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7029/9304 [21:17<08:57,  4.24it/s]

2025-05-20 16:57:12,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:12,539 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:12,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7032/9304 [21:18<06:54,  5.48it/s]

2025-05-20 16:57:12,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7033/9304 [21:18<06:45,  5.59it/s]

2025-05-20 16:57:13,045 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:13,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7035/9304 [21:18<07:09,  5.28it/s]

2025-05-20 16:57:13,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7036/9304 [21:18<06:37,  5.71it/s]

2025-05-20 16:57:13,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7037/9304 [21:18<06:00,  6.29it/s]

2025-05-20 16:57:13,725 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:14,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7039/9304 [21:19<06:33,  5.76it/s]

2025-05-20 16:57:14,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7040/9304 [21:19<08:32,  4.42it/s]

2025-05-20 16:57:14,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:14,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:14,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7043/9304 [21:20<06:26,  5.85it/s]

2025-05-20 16:57:14,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7044/9304 [21:20<06:29,  5.81it/s]

2025-05-20 16:57:14,966 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:15,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7046/9304 [21:20<06:41,  5.63it/s]

2025-05-20 16:57:15,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:15,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7047/9304 [21:20<07:41,  4.89it/s]

2025-05-20 16:57:16,446 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7049/9304 [21:21<10:25,  3.61it/s]

2025-05-20 16:57:16,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:16,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:16,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7052/9304 [21:21<06:26,  5.82it/s]

2025-05-20 16:57:16,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:17,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7054/9304 [21:22<07:01,  5.33it/s]

2025-05-20 16:57:17,198 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7055/9304 [21:22<07:01,  5.34it/s]

2025-05-20 16:57:17,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7056/9304 [21:22<06:22,  5.87it/s]

2025-05-20 16:57:17,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7057/9304 [21:23<08:30,  4.40it/s]

2025-05-20 16:57:17,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7058/9304 [21:23<08:21,  4.48it/s]

2025-05-20 16:57:18,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7059/9304 [21:23<07:13,  5.18it/s]

2025-05-20 16:57:18,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7060/9304 [21:23<08:13,  4.54it/s]

2025-05-20 16:57:18,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7061/9304 [21:23<07:47,  4.80it/s]

2025-05-20 16:57:18,839 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7062/9304 [21:24<09:01,  4.14it/s]

2025-05-20 16:57:18,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:18,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7064/9304 [21:24<06:12,  6.01it/s]

2025-05-20 16:57:19,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:19,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7066/9304 [21:24<04:38,  8.03it/s]

2025-05-20 16:57:19,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:19,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7068/9304 [21:24<05:15,  7.09it/s]

2025-05-20 16:57:19,657 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7069/9304 [21:24<05:51,  6.35it/s]

2025-05-20 16:57:19,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7070/9304 [21:25<06:27,  5.76it/s]

2025-05-20 16:57:19,983 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:20,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7072/9304 [21:25<06:23,  5.82it/s]

2025-05-20 16:57:20,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7073/9304 [21:25<06:17,  5.90it/s]

2025-05-20 16:57:20,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7074/9304 [21:25<06:43,  5.52it/s]

2025-05-20 16:57:20,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7075/9304 [21:26<07:59,  4.65it/s]

2025-05-20 16:57:20,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:21,007 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:21,166 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7078/9304 [21:26<05:20,  6.94it/s]

2025-05-20 16:57:21,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7079/9304 [21:26<05:07,  7.23it/s]

2025-05-20 16:57:21,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:21,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7081/9304 [21:26<04:51,  7.62it/s]

2025-05-20 16:57:22,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:22,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7082/9304 [21:27<08:19,  4.45it/s]

2025-05-20 16:57:22,542 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:22,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7084/9304 [21:27<08:14,  4.49it/s]

2025-05-20 16:57:22,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:22,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7087/9304 [21:28<05:27,  6.77it/s]

2025-05-20 16:57:22,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:22,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7089/9304 [21:28<04:26,  8.31it/s]

2025-05-20 16:57:23,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:23,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7091/9304 [21:28<05:47,  6.37it/s]

2025-05-20 16:57:23,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7092/9304 [21:28<06:23,  5.77it/s]

2025-05-20 16:57:23,871 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7093/9304 [21:29<07:28,  4.93it/s]

2025-05-20 16:57:24,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▌  | 7094/9304 [21:29<07:34,  4.86it/s]

2025-05-20 16:57:24,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:24,180 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:24,251 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7097/9304 [21:29<04:50,  7.59it/s]

2025-05-20 16:57:24,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7098/9304 [21:29<04:53,  7.52it/s]

2025-05-20 16:57:24,542 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7099/9304 [21:29<05:02,  7.29it/s]

2025-05-20 16:57:24,735 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7100/9304 [21:30<05:31,  6.65it/s]

2025-05-20 16:57:25,142 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7101/9304 [21:30<07:51,  4.67it/s]

2025-05-20 16:57:25,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7102/9304 [21:30<07:01,  5.23it/s]

2025-05-20 16:57:25,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7103/9304 [21:31<09:21,  3.92it/s]

2025-05-20 16:57:25,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:25,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:25,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7106/9304 [21:31<06:14,  5.87it/s]

2025-05-20 16:57:26,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7107/9304 [21:31<05:44,  6.37it/s]

2025-05-20 16:57:26,172 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:26,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:26,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7110/9304 [21:31<04:08,  8.81it/s]

2025-05-20 16:57:26,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:26,659 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7112/9304 [21:31<04:59,  7.33it/s]

2025-05-20 16:57:26,766 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7113/9304 [21:32<04:47,  7.61it/s]

2025-05-20 16:57:27,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7114/9304 [21:32<06:16,  5.82it/s]

2025-05-20 16:57:27,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:27,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 76%|███████▋  | 7116/9304 [21:32<06:46,  5.38it/s]

2025-05-20 16:57:27,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:27,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:27,806 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7119/9304 [21:33<05:20,  6.82it/s]

2025-05-20 16:57:27,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7120/9304 [21:33<05:28,  6.65it/s]

2025-05-20 16:57:28,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7121/9304 [21:33<08:03,  4.51it/s]

2025-05-20 16:57:28,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:28,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7123/9304 [21:33<06:03,  6.00it/s]

2025-05-20 16:57:28,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7124/9304 [21:34<06:03,  5.99it/s]

2025-05-20 16:57:28,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7125/9304 [21:34<06:18,  5.76it/s]

2025-05-20 16:57:29,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7126/9304 [21:34<06:39,  5.46it/s]

2025-05-20 16:57:29,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:29,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7128/9304 [21:34<04:52,  7.43it/s]

2025-05-20 16:57:29,612 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7129/9304 [21:34<06:06,  5.94it/s]

2025-05-20 16:57:29,716 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7130/9304 [21:35<05:31,  6.55it/s]

2025-05-20 16:57:29,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7131/9304 [21:35<06:28,  5.59it/s]

2025-05-20 16:57:30,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7132/9304 [21:35<06:38,  5.44it/s]

2025-05-20 16:57:30,238 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:30,620 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7134/9304 [21:35<07:24,  4.89it/s]

2025-05-20 16:57:30,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7135/9304 [21:36<07:11,  5.03it/s]

2025-05-20 16:57:30,821 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:30,833 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:31,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7138/9304 [21:36<04:47,  7.53it/s]

2025-05-20 16:57:31,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7139/9304 [21:36<05:02,  7.16it/s]

2025-05-20 16:57:31,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:31,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7141/9304 [21:36<05:56,  6.07it/s]

2025-05-20 16:57:31,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7142/9304 [21:37<05:28,  6.58it/s]

2025-05-20 16:57:31,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7143/9304 [21:37<05:48,  6.20it/s]

2025-05-20 16:57:32,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7144/9304 [21:37<07:45,  4.64it/s]

2025-05-20 16:57:32,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:32,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7146/9304 [21:37<05:46,  6.23it/s]

2025-05-20 16:57:32,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:32,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7148/9304 [21:37<04:49,  7.44it/s]

2025-05-20 16:57:32,637 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:32,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:33,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7151/9304 [21:38<05:48,  6.17it/s]

2025-05-20 16:57:33,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:33,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7152/9304 [21:38<05:37,  6.38it/s]

2025-05-20 16:57:33,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7154/9304 [21:38<04:38,  7.73it/s]

2025-05-20 16:57:33,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7155/9304 [21:39<06:08,  5.84it/s]

2025-05-20 16:57:33,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:34,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7157/9304 [21:39<05:13,  6.85it/s]

2025-05-20 16:57:34,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:34,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7158/9304 [21:39<06:22,  5.60it/s]

2025-05-20 16:57:35,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7160/9304 [21:40<08:33,  4.18it/s]

2025-05-20 16:57:35,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:35,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7162/9304 [21:40<06:31,  5.48it/s]

2025-05-20 16:57:35,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7163/9304 [21:40<06:40,  5.35it/s]

2025-05-20 16:57:35,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:35,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7165/9304 [21:40<05:53,  6.05it/s]

2025-05-20 16:57:35,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:35,945 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7167/9304 [21:41<05:40,  6.27it/s]

2025-05-20 16:57:36,222 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7168/9304 [21:41<06:31,  5.46it/s]

2025-05-20 16:57:36,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7169/9304 [21:41<06:40,  5.33it/s]

2025-05-20 16:57:36,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:36,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7171/9304 [21:42<05:55,  6.00it/s]

2025-05-20 16:57:36,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7172/9304 [21:42<05:40,  6.25it/s]

2025-05-20 16:57:37,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:37,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7173/9304 [21:42<07:58,  4.45it/s]

2025-05-20 16:57:37,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:37,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7176/9304 [21:42<05:27,  6.50it/s]

2025-05-20 16:57:37,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7177/9304 [21:42<05:21,  6.62it/s]

2025-05-20 16:57:37,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7178/9304 [21:43<06:51,  5.17it/s]

2025-05-20 16:57:38,126 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7179/9304 [21:43<06:15,  5.65it/s]

2025-05-20 16:57:38,199 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:38,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7181/9304 [21:43<06:44,  5.25it/s]

2025-05-20 16:57:38,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7182/9304 [21:44<06:23,  5.53it/s]

2025-05-20 16:57:38,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7183/9304 [21:44<06:23,  5.53it/s]

2025-05-20 16:57:38,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7184/9304 [21:44<05:41,  6.22it/s]

2025-05-20 16:57:38,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:39,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7186/9304 [21:44<04:21,  8.11it/s]

2025-05-20 16:57:39,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7187/9304 [21:44<05:01,  7.02it/s]

2025-05-20 16:57:39,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:39,542 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7189/9304 [21:44<04:33,  7.74it/s]

2025-05-20 16:57:40,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7190/9304 [21:45<08:52,  3.97it/s]

2025-05-20 16:57:40,241 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:40,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7192/9304 [21:45<07:24,  4.75it/s]

2025-05-20 16:57:40,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:40,604 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:40,620 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7195/9304 [21:45<04:37,  7.59it/s]

2025-05-20 16:57:40,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:41,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7197/9304 [21:46<06:51,  5.12it/s]

2025-05-20 16:57:41,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7198/9304 [21:46<07:07,  4.93it/s]

2025-05-20 16:57:41,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:41,698 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7200/9304 [21:47<05:37,  6.24it/s]

2025-05-20 16:57:42,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7201/9304 [21:47<06:37,  5.29it/s]

2025-05-20 16:57:42,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:42,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7203/9304 [21:47<05:26,  6.44it/s]

2025-05-20 16:57:42,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:42,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7205/9304 [21:48<07:55,  4.41it/s]

2025-05-20 16:57:42,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:43,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:43,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7208/9304 [21:48<05:07,  6.82it/s]

2025-05-20 16:57:43,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:43,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 77%|███████▋  | 7210/9304 [21:48<06:20,  5.50it/s]

2025-05-20 16:57:43,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:44,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7212/9304 [21:49<06:36,  5.27it/s]

2025-05-20 16:57:44,227 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7213/9304 [21:49<06:49,  5.11it/s]

2025-05-20 16:57:44,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:44,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7214/9304 [21:49<06:53,  5.05it/s]

2025-05-20 16:57:44,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7216/9304 [21:49<05:26,  6.40it/s]

2025-05-20 16:57:44,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:45,050 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7218/9304 [21:50<06:16,  5.54it/s]

2025-05-20 16:57:45,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:45,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7220/9304 [21:50<07:14,  4.79it/s]

2025-05-20 16:57:45,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7221/9304 [21:51<08:05,  4.29it/s]

2025-05-20 16:57:45,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:46,026 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:46,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7224/9304 [21:51<06:05,  5.70it/s]

2025-05-20 16:57:46,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:46,720 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7226/9304 [21:52<06:47,  5.10it/s]

2025-05-20 16:57:46,843 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7227/9304 [21:52<06:18,  5.48it/s]

2025-05-20 16:57:47,064 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7228/9304 [21:52<06:34,  5.26it/s]

2025-05-20 16:57:47,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7229/9304 [21:52<06:31,  5.30it/s]

2025-05-20 16:57:47,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:47,433 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7231/9304 [21:52<05:13,  6.60it/s]

2025-05-20 16:57:48,012 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7232/9304 [21:53<08:27,  4.09it/s]

2025-05-20 16:57:48,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:48,433 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7234/9304 [21:53<07:58,  4.33it/s]

2025-05-20 16:57:48,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7235/9304 [21:53<08:02,  4.28it/s]

2025-05-20 16:57:48,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7236/9304 [21:54<07:28,  4.61it/s]

2025-05-20 16:57:48,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:49,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7238/9304 [21:54<06:16,  5.49it/s]

2025-05-20 16:57:49,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:49,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7240/9304 [21:55<08:19,  4.13it/s]

2025-05-20 16:57:49,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:50,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7242/9304 [21:55<08:02,  4.28it/s]

2025-05-20 16:57:50,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:50,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7244/9304 [21:55<06:01,  5.69it/s]

2025-05-20 16:57:50,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7245/9304 [21:55<05:34,  6.16it/s]

2025-05-20 16:57:50,654 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7246/9304 [21:55<05:55,  5.80it/s]

2025-05-20 16:57:51,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7247/9304 [21:56<07:20,  4.67it/s]

2025-05-20 16:57:51,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:51,235 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7249/9304 [21:56<05:57,  5.76it/s]

2025-05-20 16:57:51,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7250/9304 [21:56<06:06,  5.61it/s]

2025-05-20 16:57:51,567 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7251/9304 [21:56<06:00,  5.69it/s]

2025-05-20 16:57:51,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:52,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7253/9304 [21:57<07:28,  4.57it/s]

2025-05-20 16:57:52,270 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7254/9304 [21:57<06:40,  5.11it/s]

2025-05-20 16:57:52,374 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7255/9304 [21:57<05:58,  5.71it/s]

2025-05-20 16:57:52,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7256/9304 [21:57<06:03,  5.63it/s]

2025-05-20 16:57:52,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7257/9304 [21:58<06:50,  4.98it/s]

2025-05-20 16:57:53,040 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7258/9304 [21:58<06:53,  4.94it/s]

2025-05-20 16:57:53,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7259/9304 [21:58<06:51,  4.97it/s]

2025-05-20 16:57:53,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:53,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7261/9304 [21:59<09:18,  3.66it/s]

2025-05-20 16:57:54,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:54,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7263/9304 [21:59<06:27,  5.26it/s]

2025-05-20 16:57:54,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7264/9304 [21:59<06:01,  5.65it/s]

2025-05-20 16:57:54,243 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:54,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7266/9304 [21:59<05:47,  5.86it/s]

2025-05-20 16:57:54,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7267/9304 [22:00<07:54,  4.29it/s]

2025-05-20 16:57:55,217 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7268/9304 [22:00<07:48,  4.34it/s]

2025-05-20 16:57:55,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7269/9304 [22:00<07:01,  4.83it/s]

2025-05-20 16:57:55,468 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7270/9304 [22:00<06:12,  5.46it/s]

2025-05-20 16:57:55,568 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7271/9304 [22:00<05:30,  6.15it/s]

2025-05-20 16:57:55,622 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:55,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:55,982 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7274/9304 [22:01<04:59,  6.78it/s]

2025-05-20 16:57:56,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:56,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7276/9304 [22:01<03:56,  8.58it/s]

2025-05-20 16:57:56,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:57,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7278/9304 [22:02<08:14,  4.09it/s]

2025-05-20 16:57:57,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7279/9304 [22:02<07:23,  4.56it/s]

2025-05-20 16:57:57,270 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:57,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:57,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7282/9304 [22:02<04:56,  6.81it/s]

2025-05-20 16:57:57,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:57,514 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7284/9304 [22:02<04:04,  8.27it/s]

2025-05-20 16:57:57,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:57,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7286/9304 [22:03<04:43,  7.11it/s]

2025-05-20 16:57:58,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:58,599 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7288/9304 [22:03<06:53,  4.88it/s]

2025-05-20 16:57:58,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7289/9304 [22:04<06:45,  4.97it/s]

2025-05-20 16:57:58,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:58,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:58,894 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7291/9304 [22:04<05:04,  6.61it/s]

2025-05-20 16:57:58,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7293/9304 [22:04<04:05,  8.19it/s]

2025-05-20 16:57:59,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:59,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7295/9304 [22:04<04:16,  7.84it/s]

2025-05-20 16:57:59,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:57:59,810 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7297/9304 [22:05<05:43,  5.83it/s]

2025-05-20 16:58:00,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7298/9304 [22:05<06:56,  4.81it/s]

2025-05-20 16:58:00,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7299/9304 [22:05<06:37,  5.04it/s]

2025-05-20 16:58:00,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:00,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:00,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 78%|███████▊  | 7302/9304 [22:05<04:03,  8.21it/s]

2025-05-20 16:58:00,474 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:00,612 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7304/9304 [22:05<03:35,  9.29it/s]

2025-05-20 16:58:00,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:01,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7306/9304 [22:06<05:44,  5.80it/s]

2025-05-20 16:58:01,559 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:01,825 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7308/9304 [22:07<06:51,  4.84it/s]

2025-05-20 16:58:01,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:01,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7310/9304 [22:07<05:22,  6.17it/s]

2025-05-20 16:58:02,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:02,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7312/9304 [22:07<06:03,  5.48it/s]

2025-05-20 16:58:02,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7313/9304 [22:08<07:05,  4.68it/s]

2025-05-20 16:58:02,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7314/9304 [22:08<06:26,  5.14it/s]

2025-05-20 16:58:03,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7315/9304 [22:08<06:32,  5.07it/s]

2025-05-20 16:58:03,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7316/9304 [22:08<05:50,  5.68it/s]

2025-05-20 16:58:03,336 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:03,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7317/9304 [22:08<05:36,  5.90it/s]

2025-05-20 16:58:03,408 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:03,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7320/9304 [22:08<03:35,  9.20it/s]

2025-05-20 16:58:03,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:04,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7322/9304 [22:09<06:10,  5.35it/s]

2025-05-20 16:58:04,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7323/9304 [22:09<05:46,  5.72it/s]

2025-05-20 16:58:04,371 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:04,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7325/9304 [22:09<05:12,  6.33it/s]

2025-05-20 16:58:04,974 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▊  | 7326/9304 [22:10<06:52,  4.80it/s]

2025-05-20 16:58:05,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:05,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:05,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:05,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7330/9304 [22:10<04:40,  7.04it/s]

2025-05-20 16:58:05,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7331/9304 [22:11<05:49,  5.65it/s]

2025-05-20 16:58:05,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:05,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7333/9304 [22:11<04:54,  6.68it/s]

2025-05-20 16:58:05,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7334/9304 [22:11<04:45,  6.90it/s]

2025-05-20 16:58:06,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7335/9304 [22:11<05:00,  6.55it/s]

2025-05-20 16:58:06,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7336/9304 [22:11<06:13,  5.26it/s]

2025-05-20 16:58:06,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:06,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7338/9304 [22:11<04:30,  7.28it/s]

2025-05-20 16:58:06,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:06,732 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7340/9304 [22:12<03:42,  8.82it/s]

2025-05-20 16:58:06,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:07,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7342/9304 [22:12<04:57,  6.59it/s]

2025-05-20 16:58:07,289 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7343/9304 [22:12<04:38,  7.04it/s]

2025-05-20 16:58:07,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7344/9304 [22:12<05:51,  5.58it/s]

2025-05-20 16:58:08,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7345/9304 [22:13<07:45,  4.20it/s]

2025-05-20 16:58:08,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7346/9304 [22:13<07:41,  4.24it/s]

2025-05-20 16:58:08,268 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:08,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:08,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7349/9304 [22:13<04:18,  7.55it/s]

2025-05-20 16:58:08,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:08,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7351/9304 [22:13<04:07,  7.90it/s]

2025-05-20 16:58:08,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:09,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7353/9304 [22:14<05:12,  6.24it/s]

2025-05-20 16:58:09,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7354/9304 [22:14<05:44,  5.65it/s]

2025-05-20 16:58:09,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:09,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7356/9304 [22:14<05:00,  6.49it/s]

2025-05-20 16:58:09,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:09,785 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7357/9304 [22:15<05:38,  5.75it/s]

2025-05-20 16:58:10,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7359/9304 [22:15<05:03,  6.41it/s]

2025-05-20 16:58:10,170 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7360/9304 [22:15<04:54,  6.60it/s]

2025-05-20 16:58:10,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7361/9304 [22:15<06:12,  5.22it/s]

2025-05-20 16:58:10,691 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7362/9304 [22:16<06:17,  5.14it/s]

2025-05-20 16:58:10,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7363/9304 [22:16<05:46,  5.60it/s]

2025-05-20 16:58:10,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:11,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7365/9304 [22:16<05:31,  5.86it/s]

2025-05-20 16:58:11,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:11,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7367/9304 [22:16<04:54,  6.57it/s]

2025-05-20 16:58:11,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:11,474 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:11,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7370/9304 [22:16<04:01,  8.00it/s]

2025-05-20 16:58:12,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7371/9304 [22:17<05:24,  5.96it/s]

2025-05-20 16:58:12,152 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7372/9304 [22:17<05:03,  6.37it/s]

2025-05-20 16:58:12,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:12,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7373/9304 [22:17<05:31,  5.83it/s]

2025-05-20 16:58:12,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7375/9304 [22:17<04:13,  7.61it/s]

2025-05-20 16:58:12,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:12,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7377/9304 [22:17<03:21,  9.57it/s]

2025-05-20 16:58:12,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:13,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7379/9304 [22:18<04:22,  7.34it/s]

2025-05-20 16:58:13,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7380/9304 [22:18<04:09,  7.70it/s]

2025-05-20 16:58:13,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7381/9304 [22:18<05:34,  5.74it/s]

2025-05-20 16:58:13,744 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7382/9304 [22:19<06:25,  4.99it/s]

2025-05-20 16:58:13,892 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7383/9304 [22:19<05:59,  5.35it/s]

2025-05-20 16:58:13,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:13,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:14,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7386/9304 [22:19<03:44,  8.55it/s]

2025-05-20 16:58:14,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:14,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7388/9304 [22:19<05:47,  5.52it/s]

2025-05-20 16:58:14,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:14,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7390/9304 [22:20<04:46,  6.67it/s]

2025-05-20 16:58:15,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7391/9304 [22:20<05:27,  5.84it/s]

2025-05-20 16:58:15,296 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7392/9304 [22:20<05:35,  5.69it/s]

2025-05-20 16:58:15,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7393/9304 [22:20<06:22,  4.99it/s]

2025-05-20 16:58:15,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7394/9304 [22:21<06:29,  4.90it/s]

2025-05-20 16:58:15,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 79%|███████▉  | 7395/9304 [22:21<06:04,  5.24it/s]

2025-05-20 16:58:16,017 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:16,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7397/9304 [22:21<04:12,  7.54it/s]

2025-05-20 16:58:16,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:16,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7399/9304 [22:21<03:49,  8.31it/s]

2025-05-20 16:58:16,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:16,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7401/9304 [22:21<03:33,  8.91it/s]

2025-05-20 16:58:16,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7402/9304 [22:22<04:44,  6.68it/s]

2025-05-20 16:58:17,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7403/9304 [22:22<07:56,  3.99it/s]

2025-05-20 16:58:17,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7404/9304 [22:22<07:22,  4.29it/s]

2025-05-20 16:58:17,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:17,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7406/9304 [22:23<06:30,  4.85it/s]

2025-05-20 16:58:17,974 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7407/9304 [22:23<05:49,  5.43it/s]

2025-05-20 16:58:18,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:18,080 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7409/9304 [22:23<04:15,  7.43it/s]

2025-05-20 16:58:18,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:18,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7411/9304 [22:24<06:59,  4.52it/s]

2025-05-20 16:58:18,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:19,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7413/9304 [22:24<06:15,  5.03it/s]

2025-05-20 16:58:19,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7414/9304 [22:24<06:03,  5.21it/s]

2025-05-20 16:58:19,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7415/9304 [22:24<06:05,  5.17it/s]

2025-05-20 16:58:19,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:19,543 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:19,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:19,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7419/9304 [22:25<04:06,  7.66it/s]

2025-05-20 16:58:20,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7420/9304 [22:25<06:42,  4.68it/s]

2025-05-20 16:58:20,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7421/9304 [22:26<07:02,  4.45it/s]

2025-05-20 16:58:20,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:20,818 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:20,867 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7424/9304 [22:26<04:31,  6.94it/s]

2025-05-20 16:58:20,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:21,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7426/9304 [22:26<04:13,  7.40it/s]

2025-05-20 16:58:21,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:21,566 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7428/9304 [22:26<05:09,  6.07it/s]

2025-05-20 16:58:22,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7429/9304 [22:27<07:44,  4.04it/s]

2025-05-20 16:58:22,332 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7430/9304 [22:27<06:58,  4.48it/s]

2025-05-20 16:58:22,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:22,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7432/9304 [22:27<05:07,  6.09it/s]

2025-05-20 16:58:22,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7433/9304 [22:27<04:44,  6.58it/s]

2025-05-20 16:58:22,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7434/9304 [22:28<04:28,  6.97it/s]

2025-05-20 16:58:22,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7435/9304 [22:28<04:41,  6.64it/s]

2025-05-20 16:58:23,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7436/9304 [22:28<05:45,  5.40it/s]

2025-05-20 16:58:23,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7437/9304 [22:29<10:56,  2.84it/s]

2025-05-20 16:58:24,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7438/9304 [22:29<09:33,  3.25it/s]

2025-05-20 16:58:24,150 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:24,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:24,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:24,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|███████▉  | 7442/9304 [22:29<04:16,  7.26it/s]

2025-05-20 16:58:24,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:24,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7444/9304 [22:29<04:13,  7.33it/s]

2025-05-20 16:58:24,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:24,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7446/9304 [22:30<03:53,  7.97it/s]

2025-05-20 16:58:25,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:25,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7448/9304 [22:30<06:51,  4.51it/s]

2025-05-20 16:58:25,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:25,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7450/9304 [22:31<05:22,  5.75it/s]

2025-05-20 16:58:25,843 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:25,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7452/9304 [22:31<04:34,  6.74it/s]

2025-05-20 16:58:26,007 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:26,135 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7454/9304 [22:31<04:14,  7.26it/s]

2025-05-20 16:58:26,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:26,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7456/9304 [22:31<05:18,  5.80it/s]

2025-05-20 16:58:26,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7457/9304 [22:32<06:00,  5.13it/s]

2025-05-20 16:58:27,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:27,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7459/9304 [22:32<04:31,  6.80it/s]

2025-05-20 16:58:27,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:27,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7461/9304 [22:32<03:33,  8.62it/s]

2025-05-20 16:58:27,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:27,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7463/9304 [22:32<04:31,  6.78it/s]

2025-05-20 16:58:27,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:28,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7465/9304 [22:33<06:08,  5.00it/s]

2025-05-20 16:58:28,443 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7466/9304 [22:33<06:18,  4.86it/s]

2025-05-20 16:58:28,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:28,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7468/9304 [22:34<06:03,  5.05it/s]

2025-05-20 16:58:29,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7469/9304 [22:34<06:35,  4.64it/s]

2025-05-20 16:58:29,223 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:29,226 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7470/9304 [22:34<05:59,  5.10it/s]

2025-05-20 16:58:29,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7472/9304 [22:34<05:26,  5.61it/s]

2025-05-20 16:58:30,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7473/9304 [22:35<07:48,  3.91it/s]

2025-05-20 16:58:30,108 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:30,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7475/9304 [22:35<05:29,  5.56it/s]

2025-05-20 16:58:30,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7476/9304 [22:35<05:27,  5.58it/s]

2025-05-20 16:58:30,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:30,612 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7478/9304 [22:35<04:54,  6.21it/s]

2025-05-20 16:58:30,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7479/9304 [22:36<05:17,  5.75it/s]

2025-05-20 16:58:30,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:30,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7481/9304 [22:36<04:00,  7.58it/s]

2025-05-20 16:58:31,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7482/9304 [22:36<03:58,  7.63it/s]

2025-05-20 16:58:31,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7483/9304 [22:36<06:04,  5.00it/s]

2025-05-20 16:58:31,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:31,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7485/9304 [22:37<05:04,  5.97it/s]

2025-05-20 16:58:32,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7486/9304 [22:37<06:54,  4.39it/s]

2025-05-20 16:58:32,476 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 80%|████████  | 7487/9304 [22:37<07:20,  4.13it/s]

2025-05-20 16:58:32,498 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:32,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:32,648 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7490/9304 [22:37<04:27,  6.78it/s]

2025-05-20 16:58:32,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:32,744 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:33,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7493/9304 [22:38<04:54,  6.15it/s]

2025-05-20 16:58:33,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7494/9304 [22:38<05:02,  5.97it/s]

2025-05-20 16:58:33,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7495/9304 [22:38<05:18,  5.68it/s]

2025-05-20 16:58:33,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:33,930 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7497/9304 [22:39<05:10,  5.82it/s]

2025-05-20 16:58:33,980 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:34,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7499/9304 [22:39<04:15,  7.05it/s]

2025-05-20 16:58:34,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:34,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7501/9304 [22:39<04:32,  6.63it/s]

2025-05-20 16:58:34,487 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:34,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7503/9304 [22:39<03:50,  7.81it/s]

2025-05-20 16:58:34,713 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7504/9304 [22:40<03:47,  7.92it/s]

2025-05-20 16:58:35,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7505/9304 [22:40<06:52,  4.36it/s]

2025-05-20 16:58:35,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7506/9304 [22:40<06:29,  4.62it/s]

2025-05-20 16:58:35,616 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7507/9304 [22:40<06:02,  4.96it/s]

2025-05-20 16:58:35,711 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:35,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:35,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7509/9304 [22:41<04:49,  6.20it/s]

2025-05-20 16:58:36,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7511/9304 [22:41<04:28,  6.67it/s]

2025-05-20 16:58:36,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7512/9304 [22:41<04:56,  6.05it/s]

2025-05-20 16:58:36,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7513/9304 [22:41<05:48,  5.14it/s]

2025-05-20 16:58:36,825 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7514/9304 [22:42<05:45,  5.18it/s]

2025-05-20 16:58:36,992 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7515/9304 [22:42<05:30,  5.42it/s]

2025-05-20 16:58:37,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7516/9304 [22:42<06:17,  4.74it/s]

2025-05-20 16:58:37,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:37,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:37,565 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7518/9304 [22:42<05:23,  5.52it/s]

2025-05-20 16:58:37,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7520/9304 [22:43<04:41,  6.34it/s]

2025-05-20 16:58:37,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:37,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:37,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7523/9304 [22:43<03:11,  9.32it/s]

2025-05-20 16:58:38,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:38,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7525/9304 [22:44<05:57,  4.97it/s]

2025-05-20 16:58:39,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7526/9304 [22:44<06:38,  4.47it/s]

2025-05-20 16:58:39,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7527/9304 [22:44<06:23,  4.64it/s]

2025-05-20 16:58:39,338 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:39,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:39,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7530/9304 [22:44<03:57,  7.48it/s]

2025-05-20 16:58:39,443 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:39,474 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:39,893 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7533/9304 [22:45<04:16,  6.91it/s]

2025-05-20 16:58:40,472 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:40,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7535/9304 [22:45<05:27,  5.40it/s]

2025-05-20 16:58:40,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:40,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7537/9304 [22:45<04:38,  6.35it/s]

2025-05-20 16:58:40,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7538/9304 [22:46<04:52,  6.03it/s]

2025-05-20 16:58:41,155 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7539/9304 [22:46<05:37,  5.23it/s]

2025-05-20 16:58:41,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:41,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:41,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7542/9304 [22:46<03:33,  8.25it/s]

2025-05-20 16:58:41,334 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:41,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7544/9304 [22:47<04:18,  6.80it/s]

2025-05-20 16:58:41,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:42,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7546/9304 [22:47<06:50,  4.28it/s]

2025-05-20 16:58:42,624 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:42,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7548/9304 [22:48<06:06,  4.80it/s]

2025-05-20 16:58:42,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:43,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7550/9304 [22:48<05:11,  5.62it/s]

2025-05-20 16:58:43,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7551/9304 [22:48<05:13,  5.60it/s]

2025-05-20 16:58:43,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:43,415 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7553/9304 [22:48<04:18,  6.79it/s]

2025-05-20 16:58:43,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7554/9304 [22:48<04:29,  6.50it/s]

2025-05-20 16:58:44,108 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7555/9304 [22:49<06:45,  4.32it/s]

2025-05-20 16:58:44,286 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7556/9304 [22:49<06:22,  4.57it/s]

2025-05-20 16:58:44,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7557/9304 [22:49<05:51,  4.97it/s]

2025-05-20 16:58:44,566 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7558/9304 [22:49<05:20,  5.45it/s]

2025-05-20 16:58:44,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████  | 7559/9304 [22:50<06:46,  4.29it/s]

2025-05-20 16:58:44,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:44,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:45,070 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7562/9304 [22:50<03:50,  7.56it/s]

2025-05-20 16:58:45,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:45,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7564/9304 [22:50<04:23,  6.62it/s]

2025-05-20 16:58:45,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7565/9304 [22:51<06:07,  4.73it/s]

2025-05-20 16:58:45,997 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:46,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7567/9304 [22:51<05:28,  5.28it/s]

2025-05-20 16:58:46,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:46,462 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7569/9304 [22:51<04:52,  5.92it/s]

2025-05-20 16:58:46,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:46,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7571/9304 [22:51<03:46,  7.64it/s]

2025-05-20 16:58:46,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:47,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7573/9304 [22:52<06:01,  4.79it/s]

2025-05-20 16:58:47,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:47,498 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7574/9304 [22:52<05:53,  4.90it/s]

2025-05-20 16:58:47,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:47,928 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7577/9304 [22:53<05:04,  5.68it/s]

2025-05-20 16:58:47,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:48,090 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7579/9304 [22:53<04:16,  6.73it/s]

2025-05-20 16:58:48,143 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:48,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 81%|████████▏ | 7581/9304 [22:53<03:37,  7.91it/s]

2025-05-20 16:58:48,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:48,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7583/9304 [22:54<05:23,  5.32it/s]

2025-05-20 16:58:48,989 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:49,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7585/9304 [22:54<04:37,  6.19it/s]

2025-05-20 16:58:49,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:49,453 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7587/9304 [22:54<04:44,  6.04it/s]

2025-05-20 16:58:49,530 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:49,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7589/9304 [22:55<04:17,  6.67it/s]

2025-05-20 16:58:49,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:50,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7591/9304 [22:55<04:21,  6.56it/s]

2025-05-20 16:58:50,519 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7592/9304 [22:55<06:10,  4.62it/s]

2025-05-20 16:58:50,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:50,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7594/9304 [22:56<04:53,  5.83it/s]

2025-05-20 16:58:50,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:50,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7596/9304 [22:56<03:58,  7.15it/s]

2025-05-20 16:58:50,979 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7597/9304 [22:56<04:00,  7.09it/s]

2025-05-20 16:58:50,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:51,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7599/9304 [22:56<03:39,  7.77it/s]

2025-05-20 16:58:51,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7600/9304 [22:56<04:45,  5.96it/s]

2025-05-20 16:58:51,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7601/9304 [22:57<06:17,  4.51it/s]

2025-05-20 16:58:51,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:52,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7603/9304 [22:57<04:28,  6.35it/s]

2025-05-20 16:58:52,081 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:52,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7605/9304 [22:57<03:43,  7.61it/s]

2025-05-20 16:58:52,250 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:52,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7607/9304 [22:58<04:43,  5.98it/s]

2025-05-20 16:58:52,834 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7608/9304 [22:58<04:39,  6.07it/s]

2025-05-20 16:58:52,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:53,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7610/9304 [22:58<04:24,  6.41it/s]

2025-05-20 16:58:53,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7611/9304 [22:58<04:37,  6.10it/s]

2025-05-20 16:58:53,457 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7612/9304 [22:58<04:32,  6.20it/s]

2025-05-20 16:58:53,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:53,630 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7614/9304 [22:58<03:42,  7.58it/s]

2025-05-20 16:58:53,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7615/9304 [22:59<03:42,  7.60it/s]

2025-05-20 16:58:53,838 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:54,216 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7617/9304 [22:59<04:42,  5.97it/s]

2025-05-20 16:58:54,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7618/9304 [22:59<04:41,  5.98it/s]

2025-05-20 16:58:54,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7619/9304 [22:59<05:06,  5.50it/s]

2025-05-20 16:58:54,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7620/9304 [23:00<04:54,  5.72it/s]

2025-05-20 16:58:54,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7621/9304 [23:00<04:54,  5.72it/s]

2025-05-20 16:58:55,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7622/9304 [23:00<04:26,  6.30it/s]

2025-05-20 16:58:55,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:55,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7624/9304 [23:00<04:02,  6.92it/s]

2025-05-20 16:58:55,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7625/9304 [23:00<03:46,  7.40it/s]

2025-05-20 16:58:55,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:55,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7627/9304 [23:00<03:14,  8.64it/s]

2025-05-20 16:58:55,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7628/9304 [23:01<04:38,  6.03it/s]

2025-05-20 16:58:56,202 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7629/9304 [23:01<05:23,  5.18it/s]

2025-05-20 16:58:56,421 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7630/9304 [23:01<05:34,  5.00it/s]

2025-05-20 16:58:56,566 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7631/9304 [23:01<05:08,  5.43it/s]

2025-05-20 16:58:56,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:56,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7633/9304 [23:02<04:42,  5.91it/s]

2025-05-20 16:58:56,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:56,955 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:56,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7636/9304 [23:02<02:54,  9.56it/s]

2025-05-20 16:58:57,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:57,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7638/9304 [23:02<03:39,  7.59it/s]

2025-05-20 16:58:58,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:58,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7640/9304 [23:03<05:27,  5.08it/s]

2025-05-20 16:58:58,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7641/9304 [23:03<05:04,  5.46it/s]

2025-05-20 16:58:58,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:58,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7643/9304 [23:03<04:10,  6.64it/s]

2025-05-20 16:58:58,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:58,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7645/9304 [23:04<04:32,  6.08it/s]

2025-05-20 16:58:58,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7646/9304 [23:04<04:23,  6.30it/s]

2025-05-20 16:58:58,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:59,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7648/9304 [23:04<06:02,  4.57it/s]

2025-05-20 16:58:59,644 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7649/9304 [23:04<05:33,  4.96it/s]

2025-05-20 16:58:59,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:59,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:58:59,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7652/9304 [23:05<03:40,  7.49it/s]

2025-05-20 16:59:00,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:00,222 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:00,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7654/9304 [23:05<04:22,  6.28it/s]

2025-05-20 16:59:00,752 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7656/9304 [23:06<05:09,  5.32it/s]

2025-05-20 16:59:00,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:00,859 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7658/9304 [23:06<04:02,  6.77it/s]

2025-05-20 16:59:01,552 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:01,649 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:01,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7660/9304 [23:06<06:07,  4.48it/s]

2025-05-20 16:59:01,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7662/9304 [23:07<05:11,  5.27it/s]

2025-05-20 16:59:02,057 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7663/9304 [23:07<05:07,  5.33it/s]

2025-05-20 16:59:02,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:02,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7665/9304 [23:07<04:55,  5.55it/s]

2025-05-20 16:59:02,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:02,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7667/9304 [23:08<05:44,  4.75it/s]

2025-05-20 16:59:03,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7668/9304 [23:08<06:36,  4.13it/s]

2025-05-20 16:59:03,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:03,418 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:03,426 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:03,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7670/9304 [23:08<04:50,  5.62it/s]

2025-05-20 16:59:03,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7673/9304 [23:09<03:47,  7.16it/s]

2025-05-20 16:59:03,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7674/9304 [23:09<04:00,  6.77it/s]

2025-05-20 16:59:03,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 82%|████████▏ | 7675/9304 [23:09<03:48,  7.12it/s]

2025-05-20 16:59:04,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7676/9304 [23:09<03:57,  6.87it/s]

2025-05-20 16:59:04,895 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7677/9304 [23:10<07:44,  3.51it/s]

2025-05-20 16:59:05,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7678/9304 [23:10<07:07,  3.80it/s]

2025-05-20 16:59:05,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:05,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:05,179 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:05,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7682/9304 [23:10<03:29,  7.74it/s]

2025-05-20 16:59:05,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:05,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7684/9304 [23:10<03:39,  7.37it/s]

2025-05-20 16:59:05,742 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:05,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7686/9304 [23:11<04:17,  6.29it/s]

2025-05-20 16:59:06,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7687/9304 [23:11<06:05,  4.43it/s]

2025-05-20 16:59:06,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:06,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:06,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7690/9304 [23:12<05:00,  5.36it/s]

2025-05-20 16:59:06,953 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:06,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:07,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7693/9304 [23:12<04:34,  5.87it/s]

2025-05-20 16:59:07,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7694/9304 [23:12<04:57,  5.42it/s]

2025-05-20 16:59:07,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:08,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7696/9304 [23:13<05:14,  5.11it/s]

2025-05-20 16:59:08,095 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:08,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7698/9304 [23:13<04:14,  6.31it/s]

2025-05-20 16:59:08,422 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7699/9304 [23:13<04:34,  5.84it/s]

2025-05-20 16:59:08,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:08,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7701/9304 [23:14<05:30,  4.85it/s]

2025-05-20 16:59:09,237 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7702/9304 [23:14<05:50,  4.58it/s]

2025-05-20 16:59:09,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7703/9304 [23:14<05:45,  4.63it/s]

2025-05-20 16:59:09,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:09,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7705/9304 [23:14<04:16,  6.22it/s]

2025-05-20 16:59:09,744 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7706/9304 [23:15<04:14,  6.28it/s]

2025-05-20 16:59:09,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:10,221 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7708/9304 [23:15<05:02,  5.28it/s]

2025-05-20 16:59:10,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7709/9304 [23:15<06:00,  4.42it/s]

2025-05-20 16:59:10,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:10,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7711/9304 [23:16<05:07,  5.18it/s]

2025-05-20 16:59:10,873 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:11,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7713/9304 [23:16<04:05,  6.47it/s]

2025-05-20 16:59:11,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7714/9304 [23:16<04:27,  5.94it/s]

2025-05-20 16:59:11,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:11,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7716/9304 [23:16<03:55,  6.74it/s]

2025-05-20 16:59:11,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7717/9304 [23:16<03:57,  6.67it/s]

2025-05-20 16:59:11,841 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7718/9304 [23:17<04:18,  6.15it/s]

2025-05-20 16:59:11,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:12,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7720/9304 [23:17<03:28,  7.59it/s]

2025-05-20 16:59:12,332 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7721/9304 [23:17<04:34,  5.77it/s]

2025-05-20 16:59:12,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:12,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7723/9304 [23:17<04:07,  6.38it/s]

2025-05-20 16:59:12,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7724/9304 [23:18<04:38,  5.68it/s]

2025-05-20 16:59:13,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7725/9304 [23:18<05:10,  5.09it/s]

2025-05-20 16:59:13,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:13,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7727/9304 [23:18<03:47,  6.94it/s]

2025-05-20 16:59:13,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7728/9304 [23:18<05:07,  5.13it/s]

2025-05-20 16:59:13,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7729/9304 [23:19<04:50,  5.41it/s]

2025-05-20 16:59:13,798 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:14,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7731/9304 [23:19<04:11,  6.26it/s]

2025-05-20 16:59:14,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:14,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7733/9304 [23:19<03:14,  8.08it/s]

2025-05-20 16:59:14,331 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7734/9304 [23:19<03:39,  7.16it/s]

2025-05-20 16:59:14,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7735/9304 [23:19<03:42,  7.04it/s]

2025-05-20 16:59:14,541 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:15,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7737/9304 [23:20<05:21,  4.87it/s]

2025-05-20 16:59:15,324 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7738/9304 [23:20<05:34,  4.68it/s]

2025-05-20 16:59:15,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:15,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:15,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7741/9304 [23:20<03:56,  6.61it/s]

2025-05-20 16:59:15,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:15,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7743/9304 [23:21<03:39,  7.12it/s]

2025-05-20 16:59:16,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7744/9304 [23:21<04:09,  6.25it/s]

2025-05-20 16:59:16,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7745/9304 [23:21<06:01,  4.31it/s]

2025-05-20 16:59:16,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7746/9304 [23:21<05:15,  4.94it/s]

2025-05-20 16:59:16,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:16,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7748/9304 [23:22<04:28,  5.79it/s]

2025-05-20 16:59:16,945 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:16,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:16,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:17,066 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7752/9304 [23:22<02:34, 10.02it/s]

2025-05-20 16:59:17,638 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:17,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7754/9304 [23:23<04:56,  5.22it/s]

2025-05-20 16:59:18,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:18,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7756/9304 [23:23<04:44,  5.44it/s]

2025-05-20 16:59:18,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:18,488 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7758/9304 [23:23<04:12,  6.12it/s]

2025-05-20 16:59:18,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:18,621 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7760/9304 [23:23<03:29,  7.37it/s]

2025-05-20 16:59:18,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:18,772 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7762/9304 [23:24<03:01,  8.50it/s]

2025-05-20 16:59:19,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:19,619 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7764/9304 [23:24<05:19,  4.82it/s]

2025-05-20 16:59:19,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7765/9304 [23:25<05:11,  4.94it/s]

2025-05-20 16:59:19,851 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:19,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:20,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 83%|████████▎ | 7768/9304 [23:25<03:47,  6.75it/s]

2025-05-20 16:59:20,161 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7769/9304 [23:25<03:45,  6.81it/s]

2025-05-20 16:59:20,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7770/9304 [23:25<04:07,  6.19it/s]

2025-05-20 16:59:20,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7771/9304 [23:25<04:11,  6.10it/s]

2025-05-20 16:59:20,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7772/9304 [23:26<04:13,  6.03it/s]

2025-05-20 16:59:21,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7773/9304 [23:26<05:18,  4.80it/s]

2025-05-20 16:59:21,123 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:21,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7775/9304 [23:26<04:33,  5.59it/s]

2025-05-20 16:59:21,507 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7776/9304 [23:26<04:30,  5.66it/s]

2025-05-20 16:59:21,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:21,655 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7778/9304 [23:26<03:26,  7.39it/s]

2025-05-20 16:59:21,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7779/9304 [23:27<04:18,  5.91it/s]

2025-05-20 16:59:22,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:22,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7781/9304 [23:27<03:48,  6.67it/s]

2025-05-20 16:59:22,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7782/9304 [23:27<04:04,  6.22it/s]

2025-05-20 16:59:22,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7783/9304 [23:27<04:35,  5.52it/s]

2025-05-20 16:59:22,686 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:22,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7785/9304 [23:28<04:00,  6.32it/s]

2025-05-20 16:59:23,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7786/9304 [23:28<04:41,  5.40it/s]

2025-05-20 16:59:23,345 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7787/9304 [23:28<04:42,  5.37it/s]

2025-05-20 16:59:23,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:23,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7789/9304 [23:28<04:04,  6.20it/s]

2025-05-20 16:59:23,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:23,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7791/9304 [23:29<03:43,  6.76it/s]

2025-05-20 16:59:23,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▎ | 7792/9304 [23:29<03:41,  6.83it/s]

2025-05-20 16:59:24,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7793/9304 [23:29<04:02,  6.24it/s]

2025-05-20 16:59:24,415 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7794/9304 [23:29<04:24,  5.71it/s]

2025-05-20 16:59:24,535 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7795/9304 [23:29<04:04,  6.17it/s]

2025-05-20 16:59:24,603 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:24,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7797/9304 [23:30<03:53,  6.45it/s]

2025-05-20 16:59:25,286 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7798/9304 [23:30<05:39,  4.43it/s]

2025-05-20 16:59:25,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:25,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7800/9304 [23:31<05:32,  4.52it/s]

2025-05-20 16:59:25,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:25,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:25,905 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7803/9304 [23:31<03:42,  6.73it/s]

2025-05-20 16:59:26,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7804/9304 [23:31<04:30,  5.56it/s]

2025-05-20 16:59:26,244 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:26,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:26,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7807/9304 [23:31<03:19,  7.49it/s]

2025-05-20 16:59:26,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:26,817 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7809/9304 [23:32<03:41,  6.75it/s]

2025-05-20 16:59:27,050 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7810/9304 [23:32<04:03,  6.14it/s]

2025-05-20 16:59:27,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:27,324 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7812/9304 [23:32<03:50,  6.47it/s]

2025-05-20 16:59:27,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:27,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:27,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7815/9304 [23:33<03:34,  6.93it/s]

2025-05-20 16:59:27,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7816/9304 [23:33<03:54,  6.34it/s]

2025-05-20 16:59:28,274 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7817/9304 [23:33<04:44,  5.23it/s]

2025-05-20 16:59:28,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:28,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7819/9304 [23:33<03:37,  6.82it/s]

2025-05-20 16:59:28,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7820/9304 [23:33<04:00,  6.17it/s]

2025-05-20 16:59:28,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:28,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7822/9304 [23:34<03:20,  7.41it/s]

2025-05-20 16:59:29,343 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7823/9304 [23:34<05:25,  4.56it/s]

2025-05-20 16:59:29,366 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:29,495 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7825/9304 [23:34<04:05,  6.02it/s]

2025-05-20 16:59:29,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:29,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7827/9304 [23:34<03:09,  7.78it/s]

2025-05-20 16:59:29,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:29,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7829/9304 [23:35<03:11,  7.70it/s]

2025-05-20 16:59:29,923 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:30,461 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7831/9304 [23:35<04:28,  5.50it/s]

2025-05-20 16:59:30,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7832/9304 [23:36<05:12,  4.71it/s]

2025-05-20 16:59:30,855 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:30,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7834/9304 [23:36<03:58,  6.16it/s]

2025-05-20 16:59:31,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7835/9304 [23:36<03:49,  6.40it/s]

2025-05-20 16:59:31,200 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7836/9304 [23:36<03:38,  6.72it/s]

2025-05-20 16:59:31,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:31,352 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7838/9304 [23:36<02:56,  8.30it/s]

2025-05-20 16:59:31,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7839/9304 [23:36<03:12,  7.62it/s]

2025-05-20 16:59:31,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7840/9304 [23:37<03:31,  6.92it/s]

2025-05-20 16:59:32,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7841/9304 [23:37<04:49,  5.05it/s]

2025-05-20 16:59:32,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7842/9304 [23:37<05:10,  4.71it/s]

2025-05-20 16:59:32,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7843/9304 [23:37<04:51,  5.01it/s]

2025-05-20 16:59:32,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7844/9304 [23:37<04:14,  5.73it/s]

2025-05-20 16:59:32,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:32,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:32,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7847/9304 [23:38<03:12,  7.55it/s]

2025-05-20 16:59:33,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7848/9304 [23:38<03:59,  6.08it/s]

2025-05-20 16:59:33,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7849/9304 [23:38<05:20,  4.54it/s]

2025-05-20 16:59:33,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7850/9304 [23:39<06:15,  3.87it/s]

2025-05-20 16:59:33,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:34,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:34,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7853/9304 [23:39<04:04,  5.94it/s]

2025-05-20 16:59:34,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7854/9304 [23:39<03:51,  6.27it/s]

2025-05-20 16:59:34,564 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7855/9304 [23:39<04:14,  5.69it/s]

2025-05-20 16:59:34,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:34,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7857/9304 [23:40<03:54,  6.16it/s]

2025-05-20 16:59:35,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7858/9304 [23:40<06:02,  3.99it/s]

2025-05-20 16:59:35,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7859/9304 [23:40<05:54,  4.07it/s]

2025-05-20 16:59:35,757 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 84%|████████▍ | 7860/9304 [23:41<05:08,  4.69it/s]

2025-05-20 16:59:35,781 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:35,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7862/9304 [23:41<03:38,  6.60it/s]

2025-05-20 16:59:36,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7863/9304 [23:41<03:33,  6.75it/s]

2025-05-20 16:59:36,048 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:36,217 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:36,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7865/9304 [23:41<03:02,  7.88it/s]

2025-05-20 16:59:36,599 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7867/9304 [23:41<03:35,  6.68it/s]

2025-05-20 16:59:37,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7868/9304 [23:42<05:36,  4.26it/s]

2025-05-20 16:59:37,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7869/9304 [23:42<05:01,  4.76it/s]

2025-05-20 16:59:37,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:37,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7871/9304 [23:42<03:46,  6.33it/s]

2025-05-20 16:59:37,495 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:37,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7873/9304 [23:42<03:22,  7.08it/s]

2025-05-20 16:59:37,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7874/9304 [23:43<03:19,  7.15it/s]

2025-05-20 16:59:37,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7875/9304 [23:43<03:34,  6.66it/s]

2025-05-20 16:59:38,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7876/9304 [23:43<05:29,  4.33it/s]

2025-05-20 16:59:38,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7877/9304 [23:44<05:30,  4.32it/s]

2025-05-20 16:59:38,795 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:38,885 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7879/9304 [23:44<04:05,  5.81it/s]

2025-05-20 16:59:38,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:39,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7881/9304 [23:44<03:37,  6.56it/s]

2025-05-20 16:59:39,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:39,206 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:39,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7884/9304 [23:44<02:42,  8.72it/s]

2025-05-20 16:59:39,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7885/9304 [23:44<03:10,  7.44it/s]

2025-05-20 16:59:40,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7886/9304 [23:45<05:44,  4.11it/s]

2025-05-20 16:59:40,511 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7887/9304 [23:45<05:55,  3.99it/s]

2025-05-20 16:59:40,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:40,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:40,686 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7889/9304 [23:46<04:26,  5.32it/s]

2025-05-20 16:59:40,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7891/9304 [23:46<03:54,  6.03it/s]

2025-05-20 16:59:41,060 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7892/9304 [23:46<03:40,  6.40it/s]

2025-05-20 16:59:41,126 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:41,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7894/9304 [23:46<03:12,  7.33it/s]

2025-05-20 16:59:41,275 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:41,754 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7896/9304 [23:47<04:04,  5.75it/s]

2025-05-20 16:59:42,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7897/9304 [23:47<04:33,  5.15it/s]

2025-05-20 16:59:42,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7898/9304 [23:47<05:15,  4.45it/s]

2025-05-20 16:59:42,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7899/9304 [23:47<04:51,  4.81it/s]

2025-05-20 16:59:42,574 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:42,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7901/9304 [23:48<04:29,  5.21it/s]

2025-05-20 16:59:42,933 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:42,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7903/9304 [23:48<03:21,  6.96it/s]

2025-05-20 16:59:43,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7904/9304 [23:48<03:42,  6.30it/s]

2025-05-20 16:59:43,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7905/9304 [23:48<03:55,  5.95it/s]

2025-05-20 16:59:43,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7906/9304 [23:48<03:46,  6.17it/s]

2025-05-20 16:59:43,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:43,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▍ | 7908/9304 [23:49<02:59,  7.76it/s]

2025-05-20 16:59:43,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7909/9304 [23:49<03:39,  6.37it/s]

2025-05-20 16:59:44,136 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7910/9304 [23:49<03:49,  6.08it/s]

2025-05-20 16:59:44,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7911/9304 [23:49<05:01,  4.63it/s]

2025-05-20 16:59:44,567 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:44,689 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7913/9304 [23:50<03:48,  6.09it/s]

2025-05-20 16:59:44,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7914/9304 [23:50<03:36,  6.43it/s]

2025-05-20 16:59:44,958 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7915/9304 [23:50<03:31,  6.58it/s]

2025-05-20 16:59:45,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7916/9304 [23:50<04:15,  5.44it/s]

2025-05-20 16:59:45,386 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7917/9304 [23:50<04:02,  5.71it/s]

2025-05-20 16:59:45,713 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7918/9304 [23:51<05:01,  4.59it/s]

2025-05-20 16:59:46,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7919/9304 [23:51<06:32,  3.52it/s]

2025-05-20 16:59:46,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:46,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7920/9304 [23:51<05:47,  3.98it/s]

2025-05-20 16:59:46,375 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:46,561 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7923/9304 [23:51<03:35,  6.40it/s]

2025-05-20 16:59:46,761 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7924/9304 [23:52<03:46,  6.08it/s]

2025-05-20 16:59:46,817 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:47,222 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7926/9304 [23:52<04:18,  5.34it/s]

2025-05-20 16:59:47,325 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7927/9304 [23:52<03:56,  5.83it/s]

2025-05-20 16:59:47,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7928/9304 [23:52<04:14,  5.42it/s]

2025-05-20 16:59:47,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7929/9304 [23:53<05:16,  4.34it/s]

2025-05-20 16:59:48,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7930/9304 [23:53<05:20,  4.29it/s]

2025-05-20 16:59:48,235 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:48,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:48,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:48,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7934/9304 [23:53<03:38,  6.26it/s]

2025-05-20 16:59:48,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7935/9304 [23:54<03:27,  6.61it/s]

2025-05-20 16:59:48,783 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:48,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7937/9304 [23:54<03:10,  7.19it/s]

2025-05-20 16:59:49,092 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7938/9304 [23:54<03:11,  7.14it/s]

2025-05-20 16:59:49,687 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7939/9304 [23:55<05:23,  4.22it/s]

2025-05-20 16:59:49,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:49,804 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7941/9304 [23:55<03:52,  5.85it/s]

2025-05-20 16:59:49,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:49,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7943/9304 [23:55<03:01,  7.49it/s]

2025-05-20 16:59:50,274 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:50,378 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7945/9304 [23:55<03:39,  6.19it/s]

2025-05-20 16:59:50,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7946/9304 [23:55<03:49,  5.91it/s]

2025-05-20 16:59:50,644 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:50,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7948/9304 [23:56<03:05,  7.30it/s]

2025-05-20 16:59:50,964 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7949/9304 [23:56<03:30,  6.43it/s]

2025-05-20 16:59:51,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7950/9304 [23:56<04:08,  5.45it/s]

2025-05-20 16:59:51,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7951/9304 [23:56<04:08,  5.44it/s]

2025-05-20 16:59:51,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7952/9304 [23:57<04:31,  4.97it/s]

2025-05-20 16:59:51,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:52,068 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 85%|████████▌ | 7954/9304 [23:57<04:26,  5.07it/s]

2025-05-20 16:59:52,333 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7955/9304 [23:57<04:48,  4.68it/s]

2025-05-20 16:59:52,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:52,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7957/9304 [23:57<03:24,  6.58it/s]

2025-05-20 16:59:52,639 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7958/9304 [23:57<03:34,  6.26it/s]

2025-05-20 16:59:52,801 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7959/9304 [23:58<03:38,  6.16it/s]

2025-05-20 16:59:52,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:53,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7961/9304 [23:58<03:08,  7.14it/s]

2025-05-20 16:59:53,104 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:53,355 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7963/9304 [23:58<03:20,  6.70it/s]

2025-05-20 16:59:53,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7964/9304 [23:59<05:11,  4.31it/s]

2025-05-20 16:59:54,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7965/9304 [23:59<04:40,  4.77it/s]

2025-05-20 16:59:54,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:54,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7967/9304 [23:59<03:30,  6.35it/s]

2025-05-20 16:59:54,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7968/9304 [23:59<03:59,  5.58it/s]

2025-05-20 16:59:54,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:54,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7970/9304 [23:59<03:24,  6.53it/s]

2025-05-20 16:59:54,734 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:54,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7972/9304 [24:00<02:37,  8.46it/s]

2025-05-20 16:59:55,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:55,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7974/9304 [24:01<05:25,  4.08it/s]

2025-05-20 16:59:56,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7975/9304 [24:01<05:28,  4.04it/s]

2025-05-20 16:59:56,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7976/9304 [24:01<05:07,  4.32it/s]

2025-05-20 16:59:56,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:56,279 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:56,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7979/9304 [24:01<03:05,  7.15it/s]

2025-05-20 16:59:56,360 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:56,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7981/9304 [24:01<02:46,  7.93it/s]

2025-05-20 16:59:56,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:57,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7983/9304 [24:02<05:21,  4.11it/s]

2025-05-20 16:59:57,716 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7984/9304 [24:03<05:10,  4.25it/s]

2025-05-20 16:59:57,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:57,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:57,859 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7987/9304 [24:03<03:20,  6.58it/s]

2025-05-20 16:59:57,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:57,886 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:58,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7990/9304 [24:03<02:26,  8.95it/s]

2025-05-20 16:59:58,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:58,259 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7992/9304 [24:03<02:32,  8.59it/s]

2025-05-20 16:59:58,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:59,149 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7994/9304 [24:04<04:31,  4.82it/s]

2025-05-20 16:59:59,373 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:59,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7995/9304 [24:04<04:37,  4.71it/s]

2025-05-20 16:59:59,419 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:59,435 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 16:59:59,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 7999/9304 [24:04<02:48,  7.75it/s]

2025-05-20 16:59:59,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:00,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8001/9304 [24:05<03:31,  6.15it/s]

2025-05-20 17:00:00,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:00,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8003/9304 [24:05<02:56,  7.36it/s]

2025-05-20 17:00:00,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:00,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8005/9304 [24:06<03:49,  5.65it/s]

2025-05-20 17:00:00,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8006/9304 [24:06<03:51,  5.60it/s]

2025-05-20 17:00:01,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8007/9304 [24:06<03:33,  6.08it/s]

2025-05-20 17:00:01,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8008/9304 [24:06<03:53,  5.55it/s]

2025-05-20 17:00:01,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:01,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8010/9304 [24:06<03:44,  5.75it/s]

2025-05-20 17:00:01,752 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8011/9304 [24:07<03:33,  6.07it/s]

2025-05-20 17:00:01,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8012/9304 [24:07<03:31,  6.11it/s]

2025-05-20 17:00:01,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:02,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8014/9304 [24:07<04:15,  5.06it/s]

2025-05-20 17:00:02,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:02,552 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8016/9304 [24:07<03:16,  6.55it/s]

2025-05-20 17:00:02,915 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8017/9304 [24:08<04:10,  5.13it/s]

2025-05-20 17:00:03,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8018/9304 [24:08<04:09,  5.16it/s]

2025-05-20 17:00:03,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:03,205 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8019/9304 [24:08<03:43,  5.76it/s]

2025-05-20 17:00:03,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8021/9304 [24:08<02:57,  7.22it/s]

2025-05-20 17:00:03,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8022/9304 [24:08<03:14,  6.61it/s]

2025-05-20 17:00:03,961 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▌ | 8023/9304 [24:09<04:23,  4.87it/s]

2025-05-20 17:00:03,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:04,024 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:04,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8026/9304 [24:09<03:22,  6.30it/s]

2025-05-20 17:00:04,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8027/9304 [24:09<04:08,  5.14it/s]

2025-05-20 17:00:04,770 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8028/9304 [24:10<03:48,  5.58it/s]

2025-05-20 17:00:04,838 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:05,132 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8030/9304 [24:10<03:50,  5.53it/s]

2025-05-20 17:00:05,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:05,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8032/9304 [24:11<04:40,  4.53it/s]

2025-05-20 17:00:05,784 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:05,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:05,914 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:05,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8034/9304 [24:11<03:49,  5.53it/s]

2025-05-20 17:00:06,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8037/9304 [24:11<02:44,  7.72it/s]

2025-05-20 17:00:06,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8038/9304 [24:11<02:55,  7.19it/s]

2025-05-20 17:00:07,111 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8039/9304 [24:12<05:41,  3.70it/s]

2025-05-20 17:00:07,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:07,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8041/9304 [24:12<04:46,  4.41it/s]

2025-05-20 17:00:07,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8042/9304 [24:13<05:09,  4.07it/s]

2025-05-20 17:00:07,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:07,864 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8043/9304 [24:13<04:37,  4.54it/s]

2025-05-20 17:00:07,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8045/9304 [24:13<03:26,  6.11it/s]

2025-05-20 17:00:08,166 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8046/9304 [24:13<03:25,  6.13it/s]

2025-05-20 17:00:08,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 86%|████████▋ | 8047/9304 [24:13<04:05,  5.12it/s]

2025-05-20 17:00:09,224 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:09,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8048/9304 [24:14<07:10,  2.92it/s]

2025-05-20 17:00:09,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:09,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8050/9304 [24:14<04:40,  4.47it/s]

2025-05-20 17:00:09,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:09,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8053/9304 [24:14<03:12,  6.50it/s]

2025-05-20 17:00:09,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:09,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8055/9304 [24:15<03:17,  6.32it/s]

2025-05-20 17:00:09,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:10,931 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8057/9304 [24:16<05:29,  3.78it/s]

2025-05-20 17:00:11,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8058/9304 [24:16<05:13,  3.97it/s]

2025-05-20 17:00:11,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:11,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:11,264 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8059/9304 [24:16<04:40,  4.44it/s]

2025-05-20 17:00:11,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:11,501 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8063/9304 [24:16<02:50,  7.27it/s]

2025-05-20 17:00:11,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8064/9304 [24:17<03:39,  5.64it/s]

2025-05-20 17:00:11,968 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:12,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8066/9304 [24:17<04:45,  4.34it/s]

2025-05-20 17:00:12,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8067/9304 [24:18<04:25,  4.65it/s]

2025-05-20 17:00:12,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:12,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:12,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8070/9304 [24:18<02:58,  6.90it/s]

2025-05-20 17:00:13,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8071/9304 [24:18<03:58,  5.18it/s]

2025-05-20 17:00:13,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:13,428 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8073/9304 [24:18<03:02,  6.76it/s]

2025-05-20 17:00:13,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:13,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:13,863 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8076/9304 [24:19<03:00,  6.81it/s]

2025-05-20 17:00:14,061 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8077/9304 [24:19<03:10,  6.44it/s]

2025-05-20 17:00:14,316 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8078/9304 [24:19<03:33,  5.73it/s]

2025-05-20 17:00:14,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8079/9304 [24:19<03:22,  6.06it/s]

2025-05-20 17:00:14,692 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8080/9304 [24:20<03:44,  5.46it/s]

2025-05-20 17:00:14,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8081/9304 [24:20<03:21,  6.08it/s]

2025-05-20 17:00:15,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8082/9304 [24:20<03:57,  5.15it/s]

2025-05-20 17:00:15,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:15,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8084/9304 [24:20<03:58,  5.12it/s]

2025-05-20 17:00:15,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8085/9304 [24:20<03:47,  5.37it/s]

2025-05-20 17:00:15,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:16,063 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8087/9304 [24:21<04:02,  5.03it/s]

2025-05-20 17:00:16,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:16,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8089/9304 [24:21<02:58,  6.81it/s]

2025-05-20 17:00:16,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8090/9304 [24:22<05:35,  3.62it/s]

2025-05-20 17:00:17,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8091/9304 [24:22<05:00,  4.04it/s]

2025-05-20 17:00:17,154 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:17,292 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8093/9304 [24:22<03:48,  5.29it/s]

2025-05-20 17:00:17,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8094/9304 [24:22<04:05,  4.92it/s]

2025-05-20 17:00:17,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:17,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8096/9304 [24:23<03:01,  6.64it/s]

2025-05-20 17:00:17,808 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8097/9304 [24:23<02:55,  6.88it/s]

2025-05-20 17:00:17,838 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:18,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8099/9304 [24:23<02:54,  6.92it/s]

2025-05-20 17:00:18,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8100/9304 [24:23<03:53,  5.15it/s]

2025-05-20 17:00:18,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8101/9304 [24:24<04:24,  4.55it/s]

2025-05-20 17:00:18,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:19,119 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8103/9304 [24:24<04:00,  4.99it/s]

2025-05-20 17:00:19,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:19,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:19,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8106/9304 [24:24<03:06,  6.41it/s]

2025-05-20 17:00:19,454 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:20,015 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8108/9304 [24:25<03:56,  5.06it/s]

2025-05-20 17:00:20,180 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8109/9304 [24:25<03:48,  5.23it/s]

2025-05-20 17:00:20,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8110/9304 [24:25<04:33,  4.36it/s]

2025-05-20 17:00:20,670 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8111/9304 [24:25<04:04,  4.89it/s]

2025-05-20 17:00:20,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:20,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:20,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8114/9304 [24:26<02:25,  8.17it/s]

2025-05-20 17:00:20,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:21,409 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8116/9304 [24:26<03:37,  5.47it/s]

2025-05-20 17:00:21,814 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8117/9304 [24:27<04:25,  4.48it/s]

2025-05-20 17:00:21,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8118/9304 [24:27<04:01,  4.91it/s]

2025-05-20 17:00:22,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8119/9304 [24:27<03:35,  5.49it/s]

2025-05-20 17:00:22,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8120/9304 [24:27<03:20,  5.92it/s]

2025-05-20 17:00:22,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8121/9304 [24:27<03:49,  5.15it/s]

2025-05-20 17:00:22,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8122/9304 [24:27<03:33,  5.53it/s]

2025-05-20 17:00:22,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:22,725 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8124/9304 [24:28<02:35,  7.61it/s]

2025-05-20 17:00:22,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:23,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8126/9304 [24:28<03:25,  5.74it/s]

2025-05-20 17:00:23,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8127/9304 [24:29<04:45,  4.12it/s]

2025-05-20 17:00:23,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:24,024 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8129/9304 [24:29<04:09,  4.71it/s]

2025-05-20 17:00:24,174 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8130/9304 [24:29<03:51,  5.07it/s]

2025-05-20 17:00:24,317 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8131/9304 [24:29<03:36,  5.42it/s]

2025-05-20 17:00:24,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:24,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8133/9304 [24:29<02:58,  6.58it/s]

2025-05-20 17:00:24,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8134/9304 [24:29<02:46,  7.03it/s]

2025-05-20 17:00:24,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:24,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8136/9304 [24:30<02:36,  7.46it/s]

2025-05-20 17:00:25,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8137/9304 [24:30<03:49,  5.08it/s]

2025-05-20 17:00:25,487 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8138/9304 [24:30<03:47,  5.12it/s]

2025-05-20 17:00:25,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 87%|████████▋ | 8139/9304 [24:31<05:06,  3.79it/s]

2025-05-20 17:00:26,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:26,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8141/9304 [24:31<03:44,  5.18it/s]

2025-05-20 17:00:26,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:26,341 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8143/9304 [24:31<03:05,  6.27it/s]

2025-05-20 17:00:26,427 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:26,639 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8145/9304 [24:31<02:59,  6.47it/s]

2025-05-20 17:00:26,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8146/9304 [24:32<02:49,  6.85it/s]

2025-05-20 17:00:27,166 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8147/9304 [24:32<03:58,  4.86it/s]

2025-05-20 17:00:27,651 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8148/9304 [24:32<05:16,  3.65it/s]

2025-05-20 17:00:27,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:27,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:27,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8151/9304 [24:33<03:38,  5.28it/s]

2025-05-20 17:00:28,069 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:28,128 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8153/9304 [24:33<02:55,  6.56it/s]

2025-05-20 17:00:28,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8154/9304 [24:33<02:46,  6.91it/s]

2025-05-20 17:00:28,291 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:28,568 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8156/9304 [24:33<02:54,  6.59it/s]

2025-05-20 17:00:29,035 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8157/9304 [24:34<04:05,  4.67it/s]

2025-05-20 17:00:29,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:29,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8159/9304 [24:34<03:40,  5.20it/s]

2025-05-20 17:00:29,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8160/9304 [24:34<04:02,  4.71it/s]

2025-05-20 17:00:29,739 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8161/9304 [24:35<03:36,  5.29it/s]

2025-05-20 17:00:29,811 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:29,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:29,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:29,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8164/9304 [24:35<02:22,  8.01it/s]

2025-05-20 17:00:30,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8166/9304 [24:35<01:58,  9.57it/s]

2025-05-20 17:00:30,471 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:30,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8168/9304 [24:35<02:53,  6.54it/s]

2025-05-20 17:00:30,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8169/9304 [24:36<02:57,  6.41it/s]

2025-05-20 17:00:31,170 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8170/9304 [24:36<04:04,  4.64it/s]

2025-05-20 17:00:31,306 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8171/9304 [24:36<03:44,  5.04it/s]

2025-05-20 17:00:31,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:31,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:31,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8173/9304 [24:36<02:50,  6.63it/s]

2025-05-20 17:00:31,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:31,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8176/9304 [24:37<02:13,  8.42it/s]

2025-05-20 17:00:31,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8177/9304 [24:37<02:21,  7.99it/s]

2025-05-20 17:00:31,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8178/9304 [24:37<02:22,  7.90it/s]

2025-05-20 17:00:32,341 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8179/9304 [24:37<03:17,  5.69it/s]

2025-05-20 17:00:32,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8180/9304 [24:38<05:12,  3.60it/s]

2025-05-20 17:00:33,043 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8181/9304 [24:38<04:23,  4.27it/s]

2025-05-20 17:00:33,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:33,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:33,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8184/9304 [24:38<03:00,  6.21it/s]

2025-05-20 17:00:33,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:33,419 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:33,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8187/9304 [24:38<02:12,  8.46it/s]

2025-05-20 17:00:33,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:34,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8189/9304 [24:39<03:32,  5.26it/s]

2025-05-20 17:00:34,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:34,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8191/9304 [24:39<03:38,  5.10it/s]

2025-05-20 17:00:34,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8192/9304 [24:40<03:57,  4.68it/s]

2025-05-20 17:00:35,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:35,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8194/9304 [24:40<03:03,  6.05it/s]

2025-05-20 17:00:35,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8195/9304 [24:40<02:51,  6.48it/s]

2025-05-20 17:00:35,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:35,245 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:35,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8198/9304 [24:40<02:33,  7.20it/s]

2025-05-20 17:00:35,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8199/9304 [24:41<02:31,  7.29it/s]

2025-05-20 17:00:35,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:36,417 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8201/9304 [24:41<03:53,  4.72it/s]

2025-05-20 17:00:36,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:36,576 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8203/9304 [24:41<03:06,  5.91it/s]

2025-05-20 17:00:36,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:36,606 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:36,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8206/9304 [24:42<02:16,  8.02it/s]

2025-05-20 17:00:36,964 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:37,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8208/9304 [24:42<02:29,  7.35it/s]

2025-05-20 17:00:37,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8209/9304 [24:42<02:46,  6.56it/s]

2025-05-20 17:00:37,690 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8210/9304 [24:43<03:32,  5.16it/s]

2025-05-20 17:00:38,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8211/9304 [24:43<04:18,  4.23it/s]

2025-05-20 17:00:38,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8212/9304 [24:43<05:08,  3.54it/s]

2025-05-20 17:00:38,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8213/9304 [24:44<04:40,  3.89it/s]

2025-05-20 17:00:38,762 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:38,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:38,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8215/9304 [24:44<03:27,  5.25it/s]

2025-05-20 17:00:39,074 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8217/9304 [24:44<02:49,  6.40it/s]

2025-05-20 17:00:39,253 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8218/9304 [24:44<02:52,  6.29it/s]

2025-05-20 17:00:39,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:40,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8220/9304 [24:45<04:26,  4.07it/s]

2025-05-20 17:00:40,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8221/9304 [24:45<04:45,  3.79it/s]

2025-05-20 17:00:40,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8222/9304 [24:45<04:26,  4.06it/s]

2025-05-20 17:00:40,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:40,793 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:40,795 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8224/9304 [24:46<03:31,  5.10it/s]

2025-05-20 17:00:40,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8226/9304 [24:46<02:35,  6.95it/s]

2025-05-20 17:00:40,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:41,037 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8228/9304 [24:46<02:08,  8.40it/s]

2025-05-20 17:00:41,378 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:41,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8230/9304 [24:47<04:09,  4.30it/s]

2025-05-20 17:00:42,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:42,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8231/9304 [24:47<04:02,  4.42it/s]

2025-05-20 17:00:42,362 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8233/9304 [24:47<03:13,  5.55it/s]

2025-05-20 17:00:42,510 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 88%|████████▊ | 8234/9304 [24:47<03:06,  5.74it/s]

2025-05-20 17:00:42,748 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8235/9304 [24:48<03:20,  5.34it/s]

2025-05-20 17:00:42,791 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:42,864 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8237/9304 [24:48<02:28,  7.18it/s]

2025-05-20 17:00:42,955 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:43,115 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8239/9304 [24:48<02:21,  7.53it/s]

2025-05-20 17:00:44,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8240/9304 [24:49<05:21,  3.31it/s]

2025-05-20 17:00:44,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:44,260 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8242/9304 [24:49<03:57,  4.48it/s]

2025-05-20 17:00:44,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:44,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8244/9304 [24:49<03:21,  5.25it/s]

2025-05-20 17:00:44,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8245/9304 [24:50<03:20,  5.29it/s]

2025-05-20 17:00:44,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8246/9304 [24:50<03:18,  5.33it/s]

2025-05-20 17:00:44,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:45,693 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8248/9304 [24:51<04:47,  3.67it/s]

2025-05-20 17:00:45,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:45,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8250/9304 [24:51<03:50,  4.57it/s]

2025-05-20 17:00:46,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:46,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8252/9304 [24:51<02:51,  6.13it/s]

2025-05-20 17:00:46,302 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:46,364 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8254/9304 [24:51<02:49,  6.18it/s]

2025-05-20 17:00:46,374 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:46,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8256/9304 [24:52<02:47,  6.25it/s]

2025-05-20 17:00:47,028 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▊ | 8257/9304 [24:52<03:26,  5.08it/s]

2025-05-20 17:00:47,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8258/9304 [24:52<04:21,  3.99it/s]

2025-05-20 17:00:47,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8259/9304 [24:52<03:46,  4.61it/s]

2025-05-20 17:00:47,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:47,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:47,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8262/9304 [24:53<02:21,  7.39it/s]

2025-05-20 17:00:47,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:48,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8264/9304 [24:53<02:24,  7.21it/s]

2025-05-20 17:00:48,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8265/9304 [24:53<02:16,  7.61it/s]

2025-05-20 17:00:48,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8266/9304 [24:54<04:15,  4.07it/s]

2025-05-20 17:00:48,938 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8267/9304 [24:54<03:44,  4.61it/s]

2025-05-20 17:00:49,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8268/9304 [24:54<03:55,  4.41it/s]

2025-05-20 17:00:49,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8269/9304 [24:54<04:22,  3.94it/s]

2025-05-20 17:00:49,656 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8270/9304 [24:54<03:48,  4.52it/s]

2025-05-20 17:00:49,785 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8271/9304 [24:55<03:22,  5.11it/s]

2025-05-20 17:00:50,211 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8272/9304 [24:55<04:28,  3.84it/s]

2025-05-20 17:00:50,443 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8273/9304 [24:55<04:20,  3.95it/s]

2025-05-20 17:00:50,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8274/9304 [24:55<03:43,  4.61it/s]

2025-05-20 17:00:51,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8275/9304 [24:56<05:05,  3.37it/s]

2025-05-20 17:00:51,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:51,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8277/9304 [24:56<03:12,  5.33it/s]

2025-05-20 17:00:51,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8278/9304 [24:56<03:02,  5.63it/s]

2025-05-20 17:00:51,526 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8279/9304 [24:56<03:08,  5.45it/s]

2025-05-20 17:00:51,601 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:51,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8281/9304 [24:56<02:10,  7.82it/s]

2025-05-20 17:00:51,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:52,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8283/9304 [24:57<02:35,  6.58it/s]

2025-05-20 17:00:52,568 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8284/9304 [24:57<04:02,  4.21it/s]

2025-05-20 17:00:52,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:52,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8286/9304 [24:58<03:14,  5.22it/s]

2025-05-20 17:00:52,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8287/9304 [24:58<03:00,  5.63it/s]

2025-05-20 17:00:52,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:52,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:53,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8290/9304 [24:58<02:00,  8.39it/s]

2025-05-20 17:00:53,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:53,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8292/9304 [24:58<02:30,  6.73it/s]

2025-05-20 17:00:53,748 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8293/9304 [24:59<02:45,  6.11it/s]

2025-05-20 17:00:54,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8294/9304 [24:59<04:03,  4.15it/s]

2025-05-20 17:00:54,599 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8295/9304 [24:59<04:19,  3.89it/s]

2025-05-20 17:00:54,637 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:54,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8297/9304 [25:00<03:06,  5.41it/s]

2025-05-20 17:00:54,842 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:54,855 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8299/9304 [25:00<02:19,  7.21it/s]

2025-05-20 17:00:55,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:55,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8301/9304 [25:00<02:53,  5.77it/s]

2025-05-20 17:00:56,029 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8302/9304 [25:01<04:33,  3.66it/s]

2025-05-20 17:00:56,121 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:56,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8304/9304 [25:01<03:31,  4.72it/s]

2025-05-20 17:00:56,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8305/9304 [25:01<03:42,  4.49it/s]

2025-05-20 17:00:56,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:56,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:56,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8308/9304 [25:02<02:37,  6.32it/s]

2025-05-20 17:00:56,796 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:56,864 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:56,866 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8310/9304 [25:02<02:09,  7.69it/s]

2025-05-20 17:00:57,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8312/9304 [25:02<02:45,  6.01it/s]

2025-05-20 17:00:57,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8313/9304 [25:03<03:27,  4.77it/s]

2025-05-20 17:00:57,847 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:57,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8315/9304 [25:03<02:44,  6.00it/s]

2025-05-20 17:00:58,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:58,227 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8317/9304 [25:03<02:34,  6.37it/s]

2025-05-20 17:00:58,322 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:58,419 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8319/9304 [25:03<02:16,  7.21it/s]

2025-05-20 17:00:58,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:58,981 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8321/9304 [25:04<02:58,  5.50it/s]

2025-05-20 17:00:58,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:59,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8323/9304 [25:04<02:51,  5.73it/s]

2025-05-20 17:00:59,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8324/9304 [25:04<02:38,  6.17it/s]

2025-05-20 17:00:59,626 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 89%|████████▉ | 8325/9304 [25:04<02:51,  5.69it/s]

2025-05-20 17:00:59,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:00:59,686 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:00,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8328/9304 [25:05<03:13,  5.06it/s]

2025-05-20 17:01:00,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:00,609 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8330/9304 [25:05<02:59,  5.41it/s]

2025-05-20 17:01:00,676 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:00,686 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:00,709 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:00,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8334/9304 [25:06<02:01,  7.96it/s]

2025-05-20 17:01:00,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8335/9304 [25:06<02:00,  8.01it/s]

2025-05-20 17:01:01,006 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:01,430 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8337/9304 [25:06<02:31,  6.40it/s]

2025-05-20 17:01:02,044 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8338/9304 [25:07<03:56,  4.08it/s]

2025-05-20 17:01:02,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:02,274 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8340/9304 [25:07<03:06,  5.17it/s]

2025-05-20 17:01:02,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:02,345 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:02,583 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8343/9304 [25:07<02:30,  6.40it/s]

2025-05-20 17:01:02,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8344/9304 [25:08<02:23,  6.68it/s]

2025-05-20 17:01:02,760 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:02,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8346/9304 [25:08<02:09,  7.38it/s]

2025-05-20 17:01:03,638 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8347/9304 [25:08<03:54,  4.09it/s]

2025-05-20 17:01:03,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:03,773 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8349/9304 [25:09<02:55,  5.45it/s]

2025-05-20 17:01:04,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8350/9304 [25:09<03:06,  5.11it/s]

2025-05-20 17:01:04,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:04,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8352/9304 [25:09<02:25,  6.56it/s]

2025-05-20 17:01:04,186 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:04,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:04,272 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:04,537 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8356/9304 [25:09<01:54,  8.27it/s]

2025-05-20 17:01:05,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8357/9304 [25:10<03:06,  5.08it/s]

2025-05-20 17:01:05,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8358/9304 [25:10<02:52,  5.49it/s]

2025-05-20 17:01:05,614 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8359/9304 [25:10<03:25,  4.61it/s]

2025-05-20 17:01:05,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:05,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:05,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8361/9304 [25:11<02:52,  5.48it/s]

2025-05-20 17:01:06,085 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8363/9304 [25:11<02:28,  6.35it/s]

2025-05-20 17:01:06,407 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8364/9304 [25:11<02:58,  5.27it/s]

2025-05-20 17:01:06,421 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:06,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8366/9304 [25:11<02:38,  5.91it/s]

2025-05-20 17:01:06,703 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:07,113 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8368/9304 [25:12<02:54,  5.35it/s]

2025-05-20 17:01:07,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:07,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:07,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8371/9304 [25:12<01:56,  7.98it/s]

2025-05-20 17:01:07,429 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:07,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|████████▉ | 8373/9304 [25:13<02:30,  6.19it/s]

2025-05-20 17:01:07,883 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8374/9304 [25:13<02:27,  6.31it/s]

2025-05-20 17:01:08,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8375/9304 [25:13<02:33,  6.04it/s]

2025-05-20 17:01:08,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8376/9304 [25:13<03:07,  4.94it/s]

2025-05-20 17:01:08,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8377/9304 [25:14<03:43,  4.15it/s]

2025-05-20 17:01:08,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:08,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:08,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8380/9304 [25:14<02:18,  6.69it/s]

2025-05-20 17:01:09,049 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:09,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8382/9304 [25:14<01:58,  7.76it/s]

2025-05-20 17:01:09,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8383/9304 [25:14<02:02,  7.51it/s]

2025-05-20 17:01:09,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8384/9304 [25:14<02:50,  5.41it/s]

2025-05-20 17:01:09,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:10,253 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8386/9304 [25:15<03:30,  4.35it/s]

2025-05-20 17:01:10,328 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:10,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:10,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8389/9304 [25:15<02:21,  6.47it/s]

2025-05-20 17:01:10,490 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:10,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8391/9304 [25:16<02:18,  6.60it/s]

2025-05-20 17:01:10,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8392/9304 [25:16<02:22,  6.40it/s]

2025-05-20 17:01:11,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8393/9304 [25:16<02:30,  6.04it/s]

2025-05-20 17:01:11,308 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8394/9304 [25:16<02:34,  5.88it/s]

2025-05-20 17:01:11,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:11,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8396/9304 [25:17<02:59,  5.07it/s]

2025-05-20 17:01:11,826 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:11,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8398/9304 [25:17<02:25,  6.24it/s]

2025-05-20 17:01:12,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8399/9304 [25:17<02:20,  6.43it/s]

2025-05-20 17:01:12,137 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:12,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:12,677 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8402/9304 [25:18<02:35,  5.82it/s]

2025-05-20 17:01:12,832 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8403/9304 [25:18<02:31,  5.96it/s]

2025-05-20 17:01:12,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:13,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8405/9304 [25:18<02:21,  6.35it/s]

2025-05-20 17:01:13,274 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8406/9304 [25:18<02:23,  6.25it/s]

2025-05-20 17:01:13,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8407/9304 [25:18<03:09,  4.74it/s]

2025-05-20 17:01:13,750 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:13,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8409/9304 [25:19<02:31,  5.91it/s]

2025-05-20 17:01:13,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:14,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8411/9304 [25:19<02:56,  5.06it/s]

2025-05-20 17:01:14,388 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:14,448 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:14,586 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8414/9304 [25:19<02:07,  7.00it/s]

2025-05-20 17:01:14,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:14,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8415/9304 [25:20<02:15,  6.58it/s]

2025-05-20 17:01:15,224 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8417/9304 [25:20<02:34,  5.74it/s]

2025-05-20 17:01:15,311 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:15,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 90%|█████████ | 8419/9304 [25:21<02:57,  4.99it/s]

2025-05-20 17:01:15,820 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:16,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8421/9304 [25:21<02:52,  5.13it/s]

2025-05-20 17:01:16,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:16,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:16,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8424/9304 [25:21<02:06,  6.94it/s]

2025-05-20 17:01:16,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8425/9304 [25:22<02:44,  5.33it/s]

2025-05-20 17:01:16,825 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8426/9304 [25:22<02:30,  5.83it/s]

2025-05-20 17:01:17,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8427/9304 [25:22<02:47,  5.24it/s]

2025-05-20 17:01:17,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:17,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8429/9304 [25:22<02:24,  6.05it/s]

2025-05-20 17:01:17,719 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8430/9304 [25:23<03:05,  4.71it/s]

2025-05-20 17:01:17,837 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8431/9304 [25:23<02:46,  5.25it/s]

2025-05-20 17:01:17,860 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:18,023 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8433/9304 [25:23<02:11,  6.61it/s]

2025-05-20 17:01:18,075 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:18,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:18,250 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8436/9304 [25:23<01:41,  8.59it/s]

2025-05-20 17:01:18,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8437/9304 [25:23<02:01,  7.14it/s]

2025-05-20 17:01:18,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:18,803 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8439/9304 [25:24<02:05,  6.87it/s]

2025-05-20 17:01:19,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8440/9304 [25:24<03:36,  3.99it/s]

2025-05-20 17:01:19,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8441/9304 [25:25<03:30,  4.10it/s]

2025-05-20 17:01:19,863 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8442/9304 [25:25<03:11,  4.49it/s]

2025-05-20 17:01:19,896 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:19,934 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:19,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:19,975 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8446/9304 [25:25<01:34,  9.08it/s]

2025-05-20 17:01:20,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:20,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8448/9304 [25:25<02:29,  5.74it/s]

2025-05-20 17:01:20,861 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:21,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8450/9304 [25:26<02:54,  4.90it/s]

2025-05-20 17:01:21,205 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:21,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8452/9304 [25:26<02:25,  5.85it/s]

2025-05-20 17:01:21,524 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8453/9304 [25:26<02:23,  5.92it/s]

2025-05-20 17:01:21,792 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8454/9304 [25:27<02:40,  5.30it/s]

2025-05-20 17:01:21,835 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:21,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:22,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8457/9304 [25:27<01:54,  7.37it/s]

2025-05-20 17:01:22,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8458/9304 [25:27<03:04,  4.59it/s]

2025-05-20 17:01:22,706 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:23,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8460/9304 [25:28<03:10,  4.44it/s]

2025-05-20 17:01:23,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:23,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8462/9304 [25:28<02:24,  5.83it/s]

2025-05-20 17:01:23,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:23,443 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8464/9304 [25:28<02:08,  6.52it/s]

2025-05-20 17:01:23,497 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:23,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:23,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8466/9304 [25:28<01:49,  7.64it/s]

2025-05-20 17:01:24,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8468/9304 [25:29<02:55,  4.76it/s]

2025-05-20 17:01:24,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8469/9304 [25:29<03:06,  4.47it/s]

2025-05-20 17:01:24,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8470/9304 [25:30<03:01,  4.59it/s]

2025-05-20 17:01:24,987 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8471/9304 [25:30<02:44,  5.06it/s]

2025-05-20 17:01:25,157 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8472/9304 [25:30<02:38,  5.26it/s]

2025-05-20 17:01:25,173 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:25,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:25,240 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:25,275 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8476/9304 [25:30<01:19, 10.38it/s]

2025-05-20 17:01:25,551 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:26,356 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8478/9304 [25:31<03:07,  4.41it/s]

2025-05-20 17:01:26,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:26,513 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8480/9304 [25:31<02:32,  5.41it/s]

2025-05-20 17:01:26,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:26,658 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8482/9304 [25:31<02:03,  6.67it/s]

2025-05-20 17:01:26,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:26,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8484/9304 [25:32<01:42,  7.98it/s]

2025-05-20 17:01:26,807 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:27,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8486/9304 [25:32<01:58,  6.93it/s]

2025-05-20 17:01:27,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:27,976 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████ | 8488/9304 [25:33<03:00,  4.52it/s]

2025-05-20 17:01:27,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:28,065 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:28,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8491/9304 [25:33<02:05,  6.49it/s]

2025-05-20 17:01:28,270 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:28,372 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8493/9304 [25:33<02:00,  6.72it/s]

2025-05-20 17:01:28,544 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:28,815 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8495/9304 [25:34<02:14,  6.00it/s]

2025-05-20 17:01:28,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:28,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8497/9304 [25:34<01:53,  7.09it/s]

2025-05-20 17:01:29,361 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:29,737 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8499/9304 [25:35<02:49,  4.74it/s]

2025-05-20 17:01:29,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8500/9304 [25:35<02:40,  5.01it/s]

2025-05-20 17:01:29,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8501/9304 [25:35<02:26,  5.50it/s]

2025-05-20 17:01:30,109 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8502/9304 [25:35<02:14,  5.95it/s]

2025-05-20 17:01:30,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:30,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8503/9304 [25:35<02:18,  5.79it/s]

2025-05-20 17:01:30,502 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8505/9304 [25:35<01:55,  6.91it/s]

2025-05-20 17:01:30,858 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8506/9304 [25:36<02:33,  5.19it/s]

2025-05-20 17:01:30,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8507/9304 [25:36<02:21,  5.63it/s]

2025-05-20 17:01:31,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8508/9304 [25:36<02:39,  4.99it/s]

2025-05-20 17:01:31,365 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8509/9304 [25:36<02:19,  5.70it/s]

2025-05-20 17:01:31,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8510/9304 [25:36<02:04,  6.40it/s]

2025-05-20 17:01:31,565 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:31,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8512/9304 [25:36<01:32,  8.53it/s]

2025-05-20 17:01:31,712 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 91%|█████████▏| 8513/9304 [25:37<01:32,  8.59it/s]

2025-05-20 17:01:32,025 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8514/9304 [25:37<02:09,  6.09it/s]

2025-05-20 17:01:32,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:32,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8516/9304 [25:37<02:30,  5.23it/s]

2025-05-20 17:01:32,531 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:32,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8518/9304 [25:37<01:55,  6.78it/s]

2025-05-20 17:01:32,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8519/9304 [25:38<01:55,  6.77it/s]

2025-05-20 17:01:33,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8520/9304 [25:38<02:15,  5.78it/s]

2025-05-20 17:01:33,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8521/9304 [25:38<02:37,  4.96it/s]

2025-05-20 17:01:33,412 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:33,547 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8523/9304 [25:38<02:08,  6.08it/s]

2025-05-20 17:01:33,855 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8524/9304 [25:39<02:35,  5.03it/s]

2025-05-20 17:01:33,940 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:34,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8526/9304 [25:39<02:09,  6.00it/s]

2025-05-20 17:01:34,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:34,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:34,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8528/9304 [25:39<01:48,  7.12it/s]

2025-05-20 17:01:34,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8530/9304 [25:39<01:25,  9.02it/s]

2025-05-20 17:01:34,925 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:35,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8532/9304 [25:40<02:24,  5.33it/s]

2025-05-20 17:01:35,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8533/9304 [25:40<02:28,  5.18it/s]

2025-05-20 17:01:35,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8534/9304 [25:40<02:48,  4.58it/s]

2025-05-20 17:01:35,768 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8535/9304 [25:41<02:36,  4.91it/s]

2025-05-20 17:01:35,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:35,891 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8537/9304 [25:41<01:53,  6.77it/s]

2025-05-20 17:01:35,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:36,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8539/9304 [25:41<01:58,  6.46it/s]

2025-05-20 17:01:36,361 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8540/9304 [25:41<01:54,  6.67it/s]

2025-05-20 17:01:36,374 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:36,736 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8542/9304 [25:42<02:05,  6.09it/s]

2025-05-20 17:01:36,839 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8543/9304 [25:42<01:55,  6.60it/s]

2025-05-20 17:01:37,041 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8544/9304 [25:42<02:03,  6.16it/s]

2025-05-20 17:01:37,377 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8545/9304 [25:42<02:35,  4.88it/s]

2025-05-20 17:01:37,437 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:37,525 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8547/9304 [25:42<01:54,  6.61it/s]

2025-05-20 17:01:37,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:37,700 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8549/9304 [25:43<01:35,  7.87it/s]

2025-05-20 17:01:37,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8550/9304 [25:43<01:44,  7.22it/s]

2025-05-20 17:01:38,182 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8551/9304 [25:43<02:12,  5.66it/s]

2025-05-20 17:01:38,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8552/9304 [25:43<02:30,  4.98it/s]

2025-05-20 17:01:38,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:39,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:39,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8554/9304 [25:44<02:52,  4.34it/s]

2025-05-20 17:01:39,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:39,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:39,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8558/9304 [25:44<01:31,  8.17it/s]

2025-05-20 17:01:39,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:39,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8560/9304 [25:44<02:01,  6.11it/s]

2025-05-20 17:01:39,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:40,034 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8562/9304 [25:45<02:05,  5.92it/s]

2025-05-20 17:01:40,305 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8563/9304 [25:45<02:18,  5.35it/s]

2025-05-20 17:01:40,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8564/9304 [25:45<02:16,  5.40it/s]

2025-05-20 17:01:40,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8565/9304 [25:45<02:09,  5.69it/s]

2025-05-20 17:01:40,654 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:40,733 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8567/9304 [25:46<01:35,  7.71it/s]

2025-05-20 17:01:40,869 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:41,498 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8569/9304 [25:46<02:40,  4.58it/s]

2025-05-20 17:01:41,513 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:41,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:41,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8572/9304 [25:47<01:54,  6.37it/s]

2025-05-20 17:01:41,875 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8573/9304 [25:47<01:53,  6.42it/s]

2025-05-20 17:01:42,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8574/9304 [25:47<02:09,  5.64it/s]

2025-05-20 17:01:42,238 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:42,558 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8576/9304 [25:47<02:17,  5.31it/s]

2025-05-20 17:01:42,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:42,615 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:42,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8579/9304 [25:48<01:41,  7.15it/s]

2025-05-20 17:01:43,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8580/9304 [25:48<01:59,  6.05it/s]

2025-05-20 17:01:43,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:43,496 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8582/9304 [25:48<02:10,  5.55it/s]

2025-05-20 17:01:43,556 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:43,602 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8584/9304 [25:48<01:40,  7.15it/s]

2025-05-20 17:01:44,058 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8585/9304 [25:49<02:22,  5.05it/s]

2025-05-20 17:01:44,301 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8586/9304 [25:49<02:29,  4.81it/s]

2025-05-20 17:01:44,447 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8587/9304 [25:49<02:18,  5.19it/s]

2025-05-20 17:01:44,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:44,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:44,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8590/9304 [25:50<01:56,  6.11it/s]

2025-05-20 17:01:44,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:44,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8592/9304 [25:50<01:33,  7.64it/s]

2025-05-20 17:01:44,987 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:45,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8594/9304 [25:50<01:28,  7.99it/s]

2025-05-20 17:01:45,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8595/9304 [25:51<02:50,  4.15it/s]

2025-05-20 17:01:45,995 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:46,013 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:46,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:46,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8599/9304 [25:51<01:43,  6.78it/s]

2025-05-20 17:01:46,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:46,271 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:46,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8602/9304 [25:51<01:34,  7.44it/s]

2025-05-20 17:01:46,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8603/9304 [25:51<01:31,  7.63it/s]

2025-05-20 17:01:46,909 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8604/9304 [25:52<01:49,  6.40it/s]

2025-05-20 17:01:47,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 92%|█████████▏| 8605/9304 [25:52<02:59,  3.90it/s]

2025-05-20 17:01:47,608 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:47,679 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:47,682 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8607/9304 [25:53<02:08,  5.44it/s]

2025-05-20 17:01:47,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:47,999 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:48,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8610/9304 [25:53<01:44,  6.62it/s]

2025-05-20 17:01:48,349 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8612/9304 [25:53<01:48,  6.40it/s]

2025-05-20 17:01:48,371 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:49,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8614/9304 [25:54<02:44,  4.19it/s]

2025-05-20 17:01:49,342 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8615/9304 [25:54<02:30,  4.58it/s]

2025-05-20 17:01:49,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:49,418 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:49,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:49,555 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8619/9304 [25:54<01:33,  7.31it/s]

2025-05-20 17:01:50,314 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:50,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8621/9304 [25:55<02:33,  4.46it/s]

2025-05-20 17:01:50,636 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8622/9304 [25:55<02:24,  4.73it/s]

2025-05-20 17:01:50,698 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:50,862 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8624/9304 [25:56<02:02,  5.57it/s]

2025-05-20 17:01:50,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:51,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8626/9304 [25:56<02:00,  5.65it/s]

2025-05-20 17:01:51,307 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8627/9304 [25:56<01:51,  6.09it/s]

2025-05-20 17:01:51,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8628/9304 [25:56<02:00,  5.60it/s]

2025-05-20 17:01:51,922 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8629/9304 [25:57<02:31,  4.47it/s]

2025-05-20 17:01:52,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8630/9304 [25:57<02:13,  5.05it/s]

2025-05-20 17:01:52,061 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:52,469 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8632/9304 [25:57<02:17,  4.87it/s]

2025-05-20 17:01:52,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:52,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:52,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8635/9304 [25:58<01:37,  6.88it/s]

2025-05-20 17:01:52,840 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8636/9304 [25:58<01:36,  6.91it/s]

2025-05-20 17:01:52,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:53,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8638/9304 [25:58<01:39,  6.68it/s]

2025-05-20 17:01:53,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8639/9304 [25:58<02:02,  5.43it/s]

2025-05-20 17:01:53,683 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8640/9304 [25:59<02:04,  5.35it/s]

2025-05-20 17:01:53,948 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8641/9304 [25:59<02:16,  4.85it/s]

2025-05-20 17:01:54,086 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8642/9304 [25:59<02:04,  5.33it/s]

2025-05-20 17:01:54,154 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:54,188 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8644/9304 [25:59<01:26,  7.61it/s]

2025-05-20 17:01:54,232 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:54,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8646/9304 [25:59<01:19,  8.29it/s]

2025-05-20 17:01:54,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8647/9304 [25:59<01:37,  6.74it/s]

2025-05-20 17:01:54,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:54,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:55,468 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:55,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8650/9304 [26:00<02:15,  4.82it/s]

2025-05-20 17:01:55,675 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8652/9304 [26:00<01:53,  5.74it/s]

2025-05-20 17:01:55,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:55,882 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8654/9304 [26:01<01:39,  6.51it/s]

2025-05-20 17:01:55,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:56,072 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8656/9304 [26:01<01:27,  7.38it/s]

2025-05-20 17:01:56,233 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8657/9304 [26:01<01:30,  7.17it/s]

2025-05-20 17:01:56,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:56,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8659/9304 [26:01<01:24,  7.59it/s]

2025-05-20 17:01:56,865 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8660/9304 [26:02<01:58,  5.45it/s]

2025-05-20 17:01:57,076 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8661/9304 [26:02<02:02,  5.26it/s]

2025-05-20 17:01:57,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:57,295 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:57,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8663/9304 [26:02<01:42,  6.23it/s]

2025-05-20 17:01:57,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8665/9304 [26:02<01:18,  8.18it/s]

2025-05-20 17:01:57,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:57,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8667/9304 [26:02<01:03, 10.01it/s]

2025-05-20 17:01:57,847 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:58,062 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8669/9304 [26:03<01:38,  6.42it/s]

2025-05-20 17:01:58,517 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:58,652 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8671/9304 [26:03<02:06,  5.02it/s]

2025-05-20 17:01:58,791 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8672/9304 [26:04<02:00,  5.25it/s]

2025-05-20 17:01:58,953 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8673/9304 [26:04<01:55,  5.47it/s]

2025-05-20 17:01:59,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8674/9304 [26:04<01:54,  5.49it/s]

2025-05-20 17:01:59,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:01:59,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8676/9304 [26:04<01:48,  5.80it/s]

2025-05-20 17:01:59,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:00,539 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8678/9304 [26:05<03:12,  3.26it/s]

2025-05-20 17:02:00,598 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:00,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8680/9304 [26:05<02:17,  4.55it/s]

2025-05-20 17:02:00,924 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8681/9304 [26:06<02:24,  4.31it/s]

2025-05-20 17:02:01,011 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:01,141 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8683/9304 [26:06<01:56,  5.31it/s]

2025-05-20 17:02:01,190 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:01,293 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8685/9304 [26:06<01:32,  6.68it/s]

2025-05-20 17:02:01,389 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8686/9304 [26:06<01:26,  7.12it/s]

2025-05-20 17:02:01,845 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8687/9304 [26:07<02:08,  4.81it/s]

2025-05-20 17:02:01,996 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8688/9304 [26:07<01:59,  5.15it/s]

2025-05-20 17:02:02,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8689/9304 [26:07<02:46,  3.69it/s]

2025-05-20 17:02:02,563 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:02,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8691/9304 [26:08<02:10,  4.69it/s]

2025-05-20 17:02:02,817 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:02,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8693/9304 [26:08<01:39,  6.14it/s]

2025-05-20 17:02:03,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:03,023 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8695/9304 [26:08<01:15,  8.03it/s]

2025-05-20 17:02:03,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:03,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8697/9304 [26:08<01:47,  5.63it/s]

2025-05-20 17:02:03,856 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8698/9304 [26:09<01:58,  5.12it/s]

2025-05-20 17:02:04,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 93%|█████████▎| 8699/9304 [26:09<01:53,  5.35it/s]

2025-05-20 17:02:04,031 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:04,456 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8701/9304 [26:09<02:01,  4.98it/s]

2025-05-20 17:02:04,499 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:04,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:04,667 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8704/9304 [26:09<01:24,  7.08it/s]

2025-05-20 17:02:04,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8705/9304 [26:10<01:35,  6.28it/s]

2025-05-20 17:02:05,125 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8706/9304 [26:10<01:44,  5.73it/s]

2025-05-20 17:02:05,478 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8707/9304 [26:10<02:05,  4.77it/s]

2025-05-20 17:02:05,702 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8708/9304 [26:11<02:07,  4.68it/s]

2025-05-20 17:02:05,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8709/9304 [26:11<01:51,  5.34it/s]

2025-05-20 17:02:05,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:05,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8711/9304 [26:11<01:16,  7.74it/s]

2025-05-20 17:02:06,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:06,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8713/9304 [26:11<01:26,  6.87it/s]

2025-05-20 17:02:06,779 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8714/9304 [26:12<02:13,  4.41it/s]

2025-05-20 17:02:06,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8715/9304 [26:12<01:59,  4.94it/s]

2025-05-20 17:02:07,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8716/9304 [26:12<01:49,  5.38it/s]

2025-05-20 17:02:07,255 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8717/9304 [26:12<01:54,  5.11it/s]

2025-05-20 17:02:07,346 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:07,420 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8719/9304 [26:12<01:25,  6.84it/s]

2025-05-20 17:02:07,445 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:07,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8721/9304 [26:13<01:36,  6.01it/s]

2025-05-20 17:02:07,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▎| 8722/9304 [26:13<01:33,  6.20it/s]

2025-05-20 17:02:08,160 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:08,163 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8723/9304 [26:13<01:37,  5.95it/s]

2025-05-20 17:02:08,335 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8725/9304 [26:13<01:19,  7.29it/s]

2025-05-20 17:02:08,800 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8726/9304 [26:14<02:02,  4.74it/s]

2025-05-20 17:02:08,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8727/9304 [26:14<01:52,  5.14it/s]

2025-05-20 17:02:09,020 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:09,126 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8729/9304 [26:14<01:27,  6.59it/s]

2025-05-20 17:02:09,156 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:09,282 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8731/9304 [26:14<01:12,  7.95it/s]

2025-05-20 17:02:09,776 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8732/9304 [26:15<01:53,  5.02it/s]

2025-05-20 17:02:09,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8733/9304 [26:15<01:55,  4.94it/s]

2025-05-20 17:02:10,027 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:10,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:10,305 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8736/9304 [26:15<01:27,  6.47it/s]

2025-05-20 17:02:10,557 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8737/9304 [26:15<01:37,  5.81it/s]

2025-05-20 17:02:10,704 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8738/9304 [26:16<01:35,  5.95it/s]

2025-05-20 17:02:10,929 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8739/9304 [26:16<01:43,  5.46it/s]

2025-05-20 17:02:10,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:11,169 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8741/9304 [26:16<01:28,  6.33it/s]

2025-05-20 17:02:11,367 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8742/9304 [26:16<01:32,  6.08it/s]

2025-05-20 17:02:11,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8743/9304 [26:16<01:34,  5.93it/s]

2025-05-20 17:02:11,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:11,763 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8745/9304 [26:17<01:20,  6.96it/s]

2025-05-20 17:02:12,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8746/9304 [26:17<01:46,  5.22it/s]

2025-05-20 17:02:12,321 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8747/9304 [26:17<01:48,  5.12it/s]

2025-05-20 17:02:12,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:12,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8749/9304 [26:17<01:18,  7.09it/s]

2025-05-20 17:02:12,670 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8750/9304 [26:17<01:27,  6.32it/s]

2025-05-20 17:02:12,708 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:12,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8752/9304 [26:18<01:10,  7.86it/s]

2025-05-20 17:02:13,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8753/9304 [26:18<01:33,  5.88it/s]

2025-05-20 17:02:13,581 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8754/9304 [26:18<02:08,  4.28it/s]

2025-05-20 17:02:13,628 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:13,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8756/9304 [26:19<01:31,  6.01it/s]

2025-05-20 17:02:13,787 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:13,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8758/9304 [26:19<01:16,  7.13it/s]

2025-05-20 17:02:14,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8759/9304 [26:19<01:33,  5.84it/s]

2025-05-20 17:02:14,267 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:14,281 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:14,482 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8762/9304 [26:19<01:12,  7.43it/s]

2025-05-20 17:02:14,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8763/9304 [26:20<01:23,  6.45it/s]

2025-05-20 17:02:15,088 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8764/9304 [26:20<01:47,  5.03it/s]

2025-05-20 17:02:15,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8765/9304 [26:20<01:48,  4.98it/s]

2025-05-20 17:02:15,434 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8766/9304 [26:20<01:39,  5.43it/s]

2025-05-20 17:02:15,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8767/9304 [26:20<01:32,  5.78it/s]

2025-05-20 17:02:15,720 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8768/9304 [26:21<01:30,  5.95it/s]

2025-05-20 17:02:15,786 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:15,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8770/9304 [26:21<01:12,  7.32it/s]

2025-05-20 17:02:16,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8771/9304 [26:21<01:15,  7.05it/s]

2025-05-20 17:02:16,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8772/9304 [26:21<01:41,  5.25it/s]

2025-05-20 17:02:16,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8773/9304 [26:21<01:36,  5.50it/s]

2025-05-20 17:02:16,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8774/9304 [26:22<01:34,  5.60it/s]

2025-05-20 17:02:16,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8775/9304 [26:22<01:37,  5.41it/s]

2025-05-20 17:02:17,283 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8776/9304 [26:22<02:00,  4.39it/s]

2025-05-20 17:02:17,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:17,483 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8777/9304 [26:22<01:54,  4.58it/s]

2025-05-20 17:02:17,794 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8779/9304 [26:23<01:41,  5.20it/s]

2025-05-20 17:02:18,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8780/9304 [26:23<02:01,  4.32it/s]

2025-05-20 17:02:18,176 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:18,256 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8782/9304 [26:23<01:23,  6.27it/s]

2025-05-20 17:02:18,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:18,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:18,571 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8784/9304 [26:23<01:20,  6.44it/s]

2025-05-20 17:02:18,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8786/9304 [26:24<01:06,  7.83it/s]

2025-05-20 17:02:18,849 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8787/9304 [26:24<01:06,  7.72it/s]

2025-05-20 17:02:19,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8788/9304 [26:24<01:13,  6.98it/s]

2025-05-20 17:02:19,166 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8789/9304 [26:24<01:12,  7.14it/s]

2025-05-20 17:02:19,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8790/9304 [26:25<02:07,  4.04it/s]

2025-05-20 17:02:19,780 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:19,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 94%|█████████▍| 8792/9304 [26:25<01:31,  5.62it/s]

2025-05-20 17:02:19,932 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:19,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:19,960 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:20,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8796/9304 [26:25<00:53,  9.58it/s]

2025-05-20 17:02:20,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:20,634 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8798/9304 [26:25<01:18,  6.48it/s]

2025-05-20 17:02:21,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8799/9304 [26:26<01:53,  4.43it/s]

2025-05-20 17:02:21,376 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8800/9304 [26:26<01:47,  4.67it/s]

2025-05-20 17:02:21,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:21,432 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:21,577 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8803/9304 [26:26<01:14,  6.71it/s]

2025-05-20 17:02:21,669 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:21,717 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8805/9304 [26:27<01:02,  8.04it/s]

2025-05-20 17:02:22,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:22,159 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8807/9304 [26:27<01:15,  6.55it/s]

2025-05-20 17:02:22,467 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8808/9304 [26:27<01:29,  5.55it/s]

2025-05-20 17:02:22,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8809/9304 [26:28<01:47,  4.62it/s]

2025-05-20 17:02:22,904 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:23,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8811/9304 [26:28<01:33,  5.25it/s]

2025-05-20 17:02:23,165 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:23,191 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:23,207 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:23,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8815/9304 [26:28<01:00,  8.13it/s]

2025-05-20 17:02:24,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8816/9304 [26:29<01:55,  4.22it/s]

2025-05-20 17:02:24,390 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:24,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8817/9304 [26:29<01:50,  4.42it/s]

2025-05-20 17:02:24,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:24,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8820/9304 [26:29<01:12,  6.65it/s]

2025-05-20 17:02:24,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:25,000 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:25,003 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8822/9304 [26:30<01:23,  5.79it/s]

2025-05-20 17:02:25,091 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:25,190 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8825/9304 [26:30<01:02,  7.68it/s]

2025-05-20 17:02:25,705 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:25,798 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8827/9304 [26:31<01:24,  5.65it/s]

2025-05-20 17:02:25,927 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8828/9304 [26:31<01:20,  5.90it/s]

2025-05-20 17:02:26,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8829/9304 [26:31<01:20,  5.87it/s]

2025-05-20 17:02:26,119 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:26,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8831/9304 [26:31<01:07,  7.04it/s]

2025-05-20 17:02:26,629 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8832/9304 [26:31<01:25,  5.49it/s]

2025-05-20 17:02:26,667 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:26,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:26,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8835/9304 [26:32<01:03,  7.38it/s]

2025-05-20 17:02:27,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8836/9304 [26:32<01:20,  5.83it/s]

2025-05-20 17:02:27,345 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8837/9304 [26:32<01:17,  6.03it/s]

2025-05-20 17:02:27,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▍| 8838/9304 [26:32<01:21,  5.73it/s]

2025-05-20 17:02:27,647 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:27,950 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8840/9304 [26:33<01:25,  5.43it/s]

2025-05-20 17:02:28,083 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8841/9304 [26:33<01:20,  5.74it/s]

2025-05-20 17:02:28,193 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8842/9304 [26:33<01:12,  6.33it/s]

2025-05-20 17:02:28,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:28,234 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:28,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8845/9304 [26:34<01:14,  6.16it/s]

2025-05-20 17:02:28,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8846/9304 [26:34<01:11,  6.38it/s]

2025-05-20 17:02:28,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:29,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8848/9304 [26:34<01:42,  4.47it/s]

2025-05-20 17:02:29,538 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:29,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8850/9304 [26:34<01:17,  5.84it/s]

2025-05-20 17:02:29,724 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:30,170 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8852/9304 [26:35<01:31,  4.94it/s]

2025-05-20 17:02:30,258 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:30,276 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:30,643 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8855/9304 [26:35<01:21,  5.51it/s]

2025-05-20 17:02:30,906 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8856/9304 [26:36<01:27,  5.12it/s]

2025-05-20 17:02:31,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8857/9304 [26:36<01:21,  5.48it/s]

2025-05-20 17:02:31,304 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8858/9304 [26:36<01:29,  4.98it/s]

2025-05-20 17:02:31,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:31,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:31,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8861/9304 [26:36<00:58,  7.64it/s]

2025-05-20 17:02:31,751 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8862/9304 [26:37<01:10,  6.31it/s]

2025-05-20 17:02:31,843 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:32,038 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8864/9304 [26:37<01:07,  6.49it/s]

2025-05-20 17:02:32,119 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:32,567 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8866/9304 [26:37<01:23,  5.25it/s]

2025-05-20 17:02:32,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:32,846 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8868/9304 [26:38<01:15,  5.75it/s]

2025-05-20 17:02:33,097 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:33,098 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:33,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8869/9304 [26:38<01:23,  5.23it/s]

2025-05-20 17:02:33,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8872/9304 [26:38<01:09,  6.20it/s]

2025-05-20 17:02:33,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:33,635 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8874/9304 [26:38<00:58,  7.36it/s]

2025-05-20 17:02:34,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8875/9304 [26:39<01:22,  5.23it/s]

2025-05-20 17:02:34,101 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:34,201 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8877/9304 [26:39<01:02,  6.82it/s]

2025-05-20 17:02:34,381 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8878/9304 [26:39<01:05,  6.49it/s]

2025-05-20 17:02:34,504 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8879/9304 [26:39<01:01,  6.86it/s]

2025-05-20 17:02:34,681 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8880/9304 [26:40<01:04,  6.54it/s]

2025-05-20 17:02:34,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8881/9304 [26:40<01:15,  5.63it/s]

2025-05-20 17:02:35,210 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8882/9304 [26:40<01:27,  4.83it/s]

2025-05-20 17:02:35,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:35,416 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8884/9304 [26:40<01:07,  6.19it/s]

2025-05-20 17:02:35,532 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 95%|█████████▌| 8885/9304 [26:40<01:02,  6.68it/s]

2025-05-20 17:02:35,745 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8886/9304 [26:41<01:09,  6.04it/s]

2025-05-20 17:02:36,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8887/9304 [26:41<01:52,  3.69it/s]

2025-05-20 17:02:36,358 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:36,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:36,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:36,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8891/9304 [26:41<01:02,  6.60it/s]

2025-05-20 17:02:36,678 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:37,046 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8893/9304 [26:42<01:11,  5.78it/s]

2025-05-20 17:02:37,392 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8894/9304 [26:42<01:24,  4.88it/s]

2025-05-20 17:02:37,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8895/9304 [26:43<01:38,  4.15it/s]

2025-05-20 17:02:37,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:37,967 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8897/9304 [26:43<01:16,  5.34it/s]

2025-05-20 17:02:38,106 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8898/9304 [26:43<01:11,  5.68it/s]

2025-05-20 17:02:38,190 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:38,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8900/9304 [26:43<01:16,  5.27it/s]

2025-05-20 17:02:38,568 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:38,722 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8902/9304 [26:44<01:03,  6.35it/s]

2025-05-20 17:02:38,790 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:39,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8904/9304 [26:44<01:13,  5.46it/s]

2025-05-20 17:02:39,410 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8905/9304 [26:44<01:15,  5.26it/s]

2025-05-20 17:02:39,554 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8906/9304 [26:44<01:12,  5.47it/s]

2025-05-20 17:02:39,740 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8907/9304 [26:45<01:11,  5.53it/s]

2025-05-20 17:02:39,759 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:40,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8909/9304 [26:45<01:07,  5.83it/s]

2025-05-20 17:02:40,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:40,410 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8911/9304 [26:45<01:08,  5.75it/s]

2025-05-20 17:02:40,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:40,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8913/9304 [26:46<01:17,  5.02it/s]

2025-05-20 17:02:41,009 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8914/9304 [26:46<01:12,  5.38it/s]

2025-05-20 17:02:41,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:41,087 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:41,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8917/9304 [26:46<01:08,  5.68it/s]

2025-05-20 17:02:41,605 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:41,630 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:41,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8920/9304 [26:46<00:46,  8.24it/s]

2025-05-20 17:02:41,978 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:42,559 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8922/9304 [26:47<01:21,  4.71it/s]

2025-05-20 17:02:42,660 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8923/9304 [26:47<01:14,  5.13it/s]

2025-05-20 17:02:42,672 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:42,680 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:42,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8926/9304 [26:48<00:48,  7.75it/s]

2025-05-20 17:02:43,008 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:43,117 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8928/9304 [26:48<00:53,  7.00it/s]

2025-05-20 17:02:43,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:43,584 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8930/9304 [26:48<01:03,  5.93it/s]

2025-05-20 17:02:43,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:43,879 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8931/9304 [26:49<01:10,  5.26it/s]

2025-05-20 17:02:44,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8933/9304 [26:49<01:01,  5.99it/s]

2025-05-20 17:02:44,284 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8934/9304 [26:49<01:01,  5.98it/s]

2025-05-20 17:02:44,395 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8935/9304 [26:49<00:56,  6.51it/s]

2025-05-20 17:02:44,650 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8936/9304 [26:49<01:05,  5.65it/s]

2025-05-20 17:02:44,793 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8937/9304 [26:50<01:02,  5.91it/s]

2025-05-20 17:02:44,943 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8938/9304 [26:50<01:01,  5.95it/s]

2025-05-20 17:02:45,138 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8939/9304 [26:50<01:02,  5.85it/s]

2025-05-20 17:02:45,442 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8940/9304 [26:50<01:15,  4.79it/s]

2025-05-20 17:02:45,508 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:45,847 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8942/9304 [26:51<01:14,  4.87it/s]

2025-05-20 17:02:45,910 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:45,972 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8944/9304 [26:51<00:54,  6.66it/s]

2025-05-20 17:02:46,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8945/9304 [26:51<00:50,  7.15it/s]

2025-05-20 17:02:46,089 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:46,181 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8947/9304 [26:51<00:37,  9.42it/s]

2025-05-20 17:02:46,520 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:46,559 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8949/9304 [26:51<00:48,  7.35it/s]

2025-05-20 17:02:46,828 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8950/9304 [26:52<00:57,  6.17it/s]

2025-05-20 17:02:46,920 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:47,489 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8952/9304 [26:52<01:19,  4.44it/s]

2025-05-20 17:02:47,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8953/9304 [26:52<01:11,  4.90it/s]

2025-05-20 17:02:47,777 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▌| 8954/9304 [26:53<01:08,  5.13it/s]

2025-05-20 17:02:47,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:47,952 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8956/9304 [26:53<00:53,  6.55it/s]

2025-05-20 17:02:48,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8957/9304 [26:53<01:15,  4.60it/s]

2025-05-20 17:02:48,552 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8958/9304 [26:53<01:09,  4.96it/s]

2025-05-20 17:02:48,623 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:49,170 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8960/9304 [26:54<01:24,  4.09it/s]

2025-05-20 17:02:49,189 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:49,486 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8962/9304 [26:54<01:12,  4.70it/s]

2025-05-20 17:02:49,521 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:49,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:50,033 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8965/9304 [26:55<01:07,  5.00it/s]

2025-05-20 17:02:50,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:50,140 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:50,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8968/9304 [26:55<00:46,  7.28it/s]

2025-05-20 17:02:50,721 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:51,039 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8970/9304 [26:56<01:13,  4.56it/s]

2025-05-20 17:02:51,052 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:51,119 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:51,248 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8973/9304 [26:56<00:54,  6.08it/s]

2025-05-20 17:02:51,339 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:51,838 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8975/9304 [26:57<01:05,  5.04it/s]

2025-05-20 17:02:51,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:52,410 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8977/9304 [26:57<01:12,  4.48it/s]

2025-05-20 17:02:52,592 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 96%|█████████▋| 8978/9304 [26:57<01:10,  4.65it/s]

2025-05-20 17:02:52,775 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8979/9304 [26:58<01:07,  4.78it/s]

2025-05-20 17:02:52,790 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:52,831 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:53,230 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8982/9304 [26:58<00:59,  5.45it/s]

2025-05-20 17:02:53,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:53,285 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:53,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8985/9304 [26:59<00:55,  5.77it/s]

2025-05-20 17:02:53,809 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8986/9304 [26:59<00:51,  6.12it/s]

2025-05-20 17:02:53,881 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:54,494 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8988/9304 [26:59<01:09,  4.57it/s]

2025-05-20 17:02:54,595 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:54,741 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8990/9304 [27:00<00:59,  5.28it/s]

2025-05-20 17:02:54,756 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:54,870 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8992/9304 [27:00<00:47,  6.61it/s]

2025-05-20 17:02:55,213 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8993/9304 [27:00<00:57,  5.36it/s]

2025-05-20 17:02:55,455 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8994/9304 [27:00<01:00,  5.09it/s]

2025-05-20 17:02:55,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:55,566 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8996/9304 [27:00<00:44,  6.90it/s]

2025-05-20 17:02:55,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8997/9304 [27:01<00:56,  5.48it/s]

2025-05-20 17:02:56,095 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8998/9304 [27:01<00:57,  5.34it/s]

2025-05-20 17:02:56,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 8999/9304 [27:01<00:52,  5.76it/s]

2025-05-20 17:02:56,291 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:56,528 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9001/9304 [27:01<00:50,  6.05it/s]

2025-05-20 17:02:56,549 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:56,645 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9003/9304 [27:01<00:37,  8.01it/s]

2025-05-20 17:02:56,959 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:56,966 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9005/9304 [27:02<00:40,  7.32it/s]

2025-05-20 17:02:57,253 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9006/9304 [27:02<00:49,  5.96it/s]

2025-05-20 17:02:57,330 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:57,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9008/9304 [27:03<01:08,  4.32it/s]

2025-05-20 17:02:57,970 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:57,990 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:58,203 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9011/9304 [27:03<00:49,  5.94it/s]

2025-05-20 17:02:58,263 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:58,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9013/9304 [27:04<00:55,  5.25it/s]

2025-05-20 17:02:58,928 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9014/9304 [27:04<00:57,  5.06it/s]

2025-05-20 17:02:58,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:59,023 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:59,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9017/9304 [27:04<00:41,  6.99it/s]

2025-05-20 17:02:59,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9018/9304 [27:04<00:43,  6.58it/s]

2025-05-20 17:02:59,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:02:59,570 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9020/9304 [27:04<00:40,  6.95it/s]

2025-05-20 17:02:59,802 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9021/9304 [27:05<00:44,  6.36it/s]

2025-05-20 17:02:59,939 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9022/9304 [27:05<00:43,  6.46it/s]

2025-05-20 17:03:00,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9023/9304 [27:05<00:48,  5.74it/s]

2025-05-20 17:03:00,466 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9024/9304 [27:05<00:56,  4.97it/s]

2025-05-20 17:03:00,670 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9025/9304 [27:05<00:56,  4.95it/s]

2025-05-20 17:03:00,701 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:00,878 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9027/9304 [27:06<00:44,  6.20it/s]

2025-05-20 17:03:00,919 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:01,326 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9029/9304 [27:06<00:50,  5.41it/s]

2025-05-20 17:03:01,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9030/9304 [27:06<00:48,  5.66it/s]

2025-05-20 17:03:01,529 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:01,819 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9032/9304 [27:07<00:47,  5.75it/s]

2025-05-20 17:03:01,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:01,994 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9034/9304 [27:07<00:38,  6.96it/s]

2025-05-20 17:03:02,019 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:02,344 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9036/9304 [27:07<00:41,  6.46it/s]

2025-05-20 17:03:02,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:02,477 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9038/9304 [27:07<00:33,  7.93it/s]

2025-05-20 17:03:02,788 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9039/9304 [27:08<00:42,  6.23it/s]

2025-05-20 17:03:03,053 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9040/9304 [27:08<00:48,  5.50it/s]

2025-05-20 17:03:03,294 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9041/9304 [27:08<00:51,  5.09it/s]

2025-05-20 17:03:03,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:03,400 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9042/9304 [27:08<00:45,  5.75it/s]

2025-05-20 17:03:03,464 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:03,522 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9045/9304 [27:08<00:27,  9.49it/s]

2025-05-20 17:03:04,041 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:04,120 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9047/9304 [27:09<00:43,  5.92it/s]

2025-05-20 17:03:04,350 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9048/9304 [27:09<00:46,  5.53it/s]

2025-05-20 17:03:04,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9049/9304 [27:09<00:48,  5.30it/s]

2025-05-20 17:03:04,746 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9050/9304 [27:10<00:47,  5.36it/s]

2025-05-20 17:03:04,868 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9051/9304 [27:10<00:42,  5.90it/s]

2025-05-20 17:03:04,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:04,907 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:05,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9054/9304 [27:10<00:31,  7.83it/s]

2025-05-20 17:03:05,723 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9055/9304 [27:11<00:54,  4.54it/s]

2025-05-20 17:03:05,833 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9056/9304 [27:11<00:48,  5.12it/s]

2025-05-20 17:03:05,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9057/9304 [27:11<00:42,  5.77it/s]

2025-05-20 17:03:06,096 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9058/9304 [27:11<00:41,  5.91it/s]

2025-05-20 17:03:06,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:06,300 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9060/9304 [27:11<00:34,  7.07it/s]

2025-05-20 17:03:06,312 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:06,403 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:06,607 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9063/9304 [27:11<00:29,  8.10it/s]

2025-05-20 17:03:06,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9064/9304 [27:12<00:33,  7.11it/s]

2025-05-20 17:03:07,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9065/9304 [27:12<00:51,  4.66it/s]

2025-05-20 17:03:07,382 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:07,936 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9067/9304 [27:13<00:59,  3.99it/s]

2025-05-20 17:03:07,954 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:08,021 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:08,030 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:08,231 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 97%|█████████▋| 9071/9304 [27:13<00:36,  6.31it/s]

2025-05-20 17:03:08,485 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9072/9304 [27:13<00:40,  5.79it/s]

2025-05-20 17:03:08,956 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9073/9304 [27:14<00:52,  4.40it/s]

2025-05-20 17:03:09,185 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9074/9304 [27:14<00:52,  4.39it/s]

2025-05-20 17:03:09,385 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9075/9304 [27:14<00:50,  4.50it/s]

2025-05-20 17:03:09,585 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9076/9304 [27:14<00:49,  4.63it/s]

2025-05-20 17:03:09,600 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:09,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:09,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9078/9304 [27:15<00:36,  6.17it/s]

2025-05-20 17:03:09,897 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9080/9304 [27:15<00:28,  7.76it/s]

2025-05-20 17:03:10,327 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9081/9304 [27:15<00:42,  5.22it/s]

2025-05-20 17:03:10,610 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9082/9304 [27:15<00:46,  4.72it/s]

2025-05-20 17:03:10,674 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:10,710 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9084/9304 [27:16<00:32,  6.76it/s]

2025-05-20 17:03:10,739 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:11,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9086/9304 [27:16<00:37,  5.75it/s]

2025-05-20 17:03:11,224 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:11,553 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9088/9304 [27:16<00:40,  5.33it/s]

2025-05-20 17:03:11,934 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9089/9304 [27:17<00:47,  4.52it/s]

2025-05-20 17:03:11,957 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:12,100 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9091/9304 [27:17<00:36,  5.84it/s]

2025-05-20 17:03:12,242 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9092/9304 [27:17<00:35,  6.04it/s]

2025-05-20 17:03:12,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9093/9304 [27:17<00:34,  6.09it/s]

2025-05-20 17:03:12,451 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:12,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9095/9304 [27:17<00:25,  8.22it/s]

2025-05-20 17:03:12,668 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:13,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9097/9304 [27:18<00:34,  5.92it/s]

2025-05-20 17:03:13,320 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9098/9304 [27:18<00:40,  5.11it/s]

2025-05-20 17:03:13,632 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9099/9304 [27:18<00:45,  4.52it/s]

2025-05-20 17:03:13,898 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9100/9304 [27:19<00:47,  4.29it/s]

2025-05-20 17:03:13,918 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:13,944 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:14,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:14,313 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9103/9304 [27:19<00:37,  5.42it/s]

2025-05-20 17:03:14,384 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:14,589 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9106/9304 [27:19<00:28,  6.91it/s]

2025-05-20 17:03:14,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:14,765 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9108/9304 [27:20<00:25,  7.78it/s]

2025-05-20 17:03:15,398 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9109/9304 [27:20<00:41,  4.66it/s]

2025-05-20 17:03:15,444 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:15,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:15,986 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9111/9304 [27:21<00:46,  4.19it/s]

2025-05-20 17:03:16,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9113/9304 [27:21<00:34,  5.54it/s]

2025-05-20 17:03:16,196 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9114/9304 [27:21<00:31,  5.97it/s]

2025-05-20 17:03:16,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:16,337 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9116/9304 [27:21<00:25,  7.48it/s]

2025-05-20 17:03:16,354 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:16,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9118/9304 [27:21<00:21,  8.47it/s]

2025-05-20 17:03:16,951 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:17,175 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9120/9304 [27:22<00:35,  5.26it/s]

2025-05-20 17:03:17,473 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9121/9304 [27:22<00:37,  4.83it/s]

2025-05-20 17:03:17,591 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9122/9304 [27:22<00:34,  5.32it/s]

2025-05-20 17:03:17,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9123/9304 [27:23<00:32,  5.62it/s]

2025-05-20 17:03:18,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9124/9304 [27:23<00:35,  5.01it/s]

2025-05-20 17:03:18,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9125/9304 [27:23<00:32,  5.56it/s]

2025-05-20 17:03:18,212 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:18,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9127/9304 [27:23<00:29,  6.04it/s]

2025-05-20 17:03:18,569 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9128/9304 [27:23<00:28,  6.18it/s]

2025-05-20 17:03:18,642 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:18,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9130/9304 [27:24<00:25,  6.74it/s]

2025-05-20 17:03:19,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9131/9304 [27:24<00:31,  5.48it/s]

2025-05-20 17:03:19,162 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:19,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9133/9304 [27:24<00:29,  5.78it/s]

2025-05-20 17:03:19,771 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9134/9304 [27:25<00:35,  4.76it/s]

2025-05-20 17:03:20,016 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9135/9304 [27:25<00:36,  4.64it/s]

2025-05-20 17:03:20,133 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:20,145 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9136/9304 [27:25<00:32,  5.23it/s]

2025-05-20 17:03:20,685 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9138/9304 [27:26<00:37,  4.41it/s]

2025-05-20 17:03:20,738 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:20,782 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:21,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9141/9304 [27:26<00:30,  5.36it/s]

2025-05-20 17:03:21,309 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9142/9304 [27:26<00:30,  5.31it/s]

2025-05-20 17:03:21,379 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:21,617 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9144/9304 [27:26<00:28,  5.68it/s]

2025-05-20 17:03:21,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:21,728 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9145/9304 [27:27<00:25,  6.12it/s]

2025-05-20 17:03:21,973 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9147/9304 [27:27<00:23,  6.66it/s]

2025-05-20 17:03:22,252 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9148/9304 [27:27<00:27,  5.70it/s]

2025-05-20 17:03:22,273 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:22,698 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:22,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9150/9304 [27:28<00:32,  4.81it/s]

2025-05-20 17:03:22,890 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9152/9304 [27:28<00:23,  6.34it/s]

2025-05-20 17:03:22,928 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:23,219 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9154/9304 [27:28<00:23,  6.33it/s]

2025-05-20 17:03:23,347 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9155/9304 [27:28<00:22,  6.59it/s]

2025-05-20 17:03:23,450 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9156/9304 [27:28<00:20,  7.09it/s]

2025-05-20 17:03:23,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9157/9304 [27:28<00:20,  7.05it/s]

2025-05-20 17:03:23,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9158/9304 [27:29<00:26,  5.53it/s]

2025-05-20 17:03:23,993 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9159/9304 [27:29<00:23,  6.23it/s]

2025-05-20 17:03:24,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9160/9304 [27:29<00:25,  5.63it/s]

2025-05-20 17:03:24,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:24,318 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9162/9304 [27:29<00:17,  8.16it/s]

2025-05-20 17:03:24,546 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:24,673 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 98%|█████████▊| 9164/9304 [27:30<00:20,  6.99it/s]

2025-05-20 17:03:24,998 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9165/9304 [27:30<00:25,  5.46it/s]

2025-05-20 17:03:25,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9166/9304 [27:30<00:26,  5.19it/s]

2025-05-20 17:03:25,299 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:25,548 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9168/9304 [27:30<00:24,  5.53it/s]

2025-05-20 17:03:25,572 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:25,821 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9170/9304 [27:31<00:21,  6.11it/s]

2025-05-20 17:03:25,836 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:26,067 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9172/9304 [27:31<00:19,  6.70it/s]

2025-05-20 17:03:26,239 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9173/9304 [27:31<00:20,  6.50it/s]

2025-05-20 17:03:26,383 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9174/9304 [27:31<00:19,  6.57it/s]

2025-05-20 17:03:26,593 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9175/9304 [27:31<00:21,  6.01it/s]

2025-05-20 17:03:27,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9176/9304 [27:32<00:30,  4.16it/s]

2025-05-20 17:03:27,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:27,215 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9178/9304 [27:32<00:21,  5.76it/s]

2025-05-20 17:03:27,911 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9179/9304 [27:33<00:36,  3.39it/s]

2025-05-20 17:03:28,102 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9180/9304 [27:33<00:33,  3.73it/s]

2025-05-20 17:03:28,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:28,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9182/9304 [27:33<00:22,  5.34it/s]

2025-05-20 17:03:28,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9183/9304 [27:33<00:21,  5.54it/s]

2025-05-20 17:03:28,438 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:28,753 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9185/9304 [27:34<00:21,  5.61it/s]

2025-05-20 17:03:28,816 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:28,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▊| 9187/9304 [27:34<00:16,  7.10it/s]

2025-05-20 17:03:29,493 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9188/9304 [27:34<00:27,  4.28it/s]

2025-05-20 17:03:29,618 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9189/9304 [27:34<00:23,  4.80it/s]

2025-05-20 17:03:29,695 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:29,726 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9191/9304 [27:35<00:16,  6.75it/s]

2025-05-20 17:03:30,164 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:30,208 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9193/9304 [27:35<00:20,  5.51it/s]

2025-05-20 17:03:30,351 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9194/9304 [27:35<00:18,  5.79it/s]

2025-05-20 17:03:30,778 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9195/9304 [27:36<00:25,  4.32it/s]

2025-05-20 17:03:30,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9196/9304 [27:36<00:22,  4.83it/s]

2025-05-20 17:03:31,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9197/9304 [27:36<00:21,  4.89it/s]

2025-05-20 17:03:31,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:31,151 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:31,253 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9200/9304 [27:36<00:12,  8.23it/s]

2025-05-20 17:03:31,266 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:31,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9202/9304 [27:36<00:12,  8.03it/s]

2025-05-20 17:03:31,697 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9203/9304 [27:37<00:13,  7.33it/s]

2025-05-20 17:03:31,812 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9204/9304 [27:37<00:13,  7.56it/s]

2025-05-20 17:03:32,421 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9205/9304 [27:37<00:24,  4.11it/s]

2025-05-20 17:03:32,729 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9206/9304 [27:38<00:25,  3.85it/s]

2025-05-20 17:03:32,829 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9207/9304 [27:38<00:21,  4.60it/s]

2025-05-20 17:03:32,888 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:32,889 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:32,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9210/9304 [27:38<00:12,  7.80it/s]

2025-05-20 17:03:33,405 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:33,533 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9212/9304 [27:38<00:16,  5.61it/s]

2025-05-20 17:03:33,799 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9213/9304 [27:39<00:17,  5.12it/s]

2025-05-20 17:03:33,850 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:34,018 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9215/9304 [27:39<00:14,  6.05it/s]

2025-05-20 17:03:34,187 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9216/9304 [27:39<00:14,  6.04it/s]

2025-05-20 17:03:34,463 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9217/9304 [27:39<00:16,  5.24it/s]

2025-05-20 17:03:34,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:34,509 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:34,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9220/9304 [27:39<00:10,  7.90it/s]

2025-05-20 17:03:35,054 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9221/9304 [27:40<00:14,  5.55it/s]

2025-05-20 17:03:35,181 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9222/9304 [27:40<00:13,  5.90it/s]

2025-05-20 17:03:35,323 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9223/9304 [27:40<00:13,  6.11it/s]

2025-05-20 17:03:35,662 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9224/9304 [27:40<00:16,  4.85it/s]

2025-05-20 17:03:35,707 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:35,969 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9226/9304 [27:41<00:14,  5.42it/s]

2025-05-20 17:03:36,051 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:36,112 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9228/9304 [27:41<00:10,  6.95it/s]

2025-05-20 17:03:36,246 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9229/9304 [27:41<00:10,  7.16it/s]

2025-05-20 17:03:36,374 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9230/9304 [27:41<00:10,  7.27it/s]

2025-05-20 17:03:36,431 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:36,716 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9232/9304 [27:42<00:10,  6.63it/s]

2025-05-20 17:03:37,183 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9233/9304 [27:42<00:15,  4.52it/s]

2025-05-20 17:03:37,411 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9234/9304 [27:42<00:15,  4.51it/s]

2025-05-20 17:03:37,534 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9235/9304 [27:42<00:13,  5.05it/s]

2025-05-20 17:03:37,665 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9236/9304 [27:42<00:12,  5.57it/s]

2025-05-20 17:03:38,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:38,192 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9237/9304 [27:43<00:18,  3.69it/s]

2025-05-20 17:03:38,209 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:38,379 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9240/9304 [27:43<00:10,  6.11it/s]

2025-05-20 17:03:38,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:38,667 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9242/9304 [27:43<00:09,  6.51it/s]

2025-05-20 17:03:38,935 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9243/9304 [27:44<00:10,  5.61it/s]

2025-05-20 17:03:39,130 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9244/9304 [27:44<00:10,  5.57it/s]

2025-05-20 17:03:39,396 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9245/9304 [27:44<00:11,  4.97it/s]

2025-05-20 17:03:39,413 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:39,694 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9247/9304 [27:45<00:10,  5.59it/s]

2025-05-20 17:03:39,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:39,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9249/9304 [27:45<00:07,  7.11it/s]

2025-05-20 17:03:39,853 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:40,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9251/9304 [27:45<00:07,  7.50it/s]

2025-05-20 17:03:40,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9252/9304 [27:45<00:10,  5.01it/s]

2025-05-20 17:03:40,731 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9253/9304 [27:46<00:09,  5.11it/s]

2025-05-20 17:03:40,916 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9254/9304 [27:46<00:09,  5.19it/s]

2025-05-20 17:03:41,127 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9255/9304 [27:46<00:09,  5.06it/s]

2025-05-20 17:03:41,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:41,235 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 99%|█████████▉| 9257/9304 [27:46<00:06,  7.27it/s]

2025-05-20 17:03:41,265 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:41,424 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9259/9304 [27:46<00:05,  8.23it/s]

2025-05-20 17:03:41,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:41,774 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9261/9304 [27:47<00:06,  7.16it/s]

2025-05-20 17:03:42,181 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9262/9304 [27:47<00:08,  5.18it/s]

2025-05-20 17:03:42,484 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9263/9304 [27:47<00:08,  4.61it/s]

2025-05-20 17:03:42,637 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9264/9304 [27:47<00:08,  4.94it/s]

2025-05-20 17:03:42,727 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:42,755 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9266/9304 [27:48<00:05,  6.97it/s]

2025-05-20 17:03:42,767 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:42,947 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9268/9304 [27:48<00:04,  7.87it/s]

2025-05-20 17:03:43,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9269/9304 [27:48<00:04,  7.65it/s]

2025-05-20 17:03:43,131 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:43,178 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:43,899 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9272/9304 [27:49<00:06,  5.12it/s]

2025-05-20 17:03:44,105 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9273/9304 [27:49<00:06,  5.06it/s]

2025-05-20 17:03:44,287 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:44,290 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9274/9304 [27:49<00:05,  5.15it/s]

2025-05-20 17:03:44,394 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9276/9304 [27:49<00:03,  7.07it/s]

2025-05-20 17:03:44,406 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:44,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:44,640 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9279/9304 [27:49<00:02,  8.62it/s]

2025-05-20 17:03:45,002 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:45,055 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9281/9304 [27:50<00:03,  6.98it/s]

2025-05-20 17:03:45,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9282/9304 [27:50<00:04,  5.06it/s]

2025-05-20 17:03:45,580 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:45,653 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9284/9304 [27:50<00:03,  6.44it/s]

2025-05-20 17:03:45,871 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9285/9304 [27:51<00:03,  6.00it/s]

2025-05-20 17:03:45,928 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:46,093 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9287/9304 [27:51<00:02,  6.80it/s]

2025-05-20 17:03:46,368 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9288/9304 [27:51<00:02,  5.80it/s]

2025-05-20 17:03:46,512 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9289/9304 [27:51<00:02,  5.94it/s]

2025-05-20 17:03:46,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:46,848 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9290/9304 [27:52<00:02,  4.77it/s]

2025-05-20 17:03:47,204 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9292/9304 [27:52<00:02,  5.12it/s]

2025-05-20 17:03:47,516 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9293/9304 [27:52<00:02,  4.51it/s]

2025-05-20 17:03:47,641 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9294/9304 [27:52<00:01,  5.08it/s]

2025-05-20 17:03:47,827 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9295/9304 [27:53<00:01,  5.11it/s]

2025-05-20 17:03:47,937 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9296/9304 [27:53<00:01,  5.85it/s]

2025-05-20 17:03:47,977 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:48,459 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9298/9304 [27:53<00:01,  4.77it/s]

2025-05-20 17:03:48,527 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:48,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9300/9304 [27:54<00:00,  4.72it/s]

2025-05-20 17:03:48,984 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:49,247 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|█████████▉| 9302/9304 [27:54<00:00,  4.99it/s]

2025-05-20 17:03:49,338 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-20 17:03:50,022 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|██████████| 9304/9304 [27:58<00:00,  5.54it/s]

🎉 Done in 0:27:59.656706
✅ Output saved to: /home/pascualdiego/projects/DiscoveryHP/outputs/fullset_classified_patents_CEscore.jsonl

In [ ]:
# --------------------------------------------------------------------------- #
# 1 and 2. CLASSIFY OPENALEX RESEARCH PAPERS (Same pipeline as patents)             #
# --------------------------------------------------------------------------- #

OPENALEX_PATH = "heat_pumps_openalex.csv"
OPENALEX_OUTPUT = PROJECT_DIR / "outputs/fullset_classified_papers_CEscore.jsonl"

print("▶︎ Loading OpenAlex research dataset ...")
openalex_df = pd.read_csv(OPENALEX_PATH)
print("Total papers loaded:", len(openalex_df))

# Optional: filter rows by keyword if enabled
if filter_keywords:
    openalex_df["text"] = (
        openalex_df["title"].fillna('') + " " + openalex_df["abstract"].fillna('')
    ).str.lower()

    openalex_df = openalex_df[openalex_df["text"].str.strip() != ""]

    openalex_df = openalex_df[
        openalex_df["text"].apply(lambda t: any(k in t for k in KW2CAT))
    ].copy()

    print("After keyword filtering:", len(openalex_df))

# Load already processed DOIs
processed_dois = set()
if OPENALEX_OUTPUT.exists():
    with open(OPENALEX_OUTPUT, "r") as f:
        processed_dois = {json.loads(line).get("doi_url", "") for line in f}
    print("Resuming from checkpoint. Already done:", len(processed_dois))

# Build prompt for research paper
def make_prompt_paper(title, abstract):
    return f"""
You are a sustainable heating technology analyst.

TITLE: {title}
ABSTRACT: {abstract}

Answer:
1. What is the core technical innovation? (max 25 words)
2. Is it relevant to heat pumps? ('yes' or 'no')
3. If yes, assign exactly ONE category code: {', '.join(CATEGORIES.keys())}
4. Score 0-3 for:
   a) cost_reduction_potential
   b) efficiency_gain_potential
   c) circularity_score (use ISO 59004 lever heuristic)
   Respond ONLY as JSON:
{{"is_relevant": "...", "summary": "...", "category": "...",
  "cost_score": ..., "efficiency_score": ..., "circularity_score": ...}}
""".strip()

# LLM wrapper
def classify_paper(row):
    doi = row.get("doi_url", "")
    if doi in processed_dois:
        return None
    try:
        prompt = make_prompt_paper(row["title"], row["abstract"])
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=T_CLASSIFY,
            response_format={"type": "json_object"}
        )
        result = json.loads(response.choices[0].message.content)

        # Add both LLM and ISO circularity scores
        combined_text = f"{row['title']} {row['abstract']}"
        result["circularity_score_llm"] = result.pop("circularity_score")
        result["circularity_score_iso"] = iso_score(combined_text)

        result.update({
            "title": row["title"],
            "abstract": row["abstract"],
            "doi_url": doi
        })
        return result
    except Exception as e:
        print(f"⚠️ Error on paper: {e}")
        return None



# Run in parallel
print("▶︎ Starting OpenAlex classification ...")
t0 = datetime.now()
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor, open(OPENALEX_OUTPUT, "a") as f_out:
    futures = [executor.submit(classify_paper, row) for _, row in openalex_df.iterrows()]
    for future in tqdm(as_completed(futures), total=len(futures)):
        result = future.result()
        if result:
            f_out.write(json.dumps(result) + "\n")
print(f"🎉 Done in {datetime.now() - t0}")
print(f"✅ Output saved to: {OPENALEX_OUTPUT}")